### ISSUE TITLE
[Drone] "event":"tag","level":"info","msg":"trigger: skipping pipeline, does not match branch"

### ISSUE THREAD

**Issue by everhopingandwaiting** [go-gitea/gitea#10334]
- Gitea version (or commit ref):  1.12.0+dev-325-ge76a64dda
- Git version: latest
- Operating system: gitea/gitea docker container
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

from gitea to publish a release ， and the drone server could not trigger the tag event.
```
drone-server    | {"commit":"8069645f93dc130699f019fefe380f39e6380d0a","event":"tag","level":"info","msg":"trigger: skipping pipeline, does not match branch","pipeline":"default","ref":"refs/tags/v20","repo":"jyao/test","time":"2020-02-18T09:52:32Z"}
drone-server    | {"commit":"8069645f93dc130699f019fefe380f39e6380d0a","event":"tag","level":"info","msg":"trigger: skipping build, no matching pipelines","pipeline":"default","ref":"refs/tags/v20","repo":"jyao/test","time":"2020-02-18T09:52:32Z"}
```
...

*.drone.yml*
```
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: nginx
    detach: true
    commands:
    - echo hello
    - nginx -t
     
  - name: 微信推送
    image: appropriate/curl
    commands:
    - curl https://sc.ftqq.com/SCU2667T81a06b885fd4e8ad3e462bba35900ab16f370c.send?text=构建成功啦~
    
  - name: docker  
    image: plugins/docker
    settings:
      repo: everhopingandwaiting/test
      auto_tag: true
      auto_tag_suffix: test
      username: everh
      password: ${password}
    environment:
      username:
        from_secret: name
      password:
        from_secret: pwd
    when:
     event:
     - tag
     ref:
     - refs/tags/*
trigger:
  branch:
  - master
  event:
  - tag
  - published
  
---
kind: secret
name: pwd
get:
  path: docker/data/registry
  name: pwd
---
kind: secret
name: name
get:
  path: docker/data/registry
  name: username
```
## Screenshots

![image](https://user-images.githubusercontent.com/6021724/74729146-ef28b200-527e-11ea-98fa-f1b407357d8d.png)

**Comment by techknowlogick** [comment]
Which version of Drone are you using?

**Comment by lafriks** [comment]
Just remove:
```
ref:
     - refs/tags/*
```

**Comment by lafriks** [comment]
Anyway this is drone issue most probably but I think this could be conflicting:
```
trigger:
  branch:
  - master
  event:
  - tag
  - published
```
