### ISSUE TITLE
DISABLE_SSH not working in docker-compose

### ISSUE THREAD

**Issue by jtktam** [go-gitea/gitea#10419]
- Gitea version (or commit ref): 1.12.0+dev-356-g089ccb0c8 
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description

in my docker-compose file for my gitea instance:

  gitea:
    image: "gitea/gitea"
    environment:
      # file ids
      - USER_UID=1000
      - USER_GID=1000
      # db values
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DISABLE_SSH=true
      # rewrite values
      - ROOT_URL=http://gitea.example.com/
      - DOMAIN=gitea.example.com
    restart: always
    networks:
      - backend
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

when i start up my docker container, ssh is not disabled

i have to manually go into the app,ini file and modified the value from false to true, restart the container and the ssh option goes away as intended

**Comment by techknowlogick** [comment]
Env vars are only used in the case that app.ini doesn't exist. Once app.ini exists then it'll need to be edited.

**Comment by jtktam** [comment]
this is on a fresh install

the other values mentioned in the docker-compose file gets populated into the app.ini correctly, only the DISABLE_SSH is not

i don't think it's a closed issue

**Comment by jtktam** [comment]
thank you for reopening the issue

**Comment by zeripath** [comment]
@jtktam What version are you finding this problem on? master certainly appears correct.

Could you post your /etc/templates/app.ini and /etc/s6/gitea/setup?

**Comment by J-TAG** [comment]
I have the same issue.

I'm using Docker Swarm instead of Docker Compose , but the configuration is pretty the same.

My `docker-stack.yml` file:

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.12.5
    container_name: gitea
    environment:
      - APP_NAME="Gitea Git Server"
      - RUN_MODE=prod
      - DOMAIN=example.org
      - DISABLE_SSH=true
      - HTTP_PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea 
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

```
`/etc/templates/app.ini` inside container:

```
APP_NAME = $APP_NAME
RUN_MODE = $RUN_MODE

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH = /data/gitea
DOMAIN           = $DOMAIN
SSH_DOMAIN       = $SSH_DOMAIN
HTTP_PORT        = $HTTP_PORT
ROOT_URL         = $ROOT_URL
DISABLE_SSH      = $DISABLE_SSH
SSH_PORT         = $SSH_PORT
SSH_LISTEN_PORT  = $SSH_LISTEN_PORT
LFS_START_SERVER = $LFS_START_SERVER
LFS_CONTENT_PATH = /data/git/lfs

[database]
PATH = /data/gitea/gitea.db
DB_TYPE = $DB_TYPE
HOST    = $DB_HOST
NAME    = $DB_NAME
USER    = $DB_USER
PASSWD  = $DB_PASSWD

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = /data/gitea/log

[security]
INSTALL_LOCK = $INSTALL_LOCK
SECRET_KEY   = $SECRET_KEY

[service]
DISABLE_REGISTRATION = $DISABLE_REGISTRATION
REQUIRE_SIGNIN_VIEW  = $REQUIRE_SIGNIN_VIEW

```

`/etc/s6/gitea/setup` inside container:

```
#!/bin/bash

if [ ! -d /data/git/.ssh ]; then
    mkdir -p /data/git/.ssh
    chmod 700 /data/git/.ssh
fi

if [ ! -f /data/git/.ssh/environment ]; then
    echo "GITEA_CUSTOM=$GITEA_CUSTOM" >| /data/git/.ssh/environment
    chmod 600 /data/git/.ssh/environment

elif ! grep -q "^GITEA_CUSTOM=$GITEA_CUSTOM$" /data/git/.ssh/environment; then
    sed -i /^GITEA_CUSTOM=/d /data/git/.ssh/environment
    echo "GITEA_CUSTOM=$GITEA_CUSTOM" >> /data/git/.ssh/environment
fi

if [ ! -f ${GITEA_CUSTOM}/conf/app.ini ]; then
    mkdir -p ${GITEA_CUSTOM}/conf

    # Set INSTALL_LOCK to true only if SECRET_KEY is not empty and
    # INSTALL_LOCK is empty
    if [ -n "$SECRET_KEY" ] && [ -z "$INSTALL_LOCK" ]; then
        INSTALL_LOCK=true
    fi

    # Substitude the environment variables in the template
    APP_NAME=${APP_NAME:-"Gitea: Git with a cup of tea"} \
    RUN_MODE=${RUN_MODE:-"dev"} \
    DOMAIN=${DOMAIN:-"localhost"} \
    SSH_DOMAIN=${SSH_DOMAIN:-"localhost"} \
    HTTP_PORT=${HTTP_PORT:-"3000"} \
    ROOT_URL=${ROOT_URL:-""} \
    DISABLE_SSH=${DISABLE_SSH:-"false"} \
    SSH_PORT=${SSH_PORT:-"22"} \
    SSH_LISTEN_PORT=${SSH_LISTEN_PORT:-"${SSH_PORT}"} \
    LFS_START_SERVER=${LFS_START_SERVER:-"false"} \
    DB_TYPE=${DB_TYPE:-"sqlite3"} \
    DB_HOST=${DB_HOST:-"localhost:3306"} \
    DB_NAME=${DB_NAME:-"gitea"} \
    DB_USER=${DB_USER:-"root"} \
    DB_PASSWD=${DB_PASSWD:-""} \
    INSTALL_LOCK=${INSTALL_LOCK:-"false"} \
    DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-"false"} \
    REQUIRE_SIGNIN_VIEW=${REQUIRE_SIGNIN_VIEW:-"false"} \
    SECRET_KEY=${SECRET_KEY:-""} \
    envsubst < /etc/templates/app.ini > ${GITEA_CUSTOM}/conf/app.ini

    chown ${USER}:git ${GITEA_CUSTOM}/conf/app.ini
fi

# only chown if current owner is not already the gitea ${USER}. No recursive check to save time
if ! [[ $(ls -ld /data/gitea | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /data/gitea; fi
if ! [[ $(ls -ld /app/gitea  | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /app/gitea;  fi
if ! [[ $(ls -ld /data/git   | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /data/git;   fi
chmod 0755 /data/gitea /app/gitea /data/git

```

It seems `DISABLE_SSH` value is always false, regardless of what has been set in `docker-stack.yml` file.
