### ISSUE TITLE
Redirect loop after reverse proxying

### ISSUE THREAD

**Issue by timelf123** [go-gitea/gitea#11095]
- Gitea version (or commit ref): master
- Git version: latest
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I get redirect loops and the ROOT_URL does not seem to fix it, nor does adding a trailing slash to the proxy config. I get requests from the browser like this: `https://git.site.com/git.site.com/img/git.site.com/git.site.com/git.site.com/git.site.com/git.site.com/git.site.com/git.site.com/git.site.com/git.site.com/install`

Compose:
```
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        labels:
            - "com.dockstarter.appinfo.description: Git repo hosting"
            - "com.dockstarter.appinfo.nicename: Gitea"
        environment:
            - "APP_NAME=Gitea"
            - "ROOT_URL=https://git.site.com/"
            - DOMAIN=git.site.com
            - RUN_MODE=prod
            - SSH_PORT=2222
            - SSH_LISTEN_PORT=2222
            - SSH_DOMAIN=git.site.com
            - USER_GID=1000
            - USER_UID=1000
        restart: always
        volumes:
            - ${DOCKERSHAREDDIR}/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "2222:2222"
        restart: unless-stopped
```

Nginx conf:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name git.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app gitea;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/;
    }
}
```
