### ISSUE TITLE
Writing Manpage

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#11399]
## Description

It is convenient to have manpage for viewing Gitea docs (especially [Command Line](https://docs.gitea.io/en-us/command-line/) and [Config Cheat Sheet](https://docs.gitea.io/en-us/config-cheat-sheet/)) locally.

The manpage will be written using go-md2man as suggested by @lafriks.

The workflow (as described in [Hacking doc](https://docs.gitea.io/en-us/hacking-on-gitea/) should be modified to include that any changes to config cheat sheet and/or command line options list docs above, the corresponding changes should also be made onto manpage.

However, how should the manpage be distributed along with Gitea? Currently [dl page](https://dl.gitea.io/gitea) distribute Gitea as single binary and xz-compressed of it. So I had two options:

1. Distribute manpage separately, as xz-compressed, or
2. For compressed archive of Gitea binary, throw manpage into it.

**Comment by techknowlogick** [comment]
I believe that https://github.com/urfave/cli the CLI library we use is able to auto generate man pages.

**Comment by lafriks** [comment]
I think it uses https://github.com/cpuguy83/go-md2man/

**Comment by bagasme** [comment]
@techknowlogick i don't see manpage generation on [cli docs](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)

**Comment by techknowlogick** [comment]
Not in manual, but here is a code reference: https://github.com/urfave/cli/blob/841e5b03ad972b9578bb8ad73441e9d9a51d3c14/docs.go#L24

**Comment by silverwind** [comment]
I see that https://github.com/go-gitea/gitea/pull/11476 adds 2 more markdown source files and I'm not happy about it because if I understand correctly it would require us to change 4 files for each change in the config. The existing duplication of the config file and the hacking page is already an issue because they constantly get out of sync. I think we should work on something that generates everything from one single source file.

**Comment by bagasme** [comment]
@silverwind file formats and conventions is also common on manpages (as `man 5 /etc/sudoers` or similar).

nevertheless, I like your idea of generate docs from single files. What about your suggestion?

**Comment by silverwind** [comment]
For config, I could see

```yaml
configOptions:
  - name: APP_NAME
    default: "Gitea: Git with a cup of tea"
    comment: App name that shows in every page title
  - name: RUN_USER
    default: git
    comment: Change it if you run locally
  - name: RUN_MODE
    default: dev
    comment: Either "dev", "prod" or "test", default is "dev"
  - name: repository.ROOT
    default: ""
    comment: ""
  - name: repository.SCRIPT_TYPE
    default: bash
    comment: ""
  - name: repository.ANSI_CHARSET
    default: ""
    comment: Default ANSI charset
```

This format should be easy to parse in a script (I'd say either Go, JS or even Python) and it can generate both `app.ini.sample` and the hacking doc. A similar format could be used for `--help` and the manpage if you add a key like `cliArguments` with a similar format.
