### ISSUE TITLE
Double borders on edit file view

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1152]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (Just edit any file)
- Log gist: Not relevant

## Description

There is unnecessary double borders around the editors on the edit file view. This applies to both the markdown and the plain text editor. 

This CSS code will fix it:
````css
.repository.file.editor .tab[data-tab="write"] {
    padding: 0 !important;
}
.repository.file.editor .tab[data-tab="write"] .editor-toolbar {
    border: none !important;
}
.repository.file.editor .tab[data-tab="write"] .CodeMirror {
    border-left: none;
    border-right: none;
    border-bottom: none;
}
````

## Screenshots
|Before modifications|After modifications|
|-|-|
|![screenshot](https://cloud.githubusercontent.com/assets/13909717/23731039/29b40998-0439-11e7-8bea-b1f3c00a7aac.png)|![screenshot 1](https://cloud.githubusercontent.com/assets/13909717/23731038/29b23fdc-0439-11e7-8cce-fa5614f34013.png)|
