### ISSUE TITLE
Branch/Tag selector is scrollable

### ISSUE THREAD

**Issue by UnlimitedCookies** [go-gitea/gitea#11865]
Reproducible on any repository on https://gitea.com/ and https://try.gitea.io/

## Description

There is a scroll bar on the branch/tag selector and you can scroll down.
When you scroll down the text is not readable.

## Screenshots
![Anmerkung 2020-06-12 125040](https://user-images.githubusercontent.com/49200216/84495647-cb64fe00-acab-11ea-8c4e-c3ec652ff0b4.png)

**This is how it looks when scrolled down:**
![Anmerkung 2020-06-12 125105](https://user-images.githubusercontent.com/49200216/84495650-cdc75800-acab-11ea-9d92-027255aec5b3.png)

**Comment by CirnoT** [comment]
Caused by
```css
.dropdown:not(.selection)>.menu:not(.review-box)>* {
    overflow-x: hidden;
}
```
