### ISSUE TITLE
Can not override default logo

### ISSUE THREAD

**Issue by v-byte-cpu** [go-gitea/gitea#11901]
- Gitea version (or commit ref):
- Git version:
- Operating system: use docker image gitea/gitea:1
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

The issue https://github.com/go-gitea/gitea/issues/758 is reproduced again. I can serve aditional content, but cannot override Gitea content.

**Comment by jolheiser** [comment]
Did you follow the [docs for docker](https://docs.gitea.io/en-us/install-with-docker/)?

Make sure the files are in the right place and you restart the instance after adding new content.

**Comment by v-byte-cpu** [comment]
@jolheiser, yes, I exactly followed this guide

**Comment by jolheiser** [comment]
Forgot to ask before, specifically did you see the [customization](https://docs.gitea.io/en-us/install-with-docker/#customization) part?

Unfortunately I don't currently have an instance running in Docker to check, but the code for custom public files is the same and I am able to change it on my binary-install instance.  
My guess is an incorrect path somewhere. 🙁 

Can you give me the path where you put the file and perhaps the docker compose? Scrubbed as necessary.

**Comment by v-byte-cpu** [comment]
Yes, sure

docker-compose.yml:

```
version: '3.7'
services:
  gitea:
    image: gitea/gitea:1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - default
      - internal_net
    volumes:
      - ./data/gitea:/data
      - ./app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3081:3000"
      - "3023:22"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: some_pass
      POSTGRES_INITDB_ARGS: '--lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    networks:
      - internal_net
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  internal_net:
    internal: true
```

app.ini:

```
APP_NAME = Gitea
RUN_MODE = prod
RUN_USER = git

[database]
DB_TYPE  = postgres
HOST     = postgresql:5432
NAME     = gitea
USER     = gitea
PASSWD   = some_pass

[security]
PASSWORD_HASH_ALGO = argon2
INSTALL_LOCK       = true

[server]
OFFLINE_MODE     = true
DISABLE_GRAVATAR = true
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/gitea/lfs
HTTP_PORT        = 3000
SSH_PORT         = 22
SSH_DOMAIN       = localhost

[repository]
DISABLE_HTTP_GIT = true

[service]
DISABLE_REGISTRATION              = true
REQUIRE_SIGNIN_VIEW               = true
REGISTER_EMAIL_CONFIRM            = false
DEFAULT_KEEP_EMAIL_PRIVATE        = true

[picture]
DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = false

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[log]
MODE  = console
LEVEL = info

[session]
PROVIDER = memory
```

In my case, I put files on host machine to `./data/gitea/gitea/public/img/` folder i.e. it maps to `/data/gitea/public/img/` folder inside gitea container
