### ISSUE TITLE
No styling on Docker container.

### ISSUE THREAD

**Issue by leggettc18** [go-gitea/gitea#12009]
- Gitea version (or commit ref): latest tag of docker container
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I deployed the docker container with a Caddy reverse proxy and when I navigate to it I get what appears to be the home page with no styling. Checking the network tab of my devtools shows what appears to be a bunch of redirects to the install page, but it appears to attempt the redirect several times, resulting in urls like this getting logged: 
```
https://git.leggett.dev/git.leggett.dev/img/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/git.leggett.dev/install
```

Caddyfile
```
git.{$MY_DOMAIN} {
    reverse_proxy gitea:3000
}
```

Docker Compose
```
version: "3"

services:
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        hostname: gitea
        env_file: .env
        restart: unless-stopped
        volumes:
            - ./gitea-data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "222:22"
        depends_on:
            - gitea-db
    gitea-db:
        image: mysql:5.7
        container_name: gitea-db
        hostname: gitea-db
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./gitea-db-data:/var/lib/mysql
networks:
    default:
        external: 
            name: $DOCKER_MY_NETWORK
```

.env
```
# GENERAL
MY_DOMAIN=leggett.dev
DOCKER_MY_NETWORK=caddy_net
TZ=America/New_York

# GITEA
USER_UID=1000
USER_GID=1000
DB_TYPE=mysql
DB_HOST=gitea-db:3306
DB_NAME=gitea
DB_USER=gitea
DB_PASSWD=gitea
RUN_MODE=prod

# MYSQL
MYSQL_ROOT_PASSWORD=gitea
MYSQL_USER=gitea
MYSQL_PASSWORD=gitea
MYSQL_DATABASE=gitea
```
...
