### ISSUE TITLE
500 error on Gitea docker container when adding SSH keys

### ISSUE THREAD

**Issue by leggettc18** [go-gitea/gitea#12059]
- Gitea version (or commit ref): 1.12.1
- Git version: 2.24.3
- Operating system: Ubuntu 20.04 (though Gitea runs in a docker container)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I set up the docker container and tried to set up SSH passthrough, by creating a git user on the host, setting the proper environment variables to match its user and group IDs, creating the executable /app/gitea/gitea, creating git's ssh key, symlinking the authorized keys file, and writing the host's git users key to the authorized keys file. As far as I can tell I did all that correctly according to the instructions on the website.

docker-compose.yml
```
version: "3"

services:
    gitea:
        image: gitea/gitea:1.12.1
        container_name: gitea
        hostname: gitea
        env_file: .env
        restart: unless-stopped
        volumes:
            - /var/lib/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "127.0.0.1:2222:22"
        depends_on:
            - gitea-db
    gitea-db:
        image: mysql:5.7
        container_name: gitea-db
        hostname: gitea-db
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./gitea-db-data:/var/lib/mysql
networks:
    default:
        external: 
            name: $DOCKER_MY_NETWORK
```

.env
```
# GENERAL
MY_DOMAIN=leggett.dev
DOCKER_MY_NETWORK=caddy_net
TZ=America/New_York

# GITEA
USER_UID=1001
USER_GID=1001
DB_TYPE=mysql
DB_HOST=gitea-db:3306
DB_NAME=gitea
DB_USER=gitea
DB_PASSWD=gitea
RUN_MODE=prod
SSH_DOMAIN=git.leggett.dev
ROOT_URL=git.leggett.dev

# MYSQL
MYSQL_ROOT_PASSWORD=gitea
MYSQL_USER=gitea
MYSQL_PASSWORD=gitea
MYSQL_DATABASE=gitea
```

/app/gitea/gitea
```
#!/bin/sh
ssh -p 2222 -o StrictHostKeyChecking=no git@127.0.0.1 "SSH_ORIGINAL_COMMAND=\"$SSH_ORIGINAL_COMMAND\" $0 $@"
```

A couple of specific questions
1. The git user on the host has a password on it. Should it? I would think it should but I'm not 100% sure.
2. The key I'm trying to add is an ecdsa key, is that format not considered valid for Gitea?
...
