### ISSUE TITLE
update drone.yml receive multiple webhooks from Gitea

### ISSUE THREAD

**Issue by ysicing** [go-gitea/gitea#12124]
- Gitea version (or commit ref): 1.13.0+dev-260-geea25f8d7 built with GNU Make 4.3, go1.14.4
- Git version: 2.26.2
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

deploy gitea by docker

update drone.yml receive multiple webhooks from Gitea

## Screenshots

![image](https://user-images.githubusercontent.com/8605565/86368990-7287f480-bcb0-11ea-8008-d059fe5e1e4e.png)

![image](https://user-images.githubusercontent.com/8605565/86368701-0c02d680-bcb0-11ea-8bc5-d77c06bebe97.png)

![image](https://user-images.githubusercontent.com/8605565/86369061-86335b00-bcb0-11ea-9617-d0730668ff18.png)

**Comment by lunny** [comment]
Did the two webhooks have the same content?

**Comment by ysicing** [comment]
Yes, you look at the execution result of CI and the time of triggering hook

**Comment by ysicing** [comment]
create repo event:
 
![image](https://user-images.githubusercontent.com/8605565/86425589-2a042180-bd18-11ea-9a54-baad80688dd3.png)

**Comment by techknowlogick** [comment]
@ysicing how many webhooks exist for the repo?

**Comment by ysicing** [comment]
![image](https://user-images.githubusercontent.com/8605565/86428077-7eaa9b00-bd1e-11ea-8d20-286b127a41e4.png)

 Just one.

@techknowlogick

**Comment by ReactiioN1337** [comment]
I can confirm that. I also have only a single webhook in my repository and the webhook is called twice.

**Comment by ysicing** [comment]
How do I troubleshoot this problem?
@lunny  @techknowlogick

**Comment by lunny** [comment]
Could you also check orgnization webhooks and system webhooks?

**Comment by ysicing** [comment]
No Webhooks found for orgnization and system
@lunny

**Comment by techknowlogick** [comment]
are you able to create a new test repo and set it up with a simple drone file to see if it happens on a different repo too?

**Comment by ysicing** [comment]
Looks like the same.
![image](https://user-images.githubusercontent.com/8605565/89093993-0f45cb00-d3f2-11ea-997d-5091bb015df6.png)
![image](https://user-images.githubusercontent.com/8605565/89093999-1f5daa80-d3f2-11ea-8e8c-01d3068d50ae.png)

@techknowlogick

**Comment by flew990** [comment]
I have the same problem today.
Install on k8s using helm chart. docker  images.gitea: "gitea/gitea:latest".  All dependent resources are in k8s. 
only one webhook url.
 
![image](https://user-images.githubusercontent.com/35193505/91628676-b79c7e80-e9f4-11ea-87a5-68b4a5a5e7a0.png)

How can I fix it? Thanks

**Comment by techknowlogick** [comment]
@flew990 which helm chart are you using?

**Comment by flew990** [comment]
https://charts.k8s.land
@techknowlogick

**Comment by flew990** [comment]
images:
  registry: docker.io
  gitea: "gitea/gitea:latest"
  pullPolicy: IfNotPresent
ingress:
  hostname: gitserver.pypygo.com
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
      - gitserver.pypygo.com
      secretName: gitea.tls
  secrets: 
    - name: gitea-server-tls
      key: 4398188_core.harbor.pypygo.com.key
      certificate: 4398188_core.harbor.pypygo.com.pem
service:
  ssh:
    externalHost: git.pypygo.com
persistence:
  enabled: true
  existingGiteaClaim: gitea-pvc

**Comment by flew990** [comment]
values.yaml:

```
images:
  registry: docker.io
  gitea: "gitea/gitea:latest"
  pullPolicy: IfNotPresent
ingress:
  hostname: gitserver.pypygo.com
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
      - gitserver.pypygo.com
      secretName: gitea.tls
  secrets: 
    - name: gitea-server-tls
      key: 4398188_core.harbor.pypygo.com.key
      certificate: 4398188_core.harbor.pypygo.com.pem
service:
  ssh:
    externalHost: git.pypygo.com
persistence:
  enabled: true
  existingGiteaClaim: gitea-pvc

```
