### ISSUE TITLE
Docker -> SSH access error: "Permission denied (publickey)"

### ISSUE THREAD

**Issue by chatelp** [go-gitea/gitea#12154]
- Gitea version (or commit ref): 
- Git version: 1.13.0+dev-273-g15d3aa7b9
- Operating system: macOS Catalina + Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm unable to connect to gitea via SSH. I get the following error : _Permission denied (publickey)_
I'm using gitea/gitea:latest docker image and my docker-compose.yaml is the following:

```
version: "2"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    volumes:
      - ./gitea:/data
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    ports:
      #- "3000:3000"
      - "222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gitea"
      - "traefik.frontend.rule=Host:"
      - "traefik.port=3000"

    restart: unless-stopped
    networks:
      - traefik_default
      - gitea

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  traefik_default:
    external:
      name: traefik_default
  gitea:
    external: false
```

I've looked at https://github.com/go-gitea/gitea/issues/5623 and https://github.com/go-gitea/gitea/issues/2555, and they don't seem relevant to my problem.

I've installed my RSA public key using the gitea web interface, then I checked that the key is written in _/data/git/.ssh/authorized_keys_.

I'm not using the built-in ssh server, so I've also tried running _Update the '.ssh/authorized_keys' file with Gitea SSH keys._ from the Gitea control panel, but nothing happens (the file is not modified whatsoever, but no errors in log).

When trying to connect from my host using ssh command with debug enabled, I get the following trace:

```
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to localhost port 222.
debug1: Connection established.
debug1: identity file /Users/pierre/.ssh/id_rsa type 0
debug1: identity file /Users/pierre/.ssh/id_rsa-cert type -1
debug1: identity file /Users/pierre/.ssh/id_dsa type -1
debug1: identity file /Users/pierre/.ssh/id_dsa-cert type -1
debug1: identity file /Users/pierre/.ssh/id_ecdsa type -1
debug1: identity file /Users/pierre/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/pierre/.ssh/id_ed25519 type -1
debug1: identity file /Users/pierre/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/pierre/.ssh/id_xmss type -1
debug1: identity file /Users/pierre/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.3
debug1: match: OpenSSH_8.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to localhost:222 as 'pierre'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 
debug1: Host '[localhost]:222' is known and matches the ECDSA host key.
debug1: Found key in /Users/pierre/.ssh/known_hosts:5
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /Users/pierre/.ssh/id_rsa RSA 
debug1: Will attempt key: /Users/pierre/.ssh/id_dsa
debug1: Will attempt key: /Users/pierre/.ssh/id_ecdsa
debug1: Will attempt key: /Users/pierre/.ssh/id_ed25519
debug1: Will attempt key: /Users/pierre/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/pierre/.ssh/id_rsa RSA 
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/pierre/.ssh/id_dsa
debug1: Trying private key: /Users/pierre/.ssh/id_ecdsa
debug1: Trying private key: /Users/pierre/.ssh/id_ed25519
debug1: Trying private key: /Users/pierre/.ssh/id_xmss
debug1: No more authentication methods to try.
```

It clearly looks like the ssh server is not finding my public key I installed previously to check against my private key that IS offered by my ssh client.

**I then connected to the running gitea docker container and ran _ps_. I saw that the ssh server is running as _root_, whereas the gitea server is running as the _git_ user. Could that explain the problem? Since authorized_keys are installed for the _git_ user (_/data/git/.ssh/authorized_keys_), then _sshd_ running as _root_ doesn't load this particular file.** 

```
    1 root      0:00 /bin/s6-svscan /etc/s6
   12 root      0:00 s6-supervise gitea
   13 root      0:00 s6-supervise openssh
   14 root      0:00 sshd: /usr/sbin/sshd -D -e [listener] 0 of 10-100 startups
   15 git       1:05 /app/gitea/gitea web
   56 git       0:00 bash
   61 git       0:00 ps
```

Now, I'm at a loss what to do next. I tried switching to the "built-in ssh server" to no avail. 

Here is the server section of my current app.ini

```
[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = 
HTTP_PORT        = 3000
ROOT_URL         = http://...
DISABLE_SSH      = false
START_SSH_SERVER = false
SSH_PORT         = 222
SSH_LISTEN_PORT  = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/git/lfs
DOMAIN           = 
LFS_JWT_SECRET   = 
OFFLINE_MODE     = false
```

Thanks for your help!
