### ISSUE TITLE
Add arm/v7 tag to docker image

### ISSUE THREAD

**Issue by Slyke** [go-gitea/gitea#12323]
- Gitea version (or commit ref): Latest (Not relevant)
- Git version: Latest (Not relevant)
- Operating system: Raspberry Pi OS
- Database (use `[x]`): (Not relevant)
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Gitea doesn't seem to run on the Raspberry Pi when using the official Gitea docker image. The error is due to the Raspberry Pi running on arm/v7. I can use custom Gitea docker files which work perfectly fine on the Raspberry Pi. Would you consider adding `arm/v7` (32 and 64bit) to the [docker tags](https://hub.docker.com/r/gitea/gitea/tags)? I can already see `arm/v8` there.

Docker compose yaml:
```
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    ports:
      - "7920:3000/tcp"
      - "2222:22/tcp"
    env_file:
      - ./services/gitea/gitea.env
    volumes:
      - ./volumes/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
```

## Screenshots

![image](https://user-images.githubusercontent.com/6442613/88445884-8370e500-cdda-11ea-9a05-c8494fb82dd2.png)
