### ISSUE TITLE
After login providing two-factor auth 5XX errors. Can't login.

### ISSUE THREAD

**Issue by nodesocket** [go-gitea/gitea#12406]
- **Gitea version (or commit ref):** 1.12.3 
- **Git version:** 2.24.3
- **Operating system:** Docker container https://hub.docker.com/layers/gitea/gitea/1.12.3/images/sha256-38b8222941d8acffb7bb9c3fb0e9e0b657e06815a090f1fb11ed6900a3c9f384?context=explore
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description

When logging in, and after proving a correct two-factor auth token, I am shown a 5XX error. The logs don't provide a stack trace so can't see where in the code it's breaking.

```
[Macaron] 2020-08-01 23:10:07: Started POST /user/two_factor for 10.244.1.1
[Macaron] 2020-08-01 23:10:07: Completed POST /user/two_factor 500 Internal Server Error in 19.568867ms
```

**Comment by techknowlogick** [comment]
Here is documentation on logging that might be helpful: https://docs.gitea.io/en-us/logging-configuration/#the-xorm-logger you can enable DB logging, and you may also want to set your log level for general logs to trace as then you can get a lot more logs.

**Comment by nodesocket** [comment]
@techknowlogick ok, I need to dig into the Kubernetes Helm chart and find where to update this value and how to re-deploy the pods with `LEVEL = Trace`.

**Comment by techknowlogick** [comment]
Which helm chart are you using? I believe that our official one uses a ConfigMap to store the app.ini

**Comment by nodesocket** [comment]
```
# chart.yaml
name: gitea
version: 1.9.3
appVersion: 1.12.3
description: Git with a cup of tea
icon: https://docs.gitea.io/images/gitea.png
keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
sources:
  - https://github.com/go-gitea/gitea
  - https://hub.docker.com/r/gitea/gitea/
maintainers:
  - name: John Felten
    email: john.felten@gmail.com
```

I went in and modified `templates/gitea/gitea-config.yaml` and updated to `LEVEL = 'Trace``. The problem is getting the deployment to rebuild. Doing:

```
helm upgrade --install gitea --values gitea.yaml ./
```

Did not re-deploy the pods.
