### ISSUE TITLE
Add healthchecks to docker image 

### ISSUE THREAD

**Issue by ToeiRei** [go-gitea/gitea#12443]
- Gitea version (or commit ref):
- Git version:
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Docker can check containers for if their services are alive. This can/should be built into the container image itself and is basically a command that checks if the service is alive and kicking.

**Comment by zeripath** [comment]
PRs are welcome

**Comment by modem7** [comment]
It would be easy enough if the API had some form of public /health endpoint. 

If that occurred, we'd be able to do a healthcheck with something like:

```
    healthcheck:
      test: curl -fSs 127.0.0.1:3000/api/v1/health || exit 1
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 3
```
