### ISSUE TITLE
SSH keeps restarting / receiving signal 15 (and DISABLE_SSH does not work)

### ISSUE THREAD

**Issue by Piscator74** [go-gitea/gitea#12592]
I've just setup the latest gitea version (and version 1.12.3) with a docker image following the instructions at:
https://docs.gitea.io/en-us/install-with-docker/. All the mapped data folders / mysql folders are created from scratch (so no prior data)

I have used the following docker compose:

```
version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.12.3
    environment:
      - USER_UID=0
      - USER_GID=0
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=XXXXXXXXXX
      - DOMAIN=mydomain
      - ROOT_URL=http://mydomain:3000/
    restart: always
    networks:
      - gitea
    volumes:
      - /share/docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - "3000:3000"
       - "20122:22"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXXX
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=XXXXXXXXXX
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /share/docker/gitea/mysql:/var/lib/mysql
```

The log shows the following (ssh keeps restarting, sometimes signal 15)
```
server_1  | Received signal 15; terminating.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Received signal 15; terminating.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Received signal 15; terminating.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Received signal 15; terminating.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Received signal 15; terminating.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | Received signal 15; terminating.
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
```

I have tried plenty of things, but the following does not make any difference.
- https://github.com/go-gitea/gitea/issues/10422. Deleted /data/queues, no difference.
- I started out with an account that had limited permissions (different UID / GID), so I also did retry with root UID, no difference.
- I tried disabling the SSH server with DISABLE_SSH=true, no difference.
- I tried different versions (latest and 1.12.3)

Any suggestions how I can debug where this problem is coming from or how I can fix it?

Thanks
