### ISSUE TITLE
Hint to the "SSH Container Passthrough" / "Installation with Docker" docs

### ISSUE THREAD

**Issue by eheidt** [go-gitea/gitea#12625]
- Gitea version (or commit ref):
  - latest
- Git version:
- Operating system:
  - ubuntu 20.04 docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

We followed the [Installation with Docker](https://docs.gitea.io/en-us/install-with-docker/), but afterwards cloning via SSH did not work.
After some investigation, we found out that the "soft link" to authorized_keys was the problem. Making it as "hard link" solved the problem at first - we have not figured out why. After some time, we run into same problem, when somebody has added a new ssh key in his account.
After a second investigation we found out, that gitea is doing backups on the autorizid_keys - so the "hard link" was pointing to an old backup.

The final solution is mounting the git users ".ssh" directory directly into the gitea docker-container, with the additional entry under volumes: `- /home/git/.ssh/:/data/git/.ssh/`
Maybe it should be mentioned in https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough

````
services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
+      - DB_TYPE=postgres
+      - DB_HOST=db:5432
+      - DB_NAME=gitea
+      - DB_USER=gitea
+      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /home/git/.ssh/:/data/git/.ssh/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
````
