### ISSUE TITLE
docker-compose failed because invalid port specification: "1981342"

### ISSUE THREAD

**Issue by shui** [go-gitea/gitea#13413]
- Gitea version (or commit ref): latest
- Git version:
- Operating system: Ubuntu 20.04
  
  
  
- Database (use `[x]`):
  - [x] mariadb:10
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
  <https://gist.github.com/shui/559432daa9eef1bc70bceec19628fa82#file-log-md>

## Description

Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.25.0, build unknown

I used quick set-up docker-compose file (<https://hub.docker.com/r/gitea/gitea>):
```
version: '2'
services:
  web:
    image: gitea/gitea:latest
    container_name: gitea-web
    volumes:
      - ./data:/data
    ports:
      - 33000:3000
      - 33022:22
    depends_on:
      - db
    restart: always
    
  db:
    image: mariadb:10
    container_name: gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    volumes:
      - ./db/:/var/lib/mysql
    restart: always
```
and:
```
~/gitea$ tree
.
├── data
├── db
└── docker-compose.yml
```
But `docker-compose up -d` failed:
```
~/gitea$ docker-compose up -d
gitea-db is up-to-date
Creating gitea-web ... error

ERROR: for gitea-web  Cannot create container for service web: b'invalid port specification: "1981342"'

ERROR: for web  Cannot create container for service web: b'invalid port specification: "1981342"'
ERROR: Encountered errors while bringing up the project.
```

## Screenshots

![image](https://user-images.githubusercontent.com/6127969/98018907-17236a00-1e3c-11eb-9d6e-30c897501b07.png)
