### ISSUE TITLE
Docker : ``failed to create '/etc/gitea/app.ini': mkdir /etc/gitea: permission denied`` (had to create it manually)

### ISSUE THREAD

**Issue by Xav-Pe** [go-gitea/gitea#13456]
- Gitea version (or commit ref): 1.14.0+dev-162-g82cf67a93 built with GNU Make 4.3, go1.15.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.20.1
- Operating system: Debian GNU/Linux 10
- Docker : Docker version 19.03.13, build 4484c46d9d
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description

After the installation with docker-compose, when I pushed my repo, I had this error : 

```bash
root@myserver:~/myrep# git push
Enumerating objects: 69, done.
Counting objects: 100% (69/69), done.
Delta compression using up to 4 threads
Compressing objects: 100% (41/41), done.
Writing objects: 100% (43/43), 7.64 KiB | 1.27 MiB/s, done.
Total 43 (delta 35), reused 0 (delta 0)
remote: 2020/11/07 15:04:37 ...s/setting/setting.go:749:NewContext() [F] failed to create '/etc/gitea/app.ini': mkdir /etc/gitea: permission denied
To ssh://git.myserver.com:222/myuser/myrep.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@git.myserver.com:222/myuser/myrep.git'
```

After spending a lot of time, I finally did this : 

```bash
$ docker exec -it gitea bash
bash-5.0# cd /etc
bash-5.0# mkdir gitea
bash-5.0# cp /data/gitea/conf/app.ini /etc/gitea/
bash-5.0# chown -R git gitea
```

And *voilà*, I was able to push : 

```
# git push
Enumerating objects: 69, done.
Counting objects: 100% (69/69), done.
Delta compression using up to 4 threads
Compressing objects: 100% (41/41), done.
Writing objects: 100% (43/43), 7.64 KiB | 1.27 MiB/s, done.
Total 43 (delta 35), reused 0 (delta 0)
remote: . Processing 1 references
remote: Processed 1 references in total
To ssh://git.myserver.com:222/myuser/myrep.git'
   572c448..64c26e0  master -> master
```

This error is reproduced every time I stop+prune the container then ``docker-compose up -d`` again.
Did I miss something?
The problem appears only when push; every other operations on the website works fine.

## Configuration

docker-compose.yml (I think you can ignore traefik)

```yml
version: "3.8"
volumes:
  gitea:
  data:
  mysql:
networks:
  traefik:
    external:
      name: traefik_web
  internal:

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    labels:
      traefik.enable: true
      traefik.http.routers.gitea-http.rule: "Host(`git.myserver.com`)"
      traefik.http.routers.gitea-http.entrypoints: web
      traefik.http.routers.gitea-https.rule: "Host(`git.myserver.com`)"
      traefik.http.routers.gitea-https.tls: true
      traefik.http.routers.gitea-https.entrypoints: websecure    
      traefik.http.services.gitea-service.loadBalancer.server.port: 3000
      traefik.docker.network: traefik_web

    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=PASSWORD
    restart: always
    networks:
      - traefik
      - internal
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=PASSWORD
      - MYSQL_DATABASE=gitea
    networks:
      - internal
    volumes:
      - mysql:/var/lib/mysql
```

app.ini : 

```ini
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH    = /data/gitea
DOMAIN           = git.myserver.com
SSH_DOMAIN       = git.myserver.com
HTTP_PORT        = 3000
ROOT_URL         = https://git.myserver.com/
DISABLE_SSH      = false
SSH_PORT         = 222
SSH_LISTEN_PORT  = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/git/lfs
LFS_JWT_SECRET   = SECRET
OFFLINE_MODE     = false

[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = mysql
HOST     = db:3306
NAME     = gitea
USER     = gitea
PASSWD   = SECRET
LOG_SQL  = false
SCHEMA   =
SSL_MODE = disable
CHARSET  = utf8mb4

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER        = file

[picture]
AVATAR_UPLOAD_PATH            = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
DISABLE_GRAVATAR              = false
ENABLE_FEDERATED_AVATAR       = true

[attachment]
PATH = /data/gitea/attachments

[log]
MODE                 = console
LEVEL                = info
REDIRECT_MACARON_LOG = true
MACARON              = console
ROUTER               = console
ROOT_PATH            = /data/gitea/log

[security]
INSTALL_LOCK   = true
SECRET_KEY     = SECRET
INTERNAL_TOKEN = SECRET.SECRET.SECRET-SECRET

[service]
DISABLE_REGISTRATION              = false
REQUIRE_SIGNIN_VIEW               = false
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_ENABLE_TIMETRACKING       = false
NO_REPLY_ADDRESS                  =

[oauth2]
JWT_SECRET = SECRET

[mailer]
ENABLED = false

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false
```
