### ISSUE TITLE
Invalid clone URL for SSH in empty repo view if SSH port is not 22

### ISSUE THREAD

**Issue by kacperaniolek** [go-gitea/gitea#13574]
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
running gitea with docker compose (see below)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (no port number is required)
- Log gist:
`docker-compose.yml`:
```yml
version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=localhost:3022
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3022:22"
```

## Description
I run Gitea as a container and forward port 3022 to the container's port 22. I've found out that clone URLs provided for my repos are malformed:

```shell
kacper@kngl:~/git/gitea$ touch README.md
kacper@kngl:~/git/gitea$ git init
Initialized empty Git repository in /home/kacper/git/gitea/.git/
kacper@kngl:~/git/gitea[master]$ git add README.md
kacper@kngl:~/git/gitea[master]$ git commit -m "first commit"
[master (root-commit) 801f90b] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
kacper@kngl:~/git/gitea[master]$ git remote add origin git@localhost:3022:Kangel/example.git
kacper@kngl:~/git/gitea[master]$ git push -u origin master
ssh: connect to host localhost port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

However, if I modify the URL, it works just fine:
```shell
kacper@kngl:~/git/gitea[master]$ git remote remove origin 
kacper@kngl:~/git/gitea[master]$ git remote add origin ssh://git@localhost:3022/Kangel/example.git
kacper@kngl:~/git/gitea[master]$ git push -u origin master
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 218 bytes | 218.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: . Processing 1 references
remote: Processed 1 references in total
To ssh://localhost:3022/Kangel/example.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
```
(note thee `ssh://` and a slash following the port number)

## Screenshots
![image](https://user-images.githubusercontent.com/9115856/99191499-5a9ba380-276d-11eb-9985-e7ae57791d9b.png)
