### ISSUE TITLE
Allow to disable local login

### ISSUE THREAD

**Issue by n0emis** [go-gitea/gitea#13606]
- Gitea version (or commit ref): 1.12.6
- Git version: N/A
- Operating system: N/A
  
  
  
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description
When using gitea in an environent (e.g. corporate deployment) when SSO login is required, it would be nice to have a way to disable local login, to not have a confusing login-page, which can't be used.

A nice extra would be that, when only one authentication-source is configured, clicking on the "Sign in" button on the header automatically redirects to the IdP/SSO.

**Comment by jolheiser** [comment]
> +1. 1 year and still no response from the Gitea team. For how long we'll be waiting? This request is pretty valid.

Unfortunately none of us are paid to work on Gitea, we are all volunteers. 
You are more than welcome to send in a PR for us to review. :slightly_smiling_face: 

Alternatively, putting a bounty on an issue has worked to get things done more quickly in the past.

**Comment by MrMelon54** [comment]
This sounds very useful maybe I'll work on it in the near future?

**Comment by ranomier** [comment]
Maybe just add a option to hide it and put it on a different URL.

So its still available but most users wont see it.

**Comment by dodedodo** [comment]
In the meantime, you could use a http redirect from `/user/login*` to gitea's sso login url. In my case (traefik, authentik and gitea) the redirect rule looks like this: 

``` yaml
…
labels: 
     …
      - "traefik.http.routers.gitea.middlewares=gitea-login-redirect"
      - "traefik.http.middlewaresgitea-login-redirect.redirectregex.regex=^https://gitea.redacted.tld/user/login*"
      - "traefik.http.middlewares.gitea-login-redirect.redirectregex.replacement=https://gitea.redacted.tld/user/oauth2/Authentik-oid"
…
```

`/Authentik-oid` is the name i've assigned to gitea's authentication provider. 

I imagine this would work for other webservers and proxies as well.

**Comment by techknowlogick** [comment]
@dodedodo For authentik are you using the oidc connector for gitea logins ?

**Comment by dodedodo** [comment]
> @dodedodo For authentik are you using the oidc connector for gitea logins ?

@techknowlogick Yes I am. There's a very detailed [guide in the authentik documentation](https://goauthentik.io/integrations/services/gitea/).

**Comment by techknowlogick** [comment]
@dodedodo oh wow. Thanks for linking that <3

**Comment by MrMelon54** [comment]
Really surprised I didn't think of using a redirect on my reverse proxy. Thanks :+1:

**Comment by mcrapts** [comment]
> In the meantime, you could use an http redirect from `/user/login*` to gitea's sso login url. In my case (traefik, authentik and gitea) the redirect rule looks like this:
> 
> ```yaml
> …
> labels: 
>      …
>       - "traefik.http.routers.gitea.middlewares=gitea-login-redirect"
>       - "traefik.http.middlewaresgitea-login-redirect.redirectregex.regex=^https://gitea.redacted.tld/user/login*"
>       - "traefik.http.middlewares.gitea-login-redirect.redirectregex.replacement=https://gitea.redacted.tld/user/oauth2/Authentik-oid"
> …
> ```
> 
> `/Authentik-oid` is the name i've assigned to gitea's authentication provider.
> 
> I imagine this would work for other webservers and reverse proxies as well.

Thank you, this works. For anyone using Caddy, I did it like this:
```
gitea.domain.tld {
  rewrite /user/login /user/oauth2/authelia
  reverse_proxy <host>:<port>
}
```
Authelia is the name of the authentication provider I configured in Gitea, change it accordingly.

**Comment by nrdev88** [comment]
For anyone using NGINX as a proxy, use this:

`
	location / {
		...
		rewrite ^/user/login.*$ /user/oauth2/synology last;
		...
	}
`

Or at `server` level of course.

**Comment by grachevko** [comment]
> For anyone using NGINX as a proxy, use this:
> 
> ```
> 	location / {
> 		...
> 		rewrite ^/user/login.*$ /user/oauth2/configname last;
> 		...
> 	}
> ```
> 
> Or at `server` level of course.

Sign Out -> Homepage -> Login -> Again Logged In )

**Comment by nrdev88** [comment]
> > For anyone using NGINX as a proxy, use this:
> > ```
> > 	location / {
> > 		...
> > 		rewrite ^/user/login.*$ /user/oauth2/configname last;
> > 		...
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or at `server` level of course.
> 
> Sign Out -> Homepage -> Login -> Again Logged In )

What's your point?

**Comment by darkguy2008** [comment]
> > > For anyone using NGINX as a proxy, use this:
> > > ```
> > > 	location / {
> > > 		...
> > > 		rewrite ^/user/login.*$ /user/oauth2/configname last;
> > > 		...
> > > 	}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Or at `server` level of course.
> > 
> > 
> > Sign Out -> Homepage -> Login -> Again Logged In )
> 
> What's your point? Be clear please.

A workaround for something that should have been looked into in the 3 years that have passed, maybe?

**Comment by grachevko** [comment]
> > > For anyone using NGINX as a proxy, use this:
> > > ```
> > > 	location / {
> > > 		...
> > > 		rewrite ^/user/login.*$ /user/oauth2/configname last;
> > > 		...
> > > 	}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Or at `server` level of course.
> > 
> > 
> > Sign Out -> Homepage -> Login -> Again Logged In )
> 
> What's your point? Be clear please.

Can't sign out, instant redirect by chain above

**Comment by lukaslangrock** [comment]
If you mean that, when you manually click on login, you are automatically logged in without needing to do anything, then that's normal. You are still logged in with your oauth2 provider and thus, when you go to the login page and are getting redirected to `/user/oauth2/<configname>`, gitea will send you off to the corresponding oauth2 provider, who will then (most likely) authenticate you without requiring interaction, since you are logged in there and have previously authenticated to gitea before.

So by the process of logging out of gitea and then clicking login, you will most likely, unless your auth provider is set up to always ask you for permission, be logged in without needing to do anything.

If you wish that logging out of gitea will require entering a password etc. to log back in, you need to log out of your oauth2 provider too. oauth2 can do this automatically, but it seems like gitea does not fully support that yet. See #14270.

*I am still a noob when it comes to oauth2 and that whole realm, so I might be totally wrong here. The way I described it is the way it works on my server.*

**Comment by tuxmainy** [comment]
> 

Works like a charm. Might not be an option if you use multiple OAuth2/OpenID providers.

**Comment by tuxmainy** [comment]
> In the meantime, you could use an http redirect from `/user/login*` to gitea's sso login url. In my case (traefik, authentik and gitea) the redirect rule looks like this:
> 
> ```yaml
> …
> labels: 
>      …
>       - "traefik.http.routers.gitea.middlewares=gitea-login-redirect"
>       - "traefik.http.middlewaresgitea-login-redirect.redirectregex.regex=^https://gitea.redacted.tld/user/login*"
>       - "traefik.http.middlewares.gitea-login-redirect.redirectregex.replacement=https://gitea.redacted.tld/user/oauth2/Authentik-oid"
> …
> ```
> 
> `/Authentik-oid` is the name i've assigned to gitea's authentication provider.
> 
> I imagine this would work for other webservers and reverse proxies as well.

Works like a charm. Might not be an option if you use multiple OAuth2/OpenID providers.

**Comment by pat-s** [comment]
Here's a resource definition for k8s

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingressClassName: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /user/oauth2/<your oauth2 provider name>/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: rewrite
  namespace: gitea
spec:
  rules:
    - host: <gitea url>
      http:
        paths:
          - backend:
              service:
                name: gitea-http
                port:
                  number: 3000
            path: /user/login.*$
            pathType: Prefix

  tls:
    - hosts:
        - <gitea url>
      secretName: <gitea url>-tls
```

**Comment by joestump** [comment]
For anyone using Nginx Proxy Manager you can add the following in the Advanced tab of your Proxy Host:

```
location ~ ^/user/login.*$ {
  return 301 /user/oauth2/Authentik;
}
```

**Comment by zc-devs** [comment]
Gitea 1.21.5, Keycloak 23.0.7, Traefik 2.10.5, Kubernetes.
Gitea is configured with Authentication Source:
```
Authentication Type: OAuth2
Authentication Name: keycloak
```
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
spec:
  routes:
    - kind: Rule
      match: Host(`gitea.example.org`)
      services:
        - name: gitea
          port: http
    - kind: Rule
      match: Host(`gitea.example.org`) && Path(`/user/login`)
      middlewares:
        - name: gitea-login-replace
      services:
        - name: gitea
          port: http
```
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gitea-login-replace
spec:
  replacePath:
    path: /user/oauth2/keycloak
```
