### ISSUE TITLE
[Enhancement] Project boards / KanBan: Compact view mode

### ISSUE THREAD

**Issue by dphdave** [go-gitea/gitea#13814]
I've just started trying out the new Project boards / KanBan feature, which is really great, however there are a number of things that would need to be improved before it is really usable for me:

When you have a project (as in repo) with many hundreds of open issues, the KanBan board would be a great place to try to get an overview of a subset of these. However, when issues have a usefully descriptive name thats wraps to 2 or more lines, a milestone assigned and several labels, they take up a lot of screen space in the project 'board' or column, such that my board is full with only 3 issues and I have to use the horizontal scroll to see the rest. Thus it is pretty hard to get an overview, rendering the purpose of the board fairly useless. It is still much easier for me to get an overview of a particular category / status of issues by using labels.

![Gitea feedback](https://user-images.githubusercontent.com/58987011/101018188-0bbe7e00-3563-11eb-83ef-14f6195dd07f.png)

We need a view mode where 10s of issues can be seen within the 'board' without horizontally scrolling.

**Comment by SpyceTewan** [comment]
The horizontal scrolling is really filthy. It seems to be a flex container that wraps to the next column if needed. I'd just avoid flex here completely and make those elements normal blocks in sequence

I made a dirty quickhack to override horizontal scrolling
```css
.board-column > .cards {
    flex: 0;
    display: block;
    height: 100%;
    flex-grow: 1;
}

.ui.cards {
    flex-wrap: nowrap;
}

.ui.card, .ui.cards > .card {
    display: block;
    min-height: 3rem;
}

.ui.cards > .card {
    margin-bottom: 0.5rem !important;
}
```
**This snippet shouldn't get pushed into the repo somewhere, but just be taken as a reference point**

![image](https://user-images.githubusercontent.com/31664665/102057892-f4975000-3dee-11eb-87c3-93c13e54e8a0.png)
