### ISSUE TITLE
Avatars not persist docker

### ISSUE THREAD

**Issue by vdeville** [go-gitea/gitea#14176]
- Gitea version (or commit ref): 1.13
- Git version: Docker built-in
- Database:
  - [x] MySQL
## Description
Hello,

I use gitea inside docker but today after multiple deletion and creation of the container with mapped data to a volume, i found a bug. Organization avatars not persists.
Here, my `docker-compose.yaml` file:
```
version: '3'
services:
  web:
    image: gitea/gitea:1.13
    volumes:
      - git_data:/data
      - ./app.ini:/data/gitea/conf/app.ini
    ports:
      - "127.0.0.1:3000:3000"
      - "2222:22"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=xx
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=xx
    volumes:
      - db_data/:/var/lib/mysql

volumes:
  db_data:
  git_data:
```

## Screenshots

<img width="123" alt="Capture d’écran 2020-12-29 à 00 22 59" src="https://user-images.githubusercontent.com/6104498/103248683-03900d80-496c-11eb-9235-b346a0ffcb3d.png">
