### ISSUE TITLE
Gitea persistent storage config

### ISSUE THREAD

**Issue by songmeo** [go-gitea/gitea#14451]
Gitea version: 1.13.1
  
  
  

## Description
https://github.com/go-gitea/gitea/issues/14176#issuecomment-752671335

It's not documented that only data partition is persistent and everything under /app/gitea/data is not. This is not only about avatars but also other things like attachments, mail queues, etc. What if people restart their Gitea instances and find out that all data not under /data is lost?

**Comment by t-rood** [comment]
here, too. easy to showcase by removing the container and adding back in. is it "supported" to add a volume link to /app/gitea/data AFTER the initial setup has completed or can we move the respective locations back to the default mapped volume path using app.ini?

**Comment by wxiaoguang** [comment]
It sounds like this problem need to be looked into

**Comment by lafriks** [comment]
It's not supposed to have something in `/app/gitea/data`. How did it end up there?
Everything should be under `/data`
https://github.com/go-gitea/gitea/blob/main/Dockerfile#L59 

or under `/var/lib/gitea` and `/etc/gitea` for rootless docker:
https://github.com/go-gitea/gitea/blob/main/Dockerfile.rootless#L68

**Comment by t-rood** [comment]
when I upload a custom avatar picture for a user or an organization, they are displayed fine even after container restart. If I then throw away and recreate the docker container, the icons are broken. I use the default folder/volume mappings as shown below, so where are those uploads stored if not on /data mapping?

this is my compose.yml extract:

```
    volumes:
      - '/volume1/docker/gitea1/data/:/data/'
      - '/volume1/docker/gitea1/conf/app.ini:/data/gitea/conf/app.ini'
      - '/etc/localtime:/etc/localtime:ro'
```

**Comment by lafriks** [comment]
What values for paths do you have in app.ini?

**Comment by t-rood** [comment]
copied from runtime instance right after first initialization, as below:

```
APP_NAME = xxx
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gitea
USER     = gitea
PASSWD   = 
SCHEMA   = 
SSL_MODE = disable
CHARSET  = utf8
PATH     = /data/gitea/data/gitea.db
LOG_SQL  = false

[repository]
ROOT = /data/gitea/data/gitea-repositories

[server]
SSH_DOMAIN       = git
DOMAIN           = git
HTTP_PORT        = 3000
ROOT_URL         = http://xxx:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/gitea/data/lfs
LFS_JWT_SECRET   = xxx
OFFLINE_MODE     = false
LANDING_PAGE     = login

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
DISABLE_REGISTRATION              = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[session]
PROVIDER = file

[log]
MODE      = console
LEVEL     = info
ROOT_PATH = /data/gitea/log
ROUTER    = console

[security]
INSTALL_LOCK       = true
INTERNAL_TOKEN     = xxx
PASSWORD_HASH_ALGO = pbkdf2
```

**Comment by lafriks** [comment]
Just noticed in issue description it says you are running 1.13.1, that's right? It's quite old one

**Comment by lafriks** [comment]
You should upgrade to at least 1.15.x or 1.16.0. I think there have been quite a lot changes related to paths as we have quite same bunch of problems due to how historically paths was handled

**Comment by t-rood** [comment]
I added back to a historic thread, my bad. I'm deploying via :latest tag which displays "1.16.0 built with GNU Make 4.3, go1.17.6"

**Comment by t-rood** [comment]
overlapping posts? :latest-Tag ....

**Comment by t-rood** [comment]
and I started with this version. never used any older build. just sayin'. But isn't it "interesting" I'm facing the same historiy issue, so maybe a regression?

**Comment by lafriks** [comment]
I just spent 10 minutes looking for this issue :D it's 2021 jan not 2022 :D

Anyway I can not reproduce this issue. Just deployed new gitea instance with `:latest` tag and all paths are correct.

I used such stack yaml:
```yaml
version: '3.5'
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: 
          - node.platform.os==linux
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gitea-test.rule=Host(`test-domain`)"
        - "traefik.http.routers.gitea-test.entrypoints=web-secure"
        - "traefik.http.routers.gitea-test.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.gitea-test.loadbalancer.server.port=3000"
    networks:
      - internal
      - public
    volumes:
      - gitea:/data
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: 
          - node.platform.os==linux
          - node.role==manager
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - internal
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  internal:
  public:
    external: true

volumes:
  gitea:
  postgres:
```
