### ISSUE TITLE
Error CAfile: none CRLfile Nginx Proxy Docker

### ISSUE THREAD

**Issue by MarioProjects** [go-gitea/gitea#14948]
I am trying to use gitea with MySQL and nginx proxy. All its fine and running but when I try to clone a repository says `server certificate verification failed. CAfile: none CRLfile` If I run `git clone -c http.sslverify=false https://myrepo.git` no problems and cloned correctly. I have a `.crt` and `.key` and placed as suggested at

```
mkdir /usr/local/share/ca-certificates/extra
mv my_ca.crt /usr/local/share/ca-certificates/extra/
update-ca-certificates
```
But got 
```
Warning! Cannot copy to bundle: /usr/local/share/ca-certificates/extra
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
WARNING: ca-cert-extra.pem does not contain exactly one certificate or CRL: skipping
```

_Originally posted by @liberodark in https://github.com/go-gitea/gitea/issues/11013#issuecomment-611392731_

**Comment by zeripath** [comment]
We need more information. What is emiting this warning? These are not gitea logs and therefore I don't think this is coming from us.

Please also complete the proforma. It is therefore for a reason.

**Comment by MarioProjects** [comment]
Sorry maybe I should start step by step. To reproduce that first I launch nginx proxy:

```
docker run -d -p 80:80 -p 443:443 -v /home/maparla/ssl_nginx_proxy/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro --name nginx-proxy jwilder/nginx-proxy
```
And create at `/home/maparla/ssl_nginx_proxy/certs` the files `gitea.maparla.es.key` and `gitea.maparla.es.crt`.

Then I launch gitea with MySQL with:

```
version: "3"

services:
  server:
    image: gitea/gitea:1.13.3
    container_name: gitea-web
    network_mode: bridge
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "80"
      - "22"
    ports:
      - "80"
      - "22"
    environment:
      - VIRTUAL_HOST=gitea.maparla.es
      - HTTP_PORT=80
      - USER_UID=1000
      - USER_GID=1000
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gitea-db
    network_mode: bridge
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql
```

Using `docker-compose up -d`. I can access with gitea.maparla.es properly and perform installation using this params:

```
# Register -> 
#    Database Type: MySQL
#    Host: 192.168.1.91:3306
#    Username: gitea
#    Password: gitea
#    Database Name: gitea

#    Set Title: Whatever you want
#    SSH Server Domain: gitea.maparla.es/
#    Gitea Base URL: https://gitea.maparla.es/
```

Okey! All running and I create my first repo! But now when I perform git clone errors!

```
server certificate verification failed. CAfile: none CRLfile
```

If I use `git clone -c http.sslverify=false https://myrepo.git` all fine but I don't want to use that
