### ISSUE TITLE
Align Project board cards vertically, not horizontally

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#15506]
- Gitea version (or commit ref): 1.15.0+dev-152-gc29e85228 
- Can you reproduce the bug at https://try.gitea.io:
  - Yes : [here](https://try.gitea.io/delvh/kanban-test/projects/577)

## Description
Currently, project board cards are aligned horizontally when larger than the underlying project board.
I (and all other Gitea users I have spoken to) think that that is not exactly user friendly.

#13814 is at least partially related to this, but I thought it differs so much that creating its own unique issue for it would be adequate.

## What to do
Through some testing, I found out that that behavior is caused by exactly one line of css, which, when removed completely solves this issue on the current try.gitea.io status (don't know whether it applies to older versions too).

The responsible css block is
```css
.board-column > .cards {
    flex: 1;
    display: flex;
    flex-direction: column;
    margin: 0 !important;
    padding: 0 !important;
}
```
Simply remove ~~flex-direction: column;~~ and the problem is fixed, at least on my Browser (Firefox). The corresponding file should be `_repository.less` (exact path is web_src/less/_repository.less), line 2978

## Screenshots

![image](https://user-images.githubusercontent.com/51889757/114992393-feaf8500-9e9a-11eb-8f0a-ae667489cb7f.png)
How it is, but not how it should be
