### ISSUE TITLE
SSH not working with gitea on kubernetes.

### ISSUE THREAD

**Issue by kristvanbesien** [go-gitea/gitea#15907]
- Gitea version (or commit ref): 1.14.2
- Git version:
- Operating system:
Fedora IOT, Kubernetes 1.21.1 

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

Deployed gitea on kubernetes with the following deployment config:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea-repo
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.13.2
        ports:
        - containerPort: 3000
          name: gitea
        - containerPort: 22
          name: git-ssh
        volumeMounts:
        - mountPath: /data
          name: git-data
      volumes:
      - name: git-data
        persistentVolumeClaim:
          claimName: git-pvc
```

This does work. Web console is available. Can create users, repositories etc...
I can do git clone/push/pull using http. However I cannot do this using SSH.

I get this error: 

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Testing with SSH I get: 

```
ssh -v  git@git.kri.st
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/krist/.ssh/config
debug1: /Users/krist/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to git.kri.st port 22.
debug1: Connection established.
debug1: identity file /Users/krist/.ssh/id_rsa type 0
debug1: identity file /Users/krist/.ssh/id_rsa-cert type -1
debug1: identity file /Users/krist/.ssh/id_rsa_new type 0
debug1: identity file /Users/krist/.ssh/id_rsa_new-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.4
debug1: match: OpenSSH_8.4 pat OpenSSH* compat 0x04000000
debug1: Authenticating to git.kri.st:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
Connection reset by 192.168.80.2 port 22
```

And in the logs I see:

```
chroot("/var/empty"): Operation not permitted [preauth]
```

I think that error message points towards the underlying cause. But I don't know how to fix this.
