### ISSUE TITLE
Webui does not reflect repository after push  

### ISSUE THREAD

**Issue by LeducH** [go-gitea/gitea#15994]
- Gitea version (or commit ref): Gitea Version: 1.14.2 
- Git version: git version 2.31.1
- Operating system: 
- OS: Arch Linux x86_64 
Kernel: 5.12.6-arch1-1 

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.14.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=984
      - DISABLE_REGISTRATION=true
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/shared/AppData/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3030:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - /mnt/shared/AppData/gitea/postgres:/var/lib/postgresql/data
```
