### ISSUE TITLE
docker DISABLE_SSH and DISABLE_REGISTRATION environment variables not working

### ISSUE THREAD

**Issue by tamis-laan** [go-gitea/gitea#16018]
Using the latest docker version of gitea [docker](https://hub.docker.com/r/gitea/gitea) with docker compose:

``` yml
  gitea:
    image: gitea/gitea
    environment:
      - GITEA__server__DISABLE_SSH=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__repository__DEFAULT_PRIVATE=private
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
```

The settings `GITEA__server__DISABLE_SSH=true` and `GITEA__service__DISABLE_REGISTRATION=true` are not working while `GITEA__repository__DEFAULT_PRIVATE=private` does work. 

Looks like boolean values are not mapped properly?
