### ISSUE TITLE
git ssh push requires password?

### ISSUE THREAD

**Issue by tamis-laan** [go-gitea/gitea#16084]
Using the latest gitea version through docker hub, I have added my ssh key to gitea and I'm trying to push code to an empty repository using ssh. However gitea asks me for a password.

``` yml
  gitea:
    image: gitea/gitea
    environment:
      - GITEA__server__PROTOCOL=http
      - GITEA__server__ROOT_URL=https://my.domain.xyz/
      - GITEA__service__DISABLE_REGISTRATION=1
      - GITEA__repository__DEFAULT_PRIVATE=private
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3003:3000'
      - '2222:22'
    networks:
      - public
```
Gitea is behind a Traefik edge router when it comes to `http/https`, however ssh is directly redirected to port `2222`. 
``` ini
[server]
APP_DATA_PATH    = /data/gitea
DOMAIN           = my.domain.xyz
SSH_DOMAIN       = my.domain.xyz
HTTP_PORT        = 3000
ROOT_URL         = https://my.domain.xyz/
DISABLE_SSH      = false
SSH_PORT         = 2222
SSH_LISTEN_PORT  = 2222
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/git/lfs
PROTOCOL         = http
LFS_JWT_SECRET   = supersecretjasonwebtoken
OFFLINE_MODE     = false

[security]
INSTALL_LOCK                  = true
SECRET_KEY                    = mysecretkey
REVERSE_PROXY_LIMIT           = 1
REVERSE_PROXY_TRUSTED_PROXIES = *
INTERNAL_TOKEN                = supersecret.token.and-stufff
PASSWORD_HASH_ALGO            = superhash

[service]
DISABLE_REGISTRATION              = 1
REQUIRE_SIGNIN_VIEW               = false
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_ENABLE_TIMETRACKING       = false
NO_REPLY_ADDRESS                  =
```
When using `https` everything works fine. Any obvious problems with my setup? Or did I hit some kind of bug?
