### ISSUE TITLE
Unable to upgrade Gitea from 1.14.7 to 1.15.2

### ISSUE THREAD

**Issue by NiklasRosenstein** [go-gitea/gitea#17016]
- Gitea version (or commit ref): 1.14.7
- Git version:
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I want to upgrade my Gitea instance deployed via Docker to 1.15.2. But the server won't start up and actually dies after a minute or so.

```
$ docker-compose up
Starting gitea_server_1 ... done
Attaching to gitea_server_1
server_1  | Server listening on :: port 22.
server_1  | Server listening on 0.0.0.0 port 22.
server_1  | 2021/09/10 20:50:12 cmd/web.go:102:runWeb() [I] Starting Gitea on PID: 14
server_1  | 2021/09/10 20:50:12 cmd/web.go:146:runWeb() [I] Global init
server_1  | 2021/09/10 20:50:12 routers/init.go:74:GlobalInit() [I] Git Version: 2.30.2, Wire Protocol Version 2 Enabledserver_1  | 2021/09/10 20:50:12 routers/init.go:77:GlobalInit() [I] AppPath: /app/gitea/gitea
server_1  | 2021/09/10 20:50:12 routers/init.go:78:GlobalInit() [I] AppWorkPath: /app/gitea
server_1  | 2021/09/10 20:50:12 routers/init.go:79:GlobalInit() [I] Custom path: /data/gitea
server_1  | 2021/09/10 20:50:12 routers/init.go:80:GlobalInit() [I] Log path: /data/gitea/log
server_1  | 2021/09/10 20:50:12 routers/init.go:81:GlobalInit() [I] Run Mode: Prod
server_1  | Received signal 15; terminating.
```

My docker-compose file:

```yml
version: '2'
networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=998   # git
      - USER_GID=1007  # git
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "127.0.0.1:8701:3000"
      - "127.0.0.1:8702:22"
```

However if I go back to `gitea/gitea:1.14.7` Gitea won't start up because the schema version has been increased. Luckily I can change the schema version back via sqlite3 and it works again. 😌 

I have tried to incrementally take versions `1.15.0`, `1.15.1` and `1.15.2` but all have the same issue.

What could be going wrong here?
