### ISSUE TITLE
Cannot customize with docker installation

### ISSUE THREAD

**Issue by mashirozx** [go-gitea/gitea#17385]
### Gitea Version

1.15.4

### Operating System

Offical Docker image

### How are you running Gitea?

Using docker

```yml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.15.4
    container_name: gitea
    environment:
      - USER_UID=1003
      - USER_GID=1003
      # - GITEA_CUSTOM=/data/gitea/custom
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    ports:
      - "110:3000"
      - "222:22"
```

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Description

My mounted directory looks like this:
![image](https://user-images.githubusercontent.com/16148054/138230835-021a149a-e5c6-456a-b27f-bc456c6f0666.png)

The `GITEA_CUSTOM` is `/data/gitea` (in container), other things like app.ini were mounted successfully. 

But when I tried to add a `GITEA_CUSTOM/public/assets/css` path to add custom stylesheets, the request to `https://<DOMAIN>/assets/css/theme-<THEME>.css` always returns 404.

I also found that there is no `templates` directory as described in documentation.
