### ISSUE TITLE
Incorrect font size for PR/issue comment

### ISSUE THREAD

**Issue by proton-ab** [go-gitea/gitea#17480]
### Gitea Version

f46e67b519eb65f6feb8abd04c5c896bfd2001ea

### How are you running Gitea?

Docker image `gitea/gitea:dev-rootless`

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Font size for PR/issue comment is incorrect. It is using 16px inherited from `.markdown` class when it should be using its own overridden 14px. The issue occurred between 58cd55d3535e5afe551610cb74588b33d97786a2 (known good) and 2b2eb5d0ad0a632573da762a151ddae23c5b2e4a (known bad) but since half the commits have broken CI run I can't really test them properly without setting up full development environment.

See this try page for example: https://try.gitea.io/ChristopherHX/actions-on-gitea/pulls/2

On v1.15.6 this is handled by (generated code):
```css
.repository.view.issue .comment-list .comment .content .markup {
    font-size: 14px
}
```

On broken version we can see this instead:
```css
.repository.view.issue .comment-list .comment>.merge-section .markup {
    font-size: 14px
}
```

### Screenshots

Bad (current):
![firefox_2021-10-29_02-44-35](https://user-images.githubusercontent.com/25139420/139355101-bd3fcbaa-2b7e-4db4-90d1-d487a59af2c0.png)

Good (simulated):
![firefox_2021-10-29_02-44-57](https://user-images.githubusercontent.com/25139420/139355115-9ee21287-641a-4991-ab04-d0e594e7e7f4.png)
