### ISSUE TITLE
External OAuth2 works for login once, but shows login page again after reopening browser

### ISSUE THREAD

**Issue by darkguy2008** [go-gitea/gitea#17484]
### Gitea Version

Docker image ( 1.15.4 built with GNU Make 4.3, go1.16.9 : bindata, timetzdata, sqlite, sqlite_unlock_notify )

### Git Version

2.30.2

### Operating System

Docker, Ubuntu 21.10

### How are you running Gitea?

```
  gitea:
    restart: always
    image: gitea/gitea:latest
    environment:
      GITEA__database__DB_TYPE: sqlite3
    ports:
      - 3000:3000
    volumes:
      - ./_data:/data
```

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/darkguy2008/56599c6f4ea65056b30196856d6c4c00

### Description

What the title says, using OAuth login works during a browser session. Once you close the browser and go to the gitea site again, it shows the homepage asking you to login again. Doesn't make sense if I'm already logged in? I have other apps in the same server (i.e. Outline, DroneCI, etc.) and they don't have this behavior.

It works as intended if I do it within the same browser session (a new tab) but if I fully close Chrome and open it again, I get the login page.

### Screenshots

Nothing special, just logging in using the OpenID provider:

![image](https://user-images.githubusercontent.com/6304136/139438835-983f1803-f1ab-4c0f-8e6e-dcf39fb418de.png)
