### ISSUE TITLE
504 on /admin after Gitea upgrade because of large `action` table

### ISSUE THREAD

**Issue by tsunamaru** [go-gitea/gitea#17504]
### Gitea Version

1.15.6 (was: 1.11.1)

### Git Version

N/A

### Operating System

Amazon Linux 2 (EKS)

### How are you running Gitea?

AWS EKS, version 1.17.7

Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea-app
          image: gitea/gitea:1.15.6
          ports:
            - name: ssh
              containerPort: 10022
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: repositories
          resources:
            limits:
              memory: 4000Mi
              cpu: 3500m
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
            readOnly: false
```

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After Gitea upgrade from 1.11.1 to 1.15.6 /admin page doesn't load anymore. Everything other works okay.
We are using AWS NLB behind Gitea, but connecting directly (kubectl port-forward) makes no difference, page still doesn't load.

This is extensively used Gitea instance so logs on debug level very huge (>10Mb for few minutes online), I can't attach them at this moment.
From what I can see, GET request to /admin is started but never completed, causing 504 Gateway timeout after 5 minutes.
If you can, please guide me how I can filter logs output to track down this specific issue with /admin.
