### ISSUE TITLE
Many repositories are broken without any reason 

### ISSUE THREAD

**Issue by qjoly** [go-gitea/gitea#17937]
### Gitea Version

latest

### Git Version

git version 2.30.2

### Operating System

Debian 11

### How are you running Gitea?

I'm using the official Gitea image with a classic Docker (No Swarm, No Cluster). 
Here is my Docker-compose : 
```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:13.1.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
```

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/QJoly/0769800f86072e18c1bf1a6aac442feb#file-gitea-logs

### Description

Hello,
I realized that some repositories of my Git were "broken" (error 500, unable to access the page, impossible to clone).

To conduct the investigation, I went to the settings of the git server and realized that the "HealthCheck" was not good on different repositories .. which have nothing to do with each other (created on different accounts, at distant dates, and which do not even have similar languages).

These deposits are important, and I have no copies. :(

And as I realized quite late, my backups have the same problems. 

ps: I tried to run the container on different machines

### Screenshots

https://i.imgur.com/piCY1Mn.png
https://i.imgur.com/COM5jDI.png
https://i.imgur.com/A0H2oUz.png
