### ISSUE TITLE
Cannot connect gitea with drones, bad request

### ISSUE THREAD

**Issue by deepio** [go-gitea/gitea#18171]
### Gitea Version

1.15.9

### How are you running Gitea?

- I'm using `gitea/gitea:latest` image on a k3s cluster running ARM64 and the same with drones. Has a regression occurred? 
- I have `hostAliases` declared in the deployments but it seems to point to the right location.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: storage-volume
          mountPath: "/data"
          subPath: ""
        env:
        - name: TZ
          value: America/Toronto
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
      nodeSelector:
        kubernetes.io/arch: arm64
      restartPolicy: Always
      hostAliases:
      - ip: "10.10.26.29"
        hostnames:
        - "drones.homelab.com"
        - "gitea.homelab.com"
<snip>
```

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drones
  labels:
    app: drones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drones
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drones
    spec:
      containers:
      - name: drones
        image: drone/drone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: storage-volume
          mountPath: "/data"
          subPath: ""
        env:
        - name: DRONE_GITEA_SERVER
          value: "http://gitea.homelab.com"
        - name: DRONE_SERVER_HOST
          value: "drones.homelab.com"
        - name: DRONE_SERVER_PROTO
          value: "http"
        - name: DRONE_DATADOG_ENABLED
          value: False
        - name: "DRONE_RPC_SECRET"
          valueFrom:
            secretKeyRef:
              name: "gitea-drones"
              key: "DRONE_RPC_SECRET"
        - name: "DRONE_GITEA_CLIENT_ID"
          valueFrom:
            secretKeyRef:
              name: "gitea-drones"
              key: "DRONE_GITEA_CLIENT_ID"
        - name: "DRONE_GITEA_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: "gitea-drones"
              key: "DRONE_GITEA_CLIENT_SECRET"
      restartPolicy: Always
      hostAliases:
      - ip: "10.10.26.29"
        hostnames:
        - "drones.homelab.com"
        - "gitea.homelab.com"
<snip>
```

This is what I see from the logs on gitea.
```
│ 2022/01/03 14:07:01 Started GET /login/oauth/authorize?client_id=my_secret%0A&redirect_uri=http%3A%2F%2Fdrones.homelab.com%2Flogin&response_type=code&state=8866cb397916001e for 10.42.0.1:0                                    │
│ 2022/01/03 14:07:01 ...rs/web/user/oauth.go:683:handleAuthorizeError() [W] Authorization failed: Client ID not registered                                                                                                                                  │
│ 2022/01/03 14:07:01 Completed GET /login/oauth/authorize?client_id=my_secret%0A&redirect_uri=http%3A%2F%2Fdrones.homelab.com%2Flogin&response_type=code&state=8866cb397916001e 400 Bad Request in 22.041745ms
```

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I'm not sure if this is a problem with drones or a problem with gitea, the request from drones seems fine? 

### Screenshots

<img width="1036" alt="edited" src="https://user-images.githubusercontent.com/28245482/147972120-28a14cda-1263-451d-ad78-fafeb1f91d15.png">
