### ISSUE TITLE
Kanban issue sorting

### ISSUE THREAD

**Issue by sidewaysglance** [go-gitea/gitea#18256]
### Gitea Version

1.15.9

### Operating System

Ubuntu 20.04.03

### How are you running Gitea?

```
version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=0
      - USER_GID=0
      - DISABLE_GIT_HOOKS=false
    restart: always
    networks:
      - proxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home:/home
    ports:
      - "3000:3000"
      - "222:22"
networks:
  proxy:
    external: true
```

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Hi,

On my self hosted Gitea instance reordering Kanban issues within a Project Board does not trigger any server request.

On https://try.gitea.io I can see that a `POST` request is sent however.

It looks like the feature was implemented here: https://github.com/go-gitea/gitea/pull/17152 - that was 8th December 2021. The latest dockerhub image was produced 4th January 2022 so I would have thought that it would be in the latest docker image?

Does `image: gitea/gitea:latest` have this feature enabled, if not, when will it please?

Thanks

### Screenshots

![134781852-dd485e63-1d30-4315-87b4-1e55fdda89c5](https://user-images.githubusercontent.com/3285539/149206018-6b87d577-571f-4113-b30e-86e686ca77aa.gif)
