### ISSUE TITLE
Can't push to repository after latest update (Docker)

### ISSUE THREAD

**Issue by odinsride** [go-gitea/gitea#18355]
### Gitea Version

1.16.0+rc1

### Operating System

OpenSUSE Leap + Docker

### How are you running Gitea?

Docker-compose:

```
gitea-db:
    image: lscr.io/linuxserver/mariadb
    container_name: gitea-db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${GITEA_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${GITEA_MYSQL_USER}
      - MYSQL_PASSWORD=${GITEA_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${GITEA_MYSQL_DATABASE}
    volumes:
      - ${APPDATA_BASE}/gitea-db:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=${GITEA_UID}
      - USER_GID=${GITEA_GID}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=${GITEA_MYSQL_DATABASE}
      - GITEA__database__USER=${GITEA_MYSQL_USER}
      - GITEA__database__PASSWD=${GITEA_MYSQL_PASSWORD}
    volumes:
      - ${APPDATA_BASE}/gitea:/data
      - ${BACKUP_BASE}/gitea:/tmp
      - ${GITEA_SSH_PATH}:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"
    depends_on:
      - gitea-db
    restart: unless-stopped
```

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

```
bash: /usr/local/bin/gitea: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
```
