### ISSUE TITLE
per pvc per repo

### ISSUE THREAD

**Issue by nishit93-hub** [go-gitea/gitea#18586]
### Feature Description

Hi, Can we do per pvc per repo with gitea?

**Comment by techknowlogick** [comment]
Could you explain in more detail about what you mean by pvc?

**Comment by nishit93-hub** [comment]
The PVC means is Kubernetes PVC ( persistent volume claim). Currently, I have set up Gitea on kubernetes with 1 PVC and mounted that pvc under path /data.

Now whenever I create a new repository, it creates an under /data mount path. But I want every repository should be created under every different mount path which would be associated with different PVC.

Same thing I am doing by setting my own  GitSCM server on k8s. Here it's manifest.yaml

  ```
      image: ubuntu:latest
        ports:
        - containerPort: 22
        lifecycle:
          postStart:
            exec:
              command: ['/bin/sh', '-c', 'apt update; apt install -y git; apt-get install -y openssh-server tzdata-; /etc/init.d/ssh start; useradd -m git; echo "git:password" | chpasswd; mkdir -p /home/git/.ssh; cp /root/.ssh/* /home/git/.ssh; cp /root/.ssh/git-scm.pub /home/git/.ssh/authorized_keys; for dir in /home/git/repos/*; do(git init --bare "$dir"); chown -R git:git /home/*; done > git-logs.log']
        command: ['sh', '-c', 'sleep 6600']      
        volumeMounts:
        - mountPath: /home/git/repos/wordpress1
          name: git-wordpress1
        - mountPath: /home/git/repos/spring-boot1
          name: git-spring-boot1
        - mountPath: /home/git/repos/dockerfile
          name: git-dockerfile
        - name: ssh-key
          mountPath: /root/.ssh  

```
I am using ubuntu docker image and there I installed git and created bare repos and each repos are mounted to a different mount path. However currently I don't have any UI.

That's why I am checking Gitea so that I can get such configuration and plus UI.
