### ISSUE TITLE
[Design Changes] Make the mobile layout more compact

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18589]
# Introduction

In the mobile view there is a lot of spacing and padding in the directory list of a repo.

![image](https://user-images.githubusercontent.com/97637661/152488003-8ff8050e-698f-4fa2-b0a4-ae54915acfa4.png)

# Proposal

[FiliusPatris](https://codeberg.org/FiliusPatris) tried to inspect the directory list with the firefox devtools and was able to remove the unnecessary spacing with the following css:

```css
.name {
	display: table-cell;
	max-width: 20%;
}

.message {
	display: table-cell;
	width: 100%;
}

.age {
	display: none;
}
```

# Credits

The main idea and the proposed css changes come from the codeberg user [FiliusPatris](https://codeberg.org/FiliusPatris). For further information have a look at the issue on codeberg: https://codeberg.org/Codeberg/Community/issues/190
