### ISSUE TITLE
Unable to set fsGroup other than 1000 in helm chart

### ISSUE THREAD

**Issue by tgckpg** [go-gitea/gitea#19138]
### Gitea Version

1.16.4-rootless

### Operating System

5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

### How are you running Gitea?

Pod failed to run with the following config

values.yaml snippet
```
# Security context is only usable with rootless image due to image design
podSecurityContext:
  fsGroup: 1001

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
#   # Add the SYS_CHROOT capability for root and rootless images if you intend to
#   # run pods on nodes that use the container runtime cri-o. Otherwise, you will
#   # get an error message from the SSH server that it is not possible to read from
#   # the repository.
#   # https://gitea.com/gitea/helm-chart/issues/161
    add:
      - SYS_CHROOT
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001
```

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

**Comment by tgckpg** [comment]
Found a workaround, create a pvc and mount it to `/var/lib/gitea`.

values.yaml
```yaml
extraVolumes:
  - name: var-lib-gitea
    persistentVolumeClaim:
      claimName: var-lib-gitea

# additional volumes to mount, both to the init container and to the main
# container. As an example, can be used to mount a client cert when connecting
# to an external Postgres server.
extraVolumeMounts:
  - name: var-lib-gitea
    mountPath: "/var/lib/gitea"
```
