### ISSUE TITLE
PATCH `/admin/users/:username` API doesn't update login/username

### ISSUE THREAD

**Issue by ash-r1** [go-gitea/gitea#19181]
### Description

I'm calling the API with the body payload below:

```json
{
    "login_name": "nazo",
    "source_id": 0,
    "full_name": "Satoshi Suzuki",
    "admin": false
}
```

I tried several times, `admin`, `full_name`, or other parameters could be updated.
But `login_name` never updates its `login` or `username`.
I also tried to use `username` or `login` instead like below.

```json
{
    "login_name": "nazo",
    "source_id": 0,
    "username": "suzuki_2",
    "login": "suzuki_3",
}
```

So, how can I update the user's login/username by API ?

### Gitea Version

1.16.4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu Linux

### How are you running Gitea?

with docker-compose 

```yml
gitea:
    depends_on:
      - gitea-db
    image: gitea/gitea:1.16.4
    volumes:
      - ./gitea/data:/data
      - ./gitea/etc/s6/gitea/run:/etc/s6/gitea/run
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      USER_UID: '1000'
      USER_GID: '1000'
      # See this: https://github.com/go-gitea/gitea/blob/v1.15.3/docker/root/etc/templates/app.ini
      HTTP_PORT: '8081'
      DISABLE_SSH: 'true'
      LFS_START_SERVER: 'true'
      DB_TYPE: mysql
      DB_HOST: gitea-db
      DB_NAME: gitea
      DB_USER: root
      DB_PASSWD: gitea-password
      INSTALL_LOCK: 'true'
      SECRET_KEY: secret
      DISABLE_REGISTRATION: 'true'
      REQUIRE_SIGNIN_VIEW: 'false'
    ports:
      - '8081:8081'
```

### Database

```yml
gitea-db:
    build: ./gitea/db
    volumes:
      - ./gitea/db/data:/var/lib/mysql
      - ./gitea/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: gitea-password
      MYSQL_DATABASE: gitea
```
