### ISSUE TITLE
The buttons are too short for Russian and Malayalam.

### ISSUE THREAD

**Issue by fruworg** [go-gitea/gitea#19736]
### Description

The problem arises when working with organizations.

### Screenshots

![gitea](https://user-images.githubusercontent.com/96399261/168871814-1c0ed57f-4798-456c-8ce9-763d30ac91fb.png)

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Doesn't matter (Windows 11).

### Browser Version

Doesn't matter (Chrome/101).

**Comment by zeripath** [comment]
The operating system does matter here - as it ascribes what fonts are used. Malayam on Linux uses a smaller font size.

I'm not sure what we can do. The translators are responsible for checking that their translations result in a reasonable UI and or reporting to us when such a translation is not possible.

* Is it not possible to have a shorter translation in these cases? 
* One option is perhaps to stick a max width on these buttons - but that won't work with the current maylayam translation as it's just too big.
* Another is to adjust the css/less:

```less
:lang(ml-IN) .ui.button { // may need a few extra things to make that happen
   padding-left: 0.25em;
   padding-right: 0.25em;
}
```

* Another option is do we need to add a tooltip?
