### ISSUE TITLE
Two PRs are created when using link from Git CLI

### ISSUE THREAD

**Issue by penguineer** [go-gitea/gitea#20268]
### Description

This bug is a bit annoying, because it is hard to reproduce, but it happened multiple times by now. Steps:

1. Create a branch with commits.
2. Push branch to origin via `git push -u origin branchname`
3. Use the link provided in the push response to create a PR.
4. Create the PR from the Web UI.

Sometimes this results in *two* PRs with the same data (but distinct numbers) being created. I have verified that these are treated as individual PRs by individually changing their meta-data. There is only one branch that both PRs share.

Unfortunately this is hard to reproduce, but it happens to often to ignore (especially since closing the 2nd PR also wants to delete the branch).

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

Activating debug logs on the prod server creates a log of logging output. I am happy to follow hints on how to get the right logs efficiently.

### Git Version

From the Docker image.

### Operating System

Docker running on Debian Bullseye.

### How are you running Gitea?

We use the Docker image `gitea/gitea:1.16.8` and set up our container via Ansible:

```yaml
  - name: Setup the docker container for gitea
    docker_container:
      name: gitea
      image: "gitea/gitea:1.16.8"
      pull: true
      state: started
      restart_policy: unless-stopped
      detach: yes
      ports:
      - 127.0.0.1:9002:3000
      - 2222:2222
      env:
        APP_NAME="…"
        RUN_MODE="prod"
        SSH_DOMAIN="…"
        SSH_PORT="2222"
        SSH_START_SERVER="false"
        ROOT_URL="https://gitea.…"
        DISABLE_REGISTRATION="true"
        USER_UID=1000
        USER_GID=1000
      volumes:
      - "/srv/docker/gitea:/data:rw"
```

### Database

SQLite
