### ISSUE TITLE
Cannot get passed initial configuration

### ISSUE THREAD

**Issue by tamis-laan** [go-gitea/gitea#20436]
### Description

Using docker (compose) to host gitea: 

``` yaml
version: '3'

services:
  gitea:
    image: gitea/gitea:1.16.8
    environment:
      - GITEA__server__PROTOCOL=http
      # - GITEA__server__ROOT_URL=https://git.mydomain.com/
      - GITEA__service__DISABLE_REGISTRATION=1
      - GITEA__repository__DEFAULT_PRIVATE=private
      - GITEA__database__DB_TYPE=sqlite3
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3002:3000'
    restart: unless-stopped

volumes:
  gitea:
    name: serv-gitea
```
On http://server:3002 I find the initial configuration screen. There I add the administrator user, password and email. Pressing the `Install Gitea` button starts the browser loading but nothing happens. A refresh again shows the initial configuration screen.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker container

### Database

SQLite
