### ISSUE TITLE
1.17.0 template bug: remote head refers to nonexistent ref unable to checkout

### ISSUE THREAD

**Issue by ajeep8** [go-gitea/gitea#20846]
### Description

I clearly start a docker 1.17.0, then add a repo as template, then add a 2nd repo using the 1st repo template, when I 'git clone 2nd repo', it warning: remote head refers to nonexistent ref unable to checkout.

Then I remove the gitea directory, clearly start a docker 1.16.5, do the same process as above, it correctly git clone. 

Then I run 1.17.0 docker image on the 1.16.5 setup gitea directory, add a 3rd repo using the 1st repo template, when I 'git clon 3rd_repo',  it warning: remote head refers to nonexistent ref unable to checkout.

Then I run 1.16.5 docker image again, it can't start, [F] Your database (migration version: 224) is for a newer Gita, you can not use the newer database for this old Gitea release (211).

So, I think 1.17.0 has bug on add a repo using template, 1.16.5 is OK.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

My docker-compose.yml file: 

```
version: "3.5"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.16.5
    environment:
      - USER_UID=1002
      - USER_GID=1002
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "8122:22"
```
