### ISSUE TITLE
Pre-installation support

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#209]
This feature is very useful for rapidly creating an OEM Gitea instance. All the pre-installation will only need give a specific ini file. This file is not the same as the config.ini.

- [x] set a default database
- [x] set run user
- [x] set a default admin user and password
- [x] add users or organizations
- [x] add auth source
- [x] migrate some git repos. For example, migrate all the repos of mine in github.

**Comment by stevenroose** [comment]
Why would it not be the same as `config.ini`? All the things you mention seem to be configuration variables..

**Comment by lunny** [comment]
The first three could, but the last three cannot

**Comment by stevenroose** [comment]
Hmm. "add auth source" could, see #183. The other two indeed should not. But that are post-installation steps, imo.

**Comment by bkcsoft** [comment]
IMO just create a `gitea admin load <FILE>`-command.

`config.yml` (Yes, I like yaml. And very much hand-written, non-linted, pseudo-yaml)
```
install:
  database:
    type: sqlite
    path: data/gitea.db
    secret: FOOBAR42
  run_user: git
  admin_user:
  - name: admin
    password: foobaz
users:
- name: bkc
  password: foobar42
  admin: false
- name: lunny
  password: badf00d1337
  admin: true
organizations:
- name: octokit
migrate:
- source: https://github.com/octokit/hello-world.git
  namespace: octokit
  name: hello-world
  mirror: false
```
