### ISSUE TITLE
EditUserPost doesn't check email

### ISSUE THREAD

**Issue by pezhovski** [go-gitea/gitea#21075]
### Description

When creating a new user I can't create a user if there is a user with the same email.

When I'm editing user in admin page, I can change email to existing one. 

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Using compose file

```yaml
---
version: "2"

services:
  db:
    image: bitnami/postgresql:latest
    user: 1001
    environment:
      - POSTGRESQL_USER=gitea
      - POSTGRESQL_PASSWORD=gitea
      - POSTGRESQL_DATABASE=gitea
    networks:
      - gitea-network

  gitea:
    image: gitea/gitea:1.17.1-rootless
    user: 1000:1000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    volumes:
      - ./gitea-config:/etc/gitea
      - ./gitea-data:/var/lib/gitea
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - gitea-network

  ldap1:
    image: glauth/glauth
    user: 1000
    volumes:
      - ./ldap-config.cfg:/app/config/config.cfg
    networks:
      - gitea-network
```

### Database

PostgreSQL
