### ISSUE TITLE
Webhook does not work

### ISSUE THREAD

**Issue by MartinLau7** [go-gitea/gitea#21296]
### Description

After I executed Git push, drone did not receive the Webhook notification of GITEA as expected, and I saw the event prompt in the record was warning instead of success.
When I manually use the parameters in GITEA Webhook log, I can send data to successfully trigger Drone-CI construction, but GITEA itself fails to send.
Can you help me check whether this is the problem of GITEA or drone-CI?

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/5416852/192920851-b7c74ca6-7d0f-47b4-9b61-ef1aebdebfa6.png)

### Git Version

git version 2.25.1

### Operating System

Ubuntu 20.04.5 LTS

### How are you running Gitea?

Run through the Docker-Compose deployment.

> Docker-compose.yaml
```yaml
version: "3"

networks:
  gitea:
    external: true
  traefik:
    external: true

services:
  gitea:
    image: gitea/gitea:1.17.2
    container_name: gitea
    environment:
      - USER_UID=888
      - USER_GID=888
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=xxxx
    restart: unless-stopped
    networks:
      - traefik
      - gitea
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "22:22"
    volumes:
      - /home/git/.ssh/:/data/git/.ssh
      - /data/gitea:/data
      - /data/etc/timezone:/etc/timezone:ro
      - /data/etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.giteaweb.middlewares=https-redirect@file"
      - "traefik.http.routers.giteaweb.entrypoints=web"
      - "traefik.http.routers.giteaweb.rule=Host(`git.xxxx.com`)"
      - "traefik.http.routers.giteassl.middlewares=content-compress@file"
      - "traefik.http.routers.giteassl.entrypoints=websecure"
      - "traefik.http.routers.giteassl.tls=true"
      - "traefik.http.routers.giteassl.tls.certResolver=buypass"
      - "traefik.http.routers.giteassl.rule=Host(`git.xxxx.com`)"
      - "traefik.http.services.giteabackend.loadbalancer.server.scheme=http"
      - "traefik.http.services.giteabackend.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.giteassh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.giteassh.tls=true"
      - "traefik.tcp.routers.giteassh.entrypoints=git"
      - "traefik.tcp.routers.giteassh.service=gitea"
      - "traefik.tcp.services.gitea.loadbalancer.server.port=22"
    extra_hosts:
      - "git.xxxx.com:127.0.0.1"

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=xxx
    networks:
      - gitea
    volumes:
      - /data/gitea/postgres:/var/lib/postgresql/data
```

### Database

PostgreSQL
