### ISSUE TITLE
Missing label on linked accounts

### ISSUE THREAD

**Issue by williamdes** [go-gitea/gitea#21318]
### Gitea Version

1.18.0+dev-485-gf82f1d05b

### Can you reproduce the bug on the Gitea demo site?

No (I could not link my account)

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/193455806-09cd2f06-c7aa-470a-9a6f-162e39707ae6.png)

### How are you running Gitea?

With docker

```yml
version: "2.3"

services:
    gitea:
        image: gitea/gitea:dev
```

### Database

MySQL
