### ISSUE TITLE
ssh_exchange_identification: Exceeded MaxStartups

### ISSUE THREAD

**Issue by xtutu** [go-gitea/gitea#21732]
### Description

when i use git pull, I will get an error(it is random， some time will be success）
```bash
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.1.1.212 port 3001
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

ssh -v -T git@10.1.1.212 -p 3001
```bash
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: ssh_exchange_identification: Exceeded MaxStartups

ssh_exchange_identification: Connection closed by remote host

```

### Gitea Version

 1.18.0+rc0 built with GNU Make 4.3, go1.19.2 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.37.1.windows.1

### Operating System

ubuntu 

### How are you running Gitea?

gitea docker-compose

### Database

MySQL

**Comment by bchrao** [comment]
Hello @xtutu. Did you solve this issue? I am experiencing the same issue.

**Comment by xtutu** [comment]
@bchrao  yes. 
You can set " SSH_MAX_SESSIONS & SSH_MAX_STARTUPS " in enviroment to solve this issue.

for example (if you run gitea by docker-compose)
modify the docker-compose.yaml file
```yaml
...
services:
  server:
    image: gitea/gitea:latest
    environment:
      - ...
      - SSH_MAX_SESSIONS=500
      - SSH_MAX_STARTUPS=500:30:2000
```
