### ISSUE TITLE
Forking a private repo from one private organization to another leaks the source organisation name

### ISSUE THREAD

**Issue by kbingham** [go-gitea/gitea#21779]
### Description

I am running gitea 1.17.0 and I have two separate groups that are using the same server.
I wanted to share a project from one group to the other, to provide access to the code pre-release - but did not intend to share the source organisation, as they are separate.

When I forked from organisation1 to organisation2, I get a repository visible to organisation2 with the following message:
```
  organistion2 / uvc-gadget  [Private]
forked from organistion1/uvc-gadget
```

This seems like a leak of private information between the two groups, so I would consider this a 'bug', however it could also simply be a feature request to ask

 "Please ensure that information such as the organisation/customer name is not leaked when forking a project between private organisations."

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

provided by docker : gitea/gitea:1.17.0

### Operating System

Linux

### How are you running Gitea?

Docker compose.
```
version: '2.4'
services:
  web:
    image: gitea/gitea:1.17.0
    volumes:
      - /srv/gitea/data:/data
    expose:
      - 3000
    ports:
      - "4444:22"
    restart: unless-stopped
```

### Database

SQLite
