### ISSUE TITLE
Due is shown incorrectly

### ISSUE THREAD

**Issue by mrdunski** [go-gitea/gitea#21999]
### Description

The issue is here: https://try.gitea.io/pan_dunski/test/issues/1

I've chosen due as 2022-12-02 but after save it is converted to 2022-12-03

My timezone is CEST

### Gitea Version

1.18.0+rc1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/689358/205087149-7b1f02bc-cc90-45ab-95bb-c4f39a1308ba.png)

### How are you running Gitea?

I'm using official chart with the following values:

```yaml
image:
  repository: gitea/gitea
  pullPolicy: Always
  tag: "1.18.0-rc1"
```

### Database

PostgreSQL
