### ISSUE TITLE
Git Operations fail with a go exception

### ISSUE THREAD

**Issue by Itege** [go-gitea/gitea#22002]
### Description

Hello,
I've recently to a docker installation from an installation directly on my ubuntu machine, I'm not sure if I've misconfigured something or what, but when I attempt to do any git op(push, pull, etc) I get the following error message:

```
2022/12/01 22:41:22 ...s/setting/setting.go:635:loadFromConf() [F] Unable to find configuration file: "/etc/gitea/app.ini".
        Ensure you are running in the correct environment or set the correct configuration file with -c.
fatal: Could not read from remote repository.
```

I can not figure out a solution for this issue(I've tried setting the environment variable for the ini file, and also mounting a modified version of the image's run script to ensure that all possible options for this file are being set), I'm using the recommended docker compose script from the doc.

### Gitea Version

1.18.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker, here's my compose file:

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA_APP_INI=/data/gitea/conf/app.ini
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3001"
      - "222:22"
```

### Database

PostgreSQL
