### ISSUE TITLE
Posting emoji in an comment causes error 500

### ISSUE THREAD

**Issue by MightyPork** [go-gitea/gitea#22382]
### Description

When posting a comment with an emoji (I tried 🤔), it shows error 500.

Logs:

```
gitea-gitea-1  | 2023/01/09 14:37:49 ...rs/web/repo/issue.go:2657:NewComment() [E] [63bc26bd-9] CreateIssueComment: Error 1366: Incorrect string value: '\xF0\x9F\xA4\x94 \x0D...' for column `gitea`.`comment`.`content` at row 1
gitea-gitea-1  | 2023/01/09 14:37:55 ...rs/web/repo/issue.go:2657:NewComment() [E] [63bc26c3] CreateIssueComment: Error 1366: Incorrect string value: '\xF0\x9F\xA4\x94 \x0D...' for column `gitea`.`comment`.`content` at row 1
gitea-gitea-1  | 2023/01/09 14:38:00 ...rs/web/repo/issue.go:2657:NewComment() [E] [63bc26c8-2] CreateIssueComment: Error 1366: Incorrect string value: '\xF0\x9F\xA4\x94 \x0D...' for column `gitea`.`comment`.`content` at row 1
gitea-gitea-1  | 2023/01/09 14:38:09 ...rs/web/repo/issue.go:2657:NewComment() [E] [63bc26d1] CreateIssueComment: Error 1366: Incorrect string value: '\xF0\x9F\xA4\x94 \x0D...' for column `gitea`.`comment`.`content` at row 1
gitea-gitea-1  | 2023/01/09 14:38:58 ...rs/web/repo/issue.go:2657:NewComment() [E] [63bc2702] CreateIssueComment: Error 1366: Incorrect string value: '\xF0\x9F\xA4\x94 \x0D...' for column `gitea`.`comment`.`content` at row 1
```

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

official docker with MariaDB

```
version: '3'
services:
  gitea:
    image: gitea/gitea:1.17
    volumes:
      - ./data:/data
      - ../wait-for:/usr/bin/wait-for
    networks:
      - traefik
      - backend
    ports:
      - "4022:22"
      - "3000"
    labels:
      - traefik.http.routers.gitea.rule=Host(`XXX`)
      - traefik.docker.network=traefik
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.enable=true
    restart: always
    command: sh -c '/usr/bin/wait-for db:3306 -- /usr/bin/entrypoint'
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    ports:
      - "3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=XXX
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=XXX
    volumes:
      - ./db/:/var/lib/mysql

networks:
  backend:    
  traefik:
    external: true

```

### Database

MySQL
