### ISSUE TITLE
Highlight Rust crates in Cargo.toml file and link to the crates.io, similar to Gitlab

### ISSUE THREAD

**Issue by tte18** [go-gitea/gitea#22402]
### Feature Description

In Gitlab there is a cool feature: while browsing the Cargo.toml file, the dependencies are show as links rather than plain text.

### Screenshots

![image](https://user-images.githubusercontent.com/30199803/211834060-72c665e2-e62a-4d61-8ddb-048be13c6cce.png)

**Comment by vbakc** [comment]
Cargo dependencies can be described in the following sections:

```toml
[dependencies]

[dev-dependencies]

[build-dependencies]
```

**Comment by vbakc** [comment]
Link to the package is built like so:

`https://crates.io/crates/#{name}`

**Comment by vbakc** [comment]
Crate name is either the key or the attribute `package`

```toml
[dependencies]
my_name_for_some_package = { package = "some_package", version = "*" }
```

**Comment by vbakc** [comment]
Skip, if some custom registry is defined for a crate

```toml
[dependencies]
some_package = { version = "*", registry = "my_registry" }
```

**Comment by vbakc** [comment]
Also, a dependency can be defined like so

```toml
[dependencies.some_package]
version = "*"
```
