### ISSUE TITLE
RewriteAllPublicKeys failed: open /data/git/.ssh/authorized_keys.tmp: permission denied

### ISSUE THREAD

**Issue by r-kane** [go-gitea/gitea#22504]
### Description

Updated docker-compose.yml to use v1.18.1 (previously 1.17.3).
After starting `docker-compose pull` and `docker-compose up -d` the server won't start.

The gitea.log file shows this lines:
```bash
2023/01/18 10:21:46 routers/init.go:101:syncAppConfForGit() [I] re-write ssh public keys ...
2023/01/18 10:21:46 routers/init.go:59:mustInit() [F] code.gitea.io/gitea/models/asymkey.RewriteAllPublicKeys failed: open /data/git/.ssh/authorized_keys.tmp: permission denied
```

The gitea folder (the mapped data folder) looks like this:
```bash
gitea@gitea:~/gitea-docker/gitea$ ll
total 28
drwxr-xr-x  7 gitea gitea 4096 Jan 18 09:59 ./
drwxrwxr-x  4 gitea gitea 4096 Jan 18 10:07 ../
drwxr-xr-x  5 gitea gitea 4096 Nov  4 05:59 git/
drwxr-xr-x 17 gitea gitea 4096 Jan 18 09:42 gitea/
drwxr-xr-x  2 gitea gitea 4096 Jan 18 00:00 log/
drwx------  2 root  root  4096 Jan 18 09:59 ssh/
```

The only file inside the .ssh folder is called *environment*. The authorized_keys.tmp file doesn't even exist.

Any ideas how to fix this?

Thanks and best regards
Rafael

### Gitea Version

1.18.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 22.04.1 LTS

### How are you running Gitea?

Gitea is running in a docker container using the following docker-compose file:

```yml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.18.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__LOG__ROOT_PATH=/data/log
      - GITEA__LOG__MODE=file
      - GITEA__LOG__LEVEL=Debug
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.ssh:/data/git/.ssh
    ports:
      - "80:80"
      - "222:22"
```

### Database

SQLite
