### ISSUE TITLE
ElasticSearch index not populated for repository code

### ISSUE THREAD

**Issue by stevefan1999-personal** [go-gitea/gitea#22617]
### Description

I just added Elasticsearch to repo indexer and issue indexer via config file and run Gitea as normally as it could, but it seems like the repo code indexer is currently unable to repopulate. I did see the issue documents being populated but there are no code documents there. This is weird which means my ES setup is seemingly working so it is not my fault. I ran this on a medium-sized Gitea instance so this is very much broken.

I tried request reindex on several large repos, but there are still no documents. 

### Gitea Version

2903afb

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/29133953/215071446-b11aa039-afd8-4a8a-ab7b-852c32b6fa05.png)

### How are you running Gitea?

Gitea: on Kubernetes using the Helm chart

Elasticsearch: Also on Kubernetes but using the Elastic operator CRD

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: gitea
spec:
  version: 8.6.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.roles: ["master", "data", "ingest", "ml", "transform"]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: rook-cephfs
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

Elasticsearch is connected with HTTP only despite it has HTTPS out of the box. I don't want to hassle with it that much so I just disabled the cert.

### Database

SQLite
