### ISSUE TITLE
CORS headers not present on /api/healthz

### ISSUE THREAD

**Issue by Zokhoi** [go-gitea/gitea#22718]
### Description

I have a [homer](https://github.com/bastienwirtz/homer) dashboard on another subdomain to check the health status of my self hosted services, and have found that with correct settings in my `app.ini`:
```ini
[cors]
ENABLED = true
ALLOW_DOMAIN = *
SCHEME = http
ALLOW_CREDENTIALS = true
```
the endpoint `/api/v1/version` respond with the correct CORS headers, while `/api/healthz` does not. The endpoints are requested without user authentication, so I have only checked these.

This behavior is reproduced at https://gitea.com, but https://try.gitea.io does not respond with CORS headers at all. Not sure if they have the CORS config set.

For reference, here is the relevant part of my homer config:
```yaml
services:
  ...
  - name: "Gitea"
    icon: "fab fa-git-alt"
    url: "https://gitea.com"
    target: "_blank"
    type: Ping
    method: GET
    endpoint: "https://gitea.com/api/healthz"
    # endpoint: "https://gitea.com/api/v1/version"
```

### Gitea Version

1.18.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Ubuntu Server 22.04

### How are you running Gitea?

official binary from https://dl.gitea.io, as service with systemd

### Database

PostgreSQL
