### ISSUE TITLE
action cannot be triggered when using on.pull_request

### ISSUE THREAD

**Issue by Yiklek** [go-gitea/gitea#22958]
### Description

Action cannot be triggered when using `on.pull_request`.

New pr can trigger this action.

But push to pr source branch cannot trigger it.

Github can trigger it.

```yaml
# .gitea/workflows/build.yaml
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

### Gitea Version

ca445c

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build Gitea myself
run from command-line

### Database

SQLite

**Comment by Yiklek** [comment]
The backend receives a `pull_request_sync` event. It doesn't match the `pull_request`

Match this:
https://github.com/go-gitea/gitea/blob/ca445cf56628274ab5119816bf988f04204035a3/modules/actions/workflows.go#L208

![image](https://user-images.githubusercontent.com/21033316/219653096-d7a5c1b1-82d8-4fa5-979d-dd66669e601e.png)

**Comment by lunny** [comment]
Ah, yes. We need a event convertion from Gitea's to Github's.

**Comment by vtolstov** [comment]
any progress on this issue?

**Comment by Yiklek** [comment]
@lunny hi, I find it doesn't work yet.

```
# .gitea/workflows/build.yaml
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```
https://github.com/go-gitea/gitea/blob/ccd3a55bf4f07a390e13d48100c58fb937fd3dcf/modules/actions/workflows.go#L102-L104

In this case, `convertFromGithubEvent(evt)` always return `pull_request`, but `string(triggedEvent)` is `pull_request_sync`.
