### ISSUE TITLE
custom 自定义配置完全不生效 

### ISSUE THREAD

**Issue by hale177** [go-gitea/gitea#22966]
### Description

背景:
2年前用过 1.12 ，使用起来很顺手 
最近因为需要安装了 最新 v1.18.3  参照官方文档采用 docker-compose 安装，
同时配置了 custom/comf/app.ini  作为自定义配置，结果发现添加的所有选项都无法生效  ？ 
后面又换成 v1.16.9测试一把 ，结果一样 。

自定义添加过的选项如下：
[other]
SHOW_FOOTER_BRANDING = false
SHOW_FOOTER_VERSION = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false

[service.explore]
DISABLE_USERS_PAGE = true
REQUIRE_SIGNIN_VIEW = true

### Gitea Version

1.16.9 

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

```
version: "3"

networks:
  git:
    name: git
    external: false

services:
  gitea:
    #image: gitea/gitea:1.18.3
    image: gitea/gitea:1.16.9
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - git
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000/tcp"
      - "10022:22/tcp"
    restart: unless-stopped
```

### Database

None
