### ISSUE TITLE
Plans for Gitea 1.20

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#23072]
Hi all,

Gitea `v1.19.0-rc0` has been released.
We have created the `release/v1.19` branch accompanied by the `v1.20.0-dev` tag and are now using `main` for `1.20` development.
As always, this issue is intended to show what you can expect from the next version.

## Important

This summary is for things you **plan to do yourself**, not things you want other people to do.
Other comments will be hidden.

## Schedule

Gitea `1.20` is currently set to enter feature freeze on <time datetime="2023-05-28 23:59+00:00">2023-05-28 23:59 UTC</time>, so in the end of May.
This deadline is at the moment only a rough estimate and might change in the future.

<details><summary><h2>Previous Plans</h2></summary>

- #21598 
- #20022
- #18345
- #16429
- #14477
</details>

BTW: **This is a contribution plan issue, any off-topic comment will be hidden. Please go to the special issue or open one to discuss your idea.**

**Comment by delvh** [comment]
I'll start with my plans, which haven't changed a lot since 1.19:
- [x] Reviewing  **a lot** of PRs ([as always](https://github.com/go-gitea/gitea/pulls?q=is%3Apr+reviewed-by%3Adelvh+milestone%3A1.19.0+))
- [ ] One of (I probably will only be able to implement one of the two)
  - [ ] #20126
  - [ ] #21150

**Comment by lunny** [comment]
Mine

- Further implementations about Actions #13539

**Comment by wojtekxtx** [comment]
@lunny must say that implementing actions is quite a "heavylifting" task to accomplish. Good luck.

**Comment by delvh** [comment]
Offtopic, but: Actions are already implemented (coming with 1.19.0).
@lunny is simply talking about the further improvement.

**Comment by harryzcy** [comment]
* [ ]  [Sync issues/PRs from pull mirror #20311](https://github.com/go-gitea/gitea/issues/20311)

**Comment by wolfogre** [comment]
- Take over: #18165

**Comment by wojtekxtx** [comment]
@lunny reason my post was hidden is?

**Comment by delvh** [comment]
The same mine was hidden.
> This summary is for things you plan to do yourself, not things you want other people to do.
Other comments will be hidden.

**Comment by stuzer05** [comment]
It'll be awesome to improve time tracking (remove estimated spent time, improve interface). Also, to add issue time estimation, more info on https://support.atlassian.com/jira-software-cloud/docs/estimate-an-issue/#Concepts-about-estimation

These features and improvements are showcased in #23112

**Comment by JakobDev** [comment]
I hope that #20955 gets finally merged into 1.20.

I also plan to make existing PRs ready to merge. For new PRs I think I will do mostly minor stuff like new APIs.

I also plan to rework the Forks page. I had this Plan for quite a while since I have read a blogpost that talks about, how hard it is to find active Forks on GitHub. Since than, GitHub [has made a new Forks Page](https://github.blog/changelog/2023-02-24-new-forks-page-view/), so I think it's time to do this also in Gitea, but I don't know if I get it ready before 1.20.

**Comment by ivancxj** [comment]
#2175

**Comment by ivancxj** [comment]
- #2175

**Comment by pdxjohnny** [comment]
> * [ ]  Take over: [Add support to import repository data from an exported data of Github #18165](https://github.com/go-gitea/gitea/pull/18165)

It looks like we might be able to mirror the live event stream off the webhook events and translate into federated events for what is effectively an "online clone", some sketch work on the CI/CD front follows (translation flow is in the linked OpenSSF Metrics use case). This would of course be after the initial pull import but wanted to paste here for sake of propagating aligned discussion.

GitHub Webhook -> Forge Federation could enable users to more seamlessly migrate as they could maintain state both places after initial migration while they switch over.

Related: https://codeberg.org/ForgeFed/ForgeFed/src/commit/467dfe84670750a61992c5c1da3841e9453c1d36/rdf/context.jsonld
Related: #18240
Related: https://github.com/ietf-scitt/use-cases/issues/14
Related: [Alice Engineering Comms: 2023-03-02 Engineering Logs](https://github.com/intel/dffml/discussions/1406?sort=new#discussioncomment-5178869)

```console
$ curl -fL https://vcs.activitypub.securitytxt.dffml.chadig.com/push/outbox/ > outbox@push@vcs.activitypub.securitytxt.dffml.chadig.com
$ jq .orderedItems[].id < outbox\@push\@vcs.activitypub.securitytxt.dffml.chadig.com | wc -l
3931
$ jq -r '.orderedItems[] | [{(.id): (.object.content)}] | .[] | add' < outbox\@push\@vcs.activitypub.securitytxt.dffml.chadig.com | jq -R --unbuffered '. as $line | try (fromjson | .) catch $line'
$ jq -r '.orderedItems[] | [{(.id): (.object.content)}] | .[] | add' < outbox\@push\@vcs.activitypub.securitytxt.dffml.chadig.com | jq -R --unbuffered '. as $line | try (fromjson | .workflow_job) catch $line'
$ jq -r '.orderedItems[] | [{(.id): (.object.content)}] | .[] | add' < outbox\@push\@vcs.activitypub.securitytxt.dffml.chadig.com | jq -c -R --unbuffered '. as $line | try (fromjson | .workflow_job) catch $line' | jq -s | python3 -c "import sys, pathlib, json, yaml; print(yaml.dump(json.load(sys.stdin)))"
```

```yaml
- check_run_url: https://api.github.com/repos/intel/dffml/check-runs/11733499326
  completed_at: '2023-03-03T04:30:59Z'
  conclusion: success
  created_at: '2023-03-03T03:58:07Z'
  head_branch: main
  head_sha: 4241b49975cf364b540fc0ad961cde58e2c89623
  html_url: https://github.com/intel/dffml/actions/runs/4320093439/jobs/7539975999
  id: 11733499326
  labels:
  - ubuntu-latest
  name: test (operations/nlp, 3.7)
  node_id: CR_kwDOCOlgGM8AAAACu179vg
  run_attempt: 1
  run_id: 4320093439
  run_url: https://api.github.com/repos/intel/dffml/actions/runs/4320093439
  runner_group_id: 2
  runner_group_name: GitHub Actions
  runner_id: 16
  runner_name: GitHub Actions 16
  started_at: '2023-03-03T04:26:41Z'
  status: completed
  steps:
  - completed_at: '2023-03-03T04:26:42.000Z'
    conclusion: success
    name: Set up job
    number: 1
    started_at: '2023-03-03T04:26:40.000Z'
    status: completed
  - completed_at: '2023-03-03T04:30:57.000Z'
    conclusion: success
    name: Complete job
    number: 21
    started_at: '2023-03-03T04:30:57.000Z'
    status: completed
  url: https://api.github.com/repos/intel/dffml/actions/jobs/11733499326
  workflow_name: Tests
```
