### ISSUE TITLE
Componse包上传后打不开，报404错误

### ISSUE THREAD

**Issue by codecodify** [go-gitea/gitea#23140]
### Description

你好，我在上传`composer`包的时候，能上传成功，但是打开包的页面提示报404错误，如果在`https://try.gitea.io/`网上能正常显示包的主页，不知道我自己搭建的为什么不能正常打开呢。

提交命令示例：curl -T demo.zip -u (my account):(my password) "https://try.gitea.io/api/packages/codecodify/composer?version=1.0.0"

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

使用`docker-compose`运行，配置文件如下：
```yaml
version: '3'

services:
  gitea:
    image: 'gitea/gitea:1.18.5'
    restart: always
    privileged: true
    container_name: gitea
    environment:
      TZ: Asia/Shanghai
    ports:
      - '10080:3000'
      - '10022:22'
    volumes:
      - '$GITEA_HOME/data:/data'
```

### Database

SQLite
