### ISSUE TITLE
Actions workflow definition with unclosed string is still executed

### ISSUE THREAD

**Issue by ChristianSch** [go-gitea/gitea#23277]
### Description

Related to https://github.com/go-gitea/gitea/issues/23275

Given the following workflow file:
```
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_API_URL ${{ GITHUB_API_URL }} GITHUB_SERVER_URL ${{ GITHUB_SERVER_URL }} github.api_url ${{ github.api_url }} github.server_url ${{ github.server_url}}""
```
(note the double `"` at the end of the last line)

I expected it to be rejected because it was invalid. I'm not very familiar with the yaml grammar in that depth, but from a UX point of view I'd argue this is invalid and should be noted.

It's still executed though:
![image](https://user-images.githubusercontent.com/6138133/222840034-9662b934-1c39-4c61-874e-fe71ffa64212.png)

PS: a caveat is, that yamllint.com thinks this is valid yaml as well.

### Gitea Version

1.19.0+0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker on mac

### Database

SQLite

**Comment by wxiaoguang** [comment]
If I understand correctly:

* The YAML is valid, get the `run` with `echo "...""` , it matches the expectation
* The command `echo "...""` is invalid (invalid shell command), so the runner should report a error

**Comment by ChristianSch** [comment]
I would argue that the YAML is invalid, not the shell command. If you have `:` in your echo string (`echo "foo: bar"`), yaml complains and can't read the file. That's why I don't understand that it happily parses this workflow. I wanted to dig into the reference yaml grammar, but it seems there are a few problems with that and it seems pretty unmaintained at this point.

**Comment by wxiaoguang** [comment]
> I would argue that the YAML is invalid

Since it can be parsed by many YAML parsers (I have tried other online YAML parsers), and it passes yamllint.com , I would prefer to believe that the YAML is valid.

**Comment by ChristianSch** [comment]
Okay! Very pragmatic thinking, I like it. Then you could argue that my shell command  is simply invalid.

**Comment by wxiaoguang** [comment]
If I understand correctly, the YAML standard is like this:

* `a: b: c`: invalid
* `a: 'b: c'`: valid
* `a: it's good`: valid
* `a: anything"`: valid, it means `anything"`
* `a: anything""`: valid, it means `anything""`

**Comment by wxiaoguang** [comment]
> If you have `:` in your echo string (`echo "foo: bar"`), yaml complains and can't read the file.

You need to quote the value to make it a valid YAML input, like this:

```yaml
key1: 'my value with : char'
key2: 'my value with : " char'
key3: "my value with : \" char"
```
