### ISSUE TITLE
Actions should report invalid workflow file

### ISSUE THREAD

**Issue by ChristianSch** [go-gitea/gitea#23275]
### Feature Description

I think it would be very helpful to get an indication in case gitea detected a workflow file but deemed it invalid. Take this workflow file `main.yml`:

```
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "GITHUB_API_URL: ${{ GITHUB_API_URL }} GITHUB_SERVER_URL: ${{ GITHUB_SERVER_URL }} github.api_url: ${{ github.api_url }} github.server_url: ${{ github.server_url}}""
      - run: echo "done"
```

The logs report the following:
```
2023-03-03 22:38:02 2023/03/03 21:38:02 ...actions/workflows.go:69:DetectWorkflows() [W] ignore invalid workflow "main.yml": yaml: line 9: mapping values are not allowed in this context
```

But no action is started and no feedback is given to the user. I feel like this belongs in the UI. 

PS: The problem with this is the `:` which aren't allowed.

**Comment by techknowlogick** [comment]
> PS: The problem with this is the : which aren't allowed.

I think it might be due to the `""` at the end of line 9.

Regardless, I agree that reporting on invalid files should occur.

**Comment by ChristianSch** [comment]
I was actually thinking about reporting that as well, I actually got a run with two closing `"`, but thought it was such a small little detail to not report it. I might as well try to reproduce it, I can't right now. Seems (also as per https://www.yamllint.com) that `:` inside a string are not valid 🤷 

This doesn't run as well:
```
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_API_URL: ${{ GITHUB_API_URL }} GITHUB_SERVER_URL: ${{ GITHUB_SERVER_URL }} github.api_url: ${{ github.api_url }} github.server_url: ${{ github.server_url}}"
```
