### ISSUE TITLE
Actions runner environment has empty server_url/api_url

### ISSUE THREAD

**Issue by ChristianSch** [go-gitea/gitea#23276]
### Description

I expected to either have `GITHUB_SERVER_URL`/`GITHUB_API_URL` or `github.server_url`/`github.api_url` but none of them are passed on to my action. They are set when creating the runner env though (see logs).

References:
1: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
2: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

Given the following workflow file:

```
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.api_url ${{ github.api_url }}"
      - run: echo "github.server_url ${{ github.server_url}}"
      - run: echo "GITHUB_API_URL ${{ GITHUB_API_URL }}"
      - run: echo "GITHUB_SERVER_URL ${{ GITHUB_SERVER_URL }}"
```

The following two issues appear:
1. even though `GITHUB_API_URL` and `GITHUB_SERVER_URL` are set in the runner env (see logs), they aren't printed in any case
2. in case of accessing the variables via the full qualifier and not the `github` context, nothing is printed at all.

In case of `github.api_url`/`github.server_url` the variable is simply not resolved:
```
Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] expression 'echo "github.server_url ${{ github.server_url}}"' rewritten to 'format('echo "github.server_url {0}"', github.server_url)'
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] evaluating expression 'format('echo "github.server_url {0}"', github.server_url)'
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] expression 'format('echo "github.server_url {0}"', github.server_url)' evaluated to '%!t(string=echo "github.server_url ")'
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] Wrote command

echo "github.server_url "

 to 'workflow/1'
```

In case of the fully qualified env var, i.e. `GITHUB_API_URL` the command fails:
```
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] expression 'echo "GITHUB_SERVER_URL ${{ GITHUB_SERVER_URL }}"' rewritten to 'format('echo "GITHUB_SERVER_URL {0}"', GITHUB_SERVER_URL)'
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] evaluating expression 'format('echo "GITHUB_SERVER_URL {0}"', GITHUB_SERVER_URL)'
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] expression 'format('echo "GITHUB_SERVER_URL {0}"', GITHUB_SERVER_URL)' evaluated to '%!t(<nil>)'
[Gitea Actions Demo/Explore-Gitea-Actions] Unable to interpolate expression 'format('echo "GITHUB_SERVER_URL {0}"', GITHUB_SERVER_URL)': Unavailable context: github_server_url
[Gitea Actions Demo/Explore-Gitea-Actions] [DEBUG] Wrote command



 to 'workflow/3'
```

PS:
using the token works though:

```
      - run: echo "token ${{ secrets.GITHUB_TOKEN }}"
```

![image](https://user-images.githubusercontent.com/6138133/222837764-1cc4370d-9d40-47c9-b81d-41d573424a3e.png)

### Gitea Version

 1.19.0+0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/ChristianSch/4a99193a89feaa5053c595b6aa5613f0

### Screenshots

![Screenshot 2023-03-03 at 22 51 47](https://user-images.githubusercontent.com/6138133/222837869-fffb69a6-2553-47ad-8383-02c52e823c8e.png)

### How are you running Gitea?

docker on mac

### Database

SQLite
