### ISSUE TITLE
Docker/rootless: "ssh-keygen": executable file not found in $PATH -

### ISSUE THREAD

**Issue by williamdes** [go-gitea/gitea#23363]
### Description

```
Cannot verify your SSH key: SSHKeyGenParsePublicKey: fail to parse public key: exec: "ssh-keygen": executable file not found in $PATH -
```

After clicking on "Add deploy key" with the form in the screenshot

On `https://git.domain.tld/<org>/<repo>/settings/keys`

That said I tried to verify my SSH key that I had added to my profile and it worked fine, so maybe it uses another code function.

### Gitea Version

1.19.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/223479023-f341297a-b1e5-485f-8599-886a1cf0dc2c.png)

### How are you running Gitea?

With Docker/docker-compose

```yml
version: "2.3"

services:
    my_git:
        image: gitea/gitea:1.19.0-rc1-rootless
```

I am pretty sure it works fine with `gitea/gitea:1.19.0-rc1`

### Database

MySQL

**Comment by williamdes** [comment]
Quick fix: `docker exec -u root -it git.domain.tld apk add openssh-keygen`

Edit: maybe it also does not work with `gitea/gitea:1.19.0-rc1`, please try

**Comment by wxiaoguang** [comment]
It looks like a bug in code if you didn't disable the builtin ssh server.

The code works like this:

* If you disabled builtin ssh server, then use ssh command line to verify
* If you enabled builtin ssh server, then use gitea internal ssh package to verify

If you have enabled the builtin ssh server (didn't change any default config), then it must be a regression bug.

**Comment by williamdes** [comment]
> It looks like a bug in code if you didn't disable the builtin ssh server.

I can confirm I did not disable it, I use the SSH server with docker pass though (https://github.com/go-gitea/gitea/issues/19065#issuecomment-1066104363): https://docs.gitea.io/en-us/install-with-docker/#docker-shell-with-authorized_keys

```yml
        environment:
            # https://github.com/go-gitea/gitea/blob/release/v1.19/docker/rootless/usr/local/bin/gitea#L40
            GITEA_WORK_DIR: /data/gitea
            # https://github.com/go-gitea/gitea/blob/release/v1.19/docker/rootless/usr/local/bin/gitea#L35
            GITEA_APP_INI: /etc/gitea/app.ini
            GITEA__cron__ENABLED: "true"
            GITEA__server__SSH_DOMAIN: git-ssh.domain.tld
            GITEA__server__SSH_USER: git
            GITEA__server__SSH_PORT: 22
            GITEA__server__ROOT_URL: https://git.domain.tld/
            GITEA__server__HTTP_PORT: ${GITEA_HTTP_PORT:-3000}
            GITEA__server__DISABLE_SSH: ${GITEA_DISABLE_SSH:-true}
            GITEA__server__SSH_LISTEN_HOST: ${GITEA_SSH_LISTEN_HOST:-0.0.0.0}
            GITEA__server__SSH_LISTEN_PORT: ${GITEA_SSH_LISTEN_PORT:-2222}
            GITEA__server__APP_DATA_PATH: /data/gitea
            GITEA__server__SSH_ROOT_PATH: /home/git/.ssh
            GITEA__log__LEVEL: "Debug"
            GITEA__log__ROOT_PATH: /data/git/log
            GITEA__lfs__PATH: /data/git/lfs
            GITEA__repository__ROOT: /data/git/repositories
            GITEA__database__DB_TYPE: mysql
            GITEA__database__HOST: "${GITEA_DB_HOST}"
            GITEA__database__NAME: "${GITEA_DB_NAME}"
            GITEA__database__USER: "${GITEA_DB_USER}"
            GITEA__database__PASSWD: "${GITEA_DB_PASS}"
            GITEA__session__COOKIE_SECURE: "true"
            GITEA__session__SAME_SITE: strict
            GITEA__mailer__ENABLED: "true"
            GITEA__mailer__FROM: ${GITEA_MAIL_FROM}
            GITEA__mailer__GITEA_MAIL_SUBJECT_PREFIX: ${GITEA_MAIL_SUBJECT_PREFIX}
            GITEA__mailer__HELO_HOSTNAME: ${GITEA_MAIL_HELO_HOSTNAME}
            GITEA__mailer__PROTOCOL: smtps
            GITEA__mailer__SMTP_ADDR: ${GITEA_MAIL_SMTP_ADDR}
            GITEA__mailer__SMTP_PORT: 465
            GITEA__mailer__USER: ${GITEA_MAIL_USER}
            GITEA__mailer__PASSWD: "${GITEA_MAIL_PASSWORD}"
            GITEA__service__DISABLE_REGISTRATION: ${GITEA_DISABLE_REGISTRATION:-true}
            GITEA__service__NO_REPLY_ADDRESS: ${GITEA_NO_REPLY_ADDRESS}
            GITEA__actions__ENABLED: "true"
            GITEA__federation__ENABLED: "true"
            GITEA__cron.update_checker__ENABLED: "true"
```
