### ISSUE TITLE
Actions - Manually trigger a workflow/action

### ISSUE THREAD

**Issue by ghnp5** [go-gitea/gitea#23668]
### Feature Description

Hey!

It would be very nice if we could have a button here to trigger a specific workflow/action:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/57591332/227336362-0ac5a500-660b-43be-b929-72f36edd6f15.png">

So that I could trigger a job quickly, without having to push or waiting for a schedule.

Thanks!!

**Comment by andysh-uk** [comment]
This would be great. GitHub’s actions has a “on: workflow_dispatch” directive which enables a button in the UI to trigger it manually:

https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow

However I have found in Gitea, if you navigate to an action that ran, there is a “re-run” button you can use to trigger it again.

**Comment by ghnp5** [comment]
> However I have found in Gitea, if you navigate to an action that ran, there is a “re-run” button you can use to trigger it again.

This seems to be for single steps, only.

Unfortunately, there doesn't seem to be a way to re-run the whole workflow, unless I push a change.

**Comment by ghnp5** [comment]
Hi @andysh-uk  - yep, exactly.

I have several stages in the same yaml file, so I see multiple "re-run" buttons.

At the moment, I'm running one by one, but I'm hoping this will not be the long-term solution.

**Comment by ghnp5** [comment]
When I say stages, I mean multiple of your equivalent of `Deploy-Website-Production:`.

I have a quite complex workflow, that also uses `strategy matrix`, etc, so it would be very limiting/troublesome to be merging all into the same stage/job.

And we should not have to accommodate (or limiting ourselves) for something that should be an easy "fix" (to add a button to re-run all) 🙂 , hopefully!!

**Comment by andysh-uk** [comment]
Thanks @ghnp5 I thought it would be something more complex, but thought I'd check.

This is a first release so for (relatively) simple things, it works great. I've completely replaced my TeamCity instance with it.  I use it for deploying web apps from Git to Linux servers over SSH, running deployments commands over SSH, building Go applications and publishing them straight to S3.

I don't know if this would work in Gitea or your scenario (and I have zero experience with GH Actions) but could you have a workflow that calls your other workflows as each step?  So you'd have one "master" workflow with a single job, and multiple steps, that just calls your other ones, which you could then trigger?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by ghnp5** [comment]
Thanks. I might explore this more and more, as we go!

As soon as Actions was released, I went ahead and created this first Action (never worked with GH Actions before), and I already had a lot of challenges in the process, but glad I got it working at the end, anyway!

Well done to Gitea Developers who worked on this!

I'm giving them time, anyway, to slowly make the improvements we've all been suggesting.
Worst case scenario, I'll automate some "dummy commit" (increase a number in a file or so), to run everything manually.

The only reason I'm running manually at the moment is because `schedule` doesn't work yet, actually.

**Comment by pangliang** [comment]
Self-owned images are based on other image versions. When the dependent image releases a new version, I usually use this function to trigger a new build to use the new dependent version

```
on:  
    workflow_dispatch:  
        inputs:  
            ES_VER:  
                description: 'ElasticSearch Version'  
                required: true 
```

```
ARG ES_VER  
FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VER} 
```

**Comment by nouknouk** [comment]
> When the dependent image releases a new version, I usually use this function to trigger a new build

On my side i created a brand new repository, with one action like that:
```
name: GitHub Actions Demo
run-name: testing out GitHub Actions
on:  
    workflow_dispatch:  
        inputs:  
            ES_VER:  
                description: 'ElasticSearch Version'  
                required: true 
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
```

but I don't have any button to trigger the action (which has new ran before)

![action page](https://github.com/go-gitea/gitea/assets/4757213/988d38db-fcd9-484b-afd6-7f90a843e62c)

**Comment by ghnp5** [comment]
Yeah, there's no way to manually trigger the action, yet.

Only if you have an automatic trigger based on changing the YAML file, etc.
There is a "Re-run all jobs", but not a "Create New Run" or equivalent.

Note also that `workflow_dispatch` is ignored on Gitea.

**Comment by webvalera96** [comment]
yes, but i think this feature will be very cool

**Comment by ParadiseFallen** [comment]
+1

**Comment by deurk** [comment]
+1

**Comment by bencurio** [comment]
+1 🚀

**Comment by denyskon** [comment]
For those who need a workaround, use issue_comment as trigger and create a specific issue where you'd comment to trigger a workflow run :)

**Comment by bencurio** [comment]
I appreciate the workaround. Due to the `issue_comment` event being rather noisy, it's a good idea to put a filter on it. This way it will only run if the comment `!actions run build` and ignore others.

```yaml
name: Test
on:
  issue_comment:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '!actions run build' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo Tada!  
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '!actions run test' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo Moaar test!  
```

And here is the API call:

```bash
curl -X 'POST' \
  'https://<<host>>/api/v1/repos/<<owner>>/<<repo>>/issues/<<id>>/comments?token=<<token>>' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "!actions run build"
}'
```

**Comment by bencurio** [comment]
Thanks for the suggestion for the `issue_comment` action, I made a working example based on it.

The problem is that `issue_comment` triggers a CI JOB on all project related comments, so this is inefficient. To work around this, I put a filter condition on each job so that the job only starts if the comment is exactly `!actions run build` or `!actions run test` or `!actions run all`

The entire CI process runs even if the action is `push` or `pull_request`, or if the comment is `!actions run all`

Unfortunately, the CI process is triggered by every project comment, but quickly stops due to filtering.

```yaml
name: Test
on:
  push:  
  pull_request:
  issue_comment:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request != '' || github.event.pusher != '' || github.event.comment.body == '!actions run build' || github.event.comment.body == '!actions run all' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo Tada!            
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request != '' || github.event.pusher != '' || github.event.comment.body == '!actions run test' || github.event.comment.body == '!actions run all' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo Moaar test!      
```

Starting CI job via API request:

```bash
$ curl -X 'POST' \
  'https://<<host>>/api/v1/repos/<<org>>/<<repo>>/issues/<<issue_id>>/comments?token=<<token>>' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "!actions run all"
}'
```

Happy hacking.

**Comment by scovillo** [comment]
For those who would prefer another solution than the "issue_comment trigger", I make use of the "paths" feature.
Setup a folder in your project (e.g. "ci-trigger"), which includes a file (e.g. "<name-of-manual-ci-job>") and is reserved for triggering the "manual" ci job.
For example:
![grafik](https://github.com/go-gitea/gitea/assets/130607437/bacd7e59-28d9-43dd-ac9a-adc29015248e)

Setup your job running on a specific paths event:
```
name: Release
on:
  push:
    branches:
      - main
    paths:
      - '.gitea/workflows/trigger/release'
```

You can also filter this event on other jobs:
```
name: Snapshot
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitea/workflows/trigger/**'
```

To start a "manual" ci job via commit, just commit and push a modification of the referring ci job file in the trigger folder, e. g.

![grafik](https://github.com/go-gitea/gitea/assets/130607437/a0c2eb27-64a5-4a48-8169-b6ea87c64ef4)

Hope this helps someone.

Thanks for the great work on gitea, I love it and use it for years!
