### ISSUE TITLE
Action status check in pr is not updated

### ISSUE THREAD

**Issue by Yiklek** [go-gitea/gitea#23674]
### Description

Action status check is not updated on the pull_request synchronize event.

```yml
# .gitea/workflows/build.yaml
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on:
  pull_request: yes
  push:
    branches:
      - main
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

I create a PR `#3` from `dev` to `main`, and the status check is enabled. When I push a commit `1703af8060` to `dev`, action is triggered. But the status check on the PR page is not updated.

commit page
![image](https://user-images.githubusercontent.com/21033316/227402221-62a3fe8e-dbe8-46a6-ac02-278be825770e.png)

action page
![image](https://user-images.githubusercontent.com/21033316/227402388-72dfdad3-8e49-4b14-ad99-6f09ec5289e9.png)

### Gitea Version

df411819eb

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build Gitea myself
run from command-line

### Database

SQLite

**Comment by wolfogre** [comment]
Should be fixed by #23613, so I believe we will have it on v1.19.1

**Comment by Yiklek** [comment]
@wolfogre My build is newer than https://github.com/go-gitea/gitea/pull/23613
![Snipaste_2023-03-24_10-05-40](https://user-images.githubusercontent.com/21033316/227405952-b981fbbf-1d89-4481-a295-121d780e3bfa.png)

**Comment by wolfogre** [comment]
@Zettat123 Could you please take a look at it?

**Comment by Zettat123** [comment]
@Yiklek Could you please change
``` yml
on:
  pull_request: yes
  push:
    branches:
      - main
```
to

``` yml
on: pull_request
```

and test again?
