### ISSUE TITLE
custom label option appears twice 

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#23715]
### Description

when adding a custom yaml label file, an option appears twice. the glob appears to be searching for files as well as file types 

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![2023-03-26_14-03-1679838041](https://user-images.githubusercontent.com/4564448/227779682-82a66529-6caa-465b-8557-ecab32a93872.jpg)

```
#pwd
/var/lib/gitea/custom/options/label

#ls
test.yaml

#cat test.yaml
labels:
  - name: "foo/bar"  # name of the label that will appear in the dropdown
    exclusive: true # whether to use the exclusive namespace for scoped labels. scoped delimiter is /
    color: aabbcc # hex colour coding
    description: Some label # long description of label intent
  - name: "foo/baz"  # name of the label that will appear in the dropdown
    exclusive: true # whether to use the exclusive namespace for scoped labels. scoped delimiter is /
    color: aabbcc # hex colour coding
    description: Some other label # long description of label intent
```

### Git Version

2.40.0

### Operating System

linux (gentoo)

### How are you running Gitea?

rc-service 

### Database

None
