### ISSUE TITLE
Dark theme: release descripton doesn't look good

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#23718]
### Description

https://try.gitea.io/wxiaoguang/test/releases

1. Padding/Margin
2. Background color

![image](https://user-images.githubusercontent.com/2114189/227791236-0ebe9170-8cce-4c4b-9aaf-cc8cbd6eb92b.png)

**Comment by zeripath** [comment]
in comments the markup gets a border:

```css
.comment-body .markup {
  padding: 1em;
  border-radius: 0 0 var(--border-radius) var(--border-radius); /* don't render outside box */
}
```

We could just add `gt-px-3 gt-py-3` to the class?
