### ISSUE TITLE
Actions - send Email on Success/Failure

### ISSUE THREAD

**Issue by ghnp5** [go-gitea/gitea#23725]
### Feature Description

On GitHub, I get emails every time a run succeeds or fails:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/57591332/227800188-0a12ec9d-cbcb-4564-8f9f-d2474220180d.png">

In Gitea, even though emails are set up (and working), I'm not getting any emails when a job runs (whether successful or failed).

Would it be possible to be able to set that up?

If that could be a setting in the YAML file, even better!

Thank you very much!

**Comment by MrHaroldA** [comment]
I would like a more general 'event driven messaging system', as I also would like to get an email when a pull request is created, or when a pull request results in a merge conflict.

**Comment by GammaGames** [comment]
I needed notifications for job failures so I added this step to most of my workflows:

```yaml
- name: Send mail
    if: failure()
    uses: https://github.com/dawidd6/action-send-mail@v3
    with:
        to: ${{ secrets.MAIL_TO }}
        from: Gitea <gitea@hostname>
        subject: ${{ gitea.repository }} ${{gitea.workflow}} ${{ job.status }}
        priority: high
        convert_markdown: true
        html_body: |
            ### Job ${{ job.status }}

            ${{ github.repository }}: [${{ github.ref }}@${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/actions)
```

I tried to create a link to the failed action by adding `runs/${{ github.run_id }}` to the url, but it didn't work
