### ISSUE TITLE
Git commands error 502 after version upgrade

### ISSUE THREAD

**Issue by simonkimi** [go-gitea/gitea#23835]
### Description

I tried to upgrade from version 1.18.5 to 1.19.0.
I created a new docker compose and mounted it to the original directory, the web interface works fine, but git commands(such as clone/push/pull/fetch) returned error: 502

I found a similar issue #8041, but it doesn't solve the problem.

### Gitea Version

gitea/gitea:1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/simonkimi/6612da15f1e2da3214980e6eef8f1c19

### Git Version

2.38.4, Wire Protocol Version 2 Enabled

### Operating System

Official docker on Linux NAS 5.10.60-qnap x86_64 GNU/Linux

### How are you running Gitea?

```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.19.0
    container_name: gitea1190
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - /share/docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3022:22"
```

### Database

SQLite
