### ISSUE TITLE
gitea dump failure，permission denied

### ISSUE THREAD

**Issue by I-am-JunDa** [go-gitea/gitea#23859]
### Description

this is my docker-compose.YML file
```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.19.0
    container_name: gitea
    privileged: true
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "3422:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - TZ=Asia/Shanghai
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
```
### i try use sudo
243b46d4cab9:/$ sudo gitea dump
bash: sudo: command not found
### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/57946269/229265239-17c6dd16-435d-4e5b-aaef-223e838830c4.png)

### Operating System

windows11【docker-desktop】

### How are you running Gitea?

i use docker-compose.YML run the container

### Database

MySQL
