### ISSUE TITLE
Repository.getFilesChanged(start, end) contains the empty path filename and breaks Actions `paths` filter

### ISSUE THREAD

**Issue by ChristopherHX** [go-gitea/gitea#23919]
### Description

I wondered why this Gitea Actions workflow is triggered while changing the workflow file

Enable Gitea Actions and add the following file
Add .github/workflows/main.yml
```yaml
on:
  push:
    paths-ignore:
    - '**.yml'
jobs:
  _:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
```
I expect that the workflow doesn't trigger unless I add a file without .yml extension

Workaround exclude the empty filepath
```yaml
on:
  push:
    paths-ignore:
    - ''
    - '**.yml'
jobs:
  _:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
```

I tracked the bug down to this function: https://github.com/go-gitea/gitea/blob/c775053476295c876791889030fb734dca5c0783/modules/git/repo_commit.go#L190
Callstack
  - https://github.com/go-gitea/gitea/blob/d149093ce3c32503b95c66208de6cb5861e4e666/modules/actions/workflows.go#L211
  - https://github.com/go-gitea/gitea/blob/6b0df6d8da76d77a9b5c42dcfa78dbfe197fd56d/modules/git/commit.go#L293-L295 

Based on comment in another very similar function (without this bug)
https://github.com/go-gitea/gitea/blob/6b0df6d8da76d77a9b5c42dcfa78dbfe197fd56d/modules/git/repo_compare.go#L290
the empty filepath should be removed by the function before returning the path.

Furthermore it looks like these functions are duplicated, one bugfree and the other not.

### Gitea Version

1.19.0+53-gdff3ce089

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.17.1

### Operating System

Linux

### How are you running Gitea?

I just downloaded https://dl.gitea.com/gitea/1.19/gitea-1.19-linux-arm64.xz and enabled actions for testing purposes.

### Database

SQLite
