### ISSUE TITLE
1.19.1-rootless Expect user 'git' but current user is:

### ISSUE THREAD

**Issue by bota87** [go-gitea/gitea#24385]
### Description

This config works with 1.18.5 but fail with 1.19.1 with this error. I see that changing the user from 1002:1002 to 1000:1000 (default) fix the issue
```
cmd/web.go:105:runWeb() [I] Starting Gitea on PID: 7
...s/setting/setting.go:322:loadRunModeFrom() [F] Expect user 'git' but current user is:
```

### Gitea Version

1.19.1-rootless

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

alpine

### How are you running Gitea?

```
version: '3.9'
services:
  gitea:
    image: gitea/gitea:1.19.1-rootless
    container_name: gitea
    restart: unless-stopped
    user: "1002:1002"
    volumes:
      - /data/gitea/data:/var/lib/gitea
      - /data/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtp
      - GITEA__mailer__SMTP_PORT=25
      - GITEA__mailer__SMTP_ADDR=*
      - GITEA__mailer__FROM=*
      - GITEA__mailer__USER=*
      - GITEA__mailer__PASSWD=*
      - GITEA__mailer__FORCE_TRUST_SERVER_CERT=TRUE
      - GITEA__openid__IS_TLS_ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__IS_TLS_ENABLE_OPENID_SIGNUP=false
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__PROTOCOL=http
      - GITEA__server__DOMAIN=git.domain.it
      - GITEA__server__ROOT_URL=https://git.domain.it/
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
```

### Database

SQLite
