### ISSUE TITLE
Issue Forms have no Markdown Box

### ISSUE THREAD

**Issue by JakobDev** [go-gitea/gitea#24398]
### Description

If you use a Issue Form, the Teextarea are normal Textareas and not a Markdown Box.

Just create a new Issue For by creating `.gitea/ISSUE_TEMPLATE/bug.yaml` with this content:
```yaml
name: Bug
description: Write a Bug report
labels: [Bug]
body:
  - type: textarea
    id: bug_description
    attributes:
        label: Describe the bug
        description: A clear description what the Bug is
    validations:
        required: true
```
You can enter Markdown in the Textarea and it will be rendered, but on the Form it's just a normal Textarea and not a Markdown Box, so you missing Features like a Preview.

This Problem is also noted in the Code, but there is no Bug Report yet.
https://github.com/go-gitea/gitea/blob/bb25f85ce8f559fa3e9f462ad1027b5b5a8e2da3/templates/repo/issue/fields/textarea.tmpl#L1-L6

### Gitea Version

bb25f85ce8f559fa3e9f462ad1027b5b5a8e2da3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![grafik](https://user-images.githubusercontent.com/15185051/235069845-2ff3f4f9-1a5a-4b21-b934-a176dce4fcbb.png)

### How are you running Gitea?

Build from source

### Database

None
