### ISSUE TITLE
Display Actions user differently than the Ghost user

### ISSUE THREAD

**Issue by plantroon** [go-gitea/gitea#24580]
### Description

In gitea actions I am trying out this git-auto-commit action from github marketplace: 

https://github.com/marketplace/actions/git-auto-commit?version=v4.16.0 

Everything works fine but in the gitea dashboard it calls the user a "Ghost" while on the commit view itself it is correct.

I am wondering why the Ghost user is only in the feed on the dashboard. It apparently goes by the template here: https://github.com/go-gitea/gitea/blob/0bb52883eb8f866821fb7cb91e535bb4d051dbfb/templates/user/dashboard/feeds.tmpl#L13

Other users are properly resolved but the one that was pushed by the action is Ghost.

Here is my configuration of the action:
```
 - name: Commit the changes back
        uses: https://github.com/stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Jakub Filo
          commit_user_email: plantroon@plantroon.com
          commit_author: Jakub Filo <plantroon@plantroon.com>
```

I am unable to reproduce this on gitea demo site as the action doesn't seem to run there at all.

### Screenshots

The issue:
![1vQ](https://user-images.githubusercontent.com/9124099/236701272-0b1b5957-f7e8-46a8-bac1-4a28ffff841f.png)

The commit view is fine:
![maF](https://user-images.githubusercontent.com/9124099/236701308-8834481a-530f-4b9a-a3cd-cc4bb5c33800.png)

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 11

### Browser Version

Microsoft Edge Version 112.0.1722.68 (Official build) (64-bit)
