### ISSUE TITLE
[Actions] Support concurrency syntax

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#24769]
### Feature Description

simple:

```yaml
concurrency:
  group: container-release
```

advanced:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
