### ISSUE TITLE
Proposal : Improve left tree view

### ISSUE THREAD

**Issue by Kiiow** [go-gitea/gitea#24766]
### Description

The current tree view that we can see on PRs and commits is really cool and help navigate in different files esaily, but it's hard to spot in which folder level a file is.

It would be interesting to improve the padding on the list and add guideline to see faster in which folder a file is.

### Screenshots

![before](https://github.com/go-gitea/gitea/assets/31588247/02c847b3-db56-4799-b51b-938f8bbe6002)

I've made the modification directly in the browser using the devtools, but i don't know which css files need to be edited to get something like that.

What i've done is:
```css
/* Remove */
.item.filewrapper {
  padding-left: 18px!important;
}
/* Add */
.ui.list .list:not(.icon) {
  padding-left: 0.75em;
  margin-left: 10px;
  border-left: 1px solid #679169;
}
```
![after_insepct_improve](https://github.com/go-gitea/gitea/assets/31588247/13dd84ca-1f75-4fb1-847b-c875fc821c09)

### Gitea Version

1.19.0+62-g809225113

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### Browser Version

Brave Version 1.51.114 Chromium: 113.0.5672.92
