### ISSUE TITLE
[BUG] [nightly] Personal Access Tokens don't work

### ISSUE THREAD

**Issue by evanferrao** [go-gitea/gitea#24799]
### Description

On the nightly build of gitea 1e1e8b5d43a36aa788ce0973fa57ac6df648cbd0, Generating Tokens no longer has `scope` option. As a result, the generated tokens are useless, and are not able to clone private repositories, etc.

### Gitea Version

1e1e8b5d43a36aa788ce0973fa57ac6df648cbd0 (commit SHA)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://paste.evanferrao.win/raw/lh22z6t

### Screenshots

I'm uploading a screen recording instead of a screenshot. It helps to understand way faster.

[Gitea Token Scope missing.webm](https://github.com/go-gitea/gitea/assets/130160624/173b64c5-cdef-4303-8410-84fbe4aa01f3)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

ZorinOS 16 based on ubuntu 20.04 LTS

### How are you running Gitea?

I'm running gitea using docker-compose. I've attached it below.

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:nightly
    container_name: gitea
    restart: always
    environment:
      - GITEA__log__MODE="console"
      - GITEA__log__ROUTER="console"
      - GITEA__log__LEVEL="debug"
      - GITEA__log__STACKTRACE_LEVEL="debug"
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:2222:22"
```

### Database

SQLite
