### ISSUE TITLE
Bold text no longer displayed as bold

### ISSUE THREAD

**Issue by wolfbeast** [go-gitea/gitea#24835]
### Description

With one of the recent updates of our self-hosted Gitea (probably when moving to 1.19.3 from 1.18.*) some formatting no longer applies.
Most notably, headers and bold text is no longer rendered as such.

I checked the CSS involced and found:
```CSS
b, strong, h1, h2, h3, h4, h5, h6 {
    font-weight: var(--font-weight-bold);
}
b, strong {
    font-weight: bolder;
}
```

It seems the `--font-weight-bold` value is not filled properly or set to a bad value.
This occurs in the Pale Moon web browser. It does not occur in Edge.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

https://repo.palemoon.org/MoonchildProductions/UXP/issues/2252#issuecomment-36448
![Image1](https://github.com/go-gitea/gitea/assets/3359132/fb64b8b5-4bdd-40b1-8638-f41d7a58b377)

### Git Version

2.39.2, Wire Protocol Version 2 Enabled

### Operating System

CentOS

### How are you running Gitea?

x86_64 Linux binary downloaded from gitea.io

### Database

MySQL
