### ISSUE TITLE
[Actions] Allow `uses` to clone via different protocols

### ISSUE THREAD

**Issue by batuhanfaik** [go-gitea/gitea#24923]
### Feature Description

Currently `uses` only supports HTTP/HTTPS. I think it would be great if Gitea supported other Git URLs defined [here](https://git-scm.com/docs/git-clone#_git_urls).

For example, I would like to be able to run a job as follows:
 ```yaml
 steps:
      - name: Check out repository code
        uses: file:///git/actions/checkout@v3
        with:
          repository: {org}/{repo}
```
