### ISSUE TITLE
Commit Graph not working

### ISSUE THREAD

**Issue by alpe12** [go-gitea/gitea#24996]
### Description

All my commit graph pages load with a 500 image and this error:

```
An error occurred:

Render failed, failed to render template: repo/graph, error: template error: builtin(bindata):repo/graph:41:67 : executing "repo/graph" at <.ShortName>: can't evaluate field ShortName in type *git.Reference
----------------------------------------------------------------------
											{{svg "octicon-git-branch" 16 "gt-mr-2"}}<span title="{{.ShortName}}">{{.ShortName}}</span>
											                                                        ^
----------------------------------------------------------------------
```

Every page with commits on try.gitea.io returns 500 as well, but without an error shown. eg: https://try.gitea.io/silverwind/symlink-test/graph

### Gitea Version

1.20.0+dev-955-g51b130831

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.1

### Operating System

Ubuntu

### How are you running Gitea?

Docker

```
version: '3.3'
services:
  gitea:
    image: gitea/gitea:nightly-rootless
    container_name: gitea
    ports:
      - 192.168.1.250:2222:22
      - 127.0.0.1:8139:3000
    volumes:
      - './data:/data'
    environment:
      - TZ=America/Sao_Paulo
      
      #for rootless
      - GITEA_APP_INI=/data/gitea/conf/app.ini
      - GITEA_TEMP=/data/gitea/tmp
      - TMPDIR=/data/gitea/tmp
      - GITEA_CUSTOM=/data/gitea
      - GITEA_WORK_DIR=/app/gitea/gitea
      - GITEA__server__START_SSH_SERVER=true
      
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__server__ROOT_URL=https://192.168.1.250:48139/
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__ENABLE_GZIP=true
      - GITEA__server__LANDING_PAGE=home
      
      - GITEA__git__MAX_GIT_DIFF_LINES=5000
      - GITEA__git__MAX_GIT_DIFF_LINE_CHARACTERS=10000
      
      - GITEA__i18n__LANGS=en-US,es-ES,pt-BR
      - GITEA__i18n__NAMES=English,español,português do Brasil
      
      - GITEA__security__DISABLE_GIT_HOOKS=true
      - GITEA__security__REVERSE_PROXY_TRUSTED_PROXIES=127.0.0.1/8,172.17.0.0/12
      
      - GITEA__other__SHOW_FOOTER_VERSION=false
      - GITEA__other__SHOW_FOOTER_TEMPLATE_LOAD_TIME=false
      
      - GITEA__log__DISABLE_ROUTER_LOG=true
      - GITEA__log__ROUTER=none
      
      - GITEA__session__COOKIE_SECURE=true
      - GITEA__session__SAME_SITE=strict
      
      - GITEA__ui__DEFAULT_THEME=github-auto
      - GITEA__ui__THEMES=auto,gitea,arc-green,github,github-dark,github-auto
    restart: unless-stopped
    mem_limit: 300M
    cpu_shares: 256
    pids_limit: 100
    security_opt:
      - no-new-privileges=true
```

### Database

SQLite
