### ISSUE TITLE
[Proposal] Auto-assign projects to issues in issue templates

### ISSUE THREAD

**Issue by sebthom** [go-gitea/gitea#25028]
### Feature Description

Gitea issue templates are great! They already allow the automatic assignment of labels on issue creation.
I propose to allow the same for projects (kanban boards).

E.g.
```yaml
---
name: "Template Name"
about: "This template is for testing!"
title: "[TEST] "
ref: "main"
labels:
- bug
- "help needed" 

# new property `projects`:
projects:
- 3 # same-repo level project with ID 3
- ../1 # org level project with ID 1
---

This is the template!
```
