### ISSUE TITLE
UI: action runner state icons in organization misplaces

### ISSUE THREAD

**Issue by Bisstocuz** [go-gitea/gitea#25178]
### Description

Look at the screenshots below.

If there are two runners in the list, the bug will appear.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/42398278/d57134d7-aa07-4879-80d3-d8acffc722f7)

### Operating System

Linux

### How are you running Gitea?

Use `docker-compose.yml`:
```yml
networks:
  gitea:
    external: false

volumes:
  caddy_data:
    external: true
  caddy_config:

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: password
    volumes:
      - /mnt/gitea/mysql:/var/lib/mysql
    networks:
      - gitea

  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
    environment:
      - USER_UID=113
      - USER_GID=121
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=password
    depends_on:
      - db
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- "3000:3000"
      - "22:22"

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - gitea
```

### Database

MySQL
