### ISSUE TITLE
job use "strategy:matrix" with gitea actions ,a  dynamic array does not work

### ISSUE THREAD

**Issue by tomomuy** [go-gitea/gitea#25179]
### Description

In gitea actions, I used dorny/paths-filter as the method of file filtering and took the output as the `strategy:matrix`  parameter for the next job, but instead of generating multiple jobs, gitea actions has and will only generate one job.
This is my test on GitHub Actions and I didn't get this error,[[t · tomomuy/monorepo-test@869b14d (github.com)](https://github.com/tomomuy/monorepo-test/actions/runs/5223469755)](https://github.com/tomomuy/monorepo-test/actions/runs/5223469755)

### Gitea Version

1.20rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

gitea actions
![image](https://github.com/go-gitea/gitea/assets/116566664/8f954224-2700-4bf7-8b75-4b7fa70bfdbb)
github actions
![image](https://github.com/go-gitea/gitea/assets/116566664/7caaffbf-a3ce-4c05-9813-5a471d4ab017)

### Operating System

Linux

### How are you running Gitea?

docker:  gitea/gitea:1.20.0-rc0

### Database

SQLite

**Comment by wolfogre** [comment]
<details>
<summary>The workflow file</summary>

```yaml
name: Build Service
on: 
  push: 
    branches: [main]
jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.filter.outputs.changes }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3


    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          wall:
            - wall/**
          user:
            - user/**
            - basic/**'
            - pom.xml
          gateway:
            - gateway/**
            - basic/**'
            - pom.xml                  


  build:

    needs: pre-build
    strategy:
      matrix:
        service: ${{ fromJSON(needs.pre-build.outputs.service) }}
    runs-on: ubuntu-latest

    steps:

    - name: echo
      run: |
        echo "构建${{ matrix.service }}"
        echo "${{ needs.pre-build.outputs.service }}"
        echo "${{ fromJSON(needs.pre-build.outputs.service) }}"        

    
```

</details>

The point is

```yaml
    strategy:
      matrix:
        service: ${{ fromJSON(needs.pre-build.outputs.service) }}
```

Although Gitea can get the outputs after #24230, it doesn't evaluate expressions for `matrix`, only for `runs-on`. It could be fixed at [jobparser.go#L45-L61](https://gitea.com/gitea/act/src/commit/fe76a035ad75ef9167a87ef0e3088868521a0bf0/pkg/jobparser/jobparser.go#L45-L61).

And maybe it could also be fixed when #24603 is done.
