### ISSUE TITLE
404 when access explore/code

### ISSUE THREAD

**Issue by webysther** [go-gitea/gitea#25356]
### Description

I made a docker clean install and enable the code indexer with:

GITEA__indexer__REPO_INDEXER_ENABLED=true

Everything works like a charm, but the https://example.com/explore/code show 404 status code, every search in organization, repo works fine.

Another thing: I used gitea/gitea:latest and I get 1.20.0+rc0, RC is considered stable?

### Gitea Version

1.20.0+rc0

### Can you reproduce the bug on the Gitea demo site?

No, code search is disabled.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/750007/784c0d50-11ef-4e38-8653-75291e7feb38)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Container Manager (docker engine) on DSM 7.2

### How are you running Gitea?

My deploy:

```yml
version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: app-gitea
    env_file: .env
    networks:
      - gitea
    volumes:
      - "$STORAGE/data:/data"
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000
      - 22
    restart: unless-stopped

networks:
  gitea:
    name: gitea
```

.env

```env
USER_UID=1026
USER_GID=101
STORAGE=/volume1/docker/gitea
GITEA__migrations__ALLOW_LOCALNETWORKS=true
GITEA__indexer__REPO_INDEXER_ENABLED=true
```

### Database

SQLite
