### ISSUE TITLE
CI Task Display Error

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#25574]
### Description

When the second task (Package Build) is executed, it shows immediate completion, but in fact the task is not finished.

![图片](https://github.com/go-gitea/gitea/assets/33776693/d5dcb3d8-15f4-4028-8166-da3081ae40c6)

`.gitea/workflows/develop.yaml`
```yaml
name: Package Night Build
on: [ push ]

jobs:
  dev-rocky:
    strategy:
      matrix:
        release: [ "rocky" ]
        version: [ "el9" ]
        arch: [ "amd64","arm64" ]
    runs-on: rocky-${{matrix.arch}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Package Build
        uses: actions/package-builder@main
        with:
          release: ${{matrix.release}}
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
      - name: Upload Package
        run: |
            echo curl path/to/release  
```

act_runner_version: 0.2.0

action source : https://git.d7z.net/actions/package-builder

### Gitea Version

1.20.0-rc2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

rockylinux 9 - systemd  

### Database

SQLite

**Comment by wolfogre** [comment]
I cannot reproduce it, does it always happen or just sometimes? Is there any strange log on the act runner?

**Comment by ExplodingDragon** [comment]
The logs look fine and the task compiles and passes, except that there is a problem with the page presentation.

The situation is that the step finishes immediately, but it is actually still executing, and the log is updating when I expand the current step.

This problem occurs if I use custom Actions.

EDIT: At this point I am using the latest version of the main branch (c76b221cca)

**Comment by wolfogre** [comment]
Sorry, I understand the right way to reproduce it now. The point is that I should use the custom action.

But TBH, it's not easy for me. The custom action need a runner with podman, and it will use your custom container image to build your repo code. I don't have them, so you need to provide more details about this, maybe the runner logs, a screen recording, or the output when you exec `bash -e ${{ github.action_path }}/src/build.sh '${{inputs.profile}}'` manually.

If it is not convenient for you to provide these here, please join our QQ group (328432459) and @ me. (Or Discord, but I think you are Chinese.)

**Comment by ExplodingDragon** [comment]
I rebuilt the configuration:


```yaml
name: 'Package Builder'
description: "一个简易的软件包编译项目, 使用 bash-toolbox 来完成编译任务"
inputs:
  release:
    description: '指定发行版名称，可选 (centos,rocky,arch,debian,ubuntu)'
    required: true
  version:
    description: '指定发行版版本, 根据之前定义的发行版名称来确定，如果无效则返回错误'
    required: true
  arch:
    description: '指定发行版架构，可选 (amd64,arm64,x390s),如果对应发行版无此架构系统则返回错误'
    required: true
  profile:
    description: '指定使用的配置文件'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - id: check
      name: '检查输入参数'
      run: |
        echo '${{inputs.release}}' '${{inputs.version}}'  '${{inputs.arch}}'
        echo 模拟检测
        for (( i = 0; i < 20; i++ )); do
            echo "testing $i ..."
            sleep 1
        done        
      shell: bash
    - name: "编译项目"
      run: |
        echo ' '${{inputs.profile}}''
        for (( i = 0; i < 100; i++ )); do
            echo "build $i ..."
            sleep 1
        done        
      shell: bash
```

I suspect the problem is with `composite action`, during task execution, the `check` task is displayed normally, but the problem recurs when the execution reaches `编译项目`.

EDIT:  My running container is Podman.

Instructions for use: : https://packages.d7z.net/packages/gitea-runner
Related software packages:: https://repos.d7z.net/yum/stable/el9/Packages/gitea-runner-0.2.0-4.el9.x86_64.rpm
