### ISSUE TITLE
Docker hub version change

### ISSUE THREAD

**Issue by bauermarkus** [go-gitea/gitea#25609]
### Description

Before I always got the latest **stable** version.
With the change to 1.20.0-rc1 I got with the same docker compose file the release candidate

Is this a intended undocumented change?

```
gitea:
    image: gitea/gitea:latest #only stable versions
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=3222
      - RUN_MODE=prod
      - DISABLE_REGISTRATION=true
      - GITEA__attachment__MAX_SIZE=256
      - GITEA__attachment__MAX_FILES=25
      - GITEA__attachment__ALLOWED_TYPES=image/*|audio/*|video/*|text/plain|.csv|.zip|.docx|.pptx|.xls|.xlsx|.eml|.pdf|.mov
    hostname: gitea-docker-prod
    volumes:
      - gitea-data:/data
      #- ./volumes/gitea:/data
    ports:
      - "3280:3000"
      - "3222:3222"
```

### Gitea Version

1.20.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker

### Database

SQLite
