### ISSUE TITLE
[Actions] `push` trigger event does not work properly

### ISSUE THREAD

**Issue by Zettat123** [go-gitea/gitea#25718]
### Description

Reported in QQ group by **[EOF]** .

If a workflow has `on` like
```
on:
  push:
    tags-ignore:
      - '**'
    paths:
      - 'project.yaml'
```
The workflow cannot be triggered after editing `project.yaml`

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

cmd

### Database

None

**Comment by ExplodingDragon** [comment]
It looks like a combination problem, and it is fine to use only the following code.

```yaml
on:
  push:
    paths:
      - 'project.yaml'
```

ref: https://packages.d7z.net/packages/gitea/actions/runs/37
