### ISSUE TITLE
[CI] action triggered by push is displayed under PR

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#25736]
### Description

When a PR is merged, the action should be trigged by `push` event. But on Gitea UI, it's showing under PR commit. The issue is introduced in v1.19.4.

### Gitea Version

v1.19.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

This shows the actions is triggered by `push` and is associated with commit.

<img width="823" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/63ec216e-ccf2-4190-abe2-35e59924eb6e">

However, on the main branch, the action doesn't show up.

<img width="461" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/4f33fecd-f65e-4a28-aa5e-fee48cb892b4">

Under the already merged PR's last commit, the action is showing.

<img width="1123" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/f65819ad-ac4b-4583-9cf8-713fba0915f5">

### How are you running Gitea?

Run in Kubernetes.

### Database

PostgreSQL

**Comment by wolfogre** [comment]
Could you please show us your workflow file?

**Comment by harryzcy** [comment]
@wolfogre 

```yaml
name: Tests

on:
  push:
    tags-ignore:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  python-test:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v3

      # - name: Set up Python
      #   uses: https://github.com/actions/setup-python@v4
      #   with:
      #     python-version: "3.11"
      - name: Set up Python
        run: |
          VERSION=3.11.4
          cd /tmp/
          wget -q https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz
          tar -xzvf Python-$VERSION.tgz > /dev/null
          cd Python-$VERSION/

          apt-get update > /dev/null
          apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev > /dev/null

          ./configure --enable-optimizations > /dev/null
          make -j `nproc` > /dev/null
          make altinstall > /dev/null
          python3.11 -V

          ln -s /usr/local/bin/python3.11 /usr/local/bin/python
          ln -s /usr/local/bin/pip3.11 /usr/local/bin/pip

          python -VV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov ruff
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest --cov --cov-report=term-missing
```

**Comment by Zettat123** [comment]
The first line of job log should show the trigger event. Could you please check the log and show us the trigger event?

![image](https://github.com/go-gitea/gitea/assets/15528715/43091515-29b4-483b-b376-6a78a627c72b)

**Comment by harryzcy** [comment]
@Zettat123 For your question, it's triggered by pull_request.
<img width="587" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/1fcb8863-1755-47c6-b296-dfa6114e5498">


Now with the following workflow, two action gets triggered by merging the pull request.

```yaml
name: Tests

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - main
  pull_request:
    branches: [main]
```

<img width="839" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/37e4d41e-45b2-47a0-b1ac-8ba0966baba8">

The one on a detached commit is triggered by `pull_request`.
<img width="577" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/b401b61a-8fc8-448a-8c07-984db39b5f48">

The one on main is triggered by `push`.
<img width="503" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/1e4ddec2-1770-4215-b108-9d42c2a05abe">
