### ISSUE TITLE
Cant run Gitea Actions from private Repo

### ISSUE THREAD

**Issue by Schrolli91** [go-gitea/gitea#26032]
### Description

I have a private Repo with an example action.
Its totaly clear to me, that the runner can not clone this private repo without authentication.
So i use the checkout action with a personal access token and clone the action repo to the runner.
After that i try to run the action as follwing:

```yaml
  - name: Check out repository code
    uses: actions/checkout@v3
    with:
      token: ${{ secrets.token }}
  - name: Hello world action step
    id: hello
    uses: ./
```

But this does not work.
I have seen, that the Github docs show exactly this tooling for private repos.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow

Also i cant find any clear instructions or documentation, how to deal with private repos in actions on gitea.

### Gitea Version

1.20.0

### Operating System

Debian Linux

### How are you running Gitea?

Running via docker in an debian Linux hosted inside a VPS (LXC)

**Comment by wolfogre** [comment]
Have you set a right secret with `token` as the name?

Actually, you don't need to do this. The runner will get a temporary token to  checkout the repo even it's private. Please try again without `with`

```yaml
  - name: Check out repository code
    uses: actions/checkout@v3
```

**Comment by Schrolli91** [comment]
secret is set and it can clone successful - without it cant.

The runner maybe can checkout the "repo under test". But what happens if i want to use a action, that is hosted in another private repo?

This is the job from the github hello world action, hosted on my own gitea server.
The folowing code will fail:
![image](https://github.com/go-gitea/gitea/assets/6043382/225e90b1-5027-46d8-b53e-ded5ce6539c7)


```yaml
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: https://gitea..####/actions/hello-world-docker-action@main
        with:
          who-to-greet: 'test action'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
```
