### ISSUE TITLE
[actions] Multiple identical reusable workflow files are cached

### ISSUE THREAD

**Issue by Snazzya** [go-gitea/gitea#26092]
### Description

I used files-changed.yml to output git's file changes, and subsequently discovered that runner was caching duplicate repositories.

files-changed.yml

```yaml
name: files-changed

on:
  workflow_call:
    outputs:
      exam:
        value: ${{ jobs.detect.outputs.exam }}
      user:
        value: ${{ jobs.detect.outputs.user }}
      gateway:
        value: ${{ jobs.detect.outputs.gateway }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      gateway: ${{ steps.changes.outputs.gateway }}
      exam: ${{ steps.changes.outputs.exam }}
      user: ${{ steps.changes.outputs.user }}
    steps:
      - uses: https://github.com/actions/checkout@v3
      - uses: https://github.com/dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ gitea.ref }}
          filters: |

            exam:
              - exam/**
              - basic/**
              - pom.xml
            user:
              - user/**
              - basic/**
              - pom.xml
            gateway:
              - gateway/**
              - basic/**
              - pom.xml
```

cache files

```bash
c209e0011589:/# cd ~/.cache/act
c209e0011589:~/.cache/act# ls
***-.gitea-workflows-files-changed.yml@0c7ea79e8bf0e3ad5434d3c960f3757f2b1de783
***-.gitea-workflows-files-changed.yml@605f5b35384b5e14983f7fd06a6ad527c4965eb2
***-.gitea-workflows-files-changed.yml@7a5506b743d87f630c83d3ec456329213a5b8be9
***-.gitea-workflows-files-changed.yml@fa0181a7bb1fcd7167ea7d2cc7446c7fc98bc7f8
https---github.com-actions-checkout@v3
https---github.com-dorny-paths-filter@v2
https---github.com-actions-setup-java@v3.11.0
```

### Gitea Version

1.20

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker images: 
gitea: gitea/gitea:1.20
gitea runner: gitea/act_runner:0.2.3

### Database

SQLite
