### ISSUE TITLE
Can't run docker container anymore.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [go-gitea/gitea#26196]
### Description

Up until now I had this running flawlessly

```
---
version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - 3020:3000
      - 222:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
    labels:
      - deunhealth.restart.on.unhealthy=true
    networks:
      - gitea
    volumes:
      - /home/xxx/docker-data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  gitea:
    external: false
```

Now the log in Portainer says:

```
2023/07/28 08:13:10 ...g/config_provider.go:327:deprecatedSettingFatal() [F] Deprecated fallback `[server]` `LFS_CONTENT_PATH` present. Use `[lfs]` `PATH` instead. This fallback will be/has been removed in v1.19.0. Shutting down

Received signal 15; terminating.

Server listening on :: port 22.

Server listening on 0.0.0.0 port 22
```

### Gitea Version

whatever latest version is pulled from image: gitea/gitea:latest

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.34.1 runs on the server / whichever is included in image: gitea/gitea:latest

### Operating System

Server runs on Ubuntu 22.04.2 LTS

### How are you running Gitea?

Docker container on me server

### Database

SQLite
