### ISSUE TITLE
Workflow with on.push.paths triggers only on second push

### ISSUE THREAD

**Issue by nblock** [go-gitea/gitea#26270]
### Description

The following workflow configuration file [should trigger on push events to any branch where files anywhere below `dir2/` got changed](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths).

```yml
---
name: Run only on changes within dir2

on:
  push:
    paths:
      - dir2/**

jobs:
  dir2:
    runs-on: playground
    steps:
      - name: Step for files in dir2
        run: |
          echo 'something changed'
```

With Gitea 1.20.2 and act runner 0.2.4 this works when pushing a commit that modifies files in `dir2/` and the branch already exists on the remote (e.g. the branch `main`).

It does not work when a new commit that modifies files in `dir2`/ is pushed to a new branch on the remote. The event is silently ignored. However, the workflow triggers when pushing a second commit to the same branch.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.39.2

### Operating System

Debian 12

### How are you running Gitea?

Official release supervised by systemd.

### Database

PostgreSQL
