### ISSUE TITLE
Use matrix variable in action step name

### ISSUE THREAD

**Issue by TheZoker** [go-gitea/gitea#26307]
### Feature Description

I want to use the a matrix value within the name of a step.
Something like this:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    strategy:
      matrix:
        include:
          - docker-id: "example-a"
          - docker-id: "example-b"
    steps:
      - name: Build and push Docker image ${{ matrix.docker-id }}
        ...
```

Currently the variable is not replaced with the value and is just displayed as is. 

As reference: Github supports using a matrix variable name within the step name. 

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1368405/3c85ec12-1ad7-4620-87dc-63278d976fc4)
