### ISSUE TITLE
Registration via oauth2 provider (Keycloak)

### ISSUE THREAD

**Issue by pat-s** [go-gitea/gitea#26457]
### Description

I have set the following config options

```
[service]
      ALLOW_ONLY_EXTERNAL_REGISTRATION= true
      REQUIRE_EXTERNAL_REGISTRATION_PASSWORD= false
      SHOW_REGISTRATION_BUTTON= true
[openid]
      ENABLE_OPENID_SIGNUP= true
      ENABLE_OPENID_SIGNIN= true
```

Which results in the following UI config

![image](https://github.com/go-gitea/gitea/assets/8430564/8e539e22-c19f-4926-baaf-a7b15cfddac9)

However, I still get the following message when clicking on the "register" button

![image](https://github.com/go-gitea/gitea/assets/8430564/3fce37dc-ab84-42da-9839-ad95927a4f1c)

I've seen #22168 but cannot get it working with the values provided there. Maybe a new bug?

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea helm chart (and yes, I've checked `app.ini` manually to make sure the issue is not due to the issue of the helm chart not fully recreating the config file)

### Database

PostgreSQL

**Comment by wfjake** [comment]
I use this config. You simply click the "Signin with [OAuth2 source name]" at the bottom of the login page instead, it will login you in/autocreate a new account for you if you haven't logged in before.

```
[service]
REGISTER_EMAIL_CONFIRM            = true
DISABLE_REGISTRATION              = true
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
REQUIRE_SIGNIN_VIEW               = true

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[oauth2_client]
REGISTER_EMAIL_CONFIRM   = false
ENABLE_AUTO_REGISTRATION = true
USERNAME                 = preferred_username
ACCOUNT_LINKING          = auto
```

**Comment by pat-s** [comment]
Thanks! 

When I do that, I get a 500 back after logging into my oauth2 provider. I wonder how it can work for you when you have `ENABLE_OPENID_SIGNUP=false` and `DISABLE_REGISTRATION=true` set 🤔

**Comment by wfjake** [comment]
Can you check the logs? The 500 error is probably because we are using different IdPs and yours does not send the `preferred_username` claim and sends some other claim. OpenID is for the OpenID tab on the login page (basically anyone can use their IdP to login to your site) and is unrelated to external authentication sources.

**Comment by pat-s** [comment]
Ahh thanks! I was completely on the wrong side...confused by "external OpenID" and "oauth2".

So I now got it working for Keycloak with the following config

```
    openid:
      ENABLE_OPENID_SIGNUP: false
      ENABLE_OPENID_SIGNIN: false

    service:
      SHOW_REGISTRATION_BUTTON: false
      DISABLE_REGISTRATION: true
      ALLOW_ONLY_EXTERNAL_REGISTRATION: false

    oauth2_client:
      REGISTER_EMAIL_CONFIRM: false
      ENABLE_AUTO_REGISTRATION: true
      ACCOUNT_LINKING: auto
      USERNAME: username
      OPENID_CONNECT_SCOPES: "profile email"
```

The `openid` fields are actually not needed here - it's only about the `oauth2_client` ones.
