### ISSUE TITLE
checkout submodules auth failed on workflow/action(personal access tokens is not work)

### ISSUE THREAD

**Issue by vicalloy** [go-gitea/gitea#26507]
### Description

My repository has a private submodule. I created a Personal Access Token (PAT) and added the "read repository" permission to this token. Then, I placed this token in Actions.Secrets with the name GH_PAT.

I got errors:
```
::group::Setting up auth
[command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
[command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
[command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/git\.sf\.tech\/\.extraheader
[command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/git\.sf\.tech\/\.extraheader' && git config --local --unset-all 'http.https://git.sf.tech/.extraheader' || :
[command]/usr/bin/git config --local http.https://git.sf.tech/.extraheader AUTHORIZATION: basic ***
::endgroup::
::group::Fetching the repository
[command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +bd836639774617aba2efb873cafcd7d8dfcbcb4d:refs/remotes/origin/main
remote: Forbidden
fatal: unable to access 'https://git.sf.tech/C/CodeGen/': The requested URL returned error: 403
The process '/usr/bin/git' failed with exit code 128
Waiting 10 seconds before trying again
```

```
name: Build
run-name: Build by @${{ gitea.actor }}

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      volumes:
        - /home/vicalloy/.ssh:/root/.ssh
    steps:
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v3
        with:
          token: "${{ secrets.GH_PAT }}"
          submodules: true
```

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

```
version: "3.6"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:${GITEA_VERSION:-1.20}
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - USER_UID=1026
      - USER_GID=100
      - DOMAIN=${IP_ADDRESS}
      - SSH_DOMAIN=${IP_ADDRESS}
      - HTTP_PORT=3000
      - ROOT_URL=https://${IP_ADDRESS}
      - SSH_PORT=2222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DISABLE_REGISTRATION=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      - GITEA__oauth2_client__ACCOUNT_LINKING=auto
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=true
      - GITEA__oauth2_client__OPENID_CONNECT_SCOPES=openid email groups
      - GITEA__oauth2_client__USERNAME=email
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__webhook__ALLOWED_HOST_LIST=192.168.0.*
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  gitea:
```

### Database

None

**Comment by vicalloy** [comment]
I am trying to validate the token with Git, but I am encountering the following error.
If I provide an invalid token, Git will require username and password input.
```
base64_token = base64("x-access-token:pat_token")

git -c http.extraheader="AUTHORIZATION: basic base64_token" clone https://git.sf.tech/Castle/Castle.git
Cloning into 'Castle'...
remote: Forbidden
fatal: unable to access 'https://git.shifei.tech/Castle/Castle.git/': The requested URL returned error: 403
```

**Comment by wolfogre** [comment]
You don't have to do this, runner will use an automatically generated token to clone private repo (only the repo which trigger the workflow, not all repos in your Gitea).
So I think this is enough:

```yaml
    steps:
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v3
        with:
          submodules: true
```

Actually, `token: "${{ secrets.GH_PAT }}"` should work too, I think it failed because of incorrect permission configuration.

**Comment by vicalloy** [comment]
@wolfogre If no `token: "${{ secrets.GH_PAT }}"` , root repository can be checkout, submodules will failed with `remote: Forbidden`.
After add `token: "${{ secrets.GH_PAT }}"`, root repository will failed with `remote: Forbidden`.
![1](https://github.com/go-gitea/gitea/assets/43507/a82fecfb-6d2d-48c2-b9b4-79536ad869c6)
![2](https://github.com/go-gitea/gitea/assets/43507/3c82ed12-8162-40ab-a7f4-9cb4902f6573)

**Comment by wolfogre** [comment]
<img width="1584" alt="image" src="https://github.com/go-gitea/gitea/assets/9418365/e3aaf23c-09c9-4023-a1b5-b935a35a1718">

So it's a token that can only read packages, not codes.

You need:
<img width="963" alt="image" src="https://github.com/go-gitea/gitea/assets/9418365/8c7e3d06-c3c8-4507-9017-2eb638c66c96">

**Comment by vicalloy** [comment]
Sorry for my mistake. I created a new token. 
The root repository can be checked out successfully, but I'm still encountering errors with the submodules. 
It seems that the submodule checkout is being done through the `ssh://` protocol, and the token is not being utilized.
We are using `2222` as the SSH port, which could be a potential reason for the issue.

![3](https://github.com/go-gitea/gitea/assets/43507/d05c8e09-29a1-47bf-81da-2f1746ce1b15)
```
::group::Setting up auth for fetching submodules
[command]/usr/bin/git config --global http.https://git.sf.tech/.extraheader AUTHORIZATION: basic ***
[command]/usr/bin/git config --global --unset-all url.https://git.sf.tech/.insteadOf
[command]/usr/bin/git config --global --add url.https://git.sf.tech/.insteadOf git@git.sf.tech:
[command]/usr/bin/git config --global --add url.https://git.sf.tech/.insteadOf org-1@github.com:
::endgroup::
::group::Fetching submodules
[command]/usr/bin/git submodule sync
[command]/usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1
Submodule 'vendor/Castle' (ssh://git@git.sf.tech:2222/Castle/Castle.git) registered for path 'vendor/Castle'
Submodule 'vendor/Sample' (ssh://git@git.sf.tech:2222/Manuals/Sample.git) registered for path 'vendor/Sample'
Cloning into '/workspace/huxm/demo/vendor/Castle'...
Cloning into '/workspace/huxm/demo/vendor/Sample'...
Gitea: Public (Deploy) Key: 5:raspberry-pi is not authorized to read manuals/sample.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@git.sf.tech:2222/Manuals/Sample.git' into submodule path '/workspace/huxm/demo/vendor/Sample' failed
Failed to clone 'vendor/Sample'. Retry scheduled
Cloning into '/workspace/huxm/demo/vendor/Sample'...
Gitea: Public (Deploy) Key: 5:raspberry-pi is not authorized to read manuals/sample.
fatal: Could not read from remote repository.
```

**Comment by wolfogre** [comment]
Maybe the token does not match your needs easily, I think you should try using `ssh-key`, see https://github.com/actions/checkout#usage

**Comment by vicalloy** [comment]
Thanks, I have added a deploy key to my runner as a temporary solution.

**Comment by WilliamBolhofer** [comment]
In the Github actions checkout documentation, there's this relating to the checkout of submodules:

`# Whether to checkout submodules: true to checkout submodules or recursive to`
`# recursively checkout submodules.`
`#`
`# When the ssh-key input is not provided, SSH URLs beginning with`
`# git@github.com: are converted to HTTPS.`
`#`
`# Default: false`
`submodules: ""`

The action automatically changes the ssh prefix of the URL to https if it begins with the github string if there's no ssh-key. That step is needed if you are going to use the Access Token method. I'm not sure how this could be fixed easily because everyone's Gitea instance will have a different URL as well as a SSH port as part of the URL possibly. The only thing I can think of at the moment is to add some sort of additional option for a git ssh URL substitution string.

In the meantime, it might be better to just create an automated tool user that has an SSH key that can be specified with the 'ssh-key' option. Then give that tool user read-only access to the repos of interest.

**Comment by ljbkusters** [comment]
Sorry if this is a necrobump but I wanted to share my experience for anyone running into this issue.

I had the same issue and was able to solve it by adding a private access token through a "bot" account I added to my Gitea instance and generating a PAT through the interface with read rights for both the main and submodule repos. I also had to assign this bot account to the right organizations for it to be able to access all repos. It's really as simple as that. For security reasons I made sure this bot account and PAT only have read access. No Deploy/SSH key needed.

**Comment by lifeofguenter** [comment]
I have the same issue. Even with a PAT from a "bot" account that has access to org + repos its not working.

Exactly the same procedure works on the server directly - so its not an issue with credentials. Its like something is interfering with the auth.

**Comment by corpix** [comment]
I came across with same issue.
Here is a small example which works for me, posting this here because it took time and tons of frustration to fill all parts correctly:

> only relevant parts, my secret name is `REPOSITORIES_TOKEN`

```yaml
name: ...
jobs:
  build:
    steps:
      - name: git config
        run: |
          git config --global url.'https://git.YOUR.PRIVATE.HOST'.insteadOf 'ssh://gitea@git.YOUR.PRIVATE.HOST:2222'
      - name: checkout
        with:
          token: "${{ secrets.REPOSITORIES_TOKEN }}"
          submodules: true
```
