### ISSUE TITLE
OpenSSH started in Docker image even with built-in SSH server enabled

### ISSUE THREAD

**Issue by laurivosandi** [go-gitea/gitea#26501]
### Description

I am using following in my Kubernetes manifests to run Gitea from Docker image `gitea/gitea:1.20.2`

```
          env:
            - name: GITEA__SERVER__START_SSH_SERVER
              value: "true"
            - name: GITEA__SERVER__SSH_LISTEN_PORT
              value: "2222"
```
Looks like the `s6` init system starts OpenSSH regardless of the environment variable value:

```
gitea-0:/# netstat -lntup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      18/sshd -D -e [list
tcp        0      0 :::2222                 :::*                    LISTEN      -
tcp        0      0 :::22                   :::*                    LISTEN      18/sshd -D -e [list
tcp        0      0 :::8080                 :::*                    LISTEN      -
tcp        0      0 :::3000                 :::*                    LISTEN      -
```

I expected OpenSSH not to be started at all if the env var `GITEA__SERVER__START_SSH_SERVER` is set to true

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

N/A

### Operating System

N/A

### How are you running Gitea?

https://git.k-space.ee/k-space/kube/src/branch/master/gitea/application.yaml

### Database

MySQL
