### ISSUE TITLE
Action shows running after all tasks finished

### ISSUE THREAD

**Issue by Nathanwoodburn** [go-gitea/gitea#26559]
### Description

A few actions are showing running even though all the steps have finished.
I haven't seen anything in any of the logs (server or runners). I restarted my runners and my server. I updated the server (from 1.20.1 -> 1.20.2) and that didn't fix it.

### Gitea Version

1.20.1, 1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Nathanwoodburn/197bed532c07604739061efab3cf55b6

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/62039630/7abad9ef-56b8-4ae4-9e80-866304be76b5)
![image](https://github.com/go-gitea/gitea/assets/62039630/33c97c23-dab8-4a3b-84ec-991227d4d006)

### Git Version

2.34.1 (OS), 2.40.1 (Gitea Docker)

### Operating System

Ubuntu 22.04.2 LTS (aarch64)

### How are you running Gitea?

Running in a docker compose

```yaml
version: "3.7"
services:
  mariadb:
    hostname: mariadb
    image: linuxserver/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TZ}
    networks:
      - nginx
    restart: unless-stopped
    volumes:
      - mariadb:/config

  gitea:
    container_name: gitea
    hostname: gitea
    image: gitea/gitea:latest
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      TZ: ${TZ}
      GITEA__database__HOST: 'mariadb'
      GITEA__database__USER: ${DATABASE_USER}
      GITEA__database__PASSWD: ${DATABASE_PASSWORD}
      GITEA__database__NAME: ${DATABASE_NAME}
      GITEA__database__DB_TYPE: mysql
    networks:
      - nginx
    ports:
      - 8124:3000      
      - 2222:22      
    restart: unless-stopped
    volumes:
      - gitdata:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh:/data/git/.ssh
    depends_on:
      - mariadb

volumes:
  mariadb:
  gitdata:
  
networks:
    nginx:
        name: nginx
        external: true

```

### Database

mariadb
