### ISSUE TITLE
Schedule in actions is not working

### ISSUE THREAD

**Issue by vicalloy** [go-gitea/gitea#26571]
### Description

I tried the schedule demo, but the actions were not triggered.

```
on:
  schedule:
    - cron: '* * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
```

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

```
version: "3.6"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:${GITEA_VERSION:-1.20}
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - USER_UID=1026
      - USER_GID=100
      - DOMAIN=${IP_ADDRESS}
      - SSH_DOMAIN=${IP_ADDRESS}
      - HTTP_PORT=3000
      - ROOT_URL=https://${IP_ADDRESS}
      - SSH_PORT=2222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DISABLE_REGISTRATION=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      - GITEA__oauth2_client__ACCOUNT_LINKING=auto
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=true
      - GITEA__oauth2_client__OPENID_CONNECT_SCOPES=openid email groups
      - GITEA__oauth2_client__USERNAME=email
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__webhook__ALLOWED_HOST_LIST=192.168.0.*
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  gitea:
```

### Database

None
