### ISSUE TITLE
deb upload: unsupported compression algorithm

### ISSUE THREAD

**Issue by phoedos** [go-gitea/gitea#26702]
### Description

Trying to upload deb to gitea package registry according to official documentation: 
[](https://docs.gitea.com/next/usage/packages/packages/debian)

```
curl --user your_username:your_password_or_token \
     --upload-file path/to/file.deb \
     https://gitea.example.com/api/packages/testuser/debian/pool/bionic/main/upload
```

as example took logstash-8.9.0-amd64.deb from official Elastic site

```
curl -v --insecure --noproxy '*' --user testuser:testuser --upload-file /home/testuser/logstash-8.9.0-amd64.deb https://mysite.mydomain.local/gitea/api/packages/testorg/debian/pool/bionic/main/upload

*   Trying 192.168.0.2:443...
* TCP_NODELAY set
* Connected to mysite.mydomain.local (192.168.0.2) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject:  xxx
*  start date: Jun 29 05:48:47 2023 GMT
*  expire date: Jun 26 05:48:47 2033 GMT
*  issuer: xxx
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'testuser'
* Using Stream ID: 1 (easy handle 0x561dc7dd9b60)
> PUT /gitea/api/packages/testorg/debian/pool/bionic/main/upload HTTP/2
> Host: mysite.mydomain.local
> authorization: Basic xxx
> user-agent: curl/7.68.0
> accept: */*
> content-length: 345967036
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 400
< server: nginx/1.14.1
< date: Thu, 24 Aug 2023 05:34:30 GMT
< content-type: text/plain;charset=utf-8
< content-length: 33
< x-content-type-options: nosniff
< access-control-allow-credentials: true
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-headers: Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With,X-API-Version
<
* Connection #0 to host mysite.mydomain.local left intact

```

nginx log where gitea is proxied on localhost inside docker:
```
192.168.0.3  - mysite.mydomain.local [24/Aug/2023:10:40:30] TLSv1.3 "PUT /gitea/api/packages/testorg/debian/pool/bionic/main/upload HTTP/2.0" 400 33 "-" "" "curl/7.68.0" "-" testuser 10.859 7.859 127.0.0.1:81
```
gitea logs: 
```
2023/08/24 10:41:24 ...eb/routing/logger.go:68:func1() [W] router: slow      PUT /api/packages/testorg/debian/pool/bionic/main/upload for 192.168.0.2:0, elapsed 3730.8ms @ debian/debian.go:130(debian.UploadPackageFile)
2023/08/24 10:41:28 ...eb/routing/logger.go:102:func1() [I] router: completed PUT /api/packages/testorg/debian/pool/bionic/main/upload for 192.168.0.2:0, 400 Bad Request in 7956.9ms @ debian/debian.go:130(debian.UploadPackageFile)
```

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker-compose.yml
```
services:
  gitea:
    image: gitea:1.20.1
    container_name: gitea
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__DOMAIN: mysite.mydomain.local
      GITEA__server__HTTP_PORT: 80
      GITEA__server__ROOT_URL: https://mysite.mydomain.local/gitea/
      #ssh
      GITEA__server__SSH_PORT: 222
      GITEA__server__SSH_LISTEN_PORT: 222
      GITEA__server__SSH_LISTEN_HOST: 0.0.0.0
      GITEA__server__DISABLE_SSH: false
      GITEA__server__START_SSH_SERVER: true
      #this is trusted url for webhooks
      #GITEA__webhook__ALLOWED_HOST_LIST: mysite.mydomain.local, 192.168.0.0/24
      #GITEA__webhook__ALLOWED_HOST_LIST: '*'
      #GITEA__webhook__DISABLE_WEBHOOKS: false
      #repo migrations
      GITEA__migrations__ALLOWED_DOMAINS: '*.mydomain.local'
      GITEA__migrations__SKIP_TLS_VERIFY: true
      #indexer comment during upgrade
      #GITEA__indexer__REPO_INDEXER_ENABLED: true
      #GITEA__indexer__REPO_INDEXER_PATH: 'indexers/repos.bleve'
      #GITEA__indexer__UPDATE_BUFFER_LEN: 20
      #GITEA__indexer__MAX_FILE_SIZE: 1048576
      #GITEA__indexer__REPO_INDEXER_INCLUDE:
      #GITEA__indexer__REPO_INDEXER_EXCLUDE: 'resources/bin/**'
      #new indexer settings for 1.20.1 ref cheatsheet
      GITEA__indexer__ISSUE_INDEXER_TYPE: bleve
      GITEA__indexer__ISSUE_INDEXER_PATH: 'indexers/issues.bleve'
      GITEA__indexer__ISSUE_INDEXER_NAME: gitea_issues
      GITEA__indexer__REPO_INDEXER_ENABLED: true
      GITEA__indexer__REPO_INDEXER_REPO_TYPES: 'sources,forks,mirrors,templates'
      GITEA__indexer__REPO_INDEXER_NAME: gitea_codes
      GITEA__indexer__REPO_INDEXER_TYPE: bleve
      GITEA__indexer__REPO_INDEXER_PATH: 'indexers/repos.bleve'
      GITEA__indexer__REPO_INDEXER_EXCLUDE_VENDORED: false
      GITEA__indexer__REPO_INDEXER_INCLUDE: '**'
      GITEA__indexer__STARTUP_TIMEOUT: '30s'
      GITEA__indexer__MAX_FILE_SIZE: '1048576'
      #
      GITEA__cron__ENABLED: true
      GITEA__cron__RUN_AT_START: true
      GITEA__cron__SCHEDULE: '* */5 * * * *'
      #
      #GITEA__log__ROOT_PATH: '%(GITEA_WORK_DIR)/log)'
      GITEA__log__logger.router.MODE: ','
      #
      GITEA__service__ENABLE_NOTIFY_MAIL: true
      GITEA__mailer__ENABLED: true
      GITEA__mailer__PROTOCOL: 'smtp'
      GITEA__mailer__SMTP_ADDR: 'mail.mydomain.local'
      GITEA__mailer__SMTP_PORT: 25
      GITEA__mailer__FROM: 'gitea@mydomain.local'
      GITEA__mailer__SUBJECT_PREFIX: 'GITEA mysite.mydomain.local'
      #
      GITEA__webhook__SKIP_TLS_VERIFY: true
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
      GITEA__webhook__DISABLE_WEBHOOKS: false
      #
      NO_PROXY: 'localhost,.mydomain.local'
      http_proxy: 'http://192.168.0.1:3128'
      https_proxy: 'http://192.168.0.1:3128'
      no_proxy: 'localhost,*.mydomain.local'
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 81:80
      - 222:222
 ```

### Database

PostgreSQL
