### ISSUE TITLE
get admin password after helm install

### ISSUE THREAD

**Issue by weironz** [go-gitea/gitea#26724]
### Feature Description

helm have default username and password, but where it store
```
gitea:
  ## @param gitea.admin.username Username for the Gitea admin user
  ## @param gitea.admin.existingSecret Use an existing secret to store admin user credentials
  ## @param gitea.admin.password Password for the Gitea admin user
  ## @param gitea.admin.email Email for the Gitea admin user
  admin:
    # existingSecret: gitea-admin-secret
    existingSecret:
    username: gitea_admin
    password: r8sA8CPHD9!bt6d
    email: "gitea@local.domain"
```
i want get password with kubectl 
```
kubectl -n gitea get secret gitea-xxx-root-password -ojsonpath='{.data.password}' | base64 --decode ; echo
```
