### ISSUE TITLE
Unable to use variable in matrix for container image

### ISSUE THREAD

**Issue by plinss** [go-gitea/gitea#26749]
### Description

I'm trying to use a repository variable in a matrix and then use the matrix variable for a container image, like:
```
---
name: testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_test:
    strategy:
      matrix:
        version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}

    runs-on:
      - ubuntu-latest

    container: python:${{ matrix.version }}-bookworm

    steps:
      - run: echo "${{ vars.PYTHON_VERSIONS }}"

      - run: python --version
```

With the variable set to: `["3.10", "3.11"]`

The idea is to specify the versions of Python to run self tests against as repository variables, allowing workflow file re-use on multiple Python modules.

This works on GitHub, but fails on Gitea with the error: `unable to determine if image already exists for image 'python:-bookworm' (): Error response from daemon: invalid reference format`

Note that is does work if I specify the matrix variable entirely in the workflow file, e.g.:
```
  run_test:
    strategy:
      matrix:
        version:
          - 3.10
          - 3.11
```

It seems the variables are being processed too late.

See https://github.com/plinss/matrix-test for an example.

Possibly related to #26307 

### Gitea Version

Nightly from 08/24/2023

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian Bookworm

### How are you running Gitea?

Built, systemd service

### Database

PostgreSQL
