### ISSUE TITLE
Derived repo cannot be merged with original repo

### ISSUE THREAD

**Issue by apnote** [go-gitea/gitea#26781]
### Description

Unable to find a branch of the original Repository in the derived Repository, But this feature is normal in v1.17.4。

![image](https://github.com/go-gitea/gitea/assets/17841336/c9b258bc-6356-4043-9483-421fa29b8985)

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/17841336/c9b258bc-6356-4043-9483-421fa29b8985)

### How are you running Gitea?

I run gitea through the Docker container，The command is as follows。

docker-compose.yaml 

```yaml
version: '3'
services:
  gitea:
    image: 'gitea/gitea:1.20.3'
    container_name: dev_gitea
    hostname: "dev_gitea"
    ports:
      - '8030:3000'
      - '8022:22'
    volumes:
      - /data/gitea:/data
      - /etc/localtime:/etc/localtime:ro
    links:
      - mysql
    depends_on:
      - mysql
    user: root
    privileged: true
    restart: always
```

### Database

MySQL/MariaDB
