### ISSUE TITLE
push docker image to container packages failed: failed commit on ref "index-sha256:.....": unexpected status: 404 Not Found

### ISSUE THREAD

**Issue by vicalloy** [go-gitea/gitea#26839]
### Description

system: MacOS 13.4.1 (c)
docker desktop: 4.19.0 (106363)
     - Enable: Settings -> Features in development -> Use contained for pulling and storing images
```
DOCKER_BUILDKIT=1 docker buildx build \
	-f Dockerfile-$(name) \
	--platform linux/arm/v7,linux/arm64 \
	-t sf/$(name):$(tag) .
```
```
REPOSITORY                      TAG               IMAGE ID       CREATED              SIZE
git.sf.tech/sf/python   3.10              c52d2cefc53d   About a minute ago   2.09GB
git.sf.tech/sf/python   3.10              c52d2cefc53d   About a minute ago   2.45GB
```
```
> docker push git.shifei.tech/shifei/python:3.10
....
c52d2cefc53d: Pushing [==================================================>]     708B/708B
da67d742d02b: Pushed 
.....
failed commit on ref "index-sha256:.....": unexpected status: 404 Not Found
```

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux version 4.4.302+

### How are you running Gitea?

```
version: "3.6"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:${GITEA_VERSION:-1.20}
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - USER_UID=1026
      - USER_GID=100
      - ...
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  gitea:
 ```

### Database

None
