### ISSUE TITLE
GITEA__security__INSTALL_LOCK in environment leads to failed installation (via docker)

### ISSUE THREAD

**Issue by gko** [go-gitea/gitea#26992]
### Description

docker-compose.yml:
```yaml
networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.20.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=false
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22

volumes:
  gitea:
    driver: local
```

leads to failed install:
<img width="508" alt="CleanShot 2023-09-09 at 19 33 29@2x" src="https://github.com/go-gitea/gitea/assets/1726487/4847bd7c-9782-441a-b6a1-e43bd3a466a5">

error in docker output:
```
gitea  | 2023/09/09 19:29:21 ...s/install/install.go:501:SubmitInstall() [I] Save settings to custom config file /data/gitea/conf/app.ini
gitea  | 2023/09/09 19:29:21 ...s/setting/setting.go:103:MustInstalled() [F] Unable to load config file for a installed Gitea instance, you should either use "--config" to set your config file (app.ini), or run "gitea web" command to install Gitea.
gitea  | Received signal 15; terminating.
gitea exited with code 0
```

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

macOS 13.5

### How are you running Gitea?

through docker-compose, like indicated here: https://docs.gitea.com/installation/install-with-docker

### Database

SQLite
