### ISSUE TITLE
File-based labels system

### ISSUE THREAD

**Issue by Andre601** [go-gitea/gitea#27003]
### Feature Description

The current label system gitea offers is nice (And effectively the same to GitHub with some extras), but it can also become a quite tedious task to update them, should you update multiple at the same time.

As an example, say you have multiple `Staus/...` labels used for indicating the state of an issue or PR. All have the same colour to group them together like that.

Now you want to change the colours of these labels. What you need to do is to go to each one, press the edit button, change the colour and save the change.
Depending on how fast the repo host is you have can this take quite a while to update them all, which is just frustrating.

Because of this would I like to propose a file-based labels system.

It's somewhat simple to understand:
A user with push rights can make a `.gitea/labels.yml` file and populate it with values like this:
```yaml
"Type/Bug":
  color: 'ff0000'
  exclusive: true # Optional. Defaults to false.
"Type/Enhancement":
  color: '00ff00'
  exclusive: true # Optional. Defaults to false.
"Good first issue":
  color: '0000ff'
  exclusive: false # Optional. Defaults to false.
```
This would add the labels `Type/Bug` with color `#ff0000` and being exclusive, `Type/Enhancement` with color `#00ff00` and being exclusive and `Good first issue` with color `#0000ff` and not being exclusive.

It would allow us to update multiple labels simultaneiously by editing this file once with all the changes needed.
The web UI could still be supported by pulling the info from the YAML file and displaying it.

Further would I propose the addition of new settings for labels to limit on what type they can be applied: Issue and/or PR.
This would make it easier to find the labels you want to apply by hiding those not suited nor needed for the thing you apply it on.
