### ISSUE TITLE
[Gitea Actions] Error on cloning local repo on steps

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#27088]
### Description

Hi, i want to set up my local actions for Act Runner \ Gitea Actions and use the same Gitea instance to store code for it. But when i want to checkout repo i got an authentication error. I try to use this article for configuration: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow

And specify action like this
```
name: Quick tests against our own repository
on:
  push:
jobs:
  cleanup_old_branches:
    runs-on: ubuntu
    name: Testing Actions
    steps:
      - name: Delete git repository old branches
        uses: emb_tools/gitea-actions-delete-abandoned-branches@v1
        id: delete_stuff
        with:
          repository: https://gitea.devos.club/
          ref: v1
          token: ${{ gitea.token }}
          path: ./.github/actions/my-private-repo

```
Action output:
<img width="451" alt="zzz" src="https://github.com/go-gitea/gitea/assets/15741789/500a0194-8b4f-4842-9e41-b71b1c524468">

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by lunny** [comment]
The ${{ gitea.token }} have no enough permission to do that. You need to create an extra token to do that.

**Comment by sgabenov** [comment]
@lunny i have created a token from user with full admin access and put into actions-secrets with name "GIT_ACCESS_TOKEN" then switched to 
```
name: Quick tests against our own repository
on:
  push:
jobs:
  cleanup_old_branches:
    runs-on: ubuntu
    name: Testing Actions
    steps:
      - name: Delete git repository old branches
        uses: emb_tools/gitea-actions-delete-abandoned-branches@v1
        id: delete_stuff
        with:
          repository: https://gitea.devos.club/
          ref: v1
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: ./.github/actions/my-private-repo
```
and got the very same behaviour:
```
h-jenkins-slave02.devos.club(version:v0.2.5) received task 650 of job 408, be triggered by event: push
workflow prepared
evaluating expression 'success()'
expression 'success()' evaluated to 'true'
  ☁  git clone 'https://github.com/emb_tools/gitea-actions-delete-abandoned-branches' # ref=v1
  cloning https://github.com/emb_tools/gitea-actions-delete-abandoned-branches to /opt/gitea_act_runner/.cache/act/emb_tools-gitea-actions-delete-abandoned-branches@v1
Unable to clone https://github.com/emb_tools/gitea-actions-delete-abandoned-branches refs/heads/v1: authentication required
authentication required
skipping post step for 'Delete git repository old branches'; step was not executed
Cleaning up services for job Testing Actions
Cleaning up container for job Testing Actions
🏁  Job failed
authentication required
```
