### ISSUE TITLE
Gitea Actions Workflow Stuck in "Waiting" State

### ISSUE THREAD

**Issue by seoes** [go-gitea/gitea#27116]
### Description

# Gitea Actions Workflow Stuck in "Waiting" State

## Description
I have set up Gitea Actions on my self-hosted Gitea instance. When pushing to the test branch, the workflow correctly triggers but remains in a "waiting" state indefinitely. The logs from the Gitea server seem to indicate that POST requests related to actions are being processed correctly with a 200 status.

## Setup
Gitea version: 1.20.3
Deployment method: Docker Compose

## Steps to Reproduce
Push to the test branch.
Observe the workflow triggering in the Gitea Actions tab.
Notice that the workflow remains in a "waiting" state.

## Expected Behavior
The workflow should start executing the jobs defined in the `.gitea/workflows` YAML file.

## Actual Behavior
The workflow remains in a "waiting" state and does not progress or execute any jobs.

## Files

<br>

**deploy.yaml**

```yaml
name: Deploy Server

on:
    push:
        branches: [test]

jobs:
    deploy:
        runs-on: host
        defaults:
            run:
                working-directory: ${{ secrets.WORKING_DIRECTORY }}
        steps:
            - name: Checkout repo
              run: |
                  git fetch --all
                  git checkout test

            - name: Set environmental variables
              run: echo "${{ secrets.ENV_PRODUCTION }}" > .env

            - name: Deploy on Docker Compose container
              run: docker compose up -d

            - name: Test - make file
              run: echo "hello world" > hello-world

```

<br><br>

**docker-compose.yml**

```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=[value]
      - GITEA__database__NAME=[value]
      - GITEA__database__USER=[value]
      - GITEA__database__PASSWD=[value]
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=[value]
      - POSTGRES_PASSWORD=[value]
      - POSTGRES_DB=[value]
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

  runner:
    image: gitea/act_runner:latest
    restart: always
    environment:
      GITEA_INSTANCE_URL: "http://[server's ip]:[port]"
      GITEA_RUNNER_REGISTRATION_TOKEN: [hidden]
    depends_on:
      - server
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
```

<br>
<br>

**Logs** (docker compose logs)

```
gitea           | 2023/09/18 20:54:50 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 12.7ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:54:52 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 11.3ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:54:54 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 11.7ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:54:56 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 12.5ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:54:58 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 11.4ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:55:00 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 11.5ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:55:02 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 12.6ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
gitea           | 2023/09/18 20:55:04 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.80.1:57032, 200 OK in 11.4ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)

```

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

rocky linux 9

### How are you running Gitea?

docker-compose

### Database

PostgreSQL
