### ISSUE TITLE
Gitea 1.20.x External Storage Deployment Error

### ISSUE THREAD

**Issue by pkeech** [go-gitea/gitea#27171]
### Description

When performing a clean install of Gitea via the Helm Chart and specifing external storage (Minio in this case) the `gitea-xxxxxxxxxx-xxxxx` pod fails to deploy with `CrashLoopBackOff`. 

Reviewing the logs of the pod, the following error message has been generated;

"does not follow ip address or domain name standards". 

Upon testing, this appears to only be a 1.20.x issue. I tested a deployment of 1.19.4 with the same configuration and Gitea deployed successfully. 

Additionally, I an upgrade from Gitea 1.19.4 to 1.20.4 failed with the same error message.

### Gitea Version

1.20.x

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

n/a

### Operating System

n/a

### How are you running Gitea?

Deployed in a Kubernetes (K3s) cluster via Helm. 

### Database

PostgreSQL

**Comment by pkeech** [comment]
Here is the `values.yaml` that was used to deploy Gitea (both 1.19.4 and 1.20.4). 

```YAML
image:
  repository: gitea/gitea
  #tag: 1.19.4
  tag: 1.20.0
  rootless: true
replicaCount: 1
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
postgresql:
  enabled: true
memcached:
  enabled: true
gitea:
  config:
    queue:
      TYPE: redis
      CONN_STR: redis://redis-svc.gitea.svc.cluster.local:6379
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://redis-svc.gitea.svc.cluster.local:6379
    cache:
      ENABLED: true
      ADAPTER: redis
      HOST: redis://redis-svc.gitea.svc.cluster.local:6379   
    server:
      DOMAIN: gitea.xxxxxxxxx.io
      ROOT_URL: https://gitea.xxxxxxxxx.io
    service:
      DISABLE_REGISTRATION: true
      REQUIRE_SIGNIN_VIEW: true
      ENABLE_NOTIFY_MAIL: true
    ui:
      THEMES: "auto,gitea,arc-green"
      DEFAULT_THEME: "auto"
    openid:
      ENABLE_OPENID_SIGNIN: false
      ENABLE_OPENID_SIGNUP: false
    actions:
      ENABLED: true
    security:
      INSTALL_LOCK: true
    repository:
      DEFAULT_REPO_UNITS: "repo.code,repo.releases,repo.issues,repo.pulls,repo.wiki,repo.projects,repo.packages,repo.actions"   
    attachment:
      STORAGE_TYPE: minio
    lfs:
      STORAGE_TYPE: minio
    picture:
      AVATAR_STORAGE_TYPE: minio
    "storage.packages":
      STORAGE_TYPE: minio
    storage:
      STORAGE_TYPE: minio
      SERVE_DIRECT: false
      MINIO_ENDPOINT: minio-api-svc.gitea.svc.cluster.local:9000
      MINIO_ACCESS_KEY_ID: gitea
      MINIO_SECRET_ACCESS_KEY: giteagitea
      MINIO_BUCKET: gitea-bucket
      MINIO_LOCATION: "us-east-1"
      MINIO_BASE_PATH: /attachment
      MINIO_USE_SSL: false
  admin:
    existingSecret: gitea-admin-secret
```

**Comment by pkeech** [comment]
Here is a screenshot of the error generated by the Gitea Pod.

![CleanShot 2023-09-21 at 09 38 28](https://github.com/go-gitea/gitea/assets/65731523/d3d98ba0-e3e2-4c94-a89b-e431140028ad)

**Comment by lunny** [comment]
remove 
```
attachment:
      STORAGE_TYPE: minio
```
Then all storages will derive from [storage].

**Comment by pkeech** [comment]
Cheers @lunny. I'll test that out.

**Comment by pkeech** [comment]
@lunny I attempted to redeploy Gitea using the same Helm Chart and Values as posted above with the exception of removing `STORAGE_TYPE: minio`. 

The installation failed again with the same "code.gitea.io/gitea/modules/storage.Init failed: Endpoint:  does not follow ip address or domain name standards." error.

**Comment by lunny** [comment]
Have you changed your configuration file like below?

```yaml
image:
  repository: gitea/gitea
  #tag: 1.19.4
  tag: 1.20.0
  rootless: true
replicaCount: 1
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
postgresql:
  enabled: true
memcached:
  enabled: true
gitea:
  config:
    queue:
      TYPE: redis
      CONN_STR: redis://redis-svc.gitea.svc.cluster.local:6379
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://redis-svc.gitea.svc.cluster.local:6379
    cache:
      ENABLED: true
      ADAPTER: redis
      HOST: redis://redis-svc.gitea.svc.cluster.local:6379   
    server:
      DOMAIN: gitea.xxxxxxxxx.io
      ROOT_URL: https://gitea.xxxxxxxxx.io
    service:
      DISABLE_REGISTRATION: true
      REQUIRE_SIGNIN_VIEW: true
      ENABLE_NOTIFY_MAIL: true
    ui:
      THEMES: "auto,gitea,arc-green"
      DEFAULT_THEME: "auto"
    openid:
      ENABLE_OPENID_SIGNIN: false
      ENABLE_OPENID_SIGNUP: false
    actions:
      ENABLED: true
    security:
      INSTALL_LOCK: true
    repository:
      DEFAULT_REPO_UNITS: "repo.code,repo.releases,repo.issues,repo.pulls,repo.wiki,repo.projects,repo.packages,repo.actions"   
    #attachment:
      #STORAGE_TYPE: minio
    #lfs:
      #STORAGE_TYPE: minio
    #picture:
      #AVATAR_STORAGE_TYPE: minio
    #"storage.packages":
      #STORAGE_TYPE: minio
    storage:
      STORAGE_TYPE: minio
      SERVE_DIRECT: false
      MINIO_ENDPOINT: minio-api-svc.gitea.svc.cluster.local:9000
      MINIO_ACCESS_KEY_ID: gitea
      MINIO_SECRET_ACCESS_KEY: giteagitea
      MINIO_BUCKET: gitea-bucket
      MINIO_LOCATION: "us-east-1"
      #MINIO_BASE_PATH: /attachment
      MINIO_USE_SSL: false
  admin:
    existingSecret: gitea-admin-secret
```
