### ISSUE TITLE
Database settings invalid: sync database struct error: Error 1286 (42000): Unknown storage engine 'InnoDB'

### ISSUE THREAD

**Issue by FuckingToasters** [go-gitea/gitea#27191]
### Description

I'm currently trying to install gitea but i always face following error on the setuppage. I tried to get around it by adding the command field in the yaml file below but it havn't changed anything.
`Database settings invalid: sync database struct error: Error 1286 (42000): Unknown storage engine 'InnoDB'`
```yml
version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea_db:3306 # Use the name of the existing MariaDB container
      - GITEA__database__NAME=gitea # Use a different database name for Gitea
      - GITEA__database__USER=InfinityMonster
      - GITEA__database__PASSWD=REDACTED
    restart: always
    networks:
      - webproxy
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea_db

  gitea_db:
    image: jc21/mariadb-aria:latest
    container_name: gitea_db
    command: ["--innodb-buffer-pool-size=256M"]
    environment:
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_USER=InfinityMonster
      - MYSQL_PASSWORD=REDACTED
      - MYSQL_DATABASE=gitea
    networks:
      - webproxy
    volumes:
      - gitea_db_data:/var/lib/mysql

networks:
  webproxy:
    external: true

volumes:
  gitea_data:
  gitea_db_data:
```

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![chrome_YDA2EbxdL3](https://github.com/go-gitea/gitea/assets/94435104/eea0ac06-3481-41da-87f4-e628b559d9bb)

### Git Version

2.30.2

### Operating System

Debian 11 / Windows 10

### How are you running Gitea?

Via Docker image

### Database

MySQL/MariaDB
