### ISSUE TITLE
Can't download artifacts in gitea 1.20.4 actions workflow

### ISSUE THREAD

**Issue by PatrickHuetter** [go-gitea/gitea#27415]
### Description

I have the following github/gitea action workflow.

```
name: Build Docker Image for angular frontend

on:
  push:

jobs:
  build-node-project:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 13

      - name: Installing npm dependencies
        run: npm --userconfig ./.npmrc install --save

      - name: Npm build for production
        run: npm run build:prod

      - name: Upload compiled project for docker build
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist

  build-docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: someorg
      DOCKER_LATEST: latest
    steps:
      - name: Download compiled angular app and resources
        uses: actions/download-artifact@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: some-registry.fqdn
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT
          echo DOCKER_PATH=$(echo ${GITHUB_REPOSITORY}) >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          ACTIONS_RUNTIME_TOKEN: '' # See https://gitea.com/gitea/act_runner/issues/119
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            some-registry.fqdn/${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
            some-registry.fqdn/${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{GITHUB_SHA::7}}

```

Uploading artifacts works fine but downloading doesn't work. I get the following exception:
```
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
starting download of artifact app : 1/1
Total number of files that will be downloaded: 1
::error::An error occurred while attempting to read the response stream
A 200 response code has been received while attempting to download an artifact
Exponential backoff for retry #1. Waiting for 5398 milliseconds before continuing the download
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #1, continuing with download
Total file count: 1 ---- Processed file #0 (0.0%)
::error::An error occurred while attempting to read the response stream
A 200 response code has been received while attempting to download an artifact
Exponential backoff for retry #2. Waiting for 12442 milliseconds before continuing the download
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #2, continuing with download
Total file count: 1 ---- Processed file #0 (0.0%)
::error::An error occurred while attempting to read the response stream
A 200 response code has been received while attempting to download an artifact
Exponential backoff for retry #3. Waiting for 15363 milliseconds before continuing the download
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #3, continuing with download
Total file count: 1 ---- Processed file #0 (0.0%)
::error::An error occurred while attempting to read the response stream
A 200 response code has been received while attempting to download an artifact
Exponential backoff for retry #4. Waiting for 18236 milliseconds before continuing the download
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #4, continuing with download
Total file count: 1 ---- Processed file #0 (0.0%)
::error::An error occurred while attempting to read the response stream
A 200 response code has been received while attempting to download an artifact
Exponential backoff for retry #5. Waiting for 27568 milliseconds before continuing the download
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #5, continuing with download
Total file count: 1 ---- Processed file #0 (0.0%)
::error::An error occurred while attempting to read the response stream
A 200 response code has been received while attempting to download an artifact
::error::Unable to download the artifact: Error: Retry limit has been reached. Unable to download https://my-git-fqdn/api/actions_pipeline/_apis/pipelines/workflows/77/artifacts/2/download
```

Does anybody have an idea what's wrong here? 

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1325" alt="Bildschirm­foto 2023-10-03 um 18 15 54" src="https://github.com/go-gitea/gitea/assets/1142911/57a66c3a-81c2-44ad-944b-2bccc7aa9666">
<img width="1337" alt="Bildschirm­foto 2023-10-03 um 18 16 01" src="https://github.com/go-gitea/gitea/assets/1142911/c38977fc-077e-45a0-8010-b967a0ab1c69">

### How are you running Gitea?

Official gitea helm chart within a k3s kubernetes cluster. The ingress has the following annotations:
```
cert-manager.io/cluster-issuer: "letsencrypt-production"
kubernetes.io/ingress.class: "nginx"
nginx.ingress.kubernetes.io/proxy-body-size: "1200m"
nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
```

### Database

PostgreSQL
