### ISSUE TITLE
Enabling sticky position TOC in .md files

### ISSUE THREAD

**Issue by denis-migdal** [go-gitea/gitea#27477]
### Feature Description

Currently, we can enable a TOC in markdown pages thanks to :
````
---
gitea: none
include_toc: true
---
````

However, for long pages it would be better to have a right-align sticky TOC, e.g. through an option like :
````
---
gitea: none
include_toc: true
toc_position: float
---
````

Currently I inject the following CSS through a WebExtension :
````css
.file-view.markup.markdown > details:first-child {
	position:fixed; /* position sticky seems to cause issue in the instance of gitea I use */
	right:0em;
	top: 60px;
	z-index: 100;
	background: var(--color-box-body);
	border: 1px solid gray;
	border-radius: 5px;
	padding: 10px;
	padding-right:20px;
	margin-bottom: 0px;
	& > ul { margin-bottom:0px
	} }
````
