### ISSUE TITLE
New act runner run in docker lead to error 500 on server

### ISSUE THREAD

**Issue by falkolab** [go-gitea/gitea#27580]
### Description

I'm trying to start runner in docker.
As the docs say:
`
If you are using the docker image, behaviour will be slightly different. Registration and running are combined into one step in this case, so you need to specify the registration information when running the act runner.`

Runner doesn't register, and server throws the 500 error
It happened after reseting registration token. I'm trying to register new runner with the new token.
Gitea running in docker on another host then runner.

Runner start command:
```
docker run \
    -v $PWD/config.yaml:/config.yaml \
    -v $PWD/data:/data \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --restart unless-stopped \
    -e CONFIG_FILE=/config.yaml \
    -e GITEA_INSTANCE_URL=http://gitea.***.ru:3000/ \
    -e GITEA_RUNNER_REGISTRATION_TOKEN=*** \
    -e GITEA_RUNNER_NAME=docker01 \
    --name act_runner \
    -d gitea/act_runner:nightly
```

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/falkolab/17d5af280ef09e98856c5e998713625f

### How are you running Gitea?

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=***
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=***
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
```

### Database

None
