### ISSUE TITLE
Cryptic ORM startup error

### ISSUE THREAD

**Issue by b1ek** [go-gitea/gitea#27647]
### Description

After upgrading to the newest docker tag `1.21-nightly`, i got struck by this nonsense:

```
gitea  | 2023/10/16 15:48:07 routers/common/db.go:36:InitDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: migrate: migration[276]: Add RemoteAddress to mirrors failed: get remote remote_mirror_ITwxJDkW5g's address of blek/express-browser-detect failed: exit status 2 - error: No such remote 'remote_mirror_ITwxJDkW5g'
gitea  |  - error: No such remote 'remote_mirror_ITwxJDkW5g'
```

`blek/express-browser-detect` is a repository. I have no idea why is it trying to get the address of it, but i `grep`'d it from the config dir and it does not appear in any config file at all.

Before migrating, i did not change anything at all.

Perhaps its a nightly build issue? Unfourtunately, I can't roll it back to the previous version since the migrations were created at first commits of 1.21 (i know, it was a dumb idea)

### Gitea Version

1.21-nightly docker tag

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://bin.blek.codes/view?id=a94c45c1265ecca9

### How are you running Gitea?

I run it via [this docker tag](https://hub.docker.com/layers/gitea/gitea/1.21-nightly/images/sha256-1646849862639e372e0e91dcd671660bb24303cf823322548e2893dc57fc1229?context=explore)

### Database

PostgreSQL

**Comment by lunny** [comment]
As a workround, you can add remote for that repository manually.

`git remote add remote_mirror_ITwxJDkW5g <the_mirror_original_url>`.

**Comment by b1ek** [comment]
<details>
<summary>
docker-compose.yml
</summary>

```yaml
version: "3"

networks:
  gitea:
    external: false
    driver: 'bridge'

services:
  server:
    image: gitea/gitea:1.21.0-rc1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=
      - GITEA__database__USER=
      - GITEA__database__PASSWD=
    restart: always
    networks:
      - gitea
      - caddy_default
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22:22"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER:
      POSTGRES_DB:
    networks:
      - gitea
    volumes:
      - './postgres:/var/lib/postgresql/data'
```
</summary>
