### ISSUE TITLE
New user cannot be created using curl and Swagger API: user does not exist [uid: 0, name: , keyid: 0]

### ISSUE THREAD

**Issue by cmoulliard** [go-gitea/gitea#27695]
## Issue

New user cannot be created using curl and Swagger API as we got as response `user does not exist [uid: 0, name: , keyid: 0]`

Command executed:
```
TOKEN=$(curl -s -k -H "Content-Type: application/json" -d '{"name":"init","scopes": ["write:user", "write:admin", "write:repository"]}' -u gitea_admin:gitea_admin https://gitea.localtest.me/api/v1/users/gitea_admin/tokens | jq -r .sha1)
echo $TOKEN
42d5804b9f1bc22da80896cc356c0681fc0994be

curl -k -X 'POST' \
  'https://gitea.localtest.me/api/v1/admin/users' \
  -H 'accept: application/json' \
  -H 'Authorization: token $TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "user1@cnoe.io",
  "full_name": "user1",
  "login_name": "user1",
  "must_change_password": false,
  "password": "user11234",
  "restricted": false,
  "visibility", "public",
  "send_notify": false,
  "username": "user1"
}'
{"message":"user does not exist [uid: 0, name: , keyid: 0]","url":"http://gitea.localtest.me/api/swagger"}
```

### Gitea Version

1.20.5-rootless

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

2023/10/19 16:26:51 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/v1/admin/users for 10.244.0.6:46502, 401 Unauthorized in 0.3ms @ auth/middleware.go:39(auth.APIAuth) 

### Git Version

2.40.1

### Operating System

macos

### How are you running Gitea?

Here is how I installed gitea

1. Create a kind kube cluster
```
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install --delete-kind-cluster --port-map 32222:22
```
2. Deploy the gitea helm chart
```
cat <<EOF > helm-values.yml
redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  admin:
    username: "gitea_admin"
    password: "gitea_admin"
    email: "gi@tea.com"
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level

service:
  ssh:
    type: NodePort
    nodePort: 32222
    externalTrafficPolicy: Local

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.localtest.me
      paths:
        - path: /
          pathType: Prefix
EOF
helm install gitea gitea-charts/gitea -n gitea --create-namespace -f helm-values.yml
```

### Database

SQLite
