### ISSUE TITLE
Actions: Job with an "if: always()" are skipped

### ISSUE THREAD

**Issue by sleeperss** [go-gitea/gitea#27906]
### Description

Jobs with an `if: always()` statement that depends on a skipped one are also skipped.

```
on: 
  push:
    branches:
      - master

jobs:
  job1:
    name: Skipped job
    if: false
    steps:
      - run: echo "I am skipped"

  job2:
    name: Mustn't be skipped
    needs: job1
    if: always()
    steps:
      - run: echo "I should have been displayed :'("
```
![image](https://github.com/go-gitea/gitea/assets/6254802/de12eae9-0efb-477c-9a89-160b395b21d0)

This makes intermediate optional job impossible

### Gitea Version

1.21.0+rc2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

ubuntu

### How are you running Gitea?

container from docker hub on linux

### Database

SQLite
