### ISSUE TITLE
Two buttons "Install Gitea" on the initial installation page

### ISSUE THREAD

**Issue by serious-angel** [go-gitea/gitea#27934]
### Description

Dear Gitea Developers,

Thank you very much for the ineffably marvelous project, solution, work...

I am sorry, but just wanted to report a behavior when two "Install Gitea" buttons appear at the very first installation procedure (with Docker) for currently unknown reason. It seems like there's no such condition in the [template](https://github.com/go-gitea/gitea/blob/93bd4351bfb4a2f5f37ecb80d50496d044240e00/templates/install.tmpl#L326).

Considering some screenshots [found online](https://www.techaddressed.com/tutorials/hosting-gitea-using-docker), it looked unintentional:

<details>
<summary>An example from the reference</summary>

![image](https://github.com/go-gitea/gitea/assets/25136754/46e1cce3-35bd-459d-a9a9-1469d0b367c0)

</details>

Best and kind regards ✨ 

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img alt="chrome_Installation_-_Gitea_Git_with_a_cup_of_tea_-_Googl_2023-11-06_11-43-22_Z_9Zl24NGY" src="https://github.com/go-gitea/gitea/assets/25136754/045d8b6a-19e3-4c90-a814-e5e1b7ae5b1b">

<img width="500" alt="chrome_DevTools_-_2023-11-06_12-08-34_Z_SAkJzWKZ" src="https://github.com/go-gitea/gitea/assets/25136754/f88e5a4e-1e2c-4e3b-b057-f03a00101c26">

### Git Version

2.40.1

### Operating System

Docker at Ubuntu Server 22.04.3

### How are you running Gitea?

`Docker version 24.0.6, build ed223bc`.

<details>
<summary>`docker-compose.yaml`</summary>

```yaml
version: '3'

name: 'gitea'

services:

  gitea:
    image: 'gitea/gitea'
    hostname: "${APP_HOSTNAME}"
    environment:
      - 'USER_UID=1000'
      - 'USER_GID=1000'
      - 'GITEA__database__DB_TYPE=postgres'
      - 'GITEA__database__HOST=db:5432'
      - "GITEA__database__NAME=${DB_DATABASE}"
      - "GITEA__database__USER=${DB_USERNAME}"
      - "GITEA__database__PASSWD=${DB_PASSWORD}"
    volumes:
      - '/var/docker/gitea/data:/data'
    ports:
      - '2000:22'
    networks:
      - 'gitea'

    depends_on:
      db:
        condition: 'service_healthy'

  db:
    image: 'postgres'
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - '/var/docker/gitea/db:/var/lib/postgresql/data'
    networks:
      - 'gitea'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  gitea:
```

</details>

### Database

PostgreSQL
