### ISSUE TITLE
Gitea act_runner: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by ware32** [go-gitea/gitea#27974]
### Description

We have a gitea server in a machine and a runner in another machine.
When executing a workflow in a runner in the server machine it completes but if we execute the same workflow in a runner in another machine we get this error:
Connection refused, The process '/usr/bin/git' failed with exit code 128

Thanks in advance

### Gitea Version

v1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Self hosted

### Database

None

**Comment by baez90** [comment]
I had a similar issue, can you try whether:

```yml
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
```

resolves the problem?

Generally, sharing your workflow would help a lot to be able to help you with your problem :wink:

**Comment by ahezzati** [comment]
I have the same issue, and here is my Yaml file 
```
name: build-solution
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses:  actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build
  ```

**Comment by yp05327** [comment]
Can you try this:
- generate a config file:
```
./act_runner generate-config > config.yaml
```
- edit `container.network` to `host`
```yaml
container:
  # Specifies the network to which the container will connect.
  # Could be host, bridge or the name of a custom network.
  # If it's empty, act_runner will create a network automatically.
  network: "host"
```
- start the runner with the config file
```
./act_runner -c config.yaml register
```
