### ISSUE TITLE
act_runner configure insecure registry

### ISSUE THREAD

**Issue by Demmtop** [go-gitea/gitea#27981]
### Feature Description

I builded a self image from gitea/act_runner:latest-dind-rootless. I added /etc/docker/daemon.json. This file contains the docker insecure registrie definition.
It doesn't work.
What is the right way for this problem.

This is my build.yaml
```
jobs:
  build:
    runs-on: "self-hosted"
    container:
      image: nexus.development:8082/maven:3.9.5
    steps:
      - uses: actions/checkout@v4
      - name: "Maven build"
        run: mvn clean install
```

This are the messages from "Set up job"
```
gitea-runner(version:v0.2.6) received task 13 of job 7, be triggered by event: push
workflow prepared
evaluating expression 'success()'
expression 'success()' evaluated to 'true'
🚀  Start image=nexus.development:8082/maven:3.9.5
  🐳  docker pull image=nexus.development:8082/maven:3.9.5 platform= username= forcePull=false
  🐳  docker pull nexus.development:8082/maven:3.9.5
Image exists? false
pulling image 'nexus.development:8082/maven:3.9.5' ()
Error response from daemon: Get "https://nexus.development:8082/v2/": http: server gave HTTP response to HTTPS client
```
