### ISSUE TITLE
Icon and Log error when use 'composite' actions

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#28006]
### Description

build.yml and [seepine/action-setup-pnpm](https://github.com/seepine/action-setup-pnpm/blob/main/action.yml)
```yaml
name: Gitea Actions Demo
on: [push]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm and Install
        uses: seepine/action-setup-pnpm@v1

      - run: pnpm -v
```

#### 2. The `seepine/action-setup-pnpm` log are difference, when
```
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm and Install
        uses: seepine/action-setup-pnpm@v1
```
and
```
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm and Install
        uses: seepine/action-setup-pnpm@v1

      - run: pnpm -v
```

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

MySQL/MariaDB
