### ISSUE TITLE
Jobs in actions are restarted in an incomprehensible order

### ISSUE THREAD

**Issue by vjarskee** [go-gitea/gitea#28093]
### Description

I have a few workflows of roughly this type:

```yaml
jobs:
  First test:
    runs-on: node-16.16.0
  Second test:
    runs-on: node-16.16.0
  Build:
    needs: [First test, Second test]
    runs-on: ubuntu-22.04
  Run:
    needs: Build
    runs-on: ubuntu-22.04
```

When automatically started, workflow runs as it should, but if you manually restart one job or all of them with a button in the interface, they may start in an unclear order, for example, Build or Run may start together with First test and Second test, although they need First test and Second test.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu 20.04.4 LTS

### How are you running Gitea?

Official docker image `gitea/gitea:1.21.0`

### Database

PostgreSQL
