### ISSUE TITLE
Action shows running after all tasks finished again

### ISSUE THREAD

**Issue by Nathanwoodburn** [go-gitea/gitea#28109]
### Description

The same thing as here https://github.com/go-gitea/gitea/issues/26559 is happening again on version 1.21.0

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Nathanwoodburn/7823a4633d536d2643f3d870e5f54d2b

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/62039630/b4b829c6-d7cf-467c-ab4d-5cc2a7c3a0c6)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Ubuntu 22.04.2 LTS (amd)

### How are you running Gitea?

Via docker compose

```yaml
version: "3.7"
services:
  mariadb:
    hostname: mariadb
    image: linuxserver/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: <password>
      PUID: 1234
      PGID: 1234
      TZ: Australia/Sydney
    restart: unless-stopped
    volumes:
      - mariadb:/config

  gitea:
    container_name: gitea
    hostname: gitea
    image: gitea/gitea:latest
    environment:
      USER_UID: 1234
      USER_GID: 1234
      TZ: Australia/Sydney
      GITEA__database__HOST: 'mariadb'
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: <password>
      GITEA__database__NAME: gitea
      GITEA__database__DB_TYPE: mysql
    ports:
      - 8124:3000  # Reverse proxied via nginx
      - 2222:2222  # Port forwarded on the firewall from :22
    restart: unless-stopped
    volumes:
      - gitdata:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh:/data/git/.ssh
    depends_on:
      - mariadb

volumes:
  mariadb:
  gitdata:
```

### Database

MySQL/MariaDB
