### ISSUE TITLE
Artifact upload still not working

### ISSUE THREAD

**Issue by abosaad11** [go-gitea/gitea#28197]
### Description

Artifact upload never worked for me. I tested on try.gitea.io and I get the same error.

Here's the run:

https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-1

It results in this error:

```
With the provided path, there will be 4 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "CruelKernel-G973F" successfully created. Starting upload of file(s)
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #1. Waiting for 506[2](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-2) milliseconds before continuing the upload at offset 0
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #1. Waiting for 4760 milliseconds before continuing the upload at offset 0
Finished backoff for retry #1, continuing with upload
Finished backoff for retry #1, continuing with upload
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #2. Waiting for 10905 milliseconds before continuing the upload at offset 0
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #2. Waiting for 12655 milliseconds before continuing the upload at offset 0
Total file count: 4 ---- Processed file #0 (0.0%)
Finished backoff for retry #2, continuing with upload
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #[3](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-3). Waiting for 1[4](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-4)767 milliseconds before continuing the upload at offset 0
Finished backoff for retry #2, continuing with upload
Total file count: 4 ---- Processed file #0 (0.0%)
A [5](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-5)00 status code has been received, will attempt to retry the upload
Exponential backoff for retry #3. Waiting for 17025 milliseconds before continuing the upload at offset 0
Total file count: 4 ---- Processed file #0 (0.0%)
Finished backoff for retry #3, continuing with upload
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #4. Waiting for 19[6](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-6)61 milliseconds before continuing the upload at offset 0
Finished backoff for retry #3, continuing with upload
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #4. Waiting for 2492[7](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-7) milliseconds before continuing the upload at offset 0
Total file count: 4 ---- Processed file #0 (0.0%)
Total file count: 4 ---- Processed file #0 (0.0%)
Finished backoff for retry #4, continuing with upload
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #5. Waiting for 2403[8](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-8) milliseconds before continuing the upload at offset 0
Total file count: 4 ---- Processed file #0 (0.0%)
Finished backoff for retry #4, continuing with upload
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #5. Waiting for 276[9](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-9)7 milliseconds before continuing the upload at offset 0
Total file count: 4 ---- Processed file #0 (0.0%)
Finished backoff for retry #5, continuing with upload
A 500 status code has been received, will attempt to retry the upload
##### Begin Diagnostic HTTP information #####
Status Code: 500
Status Message: Internal Server Error
Header Information: {
  "alt-svc": "h3=\":443\"; ma=2592000",
  "content-length": "24",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 24 Nov 2023 08:45:31 GMT",
  "server": "Caddy",
  "x-content-type-options": "nosniff"
}
###### End Diagnostic HTTP information ######
Retry limit has been reached for chunk at offset 0 to https://try.gitea.io/api/actions_pipeline/_apis/pipelines/workflows/431/artifacts/ff9ae964d288f8678522b05036abaf0e/upload?itemPath=CruelKernel-G973F%2FMETA-INF%2Fcom%2Fgoogle%2Fandroid%2Fupdate-binary
::warning::Aborting upload for /root/.cache/act/449284b1cf785f64/hostexecutor/installer/META-INF/com/google/android/update-binary due to failure
::error::aborting artifact upload
Total file count: 4 ---- Processed file #1 (25.0%)
Total file count: 4 ---- Processed file #1 (25.0%)
Finished backoff for retry #5, continuing with upload
A 500 status code has been received, will attempt to retry the upload
##### Begin Diagnostic HTTP information #####
Status Code: 500
Status Message: Internal Server Error
Header Information: {
  "alt-svc": "h3=\":443\"; ma=259[20](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-20)00",
  "content-length": "24",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 24 Nov 2023 08:45:47 GMT",
  "server": "Caddy",
  "x-content-type-options": "nosniff"
}
###### End Diagnostic HTTP information ######
Retry limit has been reached for chunk at offset 0 to https://try.gitea.io/api/actions_pipeline/_apis/pipelines/workflows/431/artifacts/ff9ae964d288f86785[22](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-22)b05036abaf0e/upload?itemPath=CruelKernel-G973F%2Fclone_header
::warning::Aborting upload for /root/.cache/act/449[28](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-28)4b1cf785f64/hostexecutor/installer/clone_header due to failure
::error::aborting artifact upload
Total size of all the files uploaded is 0 bytes
File upload process has finished. Finalizing the artifact upload
Upload finished. There were 4 items that failed to upload
The raw size of all the files that were specified for upload is 4[38](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-38)[62](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-62)2 bytes
The size of all the files that were uploaded is 0 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage
Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 
::error::An error was encountered when uploading CruelKernel-G9[73](https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-73)F. There were 4 items that failed to upload.
```

And here's the relevant part of the workflow file from the repo:

```
      - name: Create CruelKernel images for ${{ matrix.model }}
        run: ./cruelbuild :mkimg
      - name: Create CruelKernel installer for ${{ matrix.model }}
        if: env.INSTALLER == 'yes'
        run: ./cruelbuild :pack

      - name: Avoid Double Zipping in Installer
        if: env.INSTALLER == 'yes'
        run: |
          mkdir -p installer && cd installer
          unzip ../CruelKernel.zip
      - name: Upload Kernel Zip
        if: env.INSTALLER == 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: CruelKernel-${{ matrix.model }}
          path: installer/*
          if-no-files-found: error
      - name: Upload Kernel Images
        if: env.INSTALLER != 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: CruelKernel-${{ matrix.model }}
          path: '*.img'
          if-no-files-found: error

      - name: Upload Kernel Info
        uses: actions/upload-artifact@v2
        with:
          name: ConfigurationInfo-${{ matrix.model }}
          path: config.*
          if-no-files-found: error
```

This always works on github, but it never works on Gitea. Any idea why? And how to make it work?

Thank you

### Gitea Version

https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-1

### Operating System

ubuntu

### How are you running Gitea?

https://try.gitea.io/xkc65869/cruel/actions/runs/2#jobstep-20-1

### Database

None
