### ISSUE TITLE
Gitea docker: Configuration missing after upgrade from 1.21.0 to 1.21.1

### ISSUE THREAD

**Issue by rosch100** [go-gitea/gitea#28230]
### Description

After pulling from the latest image (1.21.1) and restarting the docker container, the website starts with a completely new configuration.
A downgrade to 1.21.0. resolves it for the time being.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

dockerhub

### How are you running Gitea?

dockerhub gitea/gitea

### Database

MySQL/MariaDB

**Comment by stancubed** [comment]
Same here. Compose file is below!

```yaml
version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=US/Central
    restart: unless-stopped
    volumes:
      - $local-path/git:/storage
      - $local-path/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3030:3000"
      - "222:22"
```

**Comment by haiopaii** [comment]
same problem here.

**Comment by mishac** [comment]
It looks like some sort of permissions issue.  In my case the the volume is chowned to user id 8133, and in my docker compose I have UID=8133, but when I go into the container uid 8133 doesn't exist and the data folder is inaccessible (permission denied).

**Comment by kozhin** [comment]
Same for me. Using Gitea with PostgreSQL and docker volumes for persistent storage.
Reverting to previous version of Gitea's image solves the issue.

```
---
version: '3'

networks:
  pub_net:

volumes:

  drone_data:
    driver: local

  gitea_data:
    driver: local

  gitea_db:
    driver: local

services:

  gitea_db:
    image: postgres:14-alpine
    container_name: gitea_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gitea_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=REMOVED
    volumes:
      - gitea_db:/var/lib/postgresql/data
    networks:
      - pub_net
    ports:
      - 127.0.0.1:30000:5432/tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea_db
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=REMOVED
      - GITEA__mailer__ENABLED=false
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - pub_net
    ports:
      - 127.0.0.1:31000:3000/tcp
      - REMOVED
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 5s
    depends_on:
      - gitea_db
```
