### ISSUE TITLE
Actions upload-artifact fails when using MinIO storage

### ISSUE THREAD

**Issue by cennis91** [go-gitea/gitea#28279]
### Description

The following action with `upload-artifact@v3` works fine when artifact storage is set to `local`, but fails when set to `minio` on v.1.21. The file is successfully uploaded to the MinIO storage, but fails on `confirmUploadChunk`.

Might be related: https://github.com/go-gitea/gitea/pull/26400.

```
on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Example"
      - uses: actions/checkout@v3
      - run: echo "foo" > /tmp/test.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: /tmp/test.txt
```

On success:
```
.../artifacts_chunks.go:45:saveUploadChunk() [I] [artifact] check chunk md5, sum: 07BzhNET7exJ6qYjitX/AA==, header: 07BzhNET7exJ6qYjitX/AA==
.../artifacts_chunks.go:53:saveUploadChunk() [I] [artifact] save chunk tmp51/8-0-3.chunk, size: 4, artifact id: 8, start: 0, end: 3
```

On failure:
```
.../artifacts_chunks.go:45:saveUploadChunk() [I] [artifact] check chunk md5, sum: 07BzhNET7exJ6qYjitX/AA==, header: 07BzhNET7exJ6qYjitX/AA==
.../artifacts_chunks.go:53:saveUploadChunk() [I] [artifact] save chunk tmp51/8-0-3.chunk, size: 4, artifact id: 8, start: 0, end: 3
...actions/artifacts.go:291:comfirmUploadArtifact() [E] Error merge chunks: parse content range error: input does not match format
```

### Gitea Version

v1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker: [gitea/gitea:1.21.1](https://hub.docker.com/layers/gitea/gitea/1.21/images/sha256-63165c64759c98e55f0afdb5fc3be64cbb27180d3474e951fa027228e6955029)

### Database

None
