### ISSUE TITLE
What is the default time zone of cron? Can you specify the time zone

### ISSUE THREAD

**Issue by ysicing** [go-gitea/gitea#28329]
### Description

```
name: build

on:
  push:
    branches:
      - '*'
    tags:
    - 'v*'
  schedule:
    - cron: '0 7 * * *'

env:
  TZ: Asia/Shanghai

```
![image](https://github.com/go-gitea/gitea/assets/8605565/6008b45d-dd64-4d81-bf18-bcca8ae661a0)

According to the action log, the time is 2023-12-03T07:04:07Z

### Gitea Version

1.21.1 

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

SQLite
