### ISSUE TITLE
Uploaded artifacts should be overwritten

### ISSUE THREAD

**Issue by hakito** [go-gitea/gitea#28549]
### Description

According to github documentation[ artifacts sharing the same name should be overwritten](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow).

Gitea seems to discard/ignore the second upload. Here is an example workflow:

```yaml
name: Uploads
on:
  - push

jobs:
  first:
    name: upload first
    runs-on: windows
    steps:
      - run: echo "first" > actual
      - uses: actions/upload-artifact@v3
        with:
          name: actual
          path: actual
  second:
    needs: [first]
    name: upload second
    runs-on: windows
    steps:
      - run: echo "second" > actual
      - uses: actions/upload-artifact@v3
        with:
          name: actual
          path: actual
  verify:
    needs: [second]
    name: Verify contents
    runs-on: windows
    steps:
      - name: Fetch Integration Tests from Build
        uses: actions/download-artifact@v3
        with:
          name: actual
      - run: echo "second" > expected
      - run: fc.exe expected actual
```

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/320853/3bf2f460-6a9f-4760-974d-cee456be8469)

### How are you running Gitea?

gitea/gitea:latest

### Database

MySQL/MariaDB

**Comment by hakito** [comment]
Side note:

We are currently migrating our build system to gitea, and this could have become a critical problem.

We first build our software and upload the binaries. In a second job we overwrite the encrypted binaries. If I hadn't checked manually the unencrypted version would be shipped!

**Comment by lunny** [comment]
Can you run that on github successfully?

**Comment by hakito** [comment]
Yes https://github.com/hakito/Activity/actions/runs/7274027094/job/19819139031

**Comment by hakito** [comment]
FYI - Also when re-running a job it keeps the old artifacts.

**Comment by lunny** [comment]
> FYI - Also when re-running a job it keeps the old artifacts.

Wow, so this is a bug?

**Comment by hakito** [comment]
Well I would consider it a bug if I successfully upload an artifact (with re-run), but the artifact is not the uploaded. I made a very simple example do demonstrate it:

```yaml
on: [push]
jobs:
  Timestamp:
    runs-on: [windows]
    steps:
      - run: get-date -Format "o" > timestamp.txt
      - run: cat timestamp.txt
      - uses: actions/upload-artifact@v3
        with:
            path: timestamp.txt           
```

Simply run the job a 2nd time manually. After the 2nd run the output of `cat timestamp.txt` in web interface is:

> 2023-12-29T08:17:55.7576776+01:00

But the contents of the downloaded artifacts are:

> 2023-12-29T08:17:03.1341990+01:00
