### ISSUE TITLE
Error - mkdir: can't create directory '/data/git/': Permission denied

### ISSUE THREAD

**Issue by alvin6233** [go-gitea/gitea#28566]
### Description

I use helm chart to deploy gitea. Using external pvc(I have created pv/pvc) and setting the ReadWriteMany.  But the gitea pod can't be created. Then i find init-container logs and get the following error msg:
```
(base) ➜  ~ k -n gitea logs  gitea-66fb985648-khrzk  -c init-directories
+ mkdir -p /data/git/.ssh
mkdir: can't create directory '/data/git/': Permission denied
```

The pod volumes as follows:
```
Volumes:
  init:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gitea-init
    Optional:    false
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gitea
    Optional:    false
  inline-config-sources:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gitea-inline-config
    Optional:    false
  temp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  gitea-shared-storage
    ReadOnly:   false
```

Image settings:
```
image:
  registry: ""
  repository: gitea/gitea
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent
  rootless: true
  fullOverride: ""
```

Gitea helm chart: gitea-10.0.0

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

+ mkdir -p /data/git/.ssh
mkdir: can't create directory '/data/git/': Permission denied

### How are you running Gitea?

I pull helm chart and use external pvc. my persistence config as follows:
persistence:
  enabled: true
  create: false
  mount: true
  claimName: gitea-shared-storage
  size: 1000Gi
  accessModes:
    - ReadWriteMany
  labels: {}
  storageClass:
  subPath:
  volumeName: ""
  annotations:
    helm.sh/resource-policy: keep

### Database

None
