### ISSUE TITLE
Slow progressive Memory Leak with Docker Container 

### ISSUE THREAD

**Issue by Merith-TK** [go-gitea/gitea#28606]
### Description

I have noticed over the years I have spent using gitea, it has an *slow* progressive memory leak, 
In the span of 11 hours of relatively zero activity, gitea has nearly doubled its memory usage,
going from ~130mb to now ~240mb usage, 

Before I got in contact with people on the discord to address this issue officially, gitea was consuming nearly 6gb of ram, which if I wanted an git service to consume that much, I would self host gitlab lol

### Gitea Version

1.21.3+8-gf2add36a2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Merith-TK/657357fc8e60e0928aa3e1f155799472

### Git Version

Nightly Docker Container

### Operating System

Linux Host, Nightly Docker Container

### How are you running Gitea?

Docker compose. 
```yml
  gitea:
    container_name: gitea
    image: gitea/gitea:1.21-nightly
    restart: unless-stopped
    environment:
      USER_UID: 1001
      USER_GID: 1001
    networks:
      # unified networking for cross container connections
      - caddy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      # caddyserver configs
      caddy: git.merith.xyz
      caddy.reverse_proxy: "{{upstreams 3000}}"
```

### Database

PostgreSQL
