### ISSUE TITLE
Mirror warehouse does not run action

### ISSUE THREAD

**Issue by yedajiang44** [go-gitea/gitea#28699]
### Description

I create a repository and action:
```
name: test
on:
  schedule:
    - cron: '0/1 * * * *'
jobs:
  docker:
    runs-on: [ubuntu-latest]
    steps:
     - name: Test
       run: echo "Test run"
```
It works fine as expected.

But after I mirror this repository , the action of the new repository does nothing.

### Gitea Version

1.22.0+dev-506-g91aa26322 built with GNU Make 4.4.1, go1.21.5 : bindata, timetzdata, sqlite,

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker
