### ISSUE TITLE
Support multiple platforms on a single runner

### ISSUE THREAD

**Issue by koehn** [go-gitea/gitea#28695]
### Feature Description

I’d like to leverage Docker’s ability to run containers for different platforms through Gitea Actions. 

E.g., I can run `docker run node:16-buster --platform linux/amd64` even on an arm64 runner, and it will use Docker to emulate the platform I specify on the hardware I have. 

Given that, it would be nice to specify a job like:

```
jobs:
  build:
    strategy:
      matrix:
        platform: [arm64, amd64]
        release: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.release }}
      platform: ${{ matrix.platform }}
```

Gitea can find the best runner(s) to run the job. Since the runners know their platform, they can announce it to Gitea, and it can use a native runner (preferred) or one running under emulation to complete the job. 

If runners are available for multiple platforms and none is specified, the job can just run on any of them (which is basically what happens today).
