### ISSUE TITLE
Use CSS layers for implementing utility classes

### ISSUE THREAD

**Issue by rafh** [go-gitea/gitea#28706]
### Feature Description

Gitea has a `helper.css` file with a host of utility classes. However, they use `important!`. Instead, have we thought about using CSS layers? Here's a quick example of what I have in mind. 

```CSS
/* We would need to remove fomantic from webpack and add it to the CSS file */
/* Notice it is a named called framework */
@import url("../fomantic/build/semantic.css") layer(framework);

/* Custom utilities that don't need the use of important */
@layer utilities {
  .gt-mt-0 { margin-top: 0; }
  .gt-font-light { font-weight: var(--font-weight-light); }
  .gt-relative { position: relative; }
}

/* Here we order the layers in the order we want them to be in the final CSS file */
@layer framework, utilities;
```

CSS layers are well supported: https://caniuse.com/css-cascade-layers
