### ISSUE TITLE
Artifacts upload results in http error 500

### ISSUE THREAD

**Issue by StefanSa** [go-gitea/gitea#28702]
### Description

When running the following pipeline on act_runner, the artifacts are not uploaded due to http error 500.

haproxy-deps.yml:
```
name: HAProxy dependencies

on:
  workflow_call:
    inputs:
      DEBIAN_CODENAME:
        required: true
        type: string
      CLANG_VERSION:
        required: true
        type: number

jobs:
  dependency:
    runs-on: ubuntu-latest
    # container: "docker.io/library/debian:${{ inputs.DEBIAN_CODENAME }}"
    image: catthehacker/ubuntu:act-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        dependency_name:
          - lua
          - pcre2
          - quictls
          - vtest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup OS
        uses: "./.github/actions/setup-os"
      - name: Build ${{ matrix.dependency_name }}
        run: make -C deps/${{ matrix.dependency_name }}
      - name: Archive ${{ matrix.dependency_name }} distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.dependency_name }}-dist.tar.gz
          path: deps/${{ matrix.dependency_name }}/${{ matrix.dependency_name }}-dist.tar.gz
```

runner logfile
```
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-4] 🏁  Job failed
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | ##### Begin Diagnostic HTTP information #####
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | Status Code: 500
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | Status Message: Internal Server Error
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | Header Information: {
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   |   "content-type": "text/plain; charset=utf-8",
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   |   "x-content-type-options": "nosniff",
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   |   "date": "Fri, 05 Jan 2024 12:23:15 GMT",
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   |   "content-length": "19",
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   |   "connection": "close"
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | }
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | ###### End Diagnostic HTTP information ######
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   ❗  ::error::Finalize artifact upload failed: Artifact service responded with 500
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   | ::error::Finalize artifact upload failed: Artifact service responded with 500
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2]   ❌  Failure - Main Archive pcre2 distribution
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2] exitcode '1': failure
gitea-runner-runner-1  | [haproxy-dependencies/HAProxy dependencies/dependency-2] [DEBUG] expression 'Archive ${{ matrix.dependency_name }} distribution' rewritten to 'format('Archive {0} distribution', matrix.dependency_name)'

```

### Gitea Version

 1.22.0+dev-514-gdd5693387

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

openleap 15.5

### How are you running Gitea?

Self hosted on SuSe openleap 15.5

### Database

PostgreSQL
