### ISSUE TITLE
Possibility to download SSH public keys from an account.

### ISSUE THREAD

**Issue by bencurio** [go-gitea/gitea#28883]
### Feature Description

GitHub provides an option to download the SSH public keys from an account.

Example:

```bash
$ curl https://github.com/{username}.keys
ssh-rsa AAAAB3[...]tsVstaqw==
ssh-rsa AAAAB3[...]vF87AVw==
```

Use case: Ansible

```yaml
---
- name: Set authorized keys taken from url using lookup
  ansible.posix.authorized_key:
    user: {username}
    state: present
    key: "{{ lookup('url', 'https://github.com/{username}.keys', split_lines=False) }}"
```
