### ISSUE TITLE
Job triggered in Gitea Workflow even if condition is not met

### ISSUE THREAD

**Issue by msalmi77** [go-gitea/gitea#28998]
### Expectation

The job **restore_backup** in the below Gitea workflow must be triggered only when a commit is pushed to the main branch and the commit message matchs the regex: `^Merge pull request*RESTORE GITEA BACKUP.*`  

```
name: On Demand Restore Gitea Workflow
on:
  push:
   branches:
    - main

jobs:
  restore_backup:
    if: ${{ toJSON(github.event.commits[0].message) }} == "Merge pull request*RESTORE GITEA BACKUP.*"
    #if: ${{ toJSON(github.event.commits[0].message) }} == ""
    name: Restore Gitea Backup
    strategy:
      fail-fast: false

    steps:

      - name: Show Gitea Event
        run: |
          echo "MESSAGE:" $MESSAGE
        env:
          MESSAGE: ${{ toJSON(github.event.commits[0].message) }}

```

### What Happened

Job is triggered even if commit message does not match the regex

![image](https://github.com/go-gitea/gitea/assets/129944550/3088aa0e-1d6d-4a32-939b-db83b3fbd580)

### Gitea Version

1.20.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

On Kubernetes via official Helm chart

### Database

PostgreSQL
