### ISSUE TITLE
[Actions] Workflows not triggered for PR assign and review

### ISSUE THREAD

**Issue by clinche** [go-gitea/gitea#29166]
### Description

I'm currently doing the setup of the CI/CD pipeline for our Gitea organization. 
I'm writing two workflows that should be triggered by the following:

```yaml
on:
  pull_request:
    types: [assigned, review_requested, labeled]
```
and 
```yaml
on:
  pull_request:
    types: [closed, unassigned, unlabeled, review_request_removed]
```

I didn't saw at the beginning that the `review_requested*` types [are not supported by gitea](https://docs.gitea.com/usage/actions/faq#what-workflow-trigger-events-does-gitea-support), and this is okay.

However, the only events that currently trigger the workflow are `labeled`, `unlabeled`, and `closed`. From my understanding, assigned events should work but they trigger nothing.

What could be the causes? (and also, I probably should open another issue for this question but will `review*` types could be supported on workflows as they are handled by webhooks?)

I created a simple repo that can reproduce the issue [here](https://try.gitea.io/gfjdhgdf/pr_ci_tests/): the actions are launched for `labeled` and `unlabeled` but not for every other type trigger. EDIT: when the only label is removed, the called workflow is the one containing `labeled`, not `unlabeled` 

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I followed the docs on how to launch gitea using systemd, and the binary runs on bare-metal without any containerization

### Database

PostgreSQL
