### ISSUE TITLE
[actions] issue_comment event trigger not firing on pull request comments

### ISSUE THREAD

**Issue by Fratee** [go-gitea/gitea#29175]
### Description

`issue_comment` event trigger is not firing on pull request comments.

The action is starting properly when adding a comment on an issue, but not on a pull request.

```yaml
name: Collection
run-name:  CommentCollection
on:
  issue_comment:
    types: [created]
defaults:
  run:
    shell: powershell

jobs:
  Dump Gitea Context:
    if: ${{ github.event.issue.pull_request }}
    runs-on: [windows]
    steps:
      - name: Dump Gitea context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$env:GITHUB_CONTEXT"
```

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.41.0.windows.1

### Operating System

win 10

### How are you running Gitea?

self hosting, command line

### Database

SQLite
