### ISSUE TITLE
Workflows are not triggered for edited issues

### ISSUE THREAD

**Issue by IzeQube** [go-gitea/gitea#29213]
### Description

I'm currently trying to use a self hosted copy of renovateBOT. While workflows with a schedule are working great, I have a problem with the issues trigger.

The workflow shown below triggers if a new issue is created and is also trigged when I close an issue. If I edit an issue nothing happens, even though it should supported by the docs.

I have the following workflow in my GiTea Repo:
```yaml
name: Test

on: issues

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
```

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.1

### Operating System

Linux

### How are you running Gitea?

Running via Docker

### Database

SQLite
