### ISSUE TITLE
Impossible to use custom themes

### ISSUE THREAD

**Issue by Rollbacke** [go-gitea/gitea#29281]
### Description

Hi everybody,
I cannot use custom themes. I haven't paid attention since when, and I still use the "latest" tag (currently 1.25.1).
I've read the PR of the 1.25 version, and the css files are already in the `$GITEA_CUSTOM/public/assets/css/` folder.
I can access to the css by https://gitea.myfqdn.org/assets/css/
Example: https://gitea.myfqdn.org/assets/css/theme-catppuccin-macchiato-green.css

I've the variable in the app.ini, but no, I can't have the theme list in the select tab in settings.

Thanks !

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/86650802/3686ca06-dc14-414a-8220-ece02f840d77)


### Git Version

_No response_

### Operating System

Docker

### How are you running Gitea?

Use Gitea in Docker, on a Debian 12 with official Docker with compose, on kernel 6.1.0-18-amd64.
I don't use volume, i've mount point.

Here is my compose configuration :
```
  gitea-psql:                                                                                                                                                                                                      
    container_name: gitea-psql                                                                                                                                                                                     
    image: postgres:16                                                                                                                                                                                             
    env_file:                                                                                                                                                                                                      
      - "./gitea-psql/.env"                                                                                                                                                                                        
    volumes:                                                                                                                                                                                                       
      - ./gitea-psql/data/:/var/lib/postgresql/data/:rw                                                                                                                                                            
    networks:                                                                                                                                                                                                      
      net_manager-bridge:                                                                                                                                                                                          
    restart: unless-stopped                                                                                                                                                                                        
                                                                                                                                                                                                                   
  gitea:                                                                                                                                                                                                           
    container_name: gitea                                                                                                                                                                                          
    image: gitea/gitea:latest                                                                                                                                                                                      
    env_file:                                                                                                                                                                                                      
      - "./gitea/.env"                                                                                                                                                                                             
    volumes:                                                                                                                                                                                                       
      - ./gitea/data/:/data/:rw                                                                                                                                                                                    
      - /etc/timezone:/etc/timezone:ro                                                                                                                                                                             
      - /etc/localtime:/etc/localtime:ro                                                                                                                                                                           
    depends_on:                                                                                                                                                                                                    
      - gitea-psql                                                                                                                                                                                                 
    labels:                                                                                                                                                                                                        
      - "traefik.enable=true"                                                                                                                                                                                      
      - "traefik.http.services.gitea-http3000.loadbalancer.server.port=3000"                                                                                                                                       
      - "traefik.http.middlewares.gitea-redirect-https.redirectscheme.scheme=https"                                                                                                                                
      - "traefik.http.routers.gitea-http.rule=Host(`gitea.myfqdn.org`)"                                                                                                                                         
      - "traefik.http.routers.gitea-http.entrypoints=http"                                                                                                                                                         
      - "traefik.http.routers.gitea-http.middlewares=gitea-redirect-https"                                                                                                                                         
      - "traefik.http.routers.gitea-https.rule=Host(`gitea.myfqdn.org`)"                                                                                                                                        
      - "traefik.http.routers.gitea-https.tls.certresolver=myresolver"                                                                                                                                             
      - "traefik.http.routers.gitea-https.entrypoints=https"                                                                                                                                                       
      - "traefik.http.routers.gitea-https.service=gitea-http3000"                                                                                                                                                  
      - "traefik.http.routers.gitea-https.middlewares=secHeaders@file"                                                                                                                                             
    networks:                                                                                                                                                                                                      
      net_manager-bridge:                                                                                                                                                                                          
    restart: unless-stopped
```

Here is my `.env` file: 
```
GITEA__database__DB_TYPE=postgres
GITEA__database__HOST=gitea-psql:5432
GITEA__database__NAME=gitea
GITEA__database__USER=gitea
GITEA__database__PASSWD=****
GITEA__mailer__ENABLED=true
GITEA__mailer__PROTOCOL=smtps
GITEA__mailer__SMTP_ADDR=mail.myfqdn.org
GITEA__mailer__SMTP_PORT=465
GITEA__mailer__USER=gitea@myfqdn.org
GITEA__mailer__PASSWD=****
GITEA__mailer__FROM=gitea@myfqdn.org
GITEA__ui__THEME=catppuccin-latte-rosewater,catppuccin-latte-flamingo,catppuccin-latte-pink,catppuccin-latte-mauve,catppuccin-latte-red,catppuccin-latte-maroon,catppuccin-latte-peach,catppuccin-latte-yellow,catppuccin-latte-green,catppuccin-latte-teal,catppuccin-latte-sky,catppuccin-latte-sapphire,catppuccin-latte-blue,catppuccin-latte-lavender,catppuccin-frappe-rosewater,catppuccin-frappe-flamingo,catppuccin-frappe-pink,catppuccin-frappe-mauve,catppuccin-frappe-red,catppuccin-frappe-maroon,catppuccin-frappe-peach,catppuccin-frappe-yellow,catppuccin-frappe-green,catppuccin-frappe-teal,catppuccin-frappe-sky,catppuccin-frappe-sapphire,catppuccin-frappe-blue,catppuccin-frappe-lavender,catppuccin-macchiato-rosewater,catppuccin-macchiato-flamingo,catppuccin-macchiato-pink,catppuccin-macchiato-mauve,catppuccin-macchiato-red,catppuccin-macchiato-maroon,catppuccin-macchiato-peach,catppuccin-macchiato-yellow,catppuccin-macchiato-green,catppuccin-macchiato-teal,catppuccin-macchiato-sky,catppuccin-macchiato-sapphire,catppuccin-macchiato-blue,catppuccin-macchiato-lavender,catppuccin-mocha-rosewater,catppuccin-mocha-flamingo,catppuccin-mocha-pink,catppuccin-mocha-mauve,catppuccin-mocha-red,catppuccin-mocha-maroon,catppuccin-mocha-peach,catppuccin-mocha-yellow,catppuccin-mocha-green,catppuccin-mocha-teal,catppuccin-mocha-sky,catppuccin-mocha-sapphire,catppuccin-mocha-blue,catppuccin-mocha-lavender
GITEA__ui__DEFAULT_THEME=arc-green
GITEA__markdown__ENABLE_HARD_LINE_BREAK_IN_DOCUMENTS=true
SSH_DOMAIN=gitea.myfqdn.org
SSH_PORT=2222
SSH_LISTEN_PORT=22
USER_UID=1007
USER_GID=1005
```

Here is my `app.ini` file:
```
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod
RUN_USER = git
I_AM_BEING_UNSAFE_RUNNING_AS_ROOT = false
WORK_PATH = /data/gitea

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH = /data/gitea
DOMAIN = gitea.myfqdn.org
SSH_DOMAIN = gitea.myfqdn.org
HTTP_PORT = 3000
ROOT_URL = https://gitea.myfqdn.org/
DISABLE_SSH = false
SSH_PORT = 2222
SSH_LISTEN_PORT = 22
LFS_START_SERVER = true
# LFS_CONTENT_PATH=/data/git/lfs
LFS_JWT_SECRET = ****
OFFLINE_MODE = false
HTTP_ADDR = 0.0.0.0
PROTOCOL = 
USE_PROXY_PROTOCOL = false
PROXY_PROTOCOL_TLS_BRIDGING = false
PROXY_PROTOCOL_HEADER_TIMEOUT = 5s
PROXY_PROTOCOL_ACCEPT_UNKNOWN = false
ALLOW_GRACEFUL_RESTARTS = true
GRACEFUL_HAMMER_TIME = 1m0s
STARTUP_TIMEOUT = 0s
PER_WRITE_TIMEOUT = 30s
PER_WRITE_PER_KB_TIMEOUT = 10s
STATIC_URL_PREFIX = 
LOCAL_ROOT_URL = http://localhost:3000/
LOCAL_USE_PROXY_PROTOCOL = false
REDIRECT_OTHER_PORT = false
PORT_TO_REDIRECT = 80
REDIRECTOR_USE_PROXY_PROTOCOL = false
STATIC_ROOT_PATH = /app/gitea
STATIC_CACHE_TIME = 6h0m0s
ENABLE_GZIP = 
ENABLE_PPROF = false
PPROF_DATA_PATH = /app/gitea/data/tmp/pprof
LANDING_PAGE = home
SSH_SERVER_CIPHERS = 
SSH_SERVER_KEY_EXCHANGES = 
SSH_SERVER_MACS = 
SSH_KEYGEN_PATH = 
SSH_SERVER_USE_PROXY_PROTOCOL = false
SSH_TRUSTED_USER_CA_KEYS_FILENAME = /data/git/.ssh/gitea-trusted-user-ca-keys.pem
SSH_AUTHORIZED_PRINCIPALS_ALLOW = off
MINIMUM_KEY_SIZE_CHECK = true
SSH_AUTHORIZED_KEYS_BACKUP = true
SSH_CREATE_AUTHORIZED_KEYS_FILE = true
SSH_EXPOSE_ANONYMOUS = false
SSH_AUTHORIZED_KEYS_COMMAND_TEMPLATE = {{.AppPath}} --config={{.CustomConf}} serv key-{{.Key.ID}}
SSH_PER_WRITE_TIMEOUT = 30s
SSH_PER_WRITE_PER_KB_TIMEOUT = 10s
BUILTIN_SSH_SERVER_USER = git
SSH_USER = git

[database]
PATH = /data/gitea/gitea.db
DB_TYPE = postgres
HOST = gitea-psql:5432
NAME = gitea
USER = gitea
PASSWD = ****
LOG_SQL = false
SCHEMA = 
SSL_MODE = disable
CHARSET = utf8

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER = file

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
DISABLE_GRAVATAR = false
ENABLE_FEDERATED_AVATAR = true

[attachment]
PATH = /data/gitea/attachments

[log]
MODE = console
LEVEL = info
ROOT_PATH = /data/gitea/log
STACKTRACE_LEVEL = none
BUFFER_LEN = 10000
ENABLE_SSH_LOG = false
ACCESS_LOG_TEMPLATE = {{.Ctx.RemoteHost}} - {{.Identity}} {{.Start.Format "[02/Jan/2006:15:04:05 -0700]" }} "{{.Ctx.Req.Method}} {{.Ctx.Req.URL.RequestURI}} {{.Ctx.Req.Proto}}" {{.ResponseWriter.Status}} {{.ResponseWriter.Size}} "{{.Ctx.Req.Referer}}" "{{.Ctx.Req.UserAgent}}"
REQUEST_ID_HEADERS = 
logger.router.MODE = console

[security]
INSTALL_LOCK = true
SECRET_KEY = ****
REVERSE_PROXY_LIMIT = 1
REVERSE_PROXY_TRUSTED_PROXIES = *
INTERNAL_TOKEN = ****
PASSWORD_HASH_ALGO = pbkdf2

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = false
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.localhost

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[ui]
DEFAULT_THEME = arc-green
THEME = catppuccin-latte-rosewater,catppuccin-latte-flamingo,catppuccin-latte-pink,catppuccin-latte-mauve,catppuccin-latte-red,catppuccin-latte-maroon,catppuccin-latte-peach,catppuccin-latte-yellow,catppuccin-latte-green,catppuccin-latte-teal,catppuccin-latte-sky,catppuccin-latte-sapphire,catppuccin-latte-blue,catppuccin-latte-lavender,catppuccin-frappe-rosewater,catppuccin-frappe-flamingo,catppuccin-frappe-pink,catppuccin-frappe-mauve,catppuccin-frappe-red,catppuccin-frappe-maroon,catppuccin-frappe-peach,catppuccin-frappe-yellow,catppuccin-frappe-green,catppuccin-frappe-teal,catppuccin-frappe-sky,catppuccin-frappe-sapphire,catppuccin-frappe-blue,catppuccin-frappe-lavender,catppuccin-macchiato-rosewater,catppuccin-macchiato-flamingo,catppuccin-macchiato-pink,catppuccin-macchiato-mauve,catppuccin-macchiato-red,catppuccin-macchiato-maroon,catppuccin-macchiato-peach,catppuccin-macchiato-yellow,catppuccin-macchiato-green,catppuccin-macchiato-teal,catppuccin-macchiato-sky,catppuccin-macchiato-sapphire,catppuccin-macchiato-blue,catppuccin-macchiato-lavender,catppuccin-mocha-rosewater,catppuccin-mocha-flamingo,catppuccin-mocha-pink,catppuccin-mocha-mauve,catppuccin-mocha-red,catppuccin-mocha-maroon,catppuccin-mocha-peach,catppuccin-mocha-yellow,catppuccin-mocha-green,catppuccin-mocha-teal,catppuccin-mocha-sky,catppuccin-mocha-sapphire,catppuccin-mocha-blue,catppuccin-mocha-lavender

[markdown]
ENABLE_HARD_LINE_BREAK_IN_DOCUMENTS = true

[ssh.minimum_key_sizes]

[oauth2]
JWT_SECRET = ****

[mailer]
PASSWD = ****
PROTOCOL = smtps
ENABLED = true
FROM = gitea@myfqdn.org
SMTP_PORT = 465
USER = gitea@myfqdn.org
SMTP_ADDR = mail.myfqdn.org
```

Please find attached a extract of the container logs.
[logs.txt](https://github.com/go-gitea/gitea/files/14345412/logs.txt)


### Database

PostgreSQL
