### ISSUE TITLE
Gitea x Keycloak OpenID login (Self Signed Certificates)

### ISSUE THREAD

**Issue by ikamii** [go-gitea/gitea#29420]
### Description

I have deployed Gitea as well as Keycloak via Helm on Kubernetes and have cluster-issuer of cert-manager. 
I am trying to setup OpenID Login from Keycloak to Gitea.

When I try to add Authentication Source with OAuth2 - OpenID I got an error which says:
 - "tls: failed to verify certificate: x509: certificate signed by unknown authority."
 
I also have customized the config with the values but it didn't help either:

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[webhook]
SKIP_TLS_VERIFY = true

Can you please help me to find out how it works and where I do a mistake?

Thank you in advance.
 

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Helm Chart on RKE2

Changed values.yaml for host, ingress and added some for custom app.ini config.

### Database

None

**Comment by KN4CK3R** [comment]
Looks like Gitea doesn't know about your certificate and therefore can't access the keycloak endpoints.

**Comment by ikamii** [comment]
Hi @KN4CK3R,

thank you for your response. Yes, I got it but I can't find where I can add self signed certificates to Gitea. Can you maybe help me with that?

Thanks!

**Comment by KN4CK3R** [comment]
Gitea does not manage certificates. That's handled by the operating system.

**Comment by Xulunix** [comment]
I run a similar setup.
I went with just building my own image based on the official image and my ca-cert on top.
Something like this should do the trick:

`ARG Version=latest
FROM [COMPANY_REPO_SERVER]/docker-mirror/gitea/gitea:$Version

USER root
COPY COMPANY_ROOT_CA.crt /usr/local/share/ca-certificates
RUN update-ca-certificates

USER 1000:1000`

**Comment by ikamii** [comment]
I have finally solved the issue. 😄 

# Instruction 

## 1. Create secret for keycloak certificate (in Gitea namespace)
You can use tls.crt or ca.crt:
```bash
kubectl create secret generic keycloak-certificate --from-file=keycloak.crt=<PATH/TO/YOUR/tls.crt> -n <GITEA-NAMESPACE>
```
or
```bash
kubectl create secret generic keycloak-certificate --from-file=keycloak.crt=<PATH/TO/YOUR/ca.crt> -n <GITEA-NAMESPACE>
```

## 2. Update the Chart to add it under /etc/ssl/certs/ in the container

gitea/templates/gitea/deployment.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata: ...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
        - name: {{ .Chart.Name }}
          ...
          volumeMounts:
            - name: keycloak-certificate
              mountPath: "/etc/ssl/certs/keycloak.pem"
              subPath: "keycloak.crt"
              readOnly: true
      ...
      volumes:
        - name: keycloak-certificate
          secret:
            secretName: keycloak-certificate
  
```
