### ISSUE TITLE
[Actions] Runner unable to find files

### ISSUE THREAD

**Issue by diamante0018** [go-gitea/gitea#29539]
### Description

Hello,

I'm having a bug on Gitea which I am unable to get on GitHub when running the same identical setup on one of their public free tier runners.

In short, this (https://github.com/diamante0018/setup-oat) workflow can be used without issues on GitHub. I self-test it there with its own workflow so we can see that the pipeline is green. What it does is very simple, it downloads a tar from a release page, extracts it, sets executable permissions and moves it to the .OAT folder relative to the workspace environment.

We can see from this line that on GitHub "this just works" fine https://github.com/diamante0018/setup-oat/blob/main/.github/workflows/test.yml#L38

I can run the "Linker" program without issues, I can't say the same for gitea.

On my gitea runner after my setup-oat action is finished the Linker can be found in my .OAT folder However no matter what I try it's completely inaccessible. Any tips? Please see the attached screenshots. I am not 100% sure this behaviour could be gitea's fault but seeing how it works on Github it might be?

Unable to reproduce on try.gitea because actions are not set up for Linux, furthermore clicking on the "actions" tab after enabling them in the settings on that website throws a 500 error code

My repo is open-source, so if someone who can set up a runner on try.gitea wishes to do so feel free to.
https://git.alterware.dev/AlterWare/iw5-menus/src/branch/build/add-oat-build (just this branch)

Update 1:
I was able to use my own action on GitHub by copy and pasting the workflow I was using without success from my gitea I linked

See how it is successful on GitHub:
Repo: https://github.com/diamante0018/PlutoIW5Arena
Actions: https://github.com/diamante0018/PlutoIW5Arena/actions

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

I tried with both absolute path (like in the screenshot) and without (like in the test.yml I link on Github), same error.

![1](https://github.com/go-gitea/gitea/assets/37080671/5bfd7b05-9e20-40f2-ac85-6b4068adea7b)

![image](https://github.com/go-gitea/gitea/assets/37080671/45658f2b-e74d-47a4-a662-5b62704baf3f)

### Git Version

Git Version 2.34.1

### Operating System

OS Ubuntu 22.04 64 Bit

### How are you running Gitea?

Running via binary using systemd

### Database

MySQL/MariaDB

**Comment by charles7668** [comment]
This may not be a Gitea action problem.

The Linker requires some dependencies that you need to install.

Before you test this, you may need to change your action runner labels. Here, I use the 'Test' label, which is node:20.11.1, because its Debian version is 12 (which contains glibc higher than 2.34).

this is example:
```yaml
name: link

on: [push]

jobs:
  link-linux:
    name: Link on Linux
    runs-on: Test

    steps:
      - name: Check out files
        uses: actions/checkout@main
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup OAT
        uses: diamante0018/setup-oat@main
        with:
          version: "0.8.3"    
      
      - name: Install deps
        run: |
          apt update
          apt install gcc g++ gcc-multilib g++-multilib -y

      - name: Debug
        run: 
          ls -a ./.OAT

      - name: Create code_post_gfx_mp
        run: |
          ./.OAT/Linker -v -l "./deps/iw5-zones/zone/english/code_post_gfx_mp.ff" code_post_gfx_mp          

      - name: Create localized_ui_mp
        run: |
          ./.OAT/Linker -v -l "./deps/iw5-zones/zone/english/localized_ui_mp.ff" localized_ui_mp          
```

result:
![image](https://github.com/go-gitea/gitea/assets/30816317/5bf63746-3220-4807-9deb-487e163e30b4)

The failed messages are output by the Linker, so you will need to debug it yourself.
