### ISSUE TITLE
Scheduled actions are not working for non-main branch

### ISSUE THREAD

**Issue by kevchu3** [go-gitea/gitea#29574]
### Description

Scheduled actions are not working for non-main branch.  This issue is NOT fixed by the following PRs:

https://github.com/go-gitea/gitea/pull/28942
https://github.com/go-gitea/gitea/issues/28533#issuecomment-1903472061

Here is how I was able to reproduce the issue fairly easily.  I wasn't able to fire up an actions runner on the Gitea demo site to reproduce the scenario on https://try.gitea.io, but it can be reproduced with the following:

1. Create a new repository, create a file named .gitea/workflows/test-scheduled-actions.yaml with the following content (on push, but not on scheduled cron):
```
name: Test scheduled actions
on:
  push:

jobs:
  test:
    name: Test scheduled actions
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Print out
      shell: bash
      run: echo test1
```

2. Then, create a new dev branch and update the workflow with the on schedule event.  I've fired off the event every minute to trigger a test quickly.  Here's the updated test-scheduled-actions.yaml:
```
name: Test scheduled actions
on:
  schedule:
    - cron: '* * * * *'
  push:

jobs:
  test:
    name: Test scheduled actions
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Print out
      shell: bash
      run: echo test1
```

3. You'll notice that the actions runner did trigger on push both for main and dev branch commits, but not on the scheduled action on dev branch.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.39.3

### Operating System

RHEL kernel 5.14.0-284.54.1.el9_2.x86_64

### How are you running Gitea?

I've installed Gitea in my Kubernetes cluster through the Helm chart.  I am using the latest chart gitea-10.1.3 which corresponds to Gitea 1.21.7.

```
$ helm repo add gitea-charts https://dl.gitea.io/charts/
$ helm install gitea gitea-charts/gitea -f values.yaml
```

Here is my values.yaml.  Main modification is to use a postgres database in non-HA mode:
```
redis-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
```

### Database

PostgreSQL
