### ISSUE TITLE
Unable to access secrets from a expect script

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#29829]
### Description

I'm unable to access Gitea repository secrets from inside the executed except script.

Here's the workflow:

```yaml
name: Deploy
run-name: ${{ gitea.actor }}
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update repositories and install dependencies
        run: |
          apt update -y && apt install expect -y
      - name: Run deploy script
        env:
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          expect deploy.sh
```

The script:

```bash
#!/usr/bin/expect -f

set VPS_IP $env(VPS_IP)
set VPS_USERNAME $env(VPS_USERNAME)
set VPS_PASSWORD $env(VPS_PASSWORD)

set REMOTE_ROOT "~/projects/novascriptio"

spawn ssh $VPS_IP@$VPS_USERNAME "git clone git@gitea.novascript.io:NovaScript/novascriptio.git $REMOTE_ROOT && bash $REMOTE_ROOT/build.sh"
expect {
    "yes/no" { 
        send "yes\r"
        expect "password:"
        send "$VPS_PASSWORD\r"
    }
    "password:" {
        send "$VPS_PASSWORD\r"
    }
}

expect eof
```
The error:

```
spawn ssh ***@*** git clone git@gitea.novascript.io:NovaScript/novascriptio.git ~/projects/novascriptio && bash ~/projects/novascriptio/build.sh
| ssh: Could not resolve hostname ***: Name or service not known
```

### Gitea Version

1.21

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Debian 10

### How are you running Gitea?

It's a barebones installation, no Docker involved for the runner or Gitea.

### Database

SQLite
