### ISSUE TITLE
Cannot get actions to work

### ISSUE THREAD

**Issue by flixman** [go-gitea/gitea#30040]
### Description

I have created a gitea action to get to know it. Unfortunately, I cannot get to clone the repository... and the error message is not very helpful. This is the workflow file:
```yaml
---
name: CI test
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
  # issue_comment is used here to trigger workflows manually
  # until the corresponding functionality is available on gitea
  issue_comment:

jobs:
  build:
    runs-on: debian-node16
    if: ${{ github.event.pull_request != '' || github.event.pusher != '' || github.event.comment.body == '!actions run build' || github.event.comment.body == '!actions run all' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo "Build Run"

  test:
    name: Test
    runs-on: debian-node16
    if: ${{ github.event.pull_request != '' || github.event.pusher != '' || github.event.comment.body == '!actions run test' || github.event.comment.body == '!actions run all' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo "Test Run"

```
And this is the error I get, when doing the checkout
```bash
::add-matcher::/run/act/actions/actions-checkout@v4/dist/problem-matcher.json
Syncing repository: user/myrepo
::group::Getting Git version info
Working directory is '/workspace/user/myrepo'
::endgroup::
Deleting the contents of '/workspace/user/myrepo'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Not found.
Waiting 18 seconds before trying again
Downloading the archive
Not found.
Waiting 14 seconds before trying again
Downloading the archive
::remove-matcher owner=checkout-git::
::error::Not found.%0A
```
what is the archive it cannot download? could it be due to the fact that I have gitea behind an apache server that terminates the SSL connection (uses a Let's encript certificate)?

### Gitea Version

1.21.9

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

debian stable

### How are you running Gitea?

I am downloading the gitea binaries from github releases. Gitea itself is running natively, but the runners are running through docker.

### Database

PostgreSQL
