### ISSUE TITLE
GiteaActions: docker command not found

### ISSUE THREAD

**Issue by bjdaijun** [go-gitea/gitea#30131]
### Description

I used GiteaActions to build a docke image, but It failed with message : docker command  not found. Here is my yaml file:

```
name: test
 on: push
 jobs: 
  build-and-push
  runs-on: ubuntu-latest
  steps:
    - name: checkout
       uses: actions/checkout@v2
    - name: dockerbuild
       run: docker build -t test:latest .
```

The first action checkout runs successfully, but the second action dockerbuild failed with message: docker not found.

And my act_runner in docker , with /var/run/docker/sock mounted.

Is this the right usage to build a docker image in actions?

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

run by docker 

### Database

None
