### ISSUE TITLE
act_runner won't start on permission denied

### ISSUE THREAD

**Issue by asitemade4u** [go-gitea/gitea#30197]
### Description

- I have installed act_runner according to your instructions (last version)
- The runner is registered at the installation level of Gitea (last version)
- But when I execute `./act_runner daemon` I get the following error:

```error
NFO[2024-03-30T19:40:52-04:00] Starting runner daemon                       
ERRO[2024-03-30T19:40:52-04:00] fail to invoke Declare                        error="permission_denied: 403 Forbidden"
Error: permission_denied: 403 Forbidden
```
What am I doing wrong?
S.

### Gitea Version

1.21.10 built with GNU Make 4.4.1, go1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

N/A: does not concern Gitea but Gitea Actions and, more specifically, the runner

### Git Version

2.40.1

### Operating System

CentOS 9

### How are you running Gitea?

docker, here is the `docker-compose.yml` file

```yaml
version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"
    environment:
      - USER_GID=981
      - USER_UID=987
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/git/.ssh:/data/.ssh
      - /zfs212/gta/gitea:/data/gitea
      - /zfs212/git:/data/git

networks:
  default:
    name: lsio
    external: true
```

### Database

PostgreSQL
