### ISSUE TITLE
Gitea does not apply CODEOWNERS for PRs from forks

### ISSUE THREAD

**Issue by splitt3r** [go-gitea/gitea#30277]
### Description

If you create a pull request from a fork Gitea won't apply the CODEOWNERS. They only work for PRs from origin to origin.

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

```yaml
version: '3'

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  gitea:

volumes:
  gitea-data:
  postgres-data:
```

### Database

None
