### ISSUE TITLE
Actions: Checkout of self hosted repo with tag always results on main branch checkout

### ISSUE THREAD

**Issue by Fratee** [go-gitea/gitea#30543]
### Description

act runner version: 0.2.10

The following job does not use the upload-artifact at the `v3` tag, but instead uses the latest commit on the default branch.
The `actions/upload-artifact` repository is hosted locally and correctly fetched by using `DEFAULT_ACTIONS_URL=self`
 in Gitea configuration.

```yaml
jobs:
  upload:
    steps:
      - name: Create a file
        run: echo "hello world" > my-file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: my-file.txt
```

When trying to investigate the issue we found out that in the runner act cache the repository is called `actions-upload-artifact@v3` but the content in our case was of the v4.

Launch command `.\act_runner.exe daemon -c .\config.yaml`.

config.yaml
```yaml
cache:
  dir: D:\programs\runner\cache\actcache
host:
  workdir_parent: D:\programs\runner\cache\act
```

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.41.0.windows.1

### Operating System

windows 10

### How are you running Gitea?

self hosted

### Database

SQLite
