### ISSUE TITLE
Release created from an existing tag does not trigger an actions workflow

### ISSUE THREAD

**Issue by mdawar** [go-gitea/gitea#30619]
### Description

I've noticed that releases created from a tag that already exist won't trigger an actions workflow with `release` of type `published`.

But the workflow is triggered if the release creates the tag.

Here's a sample workflow:
```yml
name: Release Test

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release test"
```

I tried it on the web UI and the API.

Demo repo: https://try.gitea.io/mdawar/release-actions-demo

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.44.0

### Operating System

Linux

### How are you running Gitea?

Docker image.

### Database

SQLite
