### ISSUE TITLE
GetInfoRefs() [E] signal: killed

### ISSUE THREAD

**Issue by perfectra1n** [go-gitea/gitea#30698]
### Description

Hey all,

Lunny told me to create a GitHub issue for this. My Gitea really has become very sluggish, doesn't always respond, and has its logs filled with `context deadline exceeded`:

![image](https://github.com/go-gitea/gitea/assets/2390633/7e3c1401-04cb-4a29-b799-cce7d0ebbdfb)

I'm running the Gitea Helm Chart on my vanilla Kubernetes Cluster.

<details>
<summary>Kubernetes YAML Deployment</summary>
<br>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd

spec:
  project: default
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: "10.1.4"
    helm:
      values: |
        image:
          repository: gitea/gitea
          tag: 1.21.11
          pullPolicy: Always
          rootless: true
        replicaCount: 3
        deployment:
          annotations:
            reloader.stakater.com/auto: "true"
        resources:
          requests:
            memory: 12G
          limits:
            memory: 12G
        clusterDomain: newcluster.local
        podSecurityContext:
          fsGroupChangePolicy: "OnRootMismatch"
        containerSecurityContext:
          capabilities:
            add: ["SYS_CHROOT"]
        redis-cluster:
          enabled: false
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false
        persistence:
          enabled: true
          mount: true
          create: false
          accessModes:
            - ReadWriteMany
          claimName: "gitea-main-data"
        gitea:
          additionalConfigSources:
            - secret: 
                secretName: gitea-config-secret
          admin:
            existingSecret: gitea-admin-secret
          config:
            APP_NAME: QSBuYW1lIGNvb2wK Gitea
            RUN_MODE: dev
            indexer:
              ISSUE_INDEXER_TYPE: meilisearch
              
              REPO_INDEXER_ENABLED: false
              REPO_INDEXER_TYPE: elasticsearch
              REPO_INDEXER_REPO_TYPES: sources,mirrors,templates
              MAX_FILE_SIZE: 52428800
            repository:
              ENABLE_PUSH_CREATE_USER: true
              ENABLE_PUSH_CREATE_ORG: true
              DEFAULT_BRANCH: master
              DEFAULT_PRIVATE: true
            repository.upload:
              FILE_MAX_SIZE: 102400
              MAX_FILES: 300
            server:
              DISABLE_SSH: true
              DOMAIN: gitea.something.com
              ROOT_URL: https://gitea.something.com
              ENABLE_GZIP: true
              LFS_START_SERVER: true
            database:
              DB_TYPE: postgres
              HOST: cluster16-rw.databases.svc.newcluster.local
            session:
              PROVIDER: db
            ui:
              THEMES: gitea,arc-green,github-dark,codeberg,anamecool
              DEFAULT_THEME: arc-green
            attachment:
              MAX_SIZE: 102400
              MAX_FILES: 300
            git.timeout:
              GC: 500
            actions:
              ENABLED: true
            service:
              REGISTER_EMAIL_CONFIRM: false
              REGISTER_MANUAL_CONFIRM: true
              DISABLE_REGISTRATION: false
              REQUIRE_SIGNIN_VIEW: true
              ENABLE_NOTIFY_MAIL: true
              ALLOW_ONLY_EXTERNAL_REGISTRATION: false
              ENABLE_CAPTCHA: false
              DEFAULT_KEEP_EMAIL_PRIVATE: true
              DEFAULT_ALLOW_CREATE_ORGANIZATION: true
              DEFAULT_ENABLE_TIMETRACKING: true
              NO_REPLY_ADDRESS: "noreply@gmail.com"
            cache:
              ENABLED: true
              ADAPTER: redis
              HOST: redis://:gitea@gitea-redis.gitea.svc.newcluster.local:6379/0?pool_size=100&idle_timeout=180s&
            queue:
              TYPE: redis
              CONN_STR: redis://:gitea@gitea-redis.gitea.svc.newcluster.local:6379/0?pool_size=100&idle_timeout=180s&
            cron:
              ENABLED: true
            cron.update_mirrors:
              SCHEDULE: 0 */12 * * *
            cron.resync_all_hooks:
              ENABLED: true
            cron.reinit_missing_repos:
              ENABLED: true
            security:
              LOGIN_REMEMBER_DAYS: 180
            mailer:
              ENABLED: true
          metrics:
            enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true

```
</details>

I've just run my Gitea in `dev` mode, hopefully I can also provide additional logs for `git` output.

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/perfectra1n/efb5cfa3752c34d382f0ad4291784d7a

### Screenshots

Another log gist:
https://gist.github.com/perfectra1n/9146f98c8d99e87fa97916b8af27dd14

### How are you running Gitea?

I'm running the Gitea Helm Chart on my vanilla Kubernetes Cluster. It it using PostgreSQL (CNPG), and is using democratic-csi to provide storage for the PVC that Gitea is utilizing for data.

### Database

PostgreSQL
