### ISSUE TITLE
pubring.db.lock after unclean shutdown breaks gpg related actions

### ISSUE THREAD

**Issue by Janhouse** [go-gitea/gitea#30781]
### Description

Commits page loads for a very, very long time if unclean shutdown has happened before.

#### Reason:

Since gpg creates lock file in /var/lib/gitea/home/.gnupg/public-keys.d/ , which is on a persistent volume, unclean shutdown leaves `pubring.db.lock`, and after following startup gpg operations fail because of the locked database.

#### Proposed fix:

I would suggest checking for the gpg database lock file during container startup, and remove it if it exists.

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No, requires ability to crash the container

### How are you running Gitea?

Docker compose with /var/lib/gitea persisted in volume

**Comment by xyhhx** [comment]
fwiw i experienced this on forgejo too. a workaround that worked for me was to specify a different `$GNUPGHOME`, i.e.:

```yml
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      GNUPGHOME: /.gnupg
# ...
    volumes:
      - ./data/gitea/gnupg:/.gnupg
```
