### ISSUE TITLE
Failure in Gitea API when using labeler Github action 

### ISSUE THREAD

**Issue by mariusrugan** [go-gitea/gitea#30917]
### Description

I am using **[actions/labeler@v5](https://github.com/actions/labeler)**  with Gitea's Actions, the runner is running **gitea/act_runner:nightly-dind-rootless**, the labels are not placed on the issue & the actual workflow step is failing with the following message, added below 

It's coming from the Gitea API, & i'd like to understand what how can i help to improve this.

Error:

```
The configuration file (path: .gitea/labeler.yaml) was found locally, reading from the file
::error::HttpError: []: json: cannot unmarshal number " into Go struct field IssueLabelsOption.Labels of type int64
::error::[]: json: cannot unmarshal number " into Go struct field IssueLabelsOption.Labels of type int64
```

the job looks very simple:

```
jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Labeler
        uses: actions/labeler@v5
        with:
          configuration-path: .gitea/labeler.yaml
          sync-labels: true
```

labeler.yaml

```
Documentation:
- changed-files:
  - any-glob-to-any-file: docs/**

```      

EDIT
from gitea's log:

```sh
...eb/routing/logger.go:102:func1() [I] router: completed PUT /api/v1/repos/mariusrugan/example-repo/issues/104/labels for 1.2.3.4:37056, 422 Unprocessable Entity in 20.9ms @ v1/api.go:689(v1.Routes.func1.10.1.1.2.2.bind[...])
```

Many thanks in advance!

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker container

### Database

SQLite
