### ISSUE TITLE
Difference between github and gitea actions when running contains(needs.*.result, 'success')

### ISSUE THREAD

**Issue by ldomesjo** [go-gitea/gitea#31007]
### Description

Hello,

I am trying to specify a job which is dependant on two other jobs finishing with an error, but there's seems to be a difference between how this is handled between github actions and gitea actions.
I created this example workflow for github, accessible here https://github.com/ldomesjo/testing-github-actions/tree/main/.github/workflows:
```yaml
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo meh
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo meh
  third-job:
    runs-on: ubuntu-latest
    needs:
      - first-job
      - second-job
    steps:
      - run: echo '${{ toJSON(needs) }}'
      - run: echo ${{ contains(needs.*.result, 'success') }}
```

Which outputs this:
![image](https://github.com/go-gitea/gitea/assets/49636413/c0ccab03-ecba-48c5-82dc-7391383829d4)

I then created a similar workflow for gitea actions looking like this:
```yaml
name: learn-gitea-actions
run-name: ${{ gitea.actor }} is learning Gitea Actions
on: [push]
jobs:
  first-job:
    runs-on: action-runner
    steps:
      - run: echo meh
  second-job:
    runs-on: action-runner
    steps:
      - run: echo meh
  third-job:
    runs-on: action-runner
    needs:
      - first-job
      - second-job
    steps:
      - run: echo '${{ toJSON(needs) }}'
      - run: echo ${{ contains(needs.*.result, 'success') }}
```

Giving this output:
![image](https://github.com/go-gitea/gitea/assets/49636413/642c00c6-d991-4cf2-93c7-9041ae903fe0)

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Running the rootless docker version of gitea

### Database

None
