### ISSUE TITLE
Issue template the first option will be selected by default from the dropdown of type

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#31044]
### Description

.gitea/issue_template/bug.yml
```yml
name: Bug Report
about: File a bug report
title: "[Bug]: "
body:
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

```

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="417" alt="image" src="https://github.com/go-gitea/gitea/assets/93666053/62ee5672-ed48-440b-a509-36713fed5e9e">

### How are you running Gitea?

docker

### Database

MySQL/MariaDB
