### ISSUE TITLE
GitHub action gets Killed

### ISSUE THREAD

**Issue by Vonor** [go-gitea/gitea#31156]
### Environment

I'm on a MacOS M1 Host running the official Docker Desktop

### Steps to Reproduce

Gitea Instance

```
docker run -d --name=gitea \
  -p 80:80 \
  -p 443:443 \
  -p 22:22 \
  -v $GITEA_HOME/data:/data \
  -v $GITEA_HOME/config/:/etc/gitea \
  -v $GITEA_HOME/logs:/var/log/gitea \
  -e GITEA__server__PROTOCOL=https \
  -e GITEA__server__DOMAIN=$HOSTNAME \
  -e GITEA__server__ROOT_URL=https://$HOSTNAME \
  -e GITEA__server__HTTP_ADDR=0.0.0.0 \
  -e GITEA__server__HTTP_PORT=443 \
  -e GITEA__server__LFS_START_SERVER=true \
  -e GITEA__server__LFS_CONTENT_PATH=/data/git/lfs \
  -e GITEA__server__LFS_JWT_SECRET=jwt_secret \
  -e GITEA__server__OFFLINE_MODE=false \
  -e GITEA__server__DISABLE_ROUTER_LOG=false \
  -e GITEA__server__ENABLE_GZIP=true \
  -e GITEA__server__CERT_FILE=/etc/gitea/https/$HOSTNAME.crt \
  -e GITEA__server__KEY_FILE=/etc/gitea/https/$HOSTNAME.key \
  -e GITEA__service__REGISTER_EMAIL_CONFIRM=false \
  -e GITEA__service__ENABLE_NOTIFY_MAIL=false \
  -e GITEA__service__DISABLE_REGISTRATION=false \
  -e GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=false \
  -e GITEA__service__ENABLE_CAPTCHA=true \
  -e GITEA__service__REQUIRE_SIGNIN_VIEW=false \
  -e GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false \
  -e GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=true \
  -e GITEA__service__DEFAULT_ENABLE_TIMETRACKING=true \
  -e GITEA__service__NO_REPLY_ADDRESS=noreply.example.org \
  -e GITEA__service__ENABLE_ACTIONS_RUNNER=true \
  gitea/gitea:latest
```

Action Runner Instance

```
docker run \
    -v /etc/resolv.conf:/etc/resolv.conf \
    -v $GITEA_HOME/runner/config.yaml:/config.yaml \
    -v $GITEA_HOME/runner/data:/data \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e CONFIG_FILE=/config.yaml \
    -e RUNNER_INSECURE=true \
    --name MyRunner \
    -d gitea/act_runner:latest act_runner daemon --config /config.yaml
```

config.yaml - Insecure is needed as the SSL Cert is self-signed. It's a local testing instance anyway, not reachable from outside

```yml
log:
  level: info

runner:
  file: /data/.runner
  insecure: true
```

/data/.runner

```json
{
  "WARNING": "This file is automatically generated by act-runner. Do not edit it manually unless you know what you are doing. Removing this file will cause act runner to re-register as a new runner.",
  "id": 2,
  "uuid": "...",
  "name": "MyRunner",
  "token": ".....",
  "address": "https://MacBook-Air-MM/",
  "labels": [
    "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest",
    "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04",
    "ubuntu-20.04:docker://gitea/runner-images:ubuntu-20.04"
  ]
}
```

## Repository Setup

Simple Shellscript that would throw some shellcheck issues

```shell
#!/bin/bash

# 1. Command substitution in a variable (style level)
ls_output=`ls` # SC2006: Use $(...) notation instead of legacy backticks `...`.

# 2. Unquoted variable (info level)
echo $ls_output # SC2086: Double quote to prevent globbing and word splitting.

# 3. Unused variable (warning level)
unused_var="This variable is not used anywhere" # SC2034: unused_var appears unused. Verify use (or export if used externally).

# 4. Attempt to use an undefined variable (warning level)
# echo $undefined_var # SC2154: undefined_var is referenced but not assigned.

# 5. Syntax error (error level)
# for ((i=0; i<5; i++)) # SC1073: Couldn't parse this ((...)) command. Fix to allow more checks.
```

.github/workflows/shellcheck.yml

```yml
name: ShellCheck

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        env:
          GIT_SSL_NO_VERIFY: 'true'
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.10.0
          severity: warning
```

## Expected behaviour

On Github this exact Repository and Workflow works flawlessly.

# Actual behaviour with gitea and action-runner

```
/var/run/act/workflow/1-composite-1.sh: line 2:   125 Killed                  "/var/run/act/actions/ludeeus-action-shellcheck@master/shellcheck" --version
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Untested

### How are you running Gitea?

See Description

### Database

SQLite
