### ISSUE TITLE
Gitea Workflow Trigger "release" doesn't trigger when release published by another workflow

### ISSUE THREAD

**Issue by cored0wn** [go-gitea/gitea#31298]
### Description

When publishing a release via workflow action, I expect that it will trigger an release event (type: published)
Unfortunately this is not the case.

It only triggers if I create a release manually.

### Example workflow

```
name: Test release trigger event
run-name: Check if release trigger works
on:
  release:
    types: [published]

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
```

Example workflow as well a workflow which will create a release if a tag is published can be found on [my demo repository](https://demo.gitea.com/twittor/demo/src/branch/main/.gitea/workflows)

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

official docker container

### How are you running Gitea?

Self hosted but I managed to recreate the issue on the demo [gitea instance]((https://demo.gitea.com/twittor/demo)

### Database

None
