### ISSUE TITLE
Git credential manager points to 127.0.0.1 Error code: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by Erriez** [go-gitea/gitea#31297]
### Description

I run Gitea 1.22 via Docker compose with a NGINX reverse proxy and self-signed certificate on domain `local.lan`.  When cloning a Gitea project with HTTPS connection on Windows, the web browser is opened to enter credentials as shown in the screenshot below `Authorize "Git Credential Manager" to access your count`:

![image](https://github.com/go-gitea/gitea/assets/8849873/e602e853-953d-4a96-88ea-d5676db467da)

When clicking `Authorize Application`:

![image](https://github.com/go-gitea/gitea/assets/8849873/e6799d8b-f50f-4739-a9bf-62bdf40cdda7)

The following error is generated:

```
Secure Connection Failed

An error occurred during a connection to 127.0.0.1:51398. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

Reason is that the redirect URL is pointing to `127.0.0.1` instead of the domain. However, the screenshot in the documentation shows the correct domain name: https://docs.gitea.com/development/oauth2-provider#examples.

How can the `REDIRECT_URI` in the link `https://[REDIRECT_URI]?code=RETURNED_CODE&state=STATE` changed from `127.0.0.1:<PORT>` to the domain name `local.lan`?

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.45.2.windows.1

### Operating System

Windows 10 Pro

### How are you running Gitea?

**gitea/conf/app.ini**
```
[server]
APP_DATA_PATH = /data/gitea
PROTOCOL = http
USE_PROXY_PROTOCOL = false
PROXY_PROTOCOL_TLS_BRIDGING = true
DOMAIN = local.lan
SSH_DOMAIN = local.lan
HTTP_PORT = 3000
ROOT_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
DISABLE_SSH = false
SSH_PORT = 22
SSH_LISTEN_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = <REMOVED>
OFFLINE_MODE = false
```

**nginx/config/conf.d/gitea.conf**:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name  gitea.*;

    include /etc/nginx/ssl.conf;

    location / {
        include /etc/nginx/proxy.conf;

        # gitea is the name of the Docker container listening on port 3000
        set $upstream_app gitea;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**nginx/config/proxy.conf**:
```
# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Proxy Connection Settings
proxy_buffers 32 4k;
proxy_connect_timeout 240;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
proxy_http_version 1.1;
proxy_read_timeout 240;
proxy_redirect  http://  $scheme://;
proxy_send_timeout 240;

# Proxy Cache and Cookie Settings
proxy_cache_bypass $cookie_session;
#proxy_cookie_path / "/; Secure"; # enable at your own risk, may break certain apps
proxy_no_cache $cookie_session;

# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;
```

**dockercompose.yml**:
```
version: '3'

services:
  mariadb:
    image: mariadb:11.2.2
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${VOLUME_DIR}/mariadb/data:/var/lib/mysql
      - ${VOLUME_DIR}/mariadb/imports:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  
  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    restart: always
    depends_on:
      - mariadb
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${GITEA_DB_PASSWORD}
      - APP_NAME="Git server"    # Application name, used in the page title.
      - DOMAIN=${ROOT_DOMAIN}           # Domain name of this server, used for the displayed http clone URL in Gitea’s UI.
      - ROOT_URL=https://gitea.local.lan
      - LFS_START_SERVER=true           # Enables git-lfs support.
      - DISABLE_REGISTRATION=false      # Disable registration, after which only admin can create accounts for users.
      - REQUIRE_SIGNIN_VIEW=true        # Enable this to force users to log in to view any page.
    volumes:
      - ${VOLUME_DIR}/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nginx:
    image: nginx:1.27.0
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: 192.168.203.200
    cap_add:
      - NET_ADMIN
    volumes:
      - ${VOLUME_DIR}/nginx/config/conf.d/:/etc/nginx/conf.d
      - ${VOLUME_DIR}/nginx/config/proxy.conf:/etc/nginx/proxy.conf
      - ${VOLUME_DIR}/nginx/config/resolver.conf:/etc/nginx/resolver.conf
      - ${VOLUME_DIR}/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ${VOLUME_DIR}/nginx/config/ssl.conf:/etc/nginx/ssl.conf
      - ${VOLUME_DIR}/nginx/log/:/var/log/nginx
      - ${VOLUME_DIR}/ssl:/ssl:ro

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

### Database

MySQL/MariaDB
