### ISSUE TITLE
Actions step status display error when use composite action

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#31397]
### Description

The composite action `.gitea/actions/action-docker-build-push/action.yml`
```yml
name: 'Docker build and push'
description: 'Setup docker, build image and push'

inputs:
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false

runs:
  using: 'composite'
  steps:
    - run: "echo a: Set up QEMU"

    - run: |
        sleep 10
        echo 'sleep 10 end'

    - run: "echo b: Login to DockerHub"
      if: ${{ inputs.password != '' }}

    - run: |
        sleep 10
        echo 'c: Set up Docker BuildX'
```

The workflows file `.gitea/workflows/build-docker.yml`
```yml
name: Gitea Actions Demo
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build push
        uses: ./.gitea/actions/action-docker-build-push

      - run: echo The end
```

When the `echo 'a: Set up QEMU'` step run done, the  status is `success` although there are still two more steps ahead.
And then the `b: Login to DockerHub` step skip, the status is `skip`.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots
<img width="899" alt="image" src="https://github.com/go-gitea/gitea/assets/93666053/8b6e9f49-57cc-4b12-9d37-b5b7f9e2627c">
<img width="897" alt="image" src="https://github.com/go-gitea/gitea/assets/93666053/b150e213-b0bf-4218-bea2-8183820b815b">
<img width="898" alt="image" src="https://github.com/go-gitea/gitea/assets/93666053/f378c359-1b98-4281-8558-26f1b4993cdc">

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

**Comment by Sharaf5** [comment]
This is directly related to my issue https://gitea.com/gitea/act_runner/issues/553
but you discribed it better than me

**Comment by Sharaf5** [comment]
Then this is a reusable workflow <files-changed>
![Screenshot_20240621_235556](https://github.com/go-gitea/gitea/assets/36330265/6f8c3ed8-4d03-414d-a9de-1d9f3cbdbb11)

that is called like this
![Screenshot_20240621_234900](https://github.com/go-gitea/gitea/assets/36330265/5b9b6fff-a9d3-4649-9a0c-98831112f1c0)

and this is a composite action <build_sdist>
![Screenshot_20240621_235416](https://github.com/go-gitea/gitea/assets/36330265/a565c292-1e77-4584-a620-a5a7ed7e8d1a)

that is called like this
![Screenshot_20240621_235708](https://github.com/go-gitea/gitea/assets/36330265/4ee44b79-8185-4d70-9fcb-5642ef16c699)

Am I right ?

**Comment by Sharaf5** [comment]
@ChristopherHX Thanks alot for clarification
that realy helped me much

**Comment by yp05327** [comment]
I can not run the provided workflow unless I change the workflow:
from:
``` yaml
- run: echo 'a: Set up QEMU'

    - run: echo 'b: Login to DockerHub'
      if: ${{ inputs.password != '' }}

    - run: echo 'c: Set up Docker BuildX'
 ```
I got this error:
![image](https://github.com/go-gitea/gitea/assets/18380374/2e09eb89-7619-4cb3-8c6e-e67bdcbd89bf)

to:
``` yaml
    - run: 'echo a: Set up QEMU'

    - run: 'echo b: Login to DockerHub'
      if: ${{ inputs.password != '' }}

    - run: 'echo c: Set up Docker BuildX'
```
All done:
![image](https://github.com/go-gitea/gitea/assets/18380374/c0c130e3-0632-4cc5-a1a4-bd237cec08b2)
