### ISSUE TITLE
repos/pulls api take long time for large repos

### ISSUE THREAD

**Issue by GammaGames** [go-gitea/gitea#31492]
### Description

I'm working with renovate which makes calls to `api/v1/repos/org/repo/pulls?state=all&sort=recentupdate&page=[page]`. At pages 8+ the requests take a long time. Looking at htop it's because the git diff command is blocking. 
This is likely because my repo had a large restructure, loading the diffs on the gitea web app is also very slow.

```
/usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= diff --shortstat [left]...[right]
```

Is there any way to cache diffs or any config I can use to speed them up? My current workaround is to set the request timeout to 5 min in renovate

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/GammaGames/b1ae6715c8a66da638ee181ed6f93da1

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/7832163/8458e759-ff7b-44aa-a813-9408e4411ede)

### How are you running Gitea?

Docker compose:
```yaml
services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      USER_UID: 1001
      USER_GID: 1001
    restart: unless-stopped
    volumes:
      - ./gitea:/data
    ports:
      - 127.0.0.1:3001:3000
      - 127.0.0.1:2222:22
```

### Database

SQLite
