### ISSUE TITLE
Action time negative number

### ISSUE THREAD

**Issue by Yee36951** [go-gitea/gitea#31628]
### Description

Action time negative number

### Gitea Version

1.21.7 built with GNU Make 4.4.1, go1.21.7 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/d89546e3-f340-4724-a8da-ea7811c11b3a)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

Ubuntu

### How are you running Gitea?

```
docker-compose up
```
docker-compose.yml
```
version: "3"

networks:
  gitea:
    driver: bridge

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
        gitea:
            ipv4_address: 172.21.0.2
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
        gitea:
            ipv4_address: 172.21.0.3
    volumes:
      - ./mysql:/var/lib/mysql
```

### Database

MySQL/MariaDB
