### ISSUE TITLE
Project page columns' height to be set by contents rather than viewports

### ISSUE THREAD

**Issue by Simandara** [go-gitea/gitea#31666]
### Feature Description

Currently, the Project page contains columns whose height are defined by either a minimal value or a fraction of the available viewport.
<img width="423" alt="Capture d’écran 2024-07-21 à 00 58 18" src="https://github.com/user-attachments/assets/10e7b0e6-29d5-403b-a0f4-8b541b80fa0b">

If this looks pleasing on large screens — on smaller screens (using a Macbook 14"), browsing 30+ issues is not ideal:
- Its harder to have an overview of the kanban board
- Peeking or Seeking issues is more complexe
- Browsing issues require a lot of individual scroll actions 
- Scrollbars eat up each column available surface, especially for user on Windows 10 and below and some Linux Distros, some browsers or specific (accessibility) settings
- Searching issues (via browser text search — a.k.a `Ctrl+F`) doesn't correctly scroll down to the highlighted match (tested on Firefox)

<img width="1353" alt="Capture d’écran 2024-07-21 à 01 05 35" src="https://github.com/user-attachments/assets/c21ad871-512b-435e-a313-f2c300c36186">

---

I propose to instead set the Project board to take as much space a needed by its content:
- Can make the webpage veeeeeeeery long
- 1 global scrollbar
- More effective peeking for issues
- Scroll to the match when text searching
- Access to the page footer is longer
- 1 line of code to implement?
<img width="1518" alt="Capture d’écran 2024-07-21 à 01 17 00" src="https://github.com/user-attachments/assets/c54a5514-0038-4f82-8fa0-f0f72635a870">

---

It's easy to test an implementation by deleting the `height: calc(100vh - 450px);` rule from `.project-column` selector in `index.css §9711`:

```CSS
.project-column {
  background-color:var(--color-project-board-bg)!important;
  border:1px solid var(--color-secondary)!important;
  margin:0 .5rem!important;
  padding:.5rem!important;
  width:320px;
  height:fit-content;
  /*height:calc(100vh - 450px);*/
  min-height:60vh;
  flex:0 0 auto;
  overflow:visible;
  display:flex;
  flex-direction:column;
  cursor:default
}
```

What do you think? Could that help make the Kanban board easier and quicker to use?

### Screenshots

![Jira board 2024](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwac-cdn.atlassian.com%2Fdam%2Fjcr%3A22f4ff3a-3f0a-4a23-b4c1-d74bd63dc724%2Fhow-kanban-works.png%3FcdnVersion%3Dht&f=1&nofb=1&ipt=0cd8effba8b61a986b03aff98db43d7b84037ab06a9254ded36105683f271ea1&ipo=images)
![Jira board 2020](https://merehead.com/blog/wp-content/uploads/scram-jira.jpg)
![Github](https://github.githubassets.com/assets/memex-view-board-cebeb9984e53.png)

**Comment by SimonPistache** [comment]
I realised there are room for improvement in my suggestion…

The issue is the columns are uneven:
<img width="1296" alt="Capture d’écran 2024-07-21 à 13 06 44" src="https://github.com/user-attachments/assets/1a8f8919-ede0-4796-9aca-b10697fb1317">

---
As the columns are in a flexbox container, it's easy to set them to have all the same size of the biggest one:
<img width="1314" alt="Capture d’écran 2024-07-21 à 13 14 12" src="https://github.com/user-attachments/assets/8a19a033-7739-4a1a-ba38-6e661023ab33">


```CSS
.board {
  /* […] */
  align-items: stretch;
}

.project-column {
  /* […] */
  height: initial; /* Or remove the attribute entirely */
}
```
