### ISSUE TITLE
Using helm chart, unable to deploy with oauth pre-configured

### ISSUE THREAD

**Issue by prolixalias** [go-gitea/gitea#31915]
### Description

Using `helm:` v3.15.3, `gitea chart:` v10.4.0
The values.yaml file contains:
  
```yaml
---
gitea:
  oauth:
    - name: 'gitea-oidc'
      existingSecret: gitea-oidc
      autoDiscoverUrl: 'https://git.fervid.us/.well-known/openid-configuration'
```

Resulting log in configure-gitea container:

```
Wait for redis to become avialable...
gitea-redis-cluster-headless.gitea.svc.cluster.local (10.42.0.79:6379) open
Admin account 'gitea_admin' already exist. Running update to sync password...
gitea_admin's password has been successfully updated!
...password sync done.
no ldap configuration... skipping.
No oauth configuration found with name 'gitea-oidc'. Installing it now...
Command error: auth source is not activated
```

Deployment stops there. I wasn't able to locate any related issues or locate docs on the topic.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.46.0

### Operating System

k8s

### How are you running Gitea?

Simple helm deployment. existing secret for oauth key/secret.

### Database

None
