### ISSUE TITLE
Swagger APIs that behave differently than intended

### ISSUE THREAD

**Issue by phi-friday** [go-gitea/gitea#31927]
### Description

According to https://docs.gitea.com/development/api-usage, 
when using the `Authorization` header, I should use the following
`Authorization: token ...`

However, when I run `curl` in Swagger, the command is executed like this
```bash
curl -X 'POST' \
  'https://<some url>/api/v1/repos/<owner>/<repo>/mirror-sync' \
  -H 'accept: application/json' \
  -H 'Authorization: <api key>' \
  -d ''
```

![스크린샷 2024-08-27 오전 8 47 06](https://github.com/user-attachments/assets/b41b84a0-6c4e-480d-a2e0-d9885a39d470)

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

```yaml
services:
  repository:
    container_name: git-server
    image: gitea/gitea:1.22.1
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${GITEA_SSH_PORT}:22"
    networks:
      - public-network
    command:
      - sh
      - -c
      - |
        sh /init.sh
        /bin/s6-svscan /etc/s6
    volumes:
      - git-server:/data
      - type: bind
        source: "/home/${GITEA_SSH_USER_NAME}/.ssh"
        target: "/data/git/.ssh"
        read_only: false
      - type: bind
        source: "./app.ini.default"
        target: "${GITEA_APP_DEFAULT_PATH}"
        read_only: true
      - type: bind
        source: "./init.sh"
        target: "/init.sh"
        read_only: true
    extra_hosts:
      - ${COMMON_PROXY_LOCAL_HOST}:host-gateway
      - ${COMMON_ADDITIONAL_PROXY_LOCAL_HOST}:host-gateway
    logging:
      options:
        max-size: 10m
        max-file: 1
```

### Database

PostgreSQL
