### ISSUE TITLE
An authentication error occurs when pushing an image to the `container registry`.

### ISSUE THREAD

**Issue by phi-friday** [go-gitea/gitea#31932]
### Description

I logged into the `container registry` successfully.
And pushed the image.
Some layers are pushed and I get an authentication error.
I checked the `gitea` web UI and saw that the package has not been uploaded.
But it was entered in `package` in `db`.

```shell
Last login: Tue Aug 27 14:08:47 on ttys074
❯ docker login <custom domain>:<custom port>
Authenticating with existing credentials...
Stored credentials invalid or expired
Username (***): ***
Password:
Login Succeeded
❯ docker tag <custom image>:latest <custom domain>:<custom port>/***/docker_image_test:latest
❯ docker push <custom domain>:<custom port>/***/docker_image_test:latest
The push refers to repository [<custom domain>:<custom port>/***/docker_image_test]
b3305702c05b: Pushed
5f70bf18a086: Pushed
24a6b2790c33: Pushed
3e67cd6b6345: Preparing
9a1ea02ff49c: Pushed
5a9bef041d8a: Pushed
883d4812884a: Pushed
76c46cdfc5bc: Pushed
7bb1110f7687: Pushed
410feee14859: Pushed
0576082a51ac: Pushed
91bbafc72e16: Pushed
07d2ee3f5712: Pushed
unauthorized: authentication required
```

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

## permission
![스크린샷 2024-08-28 오후 1 42 11](https://github.com/user-attachments/assets/e1f912b8-5a8d-4801-8b1f-e199fddbe327)

## db
![스크린샷 2024-08-28 오후 1 41 27](https://github.com/user-attachments/assets/8deb8d51-d3f5-403c-a1e5-fa01e2521047)

### How are you running Gitea?

```yaml
services:
  repository:
    container_name: git-server
    image: gitea/gitea:1.22.1
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${GITEA_SSH_PORT}:22"
    networks:
      - public-network
    command:
      - sh
      - -c
      - |
        sh /init.sh
        /bin/s6-svscan /etc/s6
    environment:
      - TZ=Asia/Seoul
    volumes:
      - git-server:/data
      - type: bind
        source: "/home/${GITEA_SSH_USER_NAME}/.ssh"
        target: "/data/git/.ssh"
        read_only: false
      - type: bind
        source: "./app.ini.default"
        target: "${GITEA_APP_DEFAULT_PATH}"
        read_only: true
      - type: bind
        source: "./init.sh"
        target: "/init.sh"
        read_only: true
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - ${COMMON_PROXY_LOCAL_HOST}:host-gateway
      - ${COMMON_ADDITIONAL_PROXY_LOCAL_HOST}:host-gateway
    logging:
      options:
        max-size: 10m
        max-file: 1
```

### Database

PostgreSQL
