### ISSUE TITLE
After updating from (some old version) to latest I face errors

### ISSUE THREAD

**Issue by bvn13** [go-gitea/gitea#32002]
### Description

This error:

```
...er/issues/indexer.go:226:PopulateIssueIndexer() [E] SearchRepositoryByName: Count: pq: could not read block 0 in file "base/16384/55475": read only 0 of 8192 bytes
```

What it is?

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker-compose

```
networks:
  gitea:
    external: true

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - "8080:3000"
      - "2221:22"
    expose:
      - 3000
    depends_on:
      - db
  db:
     image: postgres:13
     restart: always
     environment:
       - POSTGRES_USER=gitea
       - POSTGRES_PASSWORD=gitea
       - POSTGRES_DB=gitea
     networks:
       - gitea
     volumes:
       - ./postgres:/var/lib/postgresql/data

```

### Database

PostgreSQL
