### ISSUE TITLE
Sometimes multiple PR/PRMERGE tied workflows are run, despite paths and triggering conditions not overlapping/fullfiled

### ISSUE THREAD

**Issue by skt-mmisuth** [go-gitea/gitea#32031]
### Description

We are experiencing an issue where mutiple workflows fire unexpectedly. We observed `act_runner` logs a bit, but it seems that workflow dispatching is being handled in gitea server itself.

We need advice on how to approach this problem. We can provide sanitized logs if needed, but I would like to avoid that, due to sensitive nature of the repos being handled.

I am creating this issue in case other people are having similar problem.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/be191a8a-eb15-4636-a1a8-e8ded3ffb38e)

Both of these workflows have paths sections mapping different parts of the monorepo, yet they are being triggered:

```
...
on: 
  push:
    branches: ['main']
    paths: 
      - '.gitea/workflows/...' # self referenting name to catch its own updates
      - 'terraform/**'
...
```

```
...
on: 
  push:
    branches: ['main']
    paths: 
      - '.gitea/workflows/...' # self referenting name to catch its own updates
      - 'ansible/**'
...
```

According to our understanting, only the workflow, that matches modified paths should be triggered, yet sometimes, multiple workflows fire ... how is that possible? 

Are we misunderstading something?

### Git Version

2.39.3

### Operating System

OracleLinux 8.9

### How are you running Gitea?

Gitea is being run as system level systemd service (official one provided by gitea project and installed using official documentation) running under "git-dedicated" user.

It was installed onto the node directly using official documentation.

### Database

PostgreSQL
