### ISSUE TITLE
Env RUNNER_TOOL_CACHE not passed to runner

### ISSUE THREAD

**Issue by danielcrabtree** [go-gitea/gitea#32055]
### Description

I'm trying to enable Gitea Actions Cache as per https://about.gitea.com/resources/tutorials/enable-gitea-actions-cache-to-accelerate-cicd

I've set the env variable as follows:
```
jobs:
  build:
    env:
      RUNNER_TOOL_CACHE: /toolcache
```

However, in the set up job step, the ENV variable is unchanged:
```
ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache ...
```

The same or a similar issue was reported in #31396 but was closed without resolution due to non-response.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.45.2

### Operating System

AlmaLinux 9.4

### How are you running Gitea?

Running docker image: gitea/gitea:1.22.2

### Database

SQLite

**Comment by yp05327** [comment]
@lng2020

**Comment by lng2020** [comment]
So did the cache hit? I can't recall the details but I think it may be the display issue. It says `/opt/hostedtoolcache` but in real execution, it's `/toolcache`.

**Comment by danielcrabtree** [comment]
No, it isn't hitting the cache. (I only started looking into it because setting RUNNER_TOOL_CACHE didn't make any difference to the package restore time, which is currently 50 seconds.)

**Comment by lng2020** [comment]
According to https://github.com/nektos/act/issues/1987 and https://github.com/nektos/act/pull/1494, you don't need to set the `RUNNER_TOOL_CACHE` env to let the tool cache work now. It was needed when I wrote that article but then they fixed the issue. So can you try it without setting the `RUNNER_TOOL_CACHE`?

**Comment by danielcrabtree** [comment]
I've removed `RUNNER_TOOL_CACHE`. 

I've checked the runner server, the runner container, and the dynamic run container, and none contain `/toolcache` or `/opt/hostedtoolcache`. Where should I check to see what is being cached if anything?

**Comment by lng2020** [comment]
Something like this? I think time differences are noticeable.
![image](https://github.com/user-attachments/assets/26e58cac-f08b-47f5-9d25-04cf8a8b5eba)

**Comment by danielcrabtree** [comment]
Yes, that is what I was expecting to see. But there is no change at all on 2nd run, it takes just as long as the 1st, so I assume cache is not working.

**Comment by lng2020** [comment]
May I see the workflow sample to reproduce?

**Comment by danielcrabtree** [comment]
Sure, this is an abridged version. Restore packages is the step where I would have thought caching would help.

```
name: "Build Process"

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build & Test"
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4  

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore packages
        run: dotnet restore ./Project.sln
```

I don't actually know how the cache works, I'm assuming it acts as a proxy to intercept web requests.
