### ISSUE TITLE
ActRuner hungs up VPS server

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32140]
### Description

So the problem is I run this actions script

```yaml
name: test backend

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: root

    services:
        mysql:
            image: mysql:latest
            ports:
                - 3306/tcp
            env:
                MYSQL_DATABASE: laravel
                MYSQL_ROOT_PASSWORD: root
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 8.3

      #- run: sudo /etc/init.d/mysql start

      #- run: cp .env.ci .env
      - run: composer install
      - run: php artisan key:generate
      - run: php artisan test
```

It creates tmp containers but then server stops respongind, ssh laggs, docker ps taking too long to print etc. I have to reboot the server to later gind out this error in gitea actions logs

![image](https://github.com/user-attachments/assets/7a71660f-7644-47c3-8e50-0218a2537751)

What could be the broblem?

### Gitea Version

 1.23.0+dev-526-g3269b04d61

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

docker

### Database

PostgreSQL
