### ISSUE TITLE
Act runner doesn't start second job

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#32153]
### Description

I have act runner with configuration for `capacity = 1` (before it was 1 and no difference.

In gitea, I have this workflow
```yaml
name: test

on: [ push ]

jobs:
    backend:
        if: ${{ always() }}

        runs-on: ubuntu-latest
        env:
            DB_CONNECTION: mysql
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root

        services:
            mysql:
                image: mysql:latest
                ports:
                    - 3306/tcp
                env:
                    MYSQL_DATABASE: laravel
                    MYSQL_ROOT_PASSWORD: root
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3

            -   run: cp .env.ci .env
            -   run: composer install
            #- run: php artisan migrate
            -   run: php artisan key:generate
            -   run: php artisan test

    frontend:
        if: ${{ always() }}

        runs-on: node:18-bullseye-slim
        env:
            DEBIAN_FRONTEND: "noninteractive"

        steps:
            -   uses: actions/checkout@v2

            -   run: npm install
            -   run: npm run gulp-prod
```

problem is, job `frontend` never starts, it's always shows `waiting` in gitea. What could be the problem?
![image](https://github.com/user-attachments/assets/e3466fa8-a479-4bf3-9593-8596e4ea8756)

### Gitea Version

1.23.0+dev-531-g99d0510cb6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker both gitea and gitea act runner

### Database

PostgreSQL
