### ISSUE TITLE
Unable to upgrade Gitea from version 1.12.4 using docker on Raspberry Pi 3B

### ISSUE THREAD

**Issue by gcoter** [go-gitea/gitea#32202]
### Description

Hello there!

I've been running a local Gitea instance on a Raspberry Pi 3B for 4 years now. However, I have to admit that I did not take the time in the past to regularly upgrade it :sweat_smile: 

Today I have tried to upgrade from the current version (1.12.4) to more recent versions but I encountered various issues. This table summarizes the versions I tried and the errors I got:

| Version | Error |
| ---------- | ------- |
| 1.22.2 | Command not found: /usr/bin/entrypoint |
| 1.16.0 | Command not found: /usr/bin/entrypoint |
| 1.15.11 | Command not found: /usr/bin/entrypoint |
| 1.14.7 | Command not found: /usr/bin/entrypoint |
| 1.13.7 | Infinite warnings like "s6-supervise openssh: warning: can't happen: timeout while the service is up!" |

When I got the command not found error, I tried to decrease the version. I was thinking that I might be missing a migration step which prevents breaking changes. Version 1.13 seems to be the only one that will at least run something. But then I just get this infinite stream of warnings.

I tried to replicate the steps in this comment (found in an older issue): https://github.com/go-gitea/gitea/issues/16038#issuecomment-954920563

That did not solve the problem. And in fact, I was not able to reproduce the last step (using docker image gitea/gitea:1.15.6-rootless) because the gitea images do not exist for my hardware. Instead, I am using this repository: https://hub.docker.com/r/patrickthedev/gitea-rpi

I don't really know what to do now, I would appreciate any suggestion or help :slightly_smiling_face: 

### Gitea Version

1.12.4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Raspbian GNU/Linux 9 (stretch)

### How are you running Gitea?

I'm using docker, more precisely the images from https://hub.docker.com/r/patrickthedev/gitea-rpi.

Here is my docker compose file for reference:
```
version: "2"

volumes:
  data:
    driver: local

services:
  server:
    image: patrickthedev/gitea-rpi:1.12.4
    mem_limit: 150m
    memswap_limit: 150m
    hostname: <HOSTNAME>
    environment:
      - RUN_MODE=prod
      - SSH_DOMAIN=<HOSTNAME>
      - SSH_PORT=<SSH_PORT>
      - SSH_LISTEN_PORT=22
    networks:
      - web
    ports:
      - "9090:3000"
      - "<SSH_PORT>:22"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:<HOSTNAME>
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.port=3000
      - traefik.docker.network=web
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  web:
    external: true
```

### Database

None
