### ISSUE TITLE
Gitea Action didn't use last commit when action is triggered by schdule

### ISSUE THREAD

**Issue by ChaojuWang** [go-gitea/gitea#32219]
### Description

I set up a workflow to exec routine action every day but the action uses outdated commit when checkout the code.
![image](https://github.com/user-attachments/assets/0ce9915b-5d80-4ec5-ab67-8e7ba275f49d)
![image](https://github.com/user-attachments/assets/7fe7e172-fb98-4882-8649-7db1c75c5168)
![image](https://github.com/user-attachments/assets/a74672f2-c875-4ef6-b878-ca97ffa9f34a)
It seems that the action checkout the 2rd commit during running.

here is part of my workflow
```
name: XXX

on:
  schedule: # execute every 24 hours
    - cron: "35 6 * * *"
...
 steps:
    - name: XXX
      uses: actions/checkout@v4
      with:
        path: xxx
...
```

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.45.2

### Operating System

Docker 27.0.3 in Ubuntu 22.04.4 LTS

### How are you running Gitea?

Docker 27.0.3 in Ubuntu 22.04.4 LTS
start both Gitea and runner  by docker-compose 

### Database

SQLite
