### ISSUE TITLE
[Actions]: OCI runtime exec failed: exec failed: unable to start container process: exec: "node": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by noppelmax** [go-gitea/gitea#32346]
### Description

Hey,

I got  an error:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "node": executable file not found in $PATH: unknown
```
at the "Check out repository code" stage of the example workflow yml file once I added `container: blang/latex:ctanfull` after the "runs-on" item. Here is my workflow file:

```yml
name: Build PDF
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  buildpdf:
    runs-on: ubuntu-latest
    container: blang/latex:ctanfull
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

I guess that is an error on the runner side. Here is my docker-compose.yml file for the runner
```yml
version: "3.8"
services:
  runner:
    image: gitea/act_runner:latest
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://url"
      GITEA_RUNNER_REGISTRATION_TOKEN: "token"
      GITEA_RUNNER_NAME: "dockerlaptop"   
      GITEA_RUNNER_LABELS: "ubuntu-22.04:docker://node:16-bullseye"
    volumes:
      - ./config.yaml:/config.yaml
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
```

The config file is the example file without any changes. Please let me know which information would help you to identify the bug.

### Gitea Version

Version: 1.21.8

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/0266e7b6-2477-4d0b-b779-2feca1413eb3)

### Git Version

I don't know

### Operating System

I don't know

### How are you running Gitea?

I don't know

### Database

None
