### ISSUE TITLE
Report invalid workflow file in Pull Request

### ISSUE THREAD

**Issue by KiritaniAyaka** [go-gitea/gitea#32364]
### Feature Description

I have searched related issues and find them: #23275, #23404 

It's a useful feature, but it seems hasn't been introduced into the Pull Request. When a workflow file in a PR is invalid, it does nothing, and there's no any feedback on the Web UI.

Display feedback makes sense in many scenarios that modify the workflow file in a PR.

There's a simple invalid workflow for testing:

```yml
name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Invalid step
      run: |
      pwd # Add two spaces at the start of line to fix it
```

I tested the same example on GitHub, I found it has a different behavior to Gitea. GitHub will create an entry in "Actions" tab and mark it as failed, the reason can be found on the summary page, but Gitea will not create any entry for invalid workflows.

GitHub:

![image](https://github.com/user-attachments/assets/98700610-ce79-42a1-9922-078aa35e4dde)

I think there's two way to give feedback to users
- Create an entry for every workflow even it is invalid, like GitHub
- Add a failed badge beside commit message and put detail messages on hover bubbles. Just like a failed workflow:

![image](https://github.com/user-attachments/assets/596b3a94-8f0e-4436-a14a-1dbfb6d1b2a3)
