### ISSUE TITLE
Password Reset email

### ISSUE THREAD

**Issue by EternalRat** [go-gitea/gitea#32408]
### Description

I've setup the mailer service and the test is working fine as well as the mail confirmation when an user wants to registry.
But when I want to check if I can have the email to recover my password, even though it tells me that the mail will be send shortly (within 3h), I never receive it nor get any other message.
The mail server I'm using is mailcow and everything else is working fine and as far as I know (didn't try everything yet) only the password recover email isn't sent.

Everything's setup as VM using proxmox and telnet has been setup in order for everything to work and other things, but I don't think there's something to do with the fact that only that option isn't working.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I'm using Docker, here's the docker compose : 

```yml
services:
  server:
    image: gitea/gitea:1.22.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=x:3306
      - GITEA__database__NAME=x
      - GITEA__database__USER=x
      - GITEA__database__PASSWD=x
    restart: always
    networks:
      - web
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22104:22"
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`x.x.x`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.tcp.routers.websecure.tls.passthrough=true
      - traefik.http.routers.gitea.tls.certresolver=letsencryptresolver
      - traefik.http.routers.gitea.service=gitea_svc
      - traefik.http.services.gitea_svc.loadbalancer.server.port=3000
      - traefik.docker.network=web
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=x
      - MYSQL_USER=x
      - MYSQL_PASSWORD=x
      - MYSQL_DATABASE=x
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

  gitea-runner1:
    restart: unless-stopped
    volumes:
      - ./data-runner1:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITEA_INSTANCE_URL: http://server:3000/
      GITEA_RUNNER_REGISTRATION_TOKEN: x
      GITEA_RUNNER_NAME: Dockge1
      GITEA_RUNNER_LABELS: ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest,ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04,ubuntu-20.04:docker://ghcr.io/catthehacker/ubuntu:act-20.04
    image: gitea/act_runner:latest
    networks:
      - web
      - gitea

  gitea-runner2:
    restart: unless-stopped
    volumes:
      - ./data-runner2:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITEA_INSTANCE_URL: http://server:3000/
      GITEA_RUNNER_REGISTRATION_TOKEN: x
      GITEA_RUNNER_NAME: Dockge2
      GITEA_RUNNER_LABELS: ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest,ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04,ubuntu-20.04:docker://ghcr.io/catthehacker/ubuntu:act-20.04
    image: gitea/act_runner:latest
    networks:
      - web
      - gitea

  gitea-runner3:
    restart: unless-stopped
    volumes:
      - ./data-runner3:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITEA_INSTANCE_URL: http://server:3000/
      GITEA_RUNNER_REGISTRATION_TOKEN: x
      GITEA_RUNNER_NAME: Dockge3
      GITEA_RUNNER_LABELS: ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest,ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04,ubuntu-20.04:docker://ghcr.io/catthehacker/ubuntu:act-20.04
    image: gitea/act_runner:latest
    networks:
      - web
      - gitea
    
networks:
  web:
    name: web
    external: true
  gitea:
    external: false
```

### Database

MySQL/MariaDB
