### ISSUE TITLE
actions/checkout@v4 - /api/v1/repos/administrator/runner1/tarball/master - Page not found 404

### ISSUE THREAD

**Issue by virtualdreams** [go-gitea/gitea#32481]
### Description

The action `actions/checkout@v4` won't work if git not exists in docker container. The action tries to download from an invalid url. The url is also not available in /api/swagger.

Workflow

```yml
name: Runner1 Test Checkout
run-name: Runner1 Test Checkout
on: [push]

jobs:
  checkout:
    name: checkout
    runs-on: alpine
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
```

Output of act_runner in gitea
```
Deleting the contents of '/workspace/administrator/runner1'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
404 page not found
```
Error in log from gitea
```
GET /api/v1/repos/administrator/runner1/tarball/master for 172.19.0.2:58436, 404 Not Found in 5.7ms @ http/server.go:2188(GlobalNotFound)
```

If i try to download manually

```
curl http://gitea.example.org:3000/api/v1/repos/administrator/runner1/tarball/master
404 page not found
```

Repository is public.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

On host directly.

### Database

MySQL/MariaDB

**Comment by vcicmanec** [comment]
Facing the same issue, seems to be related to this
https://github.com/go-gitea/gitea/issues/29654

**Comment by lunny** [comment]
Gitea doesn't support  the API endpoint `/api/v1/repos/<username>/<reponame>/tarball/<branch_name>` yet.

**Comment by Tockra** [comment]
Okay, I am a little bit confused. 
I ran into a similar problem. After reading some guides in web, I though I just have to run the checkout action and the git action automatically selects the commit, which triggered the pipeline run:
```
jobs:
  build-frontend-nextjs:
    runs-on: ubuntu-latest
    container: node:22-bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend (NextJS) and create Artifact
         uses: ./.github/actions/build-nextjs
         with:
           upload-artifact: true
```

But now I'm trying to fix the 404 Not found issue since an hour. 
Is there a workaround? What is the issue? I don't understand it? Is the action not compatible with gitea ?
