### ISSUE TITLE
Action not triggered when commit message is too long

### ISSUE THREAD

**Issue by tovoro** [go-gitea/gitea#32489]
### Description

As we currently cannot trigger a Gitea Action via a UI button we do this via a Issue comment as a workaround.

When the last commit message is too long (the one which triggered the error was 230 characters), the issue-comment does not trigger the action and the following error is displayed: 

`...s/notifier_helper.go:347:handleWorkflows() [E] InsertRun: Error 1406 (22001): Data too long for column 'title' at row 1`

`gitea docter` shows no errors, its running on a mysql db. 

Thats the beginning of the action.yaml 

```
name: Angular Build

**on:
  issue_comment:
    types: [created]**

jobs:
  build:
    if: **gitea.event.issue.number == 16**
    name:DEV-Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
```

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.30.2

### Operating System

Debian 11

### How are you running Gitea?

Binary Release, running from systemd.

### Database

MySQL/MariaDB
