### ISSUE TITLE
Render failed, Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joshes** [go-gitea/gitea#32524]
### Description

I am currently receiving the following error.

```
An error occurred:

Render failed, failed to render template: user/dashboard/dashboard, error: template error: builtin(bindata):user/dashboard/feeds:20:45 : executing "user/dashboard/feeds" at <.GetRepoLink>: error calling GetRepoLink: runtime error: invalid memory address or nil pointer dereference
----------------------------------------------------------------------
							{{ctx.Locale.Tr "action.commit_repo" (.GetRepoLink ctx) (.GetRefLink ctx) .GetBranch (.ShortRepoPath ctx)}}
							                                      ^
----------------------------------------------------------------------
```

Prior to seeing this I was deleting repositories from out of an org so I could delete the org itself. This was all done via the Site Administration UI.

It seems stuck in this behaviour now.

### Gitea Version

 1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/joshes/5307eb7336c2cf47fa2d42c27e3e7850

### Screenshots

<img width="2052" alt="Screenshot 2024-11-15 at 8 03 01 AM" src="https://github.com/user-attachments/assets/db15af33-9d43-40a3-8b9d-b48ee6d70b7f">

### Git Version

2.45.2

### Operating System

OSX Sonoma

### How are you running Gitea?

Docker compose

```yaml
# docker-compose.yml
services:
  gitea:
    build:
      dockerfile: Dockerfile
      context: dockerfiles/gitea
    ports:
      - "2222:2222"
      - "3000:3000"
    restart: always
    entrypoint:
      - /usr/bin/dumb-init
      - --
      - /usr/local/bin/docker-entrypoint.sh
    volumes:
      - ./.data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

```
# Dockerfile
FROM debian:bookworm AS tmp
RUN apt-get update && \
    apt-get install -y openssl && \
    openssl rand -hex 8 > /tmp/password

FROM gitea/gitea:1.22-rootless

USER git

# Configure well-known admin user
ARG ADMIN_USER="gitea"
ARG ADMIN_MAIL="$ADMIN_USER@localhost.com"

# Provides a headless installation
ENV GITEA__security__INSTALL_LOCK="true"

WORKDIR "$HOME/.local/bin"

ENV PATH="$HOME/.local/bin/:$PATH"

# - Install wait-for-it script
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/refs/heads/master/wait-for-it.sh && \
    chmod +x wait-for-it.sh

WORKDIR "$HOME"

COPY --from=tmp --chown=git /tmp /tmp

# - Start the server
# - Wait for it to become ready
# - Create a well-known admin user and token
# - Gracefully shut-down and wait for termination
RUN nohup bash -c "/usr/local/bin/docker-entrypoint.sh &" && \
    wait-for-it.sh 0.0.0.0:3000 -t 30 -- && \
    gitea admin user create --admin --username "$ADMIN_USER" --password "$(cat /tmp/password)" --email "$ADMIN_MAIL" && \
    gitea admin user generate-access-token --username "$ADMIN_USER" --token-name "default-token" --scopes all | awk -F': ' '{print $2}' > /tmp/token && \
    gitea manager shutdown && \
    while pgrep -o gitea > /dev/null; do sleep 1; done
```

**_Note this is just for integration testing, do not use this image for production_** 

### Database

SQLite
