### ISSUE TITLE
Gitea root->rootless migration 

### ISSUE THREAD

**Issue by phoedos** [go-gitea/gitea#32829]
### Description

Please guide is it possible to make root->rootless docker image migration? 
have a typical installation of gitea, like this: 
```
services: 
  gitea:
    image: gitea/gitea:1.22.5
    restart: unless-stopped
    environment:
     ...
    volumes:
      - ./gitea_data:/data
    postges: 
...
```
if I change image to gitea/gitea:1.22.5-rootless and run the same compose, Gitea will show me a configuration screen (like on init setup) and out the error "existing gitea installation in present in DB" 

Rootless container is more secure, Is it possible somehow to make a migration? 

### Gitea Version

1.22.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

PostgreSQL
