### ISSUE TITLE
Gitea Actions use service public image and container private image username password doesnt work

### ISSUE THREAD

**Issue by rchekhina** [go-gitea/gitea#32963]
### Description

HI,

I have a strange behavior when I use service and container on the same jobs. It seems that if you use service with a public docker image without username and password and a service with a private image and username password the pull of the image doesnt work with 401 error.
Is like it take the same credential of the service.
this following job failed:
```
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
    container:
        image: mydocker.org/php/8.2:fpm-composer2
        credentials:
           username: ${{  vars.REGISTRY_USER }}
           password: ${{  secrets.REGISTRY_PASSWD }}
```
If I remove the service like this the job works:
```
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
        image: mydocker.org/php/8.2:fpm-composer2
        credentials:
           username: ${{  vars.REGISTRY_USER }}
           password: ${{  secrets.REGISTRY_PASSWD }}
```
the workaround that I found was to pass the same credentials for the public and private image like following:

```
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        credentials:
           username: ${{  vars.REGISTRY_USER }}
           password: ${{  secrets.REGISTRY_PASSWD }}
    container:
        image: mydocker.org/php/8.2:fpm-composer2
        credentials:
           username: ${{  vars.REGISTRY_USER }}
           password: ${{  secrets.REGISTRY_PASSWD }}
```

Best regards.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

running gitea on k8s install with helm

### Database

PostgreSQL
