### ISSUE TITLE
Gitea Actions Print `gitea.actor` Value Which Are Different from GitHub Action in Special Circumstances

### ISSUE THREAD

**Issue by dangjinghao** [go-gitea/gitea#33022]
### Description

when a cron workflow is triggered, the `{{ gitea.actor }}` whould be replaced with `gitea-actions` but github action would print the username who set the trigger.

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![gitea](https://github.com/user-attachments/assets/86a030ff-1e92-4684-a1aa-99e8e2341461)
![github](https://github.com/user-attachments/assets/20372ad2-c192-4bbd-bed8-d9c5a1dfb4e6)

### How are you running Gitea?

workflow configuration
```yaml
name: cron
on:
  schedule:
    - cron: "*/2 * * * *"
env:
  TZ: Asia/Shanghai

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo ${{ github.actor }}        
```

gitea:1.22.6, running in docker container, `image: gitea/gitea:latest`
gitea-runner version: v0.2.11, running in docker container, `image: gitea/act_runner:latest`

### Database

None
