### ISSUE TITLE
workflow_dispatch inputs without a description end up without any label/name in the UI

### ISSUE THREAD

**Issue by ChristopherHX** [go-gitea/gitea#33099]
### Description

Checkboxes and Comboboxes may not show any label if description is not set

```yaml
on:
  workflow_dispatch:
    inputs:
      test-a:
        type: boolean
      test-b:
        type: choice
        options:
        - a
        - b
        - c
        - d
      test-c:
        description: One with description!
        type: boolean
jobs:
  _:
    runs-on: windows-latest
    steps:
    - run: ${{ tojson(inputs) }}
      shell: cat {0}
```

### Gitea Version

1.23-rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="1511" alt="Bildschirmfoto 2025-01-03 um 23 35 21" src="https://github.com/user-attachments/assets/017cc07c-c12a-4bf8-b1fe-d2709dec220a" />

### Operating System

linux

### How are you running Gitea?

build myself / demo site

### Database

SQLite
