### ISSUE TITLE
token has invalid claims: token is missing required claim: aud claim is required, token is missing required claim: iss claim is required

### ISSUE THREAD

**Issue by droplet-js** [go-gitea/gitea#33093]
### Description

I want to use gitea as oidc provider. Combined with traefik and traefik oidc plugin, to provide user authorization function for whoami service.

----
原文：我想用 gitea 作为 oidc 提供商。结合 traefik 和 traefik oidc 插件，给 whoami 服务提供用户授权功能。

traefik + traefik oidc plugin + gitea + whoami

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

CentOS 7.9

### How are you running Gitea?

docker-compose.yaml
```yaml
services:

  traefik:
    container_name: traefik
    image: ghcr.io/traefik/traefik:v3.2.3
    restart: unless-stopped
    hostname: traefik
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/etc/traefik/acme
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=false"
      - "--log.level=INFO"
      - "--log.format=common"
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json"
      - "--certificatesresolvers.letsencrypt.acme.keyType=EC384"
      - "--certificatesresolvers.letsencrypt.acme.preferredChain=ISRG Root X1"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Middleware traefikoidcauth
      - "--experimental.plugins.traefikoidcauth.modulename=github.com/sevensolutions/traefik-oidc-auth"
      - "--experimental.plugins.traefikoidcauth.version=v0.4.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      # Middlewares
      - "traefik.http.routers.traefik.middlewares=gzip@docker"

  gitea:
    container_name: gitea
    image: gitea/gitea:1.22.6
    restart: unless-stopped
    hostname: gitea
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../dev-ops-repo/gitea:/data
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - APP_NAME=Gitea
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://gitea.${SERVER_DOMAIN:-localhost}/
      - DISABLE_SSH=true
      - DB_TYPE=sqlite3
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"

  whoami:
    container_name: whoami
    image: ghcr.io/traefik/whoami:v1.10.3
    restart: unless-stopped
    hostname: whoami
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      # Middleware: oidc plugin + gitea
      - "traefik.http.middlewares.whoamiauth.plugin.traefikoidcauth.logLevel=DEBUG"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikoidcauth.provider.url=https://gitea.${SERVER_DOMAIN:-localhost}"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikoidcauth.provider.usepkce=true"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikoidcauth.provider.clientid=${OIDC_GITEA_CLIENT_ID?err}"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikoidcauth.provider.clientsecret=${OIDC_GITEA_CLIENT_SECRET?err}"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikoidcauth.provider.scopes=openid,profile,email,groups"
      # Middlewares
      - "traefik.http.routers.whoami.middlewares=whoamiauth"

volumes:
  traefik_data:
  dex_data:
```

app.ini
```ini
APP_NAME = Gitea
RUN_MODE = prod
RUN_USER = git
WORK_PATH = /data/gitea

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH = /data/gitea
DOMAIN = gitea.yourdomain.com
SSH_DOMAIN = gitea.yourdomain.com
HTTP_PORT = 3000
ROOT_URL = https://gitea.yourdomain.com/
DISABLE_SSH = true
SSH_PORT = 22
SSH_LISTEN_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = xxxxxxxxxxxxxxxxxxxxx
OFFLINE_MODE = false

[database]
PATH = /data/gitea/gitea.db
DB_TYPE = sqlite3
HOST = localhost:3306
NAME = gitea
USER = root
PASSWD = 
LOG_SQL = false
SCHEMA = 
SSL_MODE = disable

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER = file

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars

[attachment]
PATH = /data/gitea/attachments

[log]
MODE = console
LEVEL = info
ROOT_PATH = /data/gitea/log

[security]
INSTALL_LOCK = true
SECRET_KEY = 
REVERSE_PROXY_LIMIT = 1
REVERSE_PROXY_TRUSTED_PROXIES = *
INTERNAL_TOKEN = xxxxxxxxxxxxxxxxxxxxx
PASSWORD_HASH_ALGO = pbkdf2

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.gitea.yourdomain.com

[lfs]
PATH = /data/git/lfs

[mailer]
ENABLED = false

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[cron.update_checker]
ENABLED = false

[repository.pull-request]
DEFAULT_MERGE_STYLE = merge

[repository.signing]
DEFAULT_TRUST_MODEL = committer

[oauth2]
JWT_SECRET = xxxxxxxxxxxxxxxxxxxxx
```

### Database

SQLite
