### ISSUE TITLE
Actions fail when writing to GITHUB_ENV in separate repository

### ISSUE THREAD

**Issue by noetzold** [go-gitea/gitea#33134]
### Description

Im using powershell on windows system and my action fails when write to GITHUB_ENV is performent in seperate repository.

Here is a test yml file to reproduce the issue:

```
name: build
on:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: powershell

env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

jobs:
  Build:
    runs-on: windows
    steps:
      - name: Test1
        run: echo "TEST_VAR1=Hello" >> $env:GITHUB_ENV

      - name: Test2
        uses: https://${{ secrets.ACCESS_TOKEN }}@xyz/actions/gitea-issue@master

      - name: Print test 2
        if: ${{ always() }}
        run: echo "TestVar2 $env:TEST_VAR2"
```

gitea-issue repository action.yml:
```
name: 'Set up gitea issue'

defaults:
  run:
    shell: powershell

runs:
  using: "composite"
  steps:
    - name: Test1
      run: echo "TEST_VAR2=Hello2" >> $env:GITHUB_ENV
```
Step Test1 runs fine while Test2 fails.
There is no error message. 
![image](https://github.com/user-attachments/assets/3ca84d17-68da-493a-9b92-ecb7231d4d53)

If I start the runner on a different PC with the same workflow, it works:
![image](https://github.com/user-attachments/assets/5bc91221-782d-45d1-91f1-a501f37dc932)
I do not know if it is the reason but the failing runner is on Windows 11 while the working one is on Windows 10.

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea runs from docker

### Database

MySQL/MariaDB

**Comment by lunny** [comment]
Are there any logs from the failed step?

**Comment by noetzold** [comment]
Not in the action view or in the runner output. Is there another place?

**Comment by noetzold** [comment]
Thank you @ChristopherHX for pointing me in the right direction. 

The working system has "PowerShell Core" installed, the other one does not. If "PowerShell Core" is missing, the default is "PowerShell Desktop". https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
This explains the difference. 

But why writing to `Write-Output "TEST_VAR=Hello" >> $env:GITHUB_ENV` fails in PowerShell Desktop I do not know. I am fine with the workaround of using PowerShell Core instead.

Here is a slightly more sophisticated action to reproduce this:

```
name: build
on:
  push:
    branches:
      - '**'

env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

jobs:
  Build:
    runs-on: windows
    steps:
      - name: Test
        uses: https://${{ secrets.ACCESS_TOKEN }}@git.xyz.de/actions/gitea-issue@master

      - name: Print test
        if: ${{ always() }}
        run: echo "TestVar= $env:TEST_VAR"
```
```
name: 'Set up gitea issue'

runs:
  using: "composite"
  steps:
    - name: Test
      shell: powershell
      run: |
        $host.Version
        Write-Output "TEST_VAR=Hello" >> $env:GITHUB_ENV
        get-content $env:GITHUB_ENV
```

Here is the log of this run [action-Build-533.log](https://github.com/user-attachments/files/18346066/action-Build-533.log)

![image](https://github.com/user-attachments/assets/a62ce505-c894-4b60-918b-606d043e4b94)
