### ISSUE TITLE
I can not use the ssh url on the repo panel.

### ISSUE THREAD

**Issue by ZangZehua** [go-gitea/gitea#33137]
### Description

I deployed gitea via docker on my server, and configured ssh key. I set 3022 as the ssh port on the host, listening 22 in the docker. 

I can use "git clone ssh://git@my_ip:3022/my_repo.git" to clone my repo, but the url on the repo panel is "git@my_ip:my_repo.git" and it fails to clone repo. 

I edited "SSH_DOMAIN" in app.ini to "ssh://git@my_ip:3022/", but the ssh url changed to "git@ssh://git@my_ip:3022/:my_repo,git" and it also fails to clone. git@ssh://git@my_ip:3022/:my_repo,git" and it also fails to clone. 

How can i set the right url on the repo panel? Thanks.

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Using gitea with docker. Depolyed by docker-compose.yml.

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.io/gitea/gitea:1.22.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3022:22"
```

### Database

None
