### ISSUE TITLE
Gitea + Act Runner: (actions/checkout) failing when Gitea is configured with a subpath

### ISSUE THREAD

**Issue by Usual-Coder** [go-gitea/gitea#33629]
### Description

While the (actions) runner is fully functional "out-of-the-box" when Gitea is set "basically" (with its own/dedicated fqdn), it doesn't **when** Gitea is **using a subpath** (https://hostname.tld/sub/path/to/gitea ... **unlike your demo site** = why I could not reproduce it over there, as requested when creating an issue), as it may be when configured for some "special" context (ex.: Tailscale).

Searching for a _lighter_ alternative to GitLab, I've been using Gitea for months in that context without a problem. Now I'm trying to enable runners features.

I have followed the _docker compose_ variant of your docs (and checked against the provided [example](https://gitea.com/gitea/act_runner/src/branch/main/examples/docker-compose)) to set it all = the configuration seems pretty straightforward + everything is set accordingly = added a runner in the compose file, setting the variable `GITEA_INSTANCE_URL` with the same value as the one used by `gitea`'s container (aka `ROOT_URL`):
```yaml
(...)
services:
  gitea:
    (...)
    environment:
      ROOT_URL: "https://hostname.tld/sub/path/to/gitea"
    (...)
    image: "gitea/gitea"
    (...)

  # Part added to docker-compose.yml
  runner:
    (...)
    environment:
      (...)
      GITEA_INSTANCE_URL: "https://hostname.tld/sub/path/to/gitea"
      GITEA_RUNNER_REGISTRATION_TOKEN: validtokenhere
      (...)
    image: gitea/act_runner
    (...)
```

To avoid extra complexity (aka something related to my real workflow), I'm gonna stick to filling this issue based on the [Quickstart example](https://docs.gitea.com/usage/actions/quickstart#use-actions) ... which **fails** in the same way ... while **trying to clone from the wrong URL** = **missing the subpath**!

From step `Check out repository code` (aka the one using `actions/checkout@v4`):
```
(...)
Fetching the repository
  [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +6862cbe1b72d4fd5d597280cfbf6065b6db9404e:refs/remotes/origin/main
  fatal: repository 'https://hostname.tld/owner/repo/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 17 seconds before trying again
(...)
```
> [!IMPORTANT]
> The url displayed in previous logs has been redacted without altering its structure: `https://hostname.tld/owner/repo` while `https://hostname.tld/`**`sub/path/to/gitea`**`/owner/repo` was expected = missing the **`sub/path/to/gitea`**

I didn't _tweak_ anything + checked both configurations =
- inside `gitea` container: `ROOT_URL` is correctly set in `app.ini` (otherwise Gitea wouldn't have worked in the past few months 😏)
- inside `runner` container: `data/.runner` contains `"address": "https://hostname.tld/sub/path/to/gitea"`
= `gitea` continues to work without any other issue + runner is listed and can be triggered
= **`runner` received the info** (`GITEA_INSTANCE_URL` seems to be doing its job) **about the subpath but is not using it when needed!!!**

I tried:
- _playing with_ [`github-server-url`](https://gitea.com/actions/checkout#usage) (`gitea-server-url` too ... just in case ... but you're mirroring GitHub actions so I wasn't expecting much here) = **ignored**
- concatenating everything as `repository` (using a variable as fixed instance URL + owner/repo) = **error** (not a valid repo obviously)

I'm sorry I don't have time to dig into gitea/act_runner sources. No matter what, your product is great ! Thanks for providing a qualitative alternative for a self-hosted solution 🙇

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Ubuntu LTS

### How are you running Gitea?

Docker (images with) compose

### Database

None
