### ISSUE TITLE
Make autolinking issues and PRs in markdown files configurable

### ISSUE THREAD

**Issue by neonmoe** [go-gitea/gitea#33639]
### Description

Previously, in at least 1.19.3, linking to PRs and issues with e.g. `#123` in a markdown file resulted in them being autolinked when the markdown was rendered, but in 1.23.3 (and the dev version at demo.gitea.com), this is no longer the case.

I reproduced this in a testing instance with the following docker compose (and whatever defaults it gave in the install step), just changing the version from 1.19.3 to 1.23.3.

```yaml
networks:
  gitea_testing:
    external: false

services:
  server:
    image: docker.io/gitea/gitea:1.19.3
    container_name: gitea_testing
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea_testing
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4480:3000"
      - "4422:22"
```

And just for completeness, here's the README.md seen in the screenshot:

```md
linking issue #1

```

Even if this is intentional, it would be nice if the previous behavior could be re-enabled with a configuration option. I couldn't find any issues, PRs, or release notes about this topic.

Reproduced on demo.gitea.com: https://demo.gitea.com/neonmoe/testing-repo

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Image](https://github.com/user-attachments/assets/34ac6031-0f64-4d75-a145-51694f644352)

### How are you running Gitea?

Both demo.gitea.com and using the docker-compose config I pasted in the main issue description.

### Database

SQLite
