### ISSUE TITLE
actions on push branches single value not triggering

### ISSUE THREAD

**Issue by aceArt-GmbH** [go-gitea/gitea#33657]
### Description

Up until gitea 1.22 following action config was valid and triggert on a push to master.

```yml
name: Unit tests
on:
    push:
        branches: master
```

After updating to 1.23 this no longer triggers a build.

Workaround:
```yml
name: Unit tests
on:
    push:
        branches:
            - master
```

The "workaround" is simple and may be the (only) correct thing.
But the changelog did not mention this change, so I suspect it being a regression.
I am fine with either, but it should be fixed OR mentioned as breaking change 🙃 

### Gitea Version

1.23.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.47.2

### Operating System

alpine lxc

### How are you running Gitea?

docker compose

### Database

MySQL/MariaDB
