### ISSUE TITLE
can not get triggering_actor from actions context or env variables

### ISSUE THREAD

**Issue by yougg** [go-gitea/gitea#33675]
### Description

whether `actions` is first time triggered or rerun manualy, the `triggering_actor` is always empty

[actions](https://demo.gitea.com/yougg/actions-demo/actions/runs/9/jobs/0) on the gitea demo site is always `Waiting to run`, so i don't know if it can be reporduced.

### Gitea Version

1.23.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Image](https://github.com/user-attachments/assets/b144655b-910d-47fc-8899-d46ca5f6ed0c)

![Image](https://github.com/user-attachments/assets/a4a77cc7-828b-492f-9f05-f2c1fca2996e)

### Git Version

2.39.5

### Operating System

Debian GNU/Linux 12 (bookworm)

### How are you running Gitea?

running gitea service by docker container
 
```yaml
name: gitea
services:
  gitea:
    image: 'gitea/gitea:1.23.4'
    restart: always
    container_name: gitea
    #network_mode: host
    hostname: 'gitea.example.com'
    environment:
      - DOMAIN='gitea.example.com'
      - SSH_DOMAIN='gitea.example.com'
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea_db
      - GITEA__database__USER=gitea_db_user
      - GITEA__database__PASSWD=gitea_db_pwd
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - postgres
    logging:
      options:
        max-size: 100m

  postgres:
    image: 'postgres:17.3'
    restart: always
    container_name: postgres
    shm_size: 256mb
    environment:
      - POSTGRES_USER=gitea_db_user
      - POSTGRES_PASSWORD=gitea_db_pwd
      - POSTGRES_DB=gitea_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
```

### Database

PostgreSQL
