### ISSUE TITLE
pull_request_review event doesn't seem to be fired when evaluating workflows

### ISSUE THREAD

**Issue by Zhangjian55** [go-gitea/gitea#33700]
### Description

I installed Gitea 1.22.6 and act runner 0.2.11 on the Windows 11 system. The workflow is as follows:

```yaml
name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [issue_comment, pull_request, pull_request_review, pull_request_review_comment]
defaults:
  run:
    shell: bash
env:
  GITHUB_CONTEXT: ${{ toJson(gitea) }}
  JOB_CONTEXT: ${{ toJson(job) }}
  STEPS_CONTEXT: ${{ toJson(steps) }}
  RUNNER_CONTEXT: ${{ toJson(runner) }}
  STRATEGY_CONTEXT: ${{ toJson(strategy) }}
  MATRIX_CONTEXT: ${{ toJson(matrix) }}
jobs:
  Explore-Gitea-Actions:
    runs-on: local-runner
    steps:
      - run: echo "$GITHUB_CONTEXT"
      - run: echo "$JOB_CONTEXT"
      - run: echo "$STEPS_CONTEXT"
      - run: echo "$RUNNER_CONTEXT"
      - run: echo "$STRATEGY_CONTEXT"
      - run: echo "$MATRIX_CONTEXT"
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v4
```
When I comment on a pull request, the workflow is successfully triggered. However, when I review a pull request, the workflow cannot be triggered. I've also tried creating a pull request and assigning an assignee to a pull request, but none of these actions triggered the workflow. It seems that events related to pull requests cannot be triggered normally, and no new content is generated in the log files of Gitea and act runner..

This issue was previously reported in #25868. The reporter stated that restarting the Gitea service could resolve the problem. I've tried this solution, but it didn't work for me. I sincerely request your help

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.47.1

### Operating System

Windows 11

### How are you running Gitea?

I used the binary file from https://dl.gitea.com/gitea/1.22.6/gitea-1.22.6-windows-4.0-amd64.exe to run the Gitea. Act runner was also running base on local binary file from https://dl.gitea.com/act_runner/0.2.11/act_runner-0.2.11-windows-amd64.exe.

### Database

SQLite3
