### ISSUE TITLE
Failure when running Actions Quick Start example - `Cannot find: node in PATH`

### ISSUE THREAD

**Issue by scubbo** [go-gitea/gitea#33710]
### Description

I've set up an Action Runner, and attempted to run my first action as per the [instructions](https://docs.gitea.com/usage/actions/quickstart#use-actions). YAML:

```yaml
name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions! 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
        
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

Outcome is in screenshots.

The runners are running `gitea/act_runner:0.2.11` which I [believe is the latest version](https://gitea.com/gitea/act_runner/tags).

### Gitea Version

1.23.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="899" alt="Image" src="https://github.com/user-attachments/assets/fe4e1e45-7d3c-458f-a2f0-06296622c6b0" />

<img width="894" alt="Image" src="https://github.com/user-attachments/assets/2fcc8a3b-e05d-4ef0-8016-73d58deeb6be" />

### How are you running Gitea?

Kubernetes, via the [Helm Chart](https://gitea.com/gitea/helm-chart/), on version 10.6.1 with [one small local override](https://gitea.com/gitea/helm-chart/pulls/812).

### Database

PostgreSQL
