### ISSUE TITLE
Problems with multiple ssh keys

### ISSUE THREAD

**Issue by CapSel** [go-gitea/gitea#33762]
### Description

I can't pull from gitea. The error is:
```
git@domain: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

But this is not same problem as in FAQ.

I've got 2 ssh public keys for 2 computers for single user. Only second key works, first one gives me the error.

Of course I tried removing and adding this currently-not-working key again, I verified it. Then it works but the other key stops - same symptoms.

I deployed gitea with docker image "gitea/gitea". Entire configuration was done by Web UI.

Logs from gitea when there is a failure:
```
Connection closed by authenticating user git IP.IP.IP.IP port 58344 [preauth]
```

Repo has remote set with url `ssh://git@domain:917/UserName/repo.git` for fetch and push. As mentioned before - it works only with "last" key.

### Gitea Version

1.23.4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Archlinux/docker

### How are you running Gitea?

docker-compose part for gitea:
```
  gitea:
    image: gitea/gitea
    container_name: gitea
    restart: always
    depends_on:
      - db
    env_file:
      - ./gitea.env
    volumes:
      - /srv/gitea/data:/srv/git
      - /srv/gitea/config:/data/gitea/conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:3001:3000"
      - "917:22"
```
Frontend for Web UI is nginx outside of docker.

### Database

PostgreSQL
