### ISSUE TITLE
Broken queue causes various problems, need to report in self-check

### ISSUE THREAD

**Issue by joshrnoll** [go-gitea/gitea#33882]
### Description

Sometimes, the pull/push mirrors stopped synchronizing. 

### Gitea Version

All

----

(Edited by wxiaoguang: only keep the problem description, the workaround is in the following comment)

**Comment by wxiaoguang** [comment]
Maybe this could help your case: https://github.com/go-gitea/gitea/issues/33862#issuecomment-2717931247

> Does the queue system work? Check it from admin panel -> monitor -> queue `/-/admin/monitor/queue`
> If the queue system gets stuck, you need to click "Remove All" to clean the corrupted data

**Comment by joshrnoll** [comment]
This fixed it!

For those who stumble on this in the future:

Go to *Site Administration* --> *Monitoring* --> *Queues*

Click on *Review / Add Workers* next to the **mirror** queue, then click *Remove all* (I had 9 in the queue before clearing)

![Image](https://github.com/user-attachments/assets/aaeeeb96-0bbf-4cea-ad48-4d786ef8818b)

After doing this I initially received a permission denied error, but this was because I had deleted and recreated my remote repo without recreating the PAT:

![Image](https://github.com/user-attachments/assets/c04ba629-fb02-4f4a-affc-b941ca66226e)

Once I recreated my PAT, I got a successful sync again. 

@wxiaoguang thanks for the help! Is this a bug? Should I leave this issue open or go ahead and close?

**Comment by wxiaoguang** [comment]
By the way, the corruption only occurs in "levelqueue". So you could switch to "redis" queue which won't get stuck 😆

**Comment by wxiaoguang** [comment]
> Would it be possible to replace levelqueue with something that's less prone to failing?

No idea at the moment. Gitea's queue has some special behaviors like "unique queue". IMO making levelqueue could self-heal is a quick approach.

**Comment by aceslick911** [comment]
> [@wxiaoguang](https://github.com/wxiaoguang) thanks for the help! Is this a bug? Should I leave this issue open or go ahead and close?

This didnt fix it for me unfortunately - I had a slightly different route to this mess 😓  Basically:

-> Disk-full event corrupted Gitea's LevelDB queue files. 
-> All workflows showed first job succeeding, all dependent jobs with a  `needs:` ended up permanently stuck in Blocked.

Example of a workflow that triggered fine (no needs dependencies)
```yml
jobs:
  DatabaseMigration:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repository
...
```

Example of a workflow that always just got blocked despite working fine for half a year:
```yml
  staging_DeployEnvironment:
    if: (
(github.event_name == 'workflow_dispatch' && 
github.event.inputs.target_branch == 'staging') || github.ref_name == 'staging'
) && (
github.event_name != 'workflow_dispatch' || github.event.inputs.migration_only != 'true'
)
    runs-on: [ubuntu-latest]
    needs: [DatabaseMigration, staging_BuildRelease]
    environment:
      name: staging
      url: ${{ env.PUBLIC_STAGING_URL }}
    steps:
      - name: Checkout Repository
...
```

## What didn't work:
  - `gitea doctor check --all --fix` — no queue checks, useless here
  - tried removing all `concurrency:` and `cancel-in-progress:` workflow settings - didnt help.
  - Admin → Monitoring → Queues → actions_ready_job → Remove all — cleared the item list but left the corrupted LevelDB files on disk; queue still silently failed

## What fixed it:
`rm -rf /data/gitea/queues/` (ran on Gitea server pod, then restarted) — forces Gitea to recreate clean queues on startup. Workflows immediately started transitioning correctly.

## Prevention? 
> i'm switching job_emitter to in-memory queue (no disk, can't corrupt):

`app.ini`
```
  [queue.job_emitter]
  TYPE = channel
```
