### ISSUE TITLE
No permissions for api requests using administrator account

### ISSUE THREAD

**Issue by Deathlightning** [go-gitea/gitea#33917]
### Description

I applied for an application token from the personal information interface of the administrator user to access APIs. When making API requests, I encountered a log message indicating `401 Unauthorized: /api/v1/repos/XXX/target_verify/branches?token=XXX?limit=100&page=1 for XXX:61678, 401 Unauthorized in 0.2ms @ v1/api.go:756(v1.Routes.apiAuth)`. The request I executed was `http://XX:8030/api/v1/repos/XXX/target_verify/branches?token=XXX?limit=100&page=1`.

However, when I removed the limit and page parameters, the execution was successful. That is, the request that worked was `http://XXX:8030/api/v1/repos/XXX/target_verify/branches?token=XXX`. 

![Image](https://github.com/user-attachments/assets/d0abd10b-0d84-4533-94eb-2c9ac4894944)

I applied the token in the above screen, but did not perform any action in the OAuth2 app below

### Gitea Version

gitea-1.23.5-docker

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - /home/wzh/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8030:3000"
      - "2221:22"
```

### Database

None
