### ISSUE TITLE
[Bug] Gitea fails to start due to invalid ACME_DIRECTORY configuration causing certificate issuance failure

### ISSUE THREAD

**Issue by KaidRommel** [go-gitea/gitea#33983]
### Description

Gitea fails to start when attempting to automatically obtain HTTPS certificates via ACME (Let's Encrypt). The error logs indicate an invalid ACME_DIRECTORY configuration, leading to incorrect file paths and HTTP request failures.

![Image](https://github.com/user-attachments/assets/25f1320a-d969-4c53-8bc6-2bc12e7eac83)

```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      - USER_UID=1003
      - USER_GID=1003
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    ports:
      - "443:3000"
      - "80:3080"
      - "222:22"
      - "127.0.0.1:2222:22"
```

```ini
[server]
APP_DATA_PATH = /data/gitea
DOMAIN = git.myhostname.com
SSH_DOMAIN = git.myhostname.com
ENABLE_ACME = true
ACME_ACCEPTTOS = true
ACME_DIRECTORY = https
ACME_EMAIL = mymail@mail.com
PROTOCOL  = https
HTTP_PORT = 3000
ROOT_URL = https://git.myhostname.com/
REDIRECT_OTHER_PORT = true
PORT_TO_REDIRECT = 3080
DISABLE_SSH = false
SSH_PORT = 22
SSH_LISTEN_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = ********
OFFLINE_MODE = true
```

### Gitea Version

1.23.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/KaidRommel/2ac31fd904b05879a8d116240f9efebf

### Operating System

docker.gitea.com/gitea:1.23.5

### How are you running Gitea?

docker

### Database

SQLite
