### ISSUE TITLE
Gitea Actions cron triggering at the wrong time

### ISSUE THREAD

**Issue by geek-at** [go-gitea/gitea#34138]
### Description

Hello!

My Gitea Version: `Gitea version 1.23.6 built with GNU Make 4.4.1, go1.24.1 : tidb, sqlite, sqlite_unlock_notify` running on Alpine Linux.

I have a very simple workflow to be executed with my act runners: from my repo at `.gitea/workflows/cron.yaml`

```
name: cron test

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
    - cron: '0 23 * * *' # every day at 23:00

jobs:
  crontest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running cron by a ${{ github.event_name }} event."
      - run: echo "The time is $(date)"
```

So this cron should trigger twice: Once at midnight, once at 11PM but instead it triggers at the following times yesterday

- 7. Apr. 2025, 1:00 AM MESZ
- 7. Apr. 2025, 2:00 AM MESZ
It seems to have started with the start of summertime last week. Before that it triggered at the correct time and now it's off by two hours.

**What I have checked and done:**
- Verify that the time is correct on the act runners and on the gitea server
- Verify that the time is correct on all act runners
- Configured the `DEFAULT_UI_LOCATION` in the `app.ini` which seems to be the only timezone related setting
- Restarted Gitea and the host VM
- Re-pushed the repository containing the cron

### Gitea Version

1.23.6

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.49.0

### Operating System

Alpine Linux edge 3.22.0_alpha20250108

### How are you running Gitea?

Via the Alpine Package in the edge repository: https://pkgs.alpinelinux.org/package/edge/community/x86/gitea

### Database

SQLite

**Comment by nephatrine** [comment]
I get the same issue since updating to 1.23.6 except mine are all running four hours early instead of two hours late. Probably because my DST/summer timezone is UTC−04:00. Since you seem to be in UTC+02:00 and are seeing jobs two hours late that makes me think  Gitea is now running the cron jobs against UTC instead of the local timezone on the server. I was on 1.22.2 previously and everything ran based on my server's local time.

**Comment by geek-at** [comment]
good catch I think you're right. It did appear in the last patch and makes sense that it's in UTC. wonder what change might have triggered this. Any ideas @lunny ?

**Comment by geek-at** [comment]
Ok it works when I configure my crons with the TZ parameter

```yml
on:
  schedule:
    - cron: 'TZ=Europe/Vienna 0 18 * * *' # daily at 18:00
```
