### ISSUE TITLE
Authentication error while https operation

### ISSUE THREAD

**Issue by bauermarkus** [go-gitea/gitea#34161]
### Description

Hello,
since Gitea changed to the OAuth I always get a authentication fail the first time i try to use it. If i do the same or other command again, it is working

```
markus.bauer@ELEKON-NB19 MINGW64 /c/Projekte/customer/project (main)
$ git pull
remote: Verify
fatal: Authentication failed for 'https://git.tld.de/customer/project.git/'
```

I use Gitea behind a Nginx Proxy Manager

Any idea how to search on? Is this a configuration issue with the NPM? I am just wondering as it was always working until it was changed to OAuth

### Gitea Version

1.23.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Docker

### How are you running Gitea?

```
version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=3222
      - RUN_MODE=prod
      - DISABLE_REGISTRATION=true

      - GITEA__attachment__MAX_SIZE=256
      - GITEA__attachment__MAX_FILES=25
      - GITEA__attachment__ALLOWED_TYPES=image/*|audio/*|video/*|text/plain|.csv|.zip|.docx|.pptx|.xls|.xlsx|.eml|.pdf|.mov|.drawio|.log

      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=user
      - GITEA__database__PASSWD=password

    hostname: gitea-docker-prod
    volumes:
      - ./data:/data
    networks:
      - gitea_network_compose
      - nginx-public
    ports:
      #- "3000:3000"
      - "3222:3222"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: gitea_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea_network_compose

networks:
  gitea_network_compose:
    driver: "bridge"
  nginx-public:
    external: true

```

### Database

PostgreSQL
