### ISSUE TITLE
Gitea Actions incorrectly applies path filter on tag push

### ISSUE THREAD

**Issue by kosmoz** [go-gitea/gitea#34223]
### Description

Path filters should not be evaluated for tag pushes. Consider the following Workflow definition:

```yaml
on: 
  push:
    paths: 
      - foo/**
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
```

In GitHub, when a tag is pushed, this workflow is always executed.
In Gitea, it is only executed if the path filter applies to the commit referenced by the tag (I think??).

Looking at the source seems to confirm this: https://github.com/go-gitea/gitea/blob/bde014e46d044f54653d1d035730b8904676684a/modules/actions/workflows.go#L313-L338

The correct behavior is documented here: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

### Gitea Version

1.23.7

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux

### How are you running Gitea?

Official docker image in Kubernetes

### Database

PostgreSQL
