### ISSUE TITLE
[Actions] Workflow with `pull_request.types.[opened | labeled]` triggered twice

### ISSUE THREAD

**Issue by tdesveaux** [go-gitea/gitea#34221]
### Description

Hi,

I have a workflow with the following triggers:
```
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - master
```

When opening a PR with a label, the workflow is triggered twice instead of just once.

Here is a reproduction on the demo site: https://demo.gitea.com/tdesveaux-test-org/repro-workflow-double-trigger/actions?workflow=repro.yml&actor=0&status=0

### Gitea Version

1.23.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Gitea is self built and run as a systemd service.

### Database

None
