### ISSUE TITLE
The sidebar of the repository file list does not have a fixed height

### ISSUE THREAD

**Issue by lutinglt** [go-gitea/gitea#34298]
### Description

After scrolling through the file list, the sidebar will disappear.
Not in the comparison of submitted differences and on GitHub.

### Gitea Version

1.24.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![Image](https://github.com/user-attachments/assets/eddca503-db49-48f7-b59f-7a2501c9e79e)

![Image](https://github.com/user-attachments/assets/f2d9a66b-daae-480d-b1ab-a996603ce7b9)

### How are you running Gitea?

Docker

### Database

None

**Comment by lutinglt** [comment]
@kerwin612 #34321 

Regarding the occlusion issue when scrolling to the bottom.

My solution is to hide the elements at the bottom and set the height for the file tree list (similar to GitHub's approach).

```css
// 隐藏主内容的下内容和页脚, 避免滚动文件树时滚动条遮挡
  body > .full.height:has(.repo-view-file-tree-container) {
    padding-bottom: 0;
    + .page-footer {
      display: none;
    }
  }
.repo-view-file-tree-container {
        height: calc(100vh - 64px); // 减去头部高度
}
.repo-view-content {
        padding-bottom: 40px;
}
```

![Image](https://github.com/user-attachments/assets/d92f0d8c-12f5-4f0b-a778-f89738a25a16)

The following code is an implementation in my theme.

https://github.com/lutinglt/gitea-github-theme/blob/ebc6463c3067951dea5b5c991f4021367f0ce36a/styles/components/filelist.ts#L151-L218
