### ISSUE TITLE
CPU repeatedly more than 100% after run for a while

### ISSUE THREAD

**Issue by mariaccc** [go-gitea/gitea#34340]
### Description

use Docker deploy gitea & gitea-runner.  after run for several hours, the CPU repeatedly more than 100% 
logs seems normal, no errors, I dont know what happend.
```yaml
  gitea:
    image: docker.gitea.com/gitea:1.23.7
    container_name: gitea
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      USER_UID: 1000
      USER_GID: 1000

      # 数据库配置
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: ${POSTGRES_USER}
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD}


    deploy:
      resources:
        limits:
          cpus: "2.0" 
          memory: 2G 
    volumes:
      - ${GITEA_DATA}:/data
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    networks:
      - base-service
    restart: always

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    depends_on:
      - gitea
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${GITEA_RUNNER_NAME}

      GITEA__log__LEVEL: "debug" 
      GITEA__log__MODE: "console,file"
    volumes:
      - ${GITEA_RUNNER_CONFIG}:/config.yaml
      - ${GITEA_RUNNER_DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - base-service
    restart: always
```

### Gitea Version

1.23.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Image](https://github.com/user-attachments/assets/27d13aeb-cfe2-4ab0-9fac-4a8c07b28221)

### Git Version

git --version git version 2.47.2

### Operating System

Docker

### How are you running Gitea?

Docker compose

### Database

PostgreSQL
