### ISSUE TITLE
Docker CI parallelism

### ISSUE THREAD

**Issue by dev1way** [go-gitea/gitea#34461]
### Feature Description

Hello!

Is there any availability to configure parallelism inside CI solution using docker?
When launching CI with `act_runner` I can configure `capacity`.
But when a job launched using docker container, the second job will wait and will not run even the first one is finished.

**Comment by silverwind** [comment]
Might be a bug, but from what I gather, by default jobs should run concurrently up to the sum of all active runner `capacity` values. One can control this concurrency via `concurrency.group` setting, but default behaviour should be to saturate the runners with jobs.

**Comment by mxro** [comment]
For me, `capacity` in the runners `config.yaml` controls the number of instances the Docker runner will spawn.

However, I observed something strange - it always seems to spawn exactly one runner more than I have specified under capacity 🤔

So if I set `capacity=2` I get the following.

```
mxro@cooler:~$ sudo docker container ls
[sudo] password for mxro:
CONTAINER ID   IMAGE                                  COMMAND              CREATED              STATUS              PORTS     NAMES
f17458b1ee94   ubuntu-26.04-goldstack-runner:latest   "/bin/sleep 10800"   About a minute ago   Up About a minute             GITEA-ACTIONS-TASK-273_WORKFLOW-Release_JOB-Deploy-Voice-Keeper-Prod
561e62a2909a   ubuntu-26.04-goldstack-runner:latest   "/bin/sleep 10800"   About a minute ago   Up About a minute             GITEA-ACTIONS-TASK-272_WORKFLOW-Release_JOB-Deploy-Image-Scribe-Prod
023e02ceb2d2   ubuntu-26.04-goldstack-runner:latest   "/bin/sleep 10800"   2 minutes ago        Up 2 minutes                  GITEA-ACTIONS-TASK-271_WORKFLOW-Release_JOB-Deploy-Prod
```

When I had set capacity to `1` I got two runners.

Here for reference my full config:

```
log:
  level: info

runner:
  file: .runner
  capacity: 2
  timeout: 3h
  shutdown_timeout: 0s
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  fetch_interval_max: 60s
  labels: []

cache:
  enabled: true
  dir: ""
  host: "192.168.1.187"
  port: 8088

container:
  network: ""
  privileged: false
  options: "--add-host=host.docker.internal:host-gateway"
  workdir_parent: ""
  valid_volumes: []
  docker_host: ""
  force_pull: false
  force_rebuild: false
  require_docker: false
  docker_timeout: 0s
  bind_workdir: false

host:
  workdir_parent: ""

metrics:
  enabled: false
  addr: "127.0.0.1:9101"
```

They all have the same label.

Note I have got another runner to run jobs on the host, not sure if that has got anything to do with this.
