### ISSUE TITLE
Users redirected to account linking page despite `ACCOUNT_LINKING` set to `auto`

### ISSUE THREAD

**Issue by SeraphJACK** [go-gitea/gitea#34467]
### Description

We're switching from one IDP to another, so I added a new identity source in gitea admin page.

Users can successfully authenticate with the new identity source. However, they're redirected to account linking page after authenticating with the new identity source, despite having `ACCOUNT_LINKING` set to `auto` on the server.

Relevant configuration:

```ini
[service]
DISABLE_REGISTRATION = false
REQUIRE_SIGNIN_VIEW = true
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
ALLOW_ONLY_EXTERNAL_REGISTRATION = true
ENABLE_CAPTCHA = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true
ENABLE_PASSWORD_SIGNIN_FORM = false
ENABLE_BASIC_AUTHENTICATION = false
ENABLE_PASSKEY_AUTHENTICATION = false

[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
ACCOUNT_LINKING = auto

[admin]
DISABLE_REGULAR_ORG_CREATION = true
EXTERNAL_USER_DISABLE_FEATURES = deletion,manage_ssh_keys,manage_mfa,manage_credentials
```

### Gitea Version

1.23.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/SeraphJACK/e6b5d95d786d673bcd276fbd22104e55

### Screenshots

![Image](https://github.com/user-attachments/assets/71033de9-245f-459d-b0c5-ed8c068464fc)

### How are you running Gitea?

Via docker compose:

```yaml
version: "3"

services:
  server:
    image: gitea/gitea:1.23.8
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
     #- /home/git/.ssh/:/data/git/.ssh
    ports:
      - "127.0.0.1:3001:3000"
     #- "222:22"
    restart: always

volumes:
  data: {}
```

### Database

SQLite
