### ISSUE TITLE
Webhooks - API does not validate target URL

### ISSUE THREAD

**Issue by gabriel-samfira** [go-gitea/gitea#34491]
### Description

Hi folks,

It seems that gitea doesn't properly validate the webhook config. I can create a new webhook via the API, without an actual "target URL". The UI validates correctly. The API does not. Notice the missing URL bellow:

![Image](https://github.com/user-attachments/assets/2a136e91-7695-44ba-8a14-99de16c64fa5)

And here you can see I'm editing hook with ID 14 (visible in the URL bar), but the target URL is empty:

![Image](https://github.com/user-attachments/assets/13a2b861-7cb8-4974-aecb-3099cb183dc6)

Using this body:

```go
createOpts := &createGiteaHookOptions{
		Type:         "gitea",
		Events:       hook.Events,
		Active:       hook.GetActive(),
		BranchFilter: "*",
		Config: map[string]string{
			"content_type": hook.GetConfig().GetContentType(),
			"url":          "",
			"http_method":  "post",
		},
	}
```

The struct is defined as:

```go
type createGiteaHookOptions struct {
	Type                string            `json:"type"`
	Config              map[string]string `json:"config"`
	Events              []string          `json:"events"`
	BranchFilter        string            `json:"branch_filter"`
	Active              bool              `json:"active"`
	AuthorizationHeader string            `json:"authorization_header"`
}
```

### Gitea Version

v1.24.0-rc0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### How are you running Gitea?

I'm running gitea using the docker image. The following compose config was used:

```yaml
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.24.0-rc0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "22:22"

```

### Database

None
