### ISSUE TITLE
Feature Request: AI-Powered Code Agent for Gitea

### ISSUE THREAD

**Issue by ga-it** [go-gitea/gitea#34527]
## Summary

Implement an AI-powered code agent for Gitea that provides interactive code assistance, automated code reviews, and autonomous code implementation capabilities directly within pull requests and issues. This implementation would leverage the open-source OpenAI Codex CLI as a foundation, adapting its proven architecture for seamless Gitea integration.

## Problem Statement

Currently, Gitea users lack an integrated AI assistant that can:
- Automatically review code changes and suggest improvements
- Answer questions about code architecture and implementation
- Implement code fixes and features based on natural language requests
- Provide interactive assistance during the development workflow
- **Autonomously handle complex, multi-file coding tasks** (Jules-inspired)
- **Generate entire functions and applications from natural language** (Codex-inspired)
- **Integrate with development workflows beyond just PR/issue comments**

This feature gap makes it harder for teams to leverage AI capabilities for code quality improvement, faster development cycles, and automated code reviews, especially for open-source projects and smaller teams that rely on Gitea.

### Implementation Strategy: Fork and Adapt OpenAI Codex CLI

We propose forking the [OpenAI Codex CLI](https://github.com/openai/codex) as the foundation for Gitea's AI assistant. This approach offers several advantages:

1. **Proven Architecture**: Codex CLI already implements robust sandboxing, multi-provider support, and chat-driven development
2. **Security-First Design**: Built-in approval modes, sandboxed execution, and network isolation
3. **Extensible Provider System**: Supports 10+ AI providers out of the box with easy addition of new ones
4. **Active Development**: Benefits from OpenAI's ongoing improvements and community contributions
5. **Open Source**: Apache-2.0 licensed, allowing for modification and redistribution

#### Adaptation Plan

1. **Core Integration Module** (`gitea-codex-bridge`)
   - Adapt Codex CLI's terminal interface to work with Gitea's API
   - Create webhook handlers for Gitea events
   - Implement comment parsing and response formatting for Gitea's UI

2. **Gitea Actions Wrapper**
   - Create Gitea Actions that invoke the adapted Codex CLI
   - Handle authentication and secret management
   - Manage long-running tasks and status updates

3. **Enhanced Features for Gitea**
   - Add Gitea-specific tools (PR management, issue handling, etc.)
   - Integrate with Gitea's permission system
   - Support for Gitea's unique features (e.g., repository templates, organizations)

### Core Features (Building on Codex CLI)

1. **Interactive Code Assistant** (Codex CLI Foundation)
   - Leverages Codex's existing REPL and chat interface
   - Adapts terminal interaction to PR/issue comments
   - Maintains Codex's context awareness with `AGENTS.md` files
   - Natural language to code translation using Codex's generation capabilities

2. **Automated Code Review** (Enhanced)
   - Extends Codex's code analysis capabilities
   - Integrates with Gitea's PR review system
   - Uses Codex's multi-file understanding for comprehensive reviews
   - Leverages existing security scanning capabilities

3. **Autonomous Code Implementation** (Codex CLI + Jules concepts)
   - Uses Codex's existing approval modes (suggest/auto-edit/full-auto)
   - Extends with Jules-like persistent task management
   - Leverages Codex's sandboxed execution environment
   - Builds on Codex's file manipulation and testing capabilities

4. **Advanced Code Generation** (Native Codex Features)
   - Direct use of Codex's code generation capabilities
   - Existing support for test generation and refactoring
   - Multi-language support through provider flexibility
   - SQL query generation and API client creation

5. **Security and Sandboxing** (Codex CLI's Robust Model)
   - Adopts Codex's platform-specific sandboxing (Seatbelt on macOS, Docker on Linux)
   - Network isolation with configurable exceptions
   - Approval workflows with three-tier permission model
   - Repository-scoped execution limits

### Technical Architecture

1. **Gitea Actions Integration**
   ```yaml
   name: Gitea AI Assistant (Powered by Codex)
   on:
     issue_comment:
       types: [created]
     pull_request_comment:
       types: [created]
     pull_request:
       types: [opened, synchronize]
   
   jobs:
     ai-response:
       runs-on: ubuntu-latest
       steps:
         - uses: gitea/setup-codex-action@v1
           with:
             # Install and configure the Gitea-adapted Codex CLI
             version: "latest"
             
         - uses: gitea/codex-bridge-action@v1
           with:
             # Codex CLI configuration (inherited)
             provider: ${{ vars.AI_PROVIDER || 'openai' }}
             model: ${{ vars.AI_MODEL || 'gpt-4' }}
             api_key: ${{ secrets.AI_API_KEY }}
             
             # Codex approval modes
             approval_mode: ${{ vars.APPROVAL_MODE || 'suggest' }}
             
             # Gitea-specific configuration
             gitea_token: ${{ secrets.GITEA_TOKEN }}
             trigger_phrase: "@ai"
             
             # Codex CLI features
             allowed_tools: "Edit,Replace,FileRead,CreateFile,Bash(npm test)"
             custom_instructions: |
               Follow the coding standards in CONTRIBUTING.md
               Use Gitea API for PR/issue operations
   ```

2. **Configuration Management** (Codex CLI Compatible)
   - Reuse Codex's `~/.codex/config.yaml` structure
   - Add Gitea-specific configuration section
   - Maintain compatibility with Codex's provider configuration
   - Support for `AGENTS.md` files for project-specific instructions

3. **Provider Support** (Codex CLI's Extensive List)
   - All existing Codex providers (OpenAI, Anthropic, Google, Ollama, etc.)
   - Same environment variable configuration
   - Identical model selection interface
   - Easy addition of new providers

#### Phase 1: Core Fork and Integration (Months 1-2)
1. Fork OpenAI Codex CLI repository
2. Create `gitea-codex-bridge` module
3. Implement basic Gitea Actions integration
4. Adapt comment-based interactions for Gitea's UI

#### Phase 2: Feature Parity (Months 3-4)
1. Full PR/issue comment support
2. Gitea-specific tool implementations
3. Permission system integration
4. Status reporting and progress tracking

#### Phase 3: Enhanced Capabilities (Months 5-6)
1. Long-running task support (Jules-inspired)
2. Advanced Gitea features (templates, organizations)
3. Custom Gitea-specific providers
4. Web UI configuration interface

#### Phase 4: Ecosystem Integration (Months 7-8)
1. Plugin system for custom tools
2. Integration with popular Gitea apps
3. Advanced workflow templates
4. Community provider contributions

### Key Advantages of the Codex CLI Approach

1. **Immediate Feature Set**
   - Multi-provider support (10+ providers)
   - Robust sandboxing and security
   - Proven code generation capabilities
   - Active maintenance and updates

2. **Development Efficiency**
   - Avoid reimplementing complex features
   - Focus on Gitea-specific integration
   - Benefit from Codex's bug fixes and improvements
   - Leverage existing documentation and examples

3. **Community Benefits**
   - Contributions benefit both projects
   - Shared provider implementations
   - Cross-pollination of ideas
   - Potential for official collaboration

4. **User Experience**
   - Familiar interface for Codex users
   - Consistent behavior across platforms
   - Rich configuration options
   - Proven interaction patterns

### Migration and Compatibility

1. **For Existing Codex Users**
   - Direct configuration reuse
   - Same provider setup
   - Familiar commands and workflows
   - Easy transition to Gitea integration

2. **For New Users**
   - Comprehensive onboarding from Codex
   - Extensive documentation available
   - Active community support
   - Lower learning curve

### Security Considerations (Inherited from Codex)

1. **Sandboxing** (Codex's Robust Implementation)
   - Platform-specific isolation (Seatbelt, Docker)
   - Network restrictions with OpenAI-only exceptions
   - File system access controls
   - Process isolation

2. **Approval Workflows** (Codex's Three-Tier System)
   - Suggest mode: Read-only by default
   - Auto-edit mode: File modifications allowed
   - Full-auto mode: Complete autonomy with sandboxing

3. **Authentication** (Extended for Gitea)
   - Codex's existing API key management
   - Gitea-specific token handling
   - Repository-scoped permissions
   - Audit logging for all actions

## Success Metrics

- Reduction in PR review time (target: 40%)
- Increase in code quality metrics
- User adoption rate (target: 60% of active repos)
- Community contribution to AI providers
- **Codex CLI feature adoption** (target: 80% of Codex features used)
- **Cross-project contributions** (target: 10+ shared improvements)

### Codex CLI Integration Points

1. **Core Modifications**
   - Abstract terminal interface to support Gitea comments
   - Add Gitea API client alongside existing GitHub support
   - Extend webhook handling for Gitea events
   - Adapt progress reporting for web UI

2. **Maintained Compatibility**
   - Keep Codex CLI's core architecture intact
   - Ensure provider system remains unchanged
   - Preserve configuration format
   - Maintain CLI interface for local development

3. **Gitea-Specific Extensions**
   - Custom tools for Gitea API operations
   - Integration with Gitea's notification system
   - Support for Gitea's unique features
   - Repository migration tools

## Community Impact

This feature would:
- Make Gitea more competitive with GitHub/GitLab
- Attract AI-conscious developers and organizations
- Foster innovation in open-source AI tooling
- Provide a privacy-focused alternative to proprietary solutions
- **Create synergy between Codex and Gitea communities**
- **Accelerate AI assistant adoption through proven technology**
- **Enable smaller teams to leverage enterprise-grade AI tools**

## References

- [OpenAI Codex CLI](https://github.com/openai/codex) - Foundation for implementation
- [GitHub Claude Code Action](https://github.com/anthropics/claude-code-action)
- [Google Jules](https://blog.google/technology/google-labs/jules/)
- [OpenAI Codex Introduction](https://openai.com/index/introducing-codex/)
- [Gitea Actions Documentation](https://docs.gitea.com/usage/actions/overview)

## Conclusion

By building on the OpenAI Codex CLI's proven foundation, Gitea can rapidly implement a world-class AI assistant while maintaining its commitment to open-source values and self-hosted deployments. This approach minimizes development risk, accelerates time-to-market, and ensures compatibility with the broader AI development ecosystem.

The Codex CLI's architecture, with its robust sandboxing, multi-provider support, and extensible design, provides exactly the foundation needed for a production-ready Gitea AI assistant. Rather than reinventing the wheel, we can focus on creating the best possible integration with Gitea's unique features and workflows.

---

**Note**: This proposal leverages the OpenAI Codex CLI's mature architecture while adding Gitea-specific enhancements. The implementation would maintain compatibility with Codex's ecosystem while providing a seamless experience for Gitea users. The Apache-2.0 license of Codex CLI allows for this adaptation while contributing improvements back to the original project.
