### ISSUE TITLE
Action behavior inconsist with Github Action when first job fail

### ISSUE THREAD

**Issue by nienjiuntai** [go-gitea/gitea#34821]
### Description

When running multiple jobs in a workflow, the action status is mark failed as soon as first fail happend, this cause following problems
1. remaining jobs can only be cancelled by rerun all jobs(only when there's no failure in an action show cancel buttom)
2. remaining job status require refresh the website to update

This behavior is not consistant with Gitea v1.21.1(my previous version) and Github Action, following is the reproduce workflow
```yaml
name: Gitea Action violate failing behavior demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Fail-Job:
    runs-on: ubuntu-latest
    steps:
      - name: fail the regression
        run: |
          exit 1
  Long-Running-Job:
    runs-on: ubuntu-latest
    steps:
      - name: wait for 5s then return 0
        run: |
          sleep 5
```

### Gitea Version

1.24.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Running workflow with Github Action
![Image](https://github.com/user-attachments/assets/2556e5bd-7409-49b0-98b3-064fa1db78d7)

Running workflow with Gitea Action v1.24.2, after first job fail, the cancel icon change to rerun all, and the remaining job status only update when refresh UI
![Image](https://github.com/user-attachments/assets/3201097e-378e-4399-86dc-ad691ac6d265)

### Operating System

Centos

### How are you running Gitea?

Self-hosted with release binary

### Database

None
