### ISSUE TITLE
action should allow for arbitrary git repository addresses

### ISSUE THREAD

**Issue by akkuman** [go-gitea/gitea#34858]
### Description

For network reasons, we made a github mirror proxy in the following format 
https://xxx.com/https://github.com/actions/checkout@v4 
I use it in gitea action as follows

``` 
jobs: 
 build: 
 runs-on: ubuntu-latest 
 if. ${{ github.event.inputs.rebuild == 'true' }} 
 steps.
      - name: Checkout 
 uses: https://xxx.com/https://github.com/actions/checkout@v4 
 with: 
 ref: ${{ inputs.ref }}
```

Will report error `Expected format {org}/{repo}[/path]@ref. Actual ‘https://ghfast.top/https://github.com/actions/checkout@v4’ Input string was not in a correct format`.

### Gitea Version

1.24.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker compose

### Database

None
