### ISSUE TITLE
Folder not writable error

### ISSUE THREAD

**Issue by mdziczkowski** [go-gitea/gitea#34902]
### Description

When attempting to startup a fresh gitea like in instruction, I recieve the error that `/var/lib/gitea/git` folder is not writable (Permission Denied).

It skips the fact that the required folder structure (gitea and gitea/git) may not exist yet and nwwd to be created

### Gitea Version

latest docker image

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Error log:
```
Starting composer_db_1 ... done
Starting composer_server_1 ... done
Attaching to composer_db_1, composer_server_1
db_1      | 2025-06-29 21:20:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.3.0-1.el9 started.
db_1      | 2025-06-29 21:20:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
server_1  | mkdir: can't create directory '/var/lib/gitea/git': Permission denied
server_1  | /var/lib/gitea/git is not writable
db_1      | 2025-06-29 21:20:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.3.0-1.el9 started.
server_1  | docker setup failed
db_1      | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db_1      | 2025-06-29T21:20:50.262240Z 0 [System] [MY-015015] [Server] MySQL Server - start.
db_1      | 2025-06-29T21:20:50.449663Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 9.3.0) starting as process 1
db_1      | 2025-06-29T21:20:50.457782Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
composer_server_1 exited with code 1
db_1      | 2025-06-29T21:20:56.619322Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
server_1  | mkdir: can't create directory '/var/lib/gitea/git': Permission denied
server_1  | /var/lib/gitea/git is not writable
server_1  | docker setup failed
[...]
Trunchated due repeative error messages of the "server_1" and "composer_1"

### Git Version

latest docker image

### Operating System

Devuan - based on Debian (bookworm)

### How are you running Gitea?

docker-compose

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
It's caused by the mismatched rootless UID

Broken permissions on rootless docker install #29568

**Comment by mdziczkowski** [comment]
> It's caused by the mismatched rootless UID
> 
> Broken permissions on rootless docker install [#29568](https://github.com/go-gitea/gitea/issues/29568)

any chance it becomes fixed soon?

**Comment by lunny** [comment]
Could you post your compose file?

**Comment by mdziczkowski** [comment]
```
version: "2"

services:
  server:
    image: docker.gitea.com/gitea:latest-rootless
    restart: unless-stopped

    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3080:3000"
      - "3022:2222"
```

However I use command: `docker run -itd --name gitea -p 3080:3000 -p 3022:2222 container_id` instead
