### ISSUE TITLE
It doesn't work with drone

### ISSUE THREAD

**Issue by koolay** [go-gitea/gitea#3490]
- Gitea version (or commit ref): 1.4.0 + rc1
- Git version: 
- Operating system: 
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
It dont work well with drone(version: 0.8 and 0.8.4).  
After pushed code,  drone start building, but failed to fetch codes the repository from gitea.

- log info from drone building page

```
+ git init
Initialized empty Git repository in /drone/src/10.5.1.123/demo/demo/.git/
+ git remote add origin http://10.5.1.123:3000/demo/demo.git
+ git fetch --no-tags origin +refs/heads/drone:
fatal: could not read Username for 'http://10.5.1.123:3000': No such device or address
exit status 128
```

- `drone.yml`

```yaml
version: '2'

services:
  drone-server:
    image: drone/drone:0.8.4

    ports:
      - 8000:8000
      - 9000
    volumes:
      - /home/mysoft/docker/data/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=dev:pwd@tcp(10.5.23.15:3306)/drone?parseTime=true
      - DRONE_OPEN=true
      - DRONE_HOST=http://10.5.1.123:8000
      - DRONE_ADMIN=dev
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://10.5.1.123:3000
      - DRONE_GITEA_GIT_USERNAME=dev
      - DRONE_GITEA_GIT_PASSWORD=dev123
      - DRONE_SECRET=dev@123

  drone-agent:
    image: drone/agent:0.8.4

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=dev@123
```
