### ISSUE TITLE
Cropped commit code and subtitle fonts

### ISSUE THREAD

**Issue by inmylo** [go-gitea/gitea#3578]
- Gitea version: **1.4.0-rc1**
- Operating system: **Linux**
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/Bwko/VsCode/commit/903169966590cd236c5016cdc774875215d31765)
  - [ ] No
  - [ ] Not relevant

## Description
When I open commit details in Chromium browser I see that all code text and subtitle is cropped - no upper or bottom parts of letters. And space between lines is too small. Check screenshots below (red arrows show some examples).

On Firefox text is not cropped, but line-height is still too small.

I fix it in a custom header template with CSS:
```css
/* Prevent cropped commits code fonts */
.lines-code pre code {
  line-height: 19px;
}
  
/* Prevent cropped commit description fonts (Fixes #1133) */
.repository.diff .ui.top.attached.info.clearing.segment pre {
  line-height: 13px;
}
```
... but I believe you would like to fix it globally.

## Screenshots
![cropped2](https://user-images.githubusercontent.com/8048912/36635702-67e2f2de-19c2-11e8-9852-988ee2d3944a.png)

![cropped](https://user-images.githubusercontent.com/8048912/36635573-310aa89e-19c0-11e8-9966-798b20d8d37c.png)
