### ISSUE TITLE
Compare changes very slowly!

### ISSUE THREAD

**Issue by misterpoesy** [go-gitea/gitea#3926]
- Gitea version (or commit ref): 1.4.1
- Git version: 2.1
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

## Description

When create new pull request,  compare two branches very slowly, result to nginx timeout (┬＿┬).
How can i do some optimization?

**Comment by rkmax** [comment]
I'm using gitea over two weeks running on a t2.small instance. I'm using docker image version 1.4.0 with postgres 9.6 and Git 2.15.0 and nginx as inversed proxy and I'm impress of the performance all is very quickly (I've migrated from gitlab)

here's my docker-compose.yml

```yaml
version: "3"

networks:
  gitea_app:
    external: false

services:
  gitea_app:
    image: gitea/gitea:1.4.0
    environment:
      - SSH_DOMAIN=yourdomain.com
      - ROOT_URL=https://git.yourdomain.com
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - DB_TYPE=postgres
      - DB_HOST=gitea_postgres
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea_app
    volumes:
      - ./gitea_app_data:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - gitea_postgres
  gitea_postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea_app
    volumes:
      - ./gitea_postgres_data:/var/lib/postgresql/data
  gitea_web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./gitea_web_data:/etc/nginx/conf.d
      - ./gitea_web_data/cache:/cache
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gitea_app
    depends_on:
      - gitea_app
```

the only optimization I did was add some cache for static resources on nginx, but nothing more
