### ISSUE TITLE
Members in created team for org cannot view issue details.

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#3954]
- Gitea version (or commit ref):
- Git version: 15d0ac7 
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL: https://try.gitea.io/issues )
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description and Screenshots
When creating an organization, a default *Owners* team is created. All members in the owners team can view and modify all repos in organization, including issues.

A new team is created, called "Managers", a read-only team, to allow managers to view issues. All other items are disabled. What should happen, is that when going to the issues section, they should see all open/closed issues for all repos in organization.

In my build, 15d0ac7, team users can see the list of issues, but they get a 404 when clicking on the detail of the issue, as follows:

![image](https://user-images.githubusercontent.com/14616851/39958608-daf31a8a-55ca-11e8-8579-ae8cec0e10ac.png)

![image](https://user-images.githubusercontent.com/14616851/39958619-f3a0dfa4-55ca-11e8-8a57-e86d9431fe0b.png)

On the try.gitea site, I created the following user:

* user: arrow_user
* pass: Password1

And assigned it to my new organization, in a new team called "Managers", Arrow, which has a test repo in it.

## Update:
It appears the desired behavior works correctly on try.gitea. I am not sure what I am doing wrong in my instance. I am running off a docker container, and I have just updated it to the latest, the issue persists. My apologies for the ever-changing information here. I want to make sure I am providing accurate data.

**Comment by bkraul** [comment]
This is the output from the docker container log:
```
[Macaron] 2018-05-12 15:27:08: Started GET /org/project1/issues/1 for 192.168.113.4
[Macaron] 2018-05-12 15:27:08: Completed GET /org/project1/issues/1 404 Not Found in 11.553263ms
[Macaron] 2018-05-12 15:27:42: Started GET /issues for 192.168.113.4
[Macaron] 2018-05-12 15:27:42: Completed GET /issues 200 OK in 53.552068ms
[Macaron] 2018-05-12 15:27:44: Started GET /org/project2/issues/1 for 192.168.113.4
[Macaron] 2018-05-12 15:27:44: Completed GET /org/project2/issues/1 404 Not Found in 10.398302ms
```

**Comment by bkraul** [comment]
Update, this is happening in two separate docker environments, so it can be replicated. I am using [gitea/gitea:latest](https://hub.docker.com/r/gitea/gitea/).

**Comment by bkraul** [comment]
Any updates on this?

**Comment by lafriks** [comment]
I can not seem reproduce this behaviour

**Comment by lafriks** [comment]
No, I did not use docker. try.gitea.io is running of latest docker hub image tho

**Comment by bkraul** [comment]
Not sure exactly what is going on, then. I use docker-compose as follows:
```yaml
version: '2'

networks:
  gitea:
    external: false
    driver: bridge
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  server:
    image: gitea/gitea:latest
    restart: always
    networks:
      - gitea
      - reverse-proxy
    volumes:
      - /mnt/nfs/docker/persist/gitea:/data
    environment:
      - VIRTUAL_HOST=gitea.mydomain.com
      - VIRTUAL_PORT=3000
    ports:
      - '22002:22'
    expose:
      - '3000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /mnt/nfs/docker/persist/gitea/mysql:/var/lib/mysql
```
Everything else works perfectly fine. It is just that feature that does not seem to work properly.
