### ISSUE TITLE
CLI > Ability to initialise database/database tables

### ISSUE THREAD

**Issue by nickgrealy** [go-gitea/gitea#3992]
- Gitea version (or commit ref): 1.4.1
- Git version: ?
- Operating system: Linux (Docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: N/A

## Description

**Feature Request**

It would be great to have a CLI command, to initialise the database/tables before running `gitea`.

https://discourse.gitea.io/t/i-cannot-programmatically-setup-users-in-a-docker-container/289/5

**Comment by nickgrealy** [comment]
### Workaround:

(feedback welcome)

1. Setup a dummy `gitea` instance with your intended database
1. Manually create a user and a repository
1. Use the [`./gitea dump`](https://docs.gitea.io/en-us/backup-and-restore/#restore-command-restore) command to generate a `gitea-db.sql` file (specific to database)
1. Initialise your database with the script - the script will create the required tables, and insert the user & repository data

### Attachments:

I've exported scripts for `sqlite3` and `mysql` - generated using `gitea 1.4.1` - username: `admin123` password `password` (or might be `admin123`, I forget and it's encoded in the sql file!).

- [gitea-db.zip](https://github.com/go-gitea/gitea/files/2019604/gitea-db.zip)

### Example - docker-compose.yml

```yml
version: '3'
services:
  web:
    image: gitea/gitea:1.4.1
    restart: always
    depends_on:
      - db
    volumes:
      - web_data:/data
    ports:
      - "3000:3000"
      - "22:22"
    environment:
      APP_NAME: foobar
      RUN_MODE: prod
      INSTALL_LOCK: "true"
      DB_TYPE: mysql
      DB_HOST: db:3306
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:3000"]
      interval: 5s
      timeout: 5s
      retries: 36

  db:
    image: mariadb:10.1.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
    volumes:
      - db_data:/var/lib/mysql
      - ./gitea/gitea-db-mysql.sql:/docker-entrypoint-initdb.d/gitea-db-mysql.sql

volumes:
  web_data:
  db_data:
```
