### ISSUE TITLE
Docker footer show the commit instead of tag version in 1.5.0

### ISSUE THREAD

**Issue by EnricoFerro** [go-gitea/gitea#4782]
- Gitea version (or commit ref): 1.5
- Git version:
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
In Docker in the footer of the page the displayed version is the commit instead of the version of the tag.
I see this description for the version 1.5.0 / 1.5.0-rc2 / 1.5.0-rc1 / 1.5.0-dev.

The version 1.4.3 show the correct version ( 1.4.3 )
...

## Screenshots

Version 1.5.0:
![image](https://user-images.githubusercontent.com/25525316/44575752-091e2d00-a78d-11e8-8a29-e83e128ca7ad.png)

Version 1.4.3:
![image](https://user-images.githubusercontent.com/25525316/44575982-bd1fb800-a78d-11e8-8f32-d513737eb98d.png)

**Comment by lafriks** [comment]
Are you using tag `1.5` or `1.5.0`?

**Comment by EnricoFerro** [comment]
I use this docker-compose.yml:

```
version: "2"

networks:
        gitea:
            external: false
services:
    gitea:
       container_name: gitea
       image: gitea/gitea:1.5.0
       environment:
           - USER_UID=112
           - USER_GID=117
       restart: always
       networks:
           - gitea
       volumes:
           - /home/git/gitea:/data
       ports:
           - "127.0.0.1:3000:3000"
           - "127.0.0.1:10022:22"
```

and launch:
```
sudo docker-compose up -d --build
```
