### ISSUE TITLE
Docker-compose not working on RPi 3

### ISSUE THREAD

**Issue by LegendaryB** [go-gitea/gitea#5180]
- Operating system: HypriotOS on raspberry pi 3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Hey guys,

I'm trying to get gitea running using docker-compose. I have followed the documentation on the website. 

My docker compose file looks like this:
```
version: "2"
networks:
    gitea:
        external: false
services:
    server:
        image: gitea/gitea:latest
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - RUN_MODE=prod
        restart: always
        networks:
            - gitea
        volumes:
            - .:/data
        ports:
            - "3000:3000"
            - "222:22"
```

When I now run the docker-compose up command i get the following output:
```
Starting gitea_server_1 ... done
Attaching to gitea_server_1
server_1  | standard_init_linux.go:190: exec user process caused "exec format error"
gitea_server_1 exited with code 1
server_1  | standard_init_linux.go:190: exec user process caused "exec format error"
```

And that message is repeated the entire time. Also the gitea server is not accessible on port 3000. I think maybe it's an problem with the image? Maybe it is somehow pulling the wrong image for the architecture?

Kind Regards,
Daniel
