### ISSUE TITLE
After migration russian letters are incorrectly encoded

### ISSUE THREAD

**Issue by iddm** [go-gitea/gitea#5185]
I have recently migrated from binary gitea to docker gitea. I made a dump and it imported into database inside docker also and now my issues look like this:

[![](https://i.imgur.com/h451lCE.png)](https://i.imgur.com/h451lCE.png)

I also have `500 Internal Server Error` error very often and when I look for the problem in the logs I see this:

> ERROR: invalid character '\n' in string literal

I have no idea what I have done wrong, could anyone help me please?

My `docker-compose.yml`:

```yaml
version: "2"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql

  server:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1006
      - USER_GID=1006
      - USER=gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
```

**Comment by zeripath** [comment]
I think your mariaDB has not been set-up to use utf-8, see https://github.com/docker-library/docs/issues/613

Basically you need `docker-compose.yml` to read:
```yaml
version: "2"

services:
  db:
    image: mariadb:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql

  server:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1006
      - USER_GID=1006
      - USER=gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
```
