### ISSUE TITLE
Permission denied after latest docker upgrade

### ISSUE THREAD

**Issue by Aragur** [go-gitea/gitea#5688]
- Gitea version (or commit ref):  31aa00f
- Git version: 2.11.0
- Operating system: Debian
- Database (use `[x]`):
  - [X] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant
- Log gist:
```
gitea     | Found app.ini config file, migrating database
gitea     | migrate: /data/gitea/conf/app.ini: Permission denied
gitea     | Jan 10 15:41:14 syslogd started: BusyBox v1.28.4
gitea     | Jan 10 15:41:14 sshd[22]: Server listening on :: port 22.
gitea     | Jan 10 15:41:14 sshd[22]: Server listening on 0.0.0.0 port 22.
gitea     | 2019/01/10 15:41:14 [T] AppPath: /app/gitea/gitea
gitea     | 2019/01/10 15:41:14 [T] AppWorkPath: /app/gitea
gitea     | 2019/01/10 15:41:14 [T] Custom path: /data/gitea
gitea     | 2019/01/10 15:41:14 [T] Log path: /data/gitea/log
db_1_260cddf62aee | 2019-01-10T15:41:14.327150Z 2 [Note] Aborted connection 2 to db: 'gitea' user: 'gitea' host: '192.168.144.3' (Got an error reading communication packets)
```
## Description

After upgrading my docker-compose instance from Gitea to the latest version I get the following error (as seen above).  
I already tried chowning the my mounted gitea volume to 999 (docker) and 1000 (default Gitea user) with now success.

**Comment by apricote** [comment]
Can you add your `docker-compose.yaml`?

**Comment by Aragur** [comment]
Sure, this is my `docker-compose.yml`
```
version: '3.1'

networks:
  proxy:
    external:
      name: proxy
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    networks:
      - gitea
      - proxy
    volumes:
      - ./gitea:/data
    ports:
      - 2222:2222
    expose:
      - 3000
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{private}}
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD={{private}}
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
```
I'm using the `proxy` network to connect to my `nginx reverse proxy`

**Comment by danofun** [comment]
I'm getting the same error. Was running without issue prior to the update.
`docker-compose.yml`
```
version: '3.6'
services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAIN}
    ports:
      - "441:80"
      - "442:443"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_KEY}

  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: mariadb
    restart: always
    volumes:
        - ${CONFIG}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "2221:22"
    volumes:
      - ${CONFIG}/gitea:/data
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${MYSQL_PASSWORD}
      - "ROOT_URL=https://git.${DOMAIN}"
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - TZ=${TZ}
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gitea"
      - "traefik.frontend.rule=Host:git.${DOMAIN}"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAIN}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
```
