### ISSUE TITLE
The database settings are invalid: database is locked (arm64)

### ISSUE THREAD

**Issue by LukeShortCloud** [go-gitea/gitea#7069]
- Gitea version (or commit ref): 1.7.6 and 1.8.1
- Operating system: Alpine 3.8.0 (ARM64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: There are no log files generated. Here is the stdout of the gitea process as I attempt to do the install a few times: https://gist.github.com/ekultails/c5b674147716b3fd35c2402e7f1a07a3

## Description

When deploying Gitea for the first time on Kubernetes using the default settings, the installation runs for about a minute and then fails saying "The database settings are invalid: database is locked". The database file is created but it is completely empty. This happens with other versions of Gitea as well. The files in the volume are all created and owned by the user with UID 1000 (rock64). 

```
$ ls -lah /exports/gitea
total 20K
drwxr-xr-x 5 rock64 rock64 4.0K May 29 01:51 .
drwxr-xr-x 8 root   root   4.0K May 29 01:48 ..
drwxr-xr-x 3 rock64 rock64 4.0K May 29 01:51 git
drwxr-xr-x 4 rock64 rock64 4.0K May 29 02:19 gitea
drwx------ 2 root   root   4.0K May 29 01:51 ssh
$ ls -lah /exports/gitea/gitea/
total 16K
drwxr-xr-x 4 rock64 rock64 4.0K May 29 02:19 .
drwxr-xr-x 5 rock64 rock64 4.0K May 29 01:51 ..
drwxr-xr-x 2 rock64 rock64 4.0K May 29 01:51 conf
-rw-r--r-- 1 rock64 rock64    0 May 29 01:53 gitea.db
drwxr-xr-x 2 rock64 rock64 4.0K May 29 01:51 log

```

Kubernetes deployment file:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: gitea-pvc
          persistentVolumeClaim:
            claimName: gitea-volume-claim
      containers:
        - name: gitea
          image: kunde21/gitea-arm:arm64-v1.7.6
          environment:
            - USER_UID=1000
            - USER_GID=1000
          restart: always
          ports:
            - containerPort: 3000
              name: gitea-http
            - containerPort: 22
              name: gitea-ssh
          volumeMounts:
            - mountPath: /data
              name: gitea-pvc
```
