### ISSUE TITLE
custom folder is ignored in docker

### ISSUE THREAD

**Issue by i5heu** [go-gitea/gitea#7268]
Docker Gitea Version: 1.9.0+dev-370-gde9b398cd
docker Image: gitea/gitea:latest 

Hello,
i use the Docker image.
There is no custom directory in the entire Docker container after installation.
If i create an testfile (test.html) in `/data/gitea/custom/public` the file is after redeploy not available on /test.html.
If i add the environment  variable `GITEA_CUSTOM = /data/gitea/custom` into to my swarm stack config gitea will start the install process again and will write all its files in the given path .

I'm pretty sure it should work since  [the](https://docs.gitea.io/en-us/install-with-docker/)  doc exists but it dose not.

My docker swarm stack config:
```
version: '3.3'
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      SSH_DOMAIN: xxx
      START_SSH_SERVER: 'true'
    ports:
     - '22:22'
    volumes:
     - /mnt/gitea:/data
    networks:
     - gitea
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.hostname == xxx
```

app.ini:
```
APP_NAME = XXX
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH    = /data/gitea
SSH_DOMAIN       = localhost
HTTP_PORT        = 3000
ROOT_URL         = XXXX
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_CONTENT_PATH = /data/git/lfs
DOMAIN           =XXX
LFS_START_SERVER = true
LFS_JWT_SECRET   =XXX
OFFLINE_MODE     = false
ENABLE_GZIP= true

[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = sqlite3
HOST     = localhost:3306
NAME     = gitea
USER     = root
PASSWD   = 
SSL_MODE = disable
CHARSET  = utf8

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER        = file

[picture]
AVATAR_UPLOAD_PATH            = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
DISABLE_GRAVATAR              = false
ENABLE_FEDERATED_AVATAR       = true

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = /data/gitea/log
MODE      = file
LEVEL     = info

[security]
INSTALL_LOCK   = true
SECRET_KEY     = XXX
INTERNAL_TOKEN = XXX

[service]
DISABLE_REGISTRATION              = false
REQUIRE_SIGNIN_VIEW               = false
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.example.org

[oauth2]
JWT_SECRET = XXX

[mailer]
ENABLED = false

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
```
