### ISSUE TITLE
Wrong layout for "Create PR" page on personal server

### ISSUE THREAD

**Issue by Holt59** [go-gitea/gitea#7919]
- Gitea version (or commit ref): 1.10.0+dev-189-g08c63190c
- Git version: 
- Operating system: N/A (docker gitea/gitea:latest)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

The "Create Pull-Request" page is full-width instead of being "contained" like other gitea page. I checked the DOM of the pages, and here is what I found:

- on https://try.gitea.io, the containing `<div>` has `ui container` classes;
- on my server, the containing `<div>` has `ui container fluid padded`.

Tested on the same browser and same display for both hosts. On a newly created gitea server, the layout is correct.

Here is my `docker-compose.yml`:

```
version: '2'

services:
  server:
      image: gitea/gitea:latest
      restart: unless-stopped
      hostname: gitea.myhost.fr
      environment:
        VIRTUAL_HOST: 'gitea.myhost.fr'
        VIRTUAL_PORT: '3000'
      networks:
        - proxy
        - default
      expose:
        - '3000'
      ports:
        - '2222:22'
      volumes:
        - data:/data

  drone:
    image: drone/drone:latest
    restart: unless-stopped
    hostname: drone.myhost.fr
    environment:
      VIRTUAL_HOST: 'drone.myhost.fr'
      DRONE_GITEA_SERVER: 'http://server:3000'
      DRONE_GIT_ALWAYS_AUTH: 'true'
      DRONE_RUNNER_CAPACITY: 2
      DRONE_SERVER_HOST: 'drone.myhost.fr'
      DRONE_SERVER_PROTO: 'https'
      DRONE_TLS_AUTOCERT: 'false'
      DRONE_USER_CREATE: 'username:mikael.capelle,admin:true'
    networks:
      - proxy
      - default
    expose:
      - '80'
    volumes:
      - drone:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
    driver: local

  drone:
    driver: local

networks:
  proxy:
    external:
      name: nginxproxy
```

## Screenshots

Here is what I have on my server:

![image](https://user-images.githubusercontent.com/2393288/63331388-e5f17380-c335-11e9-933c-571f3a26ccc8.png)

Here is what I expect (try.gitea.io):

![image](https://user-images.githubusercontent.com/2393288/63331449-028dab80-c336-11e9-931b-998f76993602.png)
