### ISSUE TITLE
Docker - Disable Registration/SSH not working when passed as environment variable

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#8701]
```
    gitea:
        container_name: gitea
        image: {private repo}
        restart: unless-stopped
        ports:
            - "801:3000"
        environment:
            USER_UID: 1000
            USER_GID: 1000
            DISABLE_REGISTRATION: "true"
            DISABLE_SSH: "true"
            RUN_MODE: "prod"
        volumes:
            - "$HOME/Docker/Gitea:/data"
```
This is my docker-compose.yml and apparently I can create as many account as I want even though DISABLE_REGISTRATION flag is set to true.
