### ISSUE TITLE
[WIP] Gitea deployment examples 

### ISSUE THREAD

**Issue by xinity** [go-gitea/gitea#89]
Add deployment examples of gitea. 

For now :
vagrant
docker compose
kubernetes

**Comment by garyritchie** [comment]
```yml
version: "2"
volumes:
  gogs:
  db:
services:
  gogs:
    container_name: gogs
    restart: always
    image: gitea/gitea:latest
    links:
      - db:mysql
    volumes:
      - gogs:/data
    ports:
      - "10022:22"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=gitearocks.com
    networks:
      - backend
      - frontend
  db:
    container_name: gogs-db
    restart: always
    image: mysql:5.6
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somekindapass
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=someotherkindofpass
    networks:
    - backend

networks:
  frontend:
  backend:
```

I'm already using jwilder/nginx-proxy -- that's what VIRTUAL_HOST and VIRTUAL_PORT are for.

Hope this helps someone and wouldn't mind feedback on making it better.
