### ISSUE TITLE
nameserver 127.0.0.11 in docker image

### ISSUE THREAD

**Issue by fullee** [go-gitea/gitea#9106]
- Gitea version (or commit ref):1.8.1
- Git version: docker image default 
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:

```
[root@host4 gitea-compose]# docker-compose up
Creating giteacompose_gitea_1 ...
Creating giteacompose_gitea_1 ... done
Attaching to giteacompose_gitea_1
gitea_1  | Nov 21 03:46:55 syslogd started: BusyBox v1.29.3
gitea_1  | Nov 21 03:46:55 sshd[19]: Server listening on :: port 22.
gitea_1  | Nov 21 03:46:55 sshd[19]: Server listening on 0.0.0.0 port 22.
gitea_1  | 2019/11/21 03:46:55 [T] AppPath: /app/gitea/gitea
gitea_1  | 2019/11/21 03:46:55 [T] AppWorkPath: /app/gitea
gitea_1  | 2019/11/21 03:46:55 [T] Custom path: /data/gitea
gitea_1  | 2019/11/21 03:46:55 [T] Log path: /data/gitea/log
gitea_1  | 2019/11/21 03:47:28 [T] AppPath: /app/gitea/gitea
gitea_1  | 2019/11/21 03:47:28 [T] AppWorkPath: /app/gitea
gitea_1  | 2019/11/21 03:47:28 [T] Custom path: /data/gitea
gitea_1  | 2019/11/21 03:47:28 [T] Log path: /data/gitea/log

```
## Description
this is default setting of dns in docker image, Is't bug?
```
/ # cat /etc/resolv.conf
search srv
nameserver 127.0.0.11
options ndots:0
```
...

**Comment by bagasme** [comment]
@fullee Typo issue. Expected nameserver for `localhost` is `127.0.0.1`?

**Comment by fullee** [comment]
![image](https://user-images.githubusercontent.com/11188837/69304135-80759180-0c5a-11ea-99fe-a7cc125055ca.png)
This configuration within the mirror is a BUG.

This problem has been solved，flowing:
```
version: "3.0"
services:
  gitea:
    image: gitea/gitea:1.8.1
    restart: always
    volumes:
      - "./data:/data"
      - "/etc/resolv.conf:/etc/resolv.conf"
    ports:
      - "2002:3000"
      - "2003:22"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
```
